Repository GoogleContainerTools/skaffold, pull requests merged in 2019-05, with the labels that each got.

#2041 Note filesync limitation for files not owned by container user
  docs/content/en/docs/how-tos/filesync/_index.md
Labels: cla: yes

#1999 Add custom artifact for custom local builds
  .gitignore
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/samples/builders/build.sh
  docs/content/en/samples/builders/custom.yaml
  docs/content/en/schemas/v1beta10.json
  hack/boilerplate/boilerplate.py
  integration/run_test.go
  integration/testdata/custom/BUILD
  integration/testdata/custom/WORKSPACE
  integration/testdata/custom/build.sh
  integration/testdata/custom/k8s/k8s-pod.yaml
  integration/testdata/custom/main.go
  integration/testdata/custom/skaffold.yaml
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
  pkg/skaffold/build/custom/dependencies.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/local/custom.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/samples_test.go
Labels: cla: yes

#2047 Remove podname from port forward key
  pkg/skaffold/kubernetes/port_forward.go
  pkg/skaffold/kubernetes/port_forward_test.go
Labels: cla: yes

#2001 Deploy to consume build output
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/deploy_test.go
  cmd/skaffold/app/flags/build_output.go
  cmd/skaffold/app/flags/build_output_test.go
  cmd/skaffold/app/flags/image.go
  cmd/skaffold/app/flags/image_test.go
  docs/content/en/docs/references/cli/_index.md
  integration/deploy_test.go
  pkg/skaffold/build/build.go
  pkg/skaffold/build/prebuilt.go
  pkg/skaffold/build/prebuilt_test.go
  pkg/skaffold/build/util.go
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#2054 Allow --no-cache to be passed to docker
  docs/content/en/schemas/v1beta10.json
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#2052 Minor fix on Markdown to follow markdown rules
  README.md
Labels: cla: yes

#2059 Add unit test for port forwarding key
  pkg/skaffold/kubernetes/port_forward_test.go
Labels: cla: yes

#2055 Add k8 style managed by label to skaffold deployed pods
  pkg/skaffold/constants/constants.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/runner/labeller.go
  pkg/skaffold/runner/labeller_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes

#2024 Improve nodejs example to show subdirectories sync
  examples/nodejs/backend/package.json
  examples/nodejs/backend/src/index.js
  examples/nodejs/backend/src/utils/index.js
  examples/nodejs/skaffold.yaml
  integration/examples/nodejs/backend/index.js
  integration/examples/nodejs/backend/package.json
  integration/examples/nodejs/backend/src/index.js
  integration/examples/nodejs/backend/src/utils/index.js
  integration/examples/nodejs/skaffold.yaml
Labels: cla: yes

#2062 Prefix Skaffold labels with 'skaffold-'
  pkg/skaffold/config/options.go
  pkg/skaffold/config/options_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/labels.go
Labels: cla: yes

#2078 Clarify which containers are port forwarded
  docs/content/en/docs/how-tos/portforward/_index.md
Labels: cla: yes

#2072 Fix typo
  docs/content/en/schemas/v1beta10.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#2076 :bug: fix kubectl apply error handling
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
Labels: cla: yes

#1371 Automatically watch helm subcharts when skipBuildDependencies is enabled
  docs/content/en/docs/how-tos/deployers/_index.md
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, deploy/helm, docs-modifications, needs-rebase

#2085 Remove copy paste deploy_test.go
  cmd/skaffold/app/cmd/deploy_test.go
Labels: cla: yes

#2049 Add dockerfile to custom dependencies
  docs/content/en/schemas/v1beta10.json
  pkg/skaffold/build/custom/dependencies.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: !! config-change !!, build/custom, cla: yes

#2090 Mention kind in docs for local development
  docs/content/en/docs/concepts/_index.md
Labels: cla: yes

#2099 Fix image release process: master -> edge, tag -> latest
  Makefile
  deploy/cloudbuild-release.yaml
  deploy/cloudbuild.yaml
  docs/content/en/docs/getting-started/_index.md
Labels: cla: yes

#2097 Add version as unknown if version.Get().Version is empty
  pkg/skaffold/runner/labeller.go
  pkg/skaffold/runner/labeller_test.go
Labels: cla: yes

#1847 Improve syntax for artifact.sync config [1/3]
  docs/content/en/docs/how-tos/filesync/_index.md
  docs/content/en/samples/filesync/filesync.yaml
  docs/content/en/schemas/v1beta10.json
  examples/hot-reload/skaffold.yaml
  examples/nodejs/skaffold.yaml
  integration/examples/hot-reload/skaffold.yaml
  integration/examples/nodejs/skaffold.yaml
  integration/testdata/file-sync/skaffold.yaml
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/samples_test.go
  pkg/skaffold/schema/v1beta9/upgrade.go
  pkg/skaffold/schema/v1beta9/upgrade_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/sync/kubectl/kubectl.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/util/tar.go
Labels: !! config-change !!, cla: yes

#2095 Add command to custom artifact dependencies
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/schemas/v1beta10.json
  pkg/skaffold/build/custom/dependencies.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: !! config-change !!, build/custom, cla: yes

#2102 cut v0.29.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/backend/Dockerfile
  examples/nodejs/backend/src/index.js
  examples/nodejs/backend/src/utils/index.js
  examples/nodejs/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
Labels: cla: yes

#2107 added the notice about skaffold deploy
  CHANGELOG.md
Labels: cla: yes

#2104 add explanation to cloud build section docs
  docs/content/en/docs/how-tos/builders/_index.md
Labels: cla: yes

#2115 Turn port forwarding off by default
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/how-tos/portforward/_index.md
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2112 Don't panic for nil pod watch object
  pkg/skaffold/kubernetes/wait.go
Labels: cla: yes

#2113 :sparkles: Add option `--no-prune-children`
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/docker/image_util.go
Labels: cla: yes

#2043 Enable `skaffold debug` for kustomize
  docs/content/en/docs/how-tos/debug/_index.md
  integration/debug_test.go
  integration/skaffold/helper.go
  integration/testdata/jib/kustomization.yaml
  integration/testdata/jib/skaffold.yaml
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
Labels: cla: yes

#2130 Fix bugs in custom builder
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
Labels: build/custom, cla: yes

#2079 docs: correct header name for jump.
  cmd/skaffold/man/man.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, kind/documentation

#2133 Update jib
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
Labels: cla: yes

#2135 Always use the same technic to cleanup global variables in tests.
  cmd/skaffold/app/cmd/build_test.go
  pkg/skaffold/build/cache/cache_test.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/logs_test.go
  pkg/skaffold/build/custom/custom_test.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/parse_test.go
  pkg/skaffold/kubernetes/port_forward_test.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes

#2064 [Design Proposal] Setting proxy for Kaniko Pod
  docs/design_proposals/kaniko-proxy-setting.md
Labels: cla: yes, kind/design discussion

#2136 Fix yoda condition
  cmd/skaffold/app/flags/build_output_test.go
Labels: cla: yes

#2132 Use more recent Golang images
  integration/examples/compose/Dockerfile
  integration/examples/getting-started/Dockerfile
  integration/examples/google-cloud-build/Dockerfile
  integration/examples/kaniko-local/Dockerfile
  integration/examples/kaniko/Dockerfile
  integration/examples/microservices/leeroy-app/Dockerfile
  integration/examples/microservices/leeroy-web/Dockerfile
  integration/examples/structure-tests/Dockerfile
  integration/examples/tagging-with-environment-variables/Dockerfile
Labels: cla: yes

#2143 Check for env variables for root cmd persistent flags
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/man/man.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2138 skaffold debug: log unsupported objects or versions
  docs/content/en/docs/how-tos/debug/_index.md
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_test.go
Labels: cla: yes

#2148 Simpler code
  cmd/skaffold/app/cmd/config/list.go
  cmd/skaffold/app/cmd/config/set.go
  cmd/skaffold/app/cmd/config/unset.go
  pkg/skaffold/docker/image_util.go
Labels: cla: yes

#2149 Use testutil.NewTempDir() instead
  pkg/skaffold/initializer/kubectl/kubectl_test.go
  pkg/skaffold/initializer/util_test.go
  testutil/util.go
Labels: cla: yes

#2140 Bring helm integration test back
  integration/examples/helm-deployment/skaffold-int.yaml
  integration/helm_test.go
  integration/run_test.go
Labels: cla: yes

#2145 Remove duplication around cobra code.
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/commands/commands.go
  cmd/skaffold/app/cmd/commands/commands_test.go
  cmd/skaffold/app/cmd/config/flags.go
  cmd/skaffold/app/cmd/config/list.go
  cmd/skaffold/app/cmd/config/set.go
  cmd/skaffold/app/cmd/config/unset.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/fix_test.go
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/version.go
Labels: cla: yes

#2131 Fix and improve sync samples
  integration/examples/hot-reload/k8s/node.yaml
  integration/examples/hot-reload/k8s/python.yaml
  integration/examples/hot-reload/node/Dockerfile
  integration/examples/hot-reload/node/k8s/pod.yaml
  integration/examples/hot-reload/node/package-lock.json
  integration/examples/hot-reload/node/package.json
  integration/examples/hot-reload/node/src/index.js
  integration/examples/hot-reload/node/src/server.js
  integration/examples/hot-reload/python/Dockerfile
  integration/examples/hot-reload/python/k8s/pod.yaml
  integration/examples/hot-reload/skaffold.yaml
  integration/examples/nodejs/backend/Dockerfile
  integration/examples/nodejs/backend/k8s/pod.yaml
  integration/examples/nodejs/backend/package.json
  integration/examples/nodejs/k8s/deployment.yaml
  integration/examples/nodejs/skaffold.yaml
  integration/examples/react-reload/app/Dockerfile
  integration/examples/react-reload/app/k8s/pod.yaml
  integration/examples/react-reload/k8s/deployment.yaml
  integration/examples/react-reload/skaffold.yaml
  integration/run_test.go
Labels: cla: yes

#2146 Simpler Travis configuration
  .travis.yml
Labels: cla: yes

#1949 [Design Proposal] Event API v2
  docs/design_proposals/design-proposal-template.md
  docs/design_proposals/event-api-v2.md
Labels: cla: yes

#1905 Additional git tagger variants (TreeSha, AbbrevTreeSha)
  docs/content/en/schemas/v1beta11.json
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/build/tag/tag.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta10/upgrade.go
Labels: cla: yes

#1690 Option to mount HostPath in each Kaniko Pod to be used as cache volume
  docs/content/en/schemas/v1beta11.json
  pkg/skaffold/build/build.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/sources/gcs.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/schema/latest/config.go
Labels: !! config-change !!, cla: yes

#2121 Remove build dep for helm deploy
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes

#2156 Remove some old plugin related code from event handler
  pkg/skaffold/event/event.go
Labels: cla: yes

#2157 Add smoke test for `skaffold diagnose`
  integration/diagnose_test.go
  integration/skaffold/helper.go
Labels: cla: yes

#2058 Support deploying remote helm charts
  docs/content/en/schemas/v1beta11.json
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/schema/latest/config.go
Labels: !! config-change !!, cla: yes

#2155 Refactor the runner a bit
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/run.go
  pkg/skaffold/runner/run_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes

#2128 More tests
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/signals.go
  pkg/skaffold/build/cluster/sources/localdir_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/config/options_test.go
  pkg/skaffold/docker/parse_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/filters.go
  pkg/skaffold/runner/filters_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: cla: yes

#2022 Add Annotations to command and flags per phase annotation.
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/flags_test.go
  cmd/skaffold/app/cmd/run.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
Labels: area/cli, cla: yes

#2141 Add support for npm run-script-based launches for `skaffold debug`
  docs/content/en/docs/how-tos/debug/_index.md
  integration/debug_test.go
  integration/testdata/debug/jib/.gitignore
  integration/testdata/debug/jib/.mvn/wrapper/MavenWrapperDownloader.java
  integration/testdata/debug/jib/.mvn/wrapper/maven-wrapper.jar
  integration/testdata/debug/jib/.mvn/wrapper/maven-wrapper.properties
  integration/testdata/debug/jib/k8s/web.yaml
  integration/testdata/debug/jib/mvnw
  integration/testdata/debug/jib/mvnw.cmd
  integration/testdata/debug/jib/pom.xml
  integration/testdata/debug/jib/src/main/java/hello/Application.java
  integration/testdata/debug/jib/src/main/java/hello/HelloController.java
  integration/testdata/debug/kustomization.yaml
  integration/testdata/debug/nodejs/.dockerignore
  integration/testdata/debug/nodejs/.gitignore
  integration/testdata/debug/nodejs/Dockerfile
  integration/testdata/debug/nodejs/k8s/pod.yaml
  integration/testdata/debug/nodejs/package-lock.json
  integration/testdata/debug/nodejs/package.json
  integration/testdata/debug/nodejs/src/index.js
  integration/testdata/debug/nodejs/src/utils/index.js
  integration/testdata/debug/npm/.dockerignore
  integration/testdata/debug/npm/.gitignore
  integration/testdata/debug/npm/Dockerfile
  integration/testdata/debug/npm/k8s/pod.yaml
  integration/testdata/debug/npm/package-lock.json
  integration/testdata/debug/npm/package.json
  integration/testdata/debug/npm/src/index.js
  integration/testdata/debug/npm/src/utils/index.js
  integration/testdata/debug/skaffold.yaml
  integration/testdata/jib/kustomization.yaml
  integration/testdata/jib/skaffold.yaml
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/util/util.go
Labels: cla: yes

#2118 Add sync test and refactor InParallel
  pkg/skaffold/build/parallel.go
  pkg/skaffold/build/parallel_test.go
  pkg/skaffold/build/sequence_test.go
Labels: cla: yes

#2177 Remove $ from example commands
  examples/microservices/README.adoc
  integration/examples/microservices/README.adoc
Labels: cla: yes

#2172 Fix error in flag refactoring for `skaffold run --tail`
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2178 Remove trailing dot.
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2183 Remove dead code
  testutil/util.go
Labels: cla: yes

#2181 Test tester
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
  testutil/tmp.go
Labels: cla: yes

#2189 Multiple small improvements to unit tests
  cmd/skaffold/app/cmd/config/config_test.go
  integration/skaffold/helper.go
  pkg/skaffold/build/bazel/dependencies_test.go
  pkg/skaffold/build/cache/cache_test.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/local/bazel_test.go
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/jib_gradle.go
  pkg/skaffold/build/local/jib_maven.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/tag/env_template_test.go
  pkg/skaffold/color/formatter_test.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl/images_test.go
  pkg/skaffold/deploy/kubectl/version_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/docker/auth_test.go
  pkg/skaffold/docker/client_test.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/parse_test.go
  pkg/skaffold/gcp/auth_test.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_test.go
  pkg/skaffold/kubernetes/port_forward_test.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/util/env_template.go
  testutil/kubecontext.go
  testutil/util.go
Labels: cla: yes

#2182 Print logs from init containers
  pkg/skaffold/kubernetes/log.go
Labels: cla: yes

#2192 Update _index.md
  docs/content/en/docs/how-tos/builders/_index.md
Labels: cla: yes

#2199 [Refactor] Move gRPC and HTTP server logic out of event package
  pkg/skaffold/event/event.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/server/endpoints.go
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
Labels: cla: yes

#2195 Moar tests
  pkg/skaffold/build/bazel/dependencies_test.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/local/bazel_test.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/color/formatter.go
  pkg/skaffold/color/formatter_test.go
  pkg/skaffold/config/options_test.go
  pkg/skaffold/deploy/kubectl/version_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/docker/client_test.go
  pkg/skaffold/gcp/projectid.go
  pkg/skaffold/gcp/projectid_test.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_test.go
  pkg/skaffold/schema/v1alpha1/upgrade_test.go
  pkg/skaffold/schema/v1alpha2/upgrade.go
  pkg/skaffold/schema/v1alpha2/upgrade_test.go
  pkg/skaffold/schema/v1alpha3/upgrade.go
  pkg/skaffold/schema/v1alpha4/upgrade.go
  pkg/skaffold/schema/v1alpha5/upgrade.go
  pkg/skaffold/version/version_test.go
  pkg/skaffold/yamltags/tags_test.go
  testutil/cmd_helper.go
Labels: cla: yes

#2194 Add a test help to verify that a test panicked
  pkg/skaffold/apiversion/apiversion_test.go
  pkg/skaffold/yamltags/tags_test.go
  testutil/util.go
Labels: cla: yes
