Repository GoogleContainerTools/skaffold, pull requests merged in 2019-11, with the labels that each got.

#3147 Fix splash
  docs/content/en/_index.html
  docs/layouts/partials/footer.html
  docs/static/stylesheets/button.css
  docs/static/stylesheets/colors.css
Labels: cla: yes, size/L

#3068 Skaffold API docs
  docs/content/en/docs/design/api.md
  docs/content/en/docs/references/_index.md
  docs/content/en/docs/references/api/_index.md
  docs/static/stylesheets/tabs.css
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/M

#3152 Fix writing rendered manifests to files
  pkg/skaffold/deploy/kubectl.go
Labels: cla: yes, size/XS

#3154 permissive docs/themes dir creation
  deploy/docs/preview.sh
  go.mod
Labels: cla: yes, size/XS

#3159 [docs] fix alerts
  docs/content/en/docs/design/api.md
  docs/content/en/docs/install/_index.md
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/docs/pipeline-stages/taggers.md
  docs/content/en/docs/quickstart/_index.md
  docs/layouts/shortcodes/alert.html
Labels: cla: yes, priority/p0, size/S

#3167 [docs] remove diagnose from feature matrix.
  docs/content/en/docs/references/deprecation/_index.md
Labels: cla: yes, size/XS

#3164 [docs] docs changes for feature matrix
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/docs/references/deprecation/_index.md
Labels: cla: yes, priority/p0, size/S

#3169 [docs] Working With Skaffold
  docs/content/en/docs/workflows/_index.md
  docs/content/en/docs/workflows/ci-cd.md
  docs/content/en/docs/workflows/debug.md
  docs/content/en/docs/workflows/dev.md
Labels: cla: yes, priority/p0, size/XS

#3170 [docs] Add logging docs
  docs/content/en/docs/pipeline-stages/log-tailing.md
  docs/content/en/docs/pipeline-stages/logging.md
  docs/static/images/log-line-single.png
  docs/static/images/logging-output.png
Labels: cla: yes, priority/p0

#3149 [docs] add init docs
  docs/content/en/docs/design/api.md
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/docs/pipeline-stages/init.md
  docs/content/en/docs/quickstart/_index.md
  docs/content/en/docs/references/deprecation/_index.md
  docs/content/en/docs/tutorials/_index.md
  docs/content/en/docs/tutorials/buildpacks.md
  docs/content/en/docs/workflows/_index.md
  docs/content/en/docs/workflows/ci-cd.md
  docs/content/en/docs/workflows/debug.md
  docs/content/en/docs/workflows/dev.md
  docs/content/en/docs/workflows/getting-started-with-your-project.md
  docs/static/images/init-flow.png
  docs/static/images/jib-multimodule-init-flow.png
  docs/static/images/microservices-init-flow.png
Labels: cla: yes, needs-rebase, priority/p0, size/M

#3174 v1beta18 -> v1
  docs/config.toml
  docs/content/en/schemas/v1.json
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/profile-patches/skaffold.yaml
  integration/examples/bazel/skaffold.yaml
  integration/examples/buildpacks/skaffold.yaml
  integration/examples/custom/skaffold.yaml
  integration/examples/gcb-kaniko/skaffold.yaml
  integration/examples/generate-pipeline/skaffold.yaml
  integration/examples/getting-started/skaffold.yaml
  integration/examples/google-cloud-build/skaffold.yaml
  integration/examples/helm-deployment-dependencies/skaffold.yaml
  integration/examples/helm-deployment/skaffold.yaml
  integration/examples/hot-reload/skaffold.yaml
  integration/examples/jib-gradle/skaffold.yaml
  integration/examples/jib-multimodule/skaffold.yaml
  integration/examples/jib/skaffold.yaml
  integration/examples/kaniko-local/skaffold.yaml
  integration/examples/kaniko/skaffold.yaml
  integration/examples/kustomize/skaffold-kustomize-args.yaml
  integration/examples/kustomize/skaffold.yaml
  integration/examples/microservices/skaffold.yaml
  integration/examples/nodejs/skaffold.yaml
  integration/examples/profile-patches/skaffold.yaml
  integration/examples/profiles/skaffold.yaml
  integration/examples/react-reload/skaffold.yaml
  integration/examples/structure-tests/skaffold.yaml
  integration/examples/tagging-with-environment-variables/skaffold.yaml
  integration/testdata/build/skaffold.yaml
  integration/testdata/custom/skaffold.yaml
  integration/testdata/debug/skaffold.yaml
  integration/testdata/dev/skaffold.yaml
  integration/testdata/gke_loadbalancer/skaffold.yaml
  integration/testdata/jib-gradle/skaffold.yaml
  integration/testdata/jib/skaffold.yaml
  integration/testdata/kaniko-microservices/skaffold.yaml
  integration/testdata/kaniko-sub-folder/skaffold.yaml
  integration/testdata/kaniko-target/skaffold.yaml
  integration/testdata/tagPolicy/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta17/upgrade.go
  pkg/skaffold/schema/v1beta17/upgrade_test.go
Labels: cla: yes, priority/p0, size/M

#3175 [docs] change config version to v1
  docs/content/en/docs/design/api.md
  docs/content/en/docs/pipeline-stages/init.md
  docs/content/en/samples/builders/custom-buildpacks/skaffold.yaml
Labels: cla: yes, priority/p0, size/XS

#3166 [docs] update buildpacks tutorial to custom builder
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/docs/tutorials/_index.md
  docs/content/en/docs/tutorials/custom-builder.md
  docs/content/en/samples/builders/build.sh
  examples/buildpacks/build.sh
  integration/examples/custom/build.sh
Labels: cla: yes, priority/p0, size/M

#3181 [docs] a few docs changes
  docs/content/en/docs/design/api.md
Labels: cla: yes, size/M

#2964 Allow configuring `jib` plugin type
  docs/content/en/schemas/v1beta10.json
  docs/content/en/schemas/v1beta11.json
  docs/content/en/schemas/v1beta12.json
  docs/content/en/schemas/v1beta13.json
  docs/content/en/schemas/v1beta14.json
  docs/content/en/schemas/v1beta15.json
  docs/content/en/schemas/v1beta16.json
  docs/content/en/schemas/v1beta17.json
  docs/content/en/schemas/v1beta9.json
  hack/schemas/main.go
  hack/schemas/testdata/inline/input.go
  hack/schemas/testdata/inline/output.json
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/jib/jib.go
  pkg/skaffold/jib/jib_init.go
  pkg/skaffold/jib/jib_init_test.go
  pkg/skaffold/jib/jib_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta13/upgrade.go
  pkg/skaffold/schema/v1beta13/upgrade_test.go
  pkg/skaffold/schema/v1beta14/config.go
  pkg/skaffold/schema/v1beta15/config.go
  pkg/skaffold/schema/v1beta16/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes, size/L

#3173 [docs] skaffold run docs in Continuous Delivery pipeline
  docs/content/en/docs/workflows/ci-cd.md
Labels: cla: yes, priority/p0, size/S

#3141 init --analyze should return unique image names
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, size/M

#3180 [docs] Right steps for secret creation in `generate-pipeline` flow.
  examples/generate-pipeline/README.adoc
Labels: cla: yes, size/XS

#3179 [docs] minimal jib gcb docs
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/samples/builders/gcb-jib.yaml
Labels: cla: yes, priority/p0, size/S

#3177 [docs] [output] meaningful message for healthcheck context exceeded.
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, priority/p0, size/S

#3137 Use native zsh completion script generator
  cmd/skaffold/app/cmd/completion.go
Labels: cla: yes, size/L

#3185 Fix master branch
  docs/content/en/schemas/v1.json
  pkg/skaffold/schema/v1beta17/config.go
Labels: cla: yes, size/M

#3161 [example] update apiVersion of Deployment
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/deployment.yaml
  examples/helm-deployment-dependencies/skaffold-helm/templates/deployment.yaml
  examples/helm-deployment/skaffold-helm/templates/deployment.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/deployment.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/templates/deployment.yaml
  integration/examples/helm-deployment/skaffold-helm/templates/deployment.yaml
Labels: cla: yes, size/M

#3182 Improve the k8s yaml used in buildpacks sample
  integration/examples/buildpacks/k8s/pod.yaml
  integration/examples/buildpacks/k8s/web.yaml
  integration/examples/buildpacks/skaffold.yaml
  integration/run_test.go
Labels: cla: yes, size/M

#3184 [buildpacks] Run cleanup on ctrl-c
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/docker/containers.go
Labels: cla: yes, size/XS

#3183 Simplify custom builder example
  integration/examples/custom/README.adoc
  integration/examples/custom/build.sh
  integration/examples/custom/k8s/pod.yaml
  integration/examples/custom/skaffold.yaml
Labels: cla: yes

#3114 Fix EnvVarMap indices when caching is enabled
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
Labels: cla: yes, size/M

#3089 Simplify default repo handling and fix #3088
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/images.go
  pkg/skaffold/deploy/kubectl/images_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/docker/default_repo.go
  pkg/skaffold/docker/default_repo_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/runner/build_deploy.go
Labels: cla: yes, size/L

#3191 Fix redundant Jib image flags generated by init
  pkg/skaffold/jib/jib_init.go
  pkg/skaffold/jib/jib_init_test.go
Labels: cla: yes, size/M

#3178 [docs] Add healthcheck
  docs/content/en/docs/workflows/ci-cd.md
  docs/content/en/samples/deployers/healthcheck.yaml
Labels: cla: yes, priority/p0, size/L

#3197 [website] unify fonts
  docs/content/en/_index.html
  docs/layouts/partials/hooks/head-end.html
  docs/layouts/partials/navbar.html
  docs/layouts/shortcodes/blocks/testimonial-section.html
  docs/layouts/shortcodes/blocks/values-section.html
  docs/static/stylesheets/font.css
Labels: cla: yes, priority/p0, size/M

#3196 [docs] quick feedback page update
  docs/content/en/docs/resources/feedback/_index.md
Labels: cla: yes, priority/p0, size/M

#3176 [docs] Cleanup docs
  docs/content/en/docs/pipeline-stages/_index.md
  docs/content/en/docs/pipeline-stages/cleanup.md
  docs/content/en/docs/pipeline-stages/filesync.md
  docs/content/en/docs/pipeline-stages/log-tailing.md
  docs/content/en/docs/pipeline-stages/port-forwarding.md
  docs/content/en/docs/workflows/_index.md
  docs/data/maturity.json
  docs/diagrams/skaffold-workflow.gliffy
  docs/diagrams/skaffold.gliffy
  docs/static/images/architecture.png
  docs/static/images/workflow.png
Labels: cla: yes, priority/p0

#3193 [docs] move builders in to individual pages
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/docs/pipeline-stages/builders/_index.md
  docs/content/en/docs/pipeline-stages/builders/bazel.md
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
  docs/content/en/docs/pipeline-stages/builders/custom.md
  docs/content/en/docs/pipeline-stages/builders/docker.md
  docs/content/en/docs/pipeline-stages/builders/jib.md
  docs/content/en/docs/pipeline-stages/builders/remote.md
  docs/content/en/docs/pipeline-stages/init.md
  docs/content/en/docs/tutorials/custom-builder.md
  docs/data/maturity.json
Labels: cla: yes, priority/p0, size/XL

#3198 [docs] add docs for buildpacks
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
  docs/content/en/docs/pipeline-stages/builders/remote.md
  docs/content/en/samples/builders/buildpacks.yaml
Labels: cla: yes, priority/p0, size/M

#3199 [Doc] Buildpacks
  docs/content/en/docs/_index.md
  docs/content/en/docs/design/_index.md
  docs/content/en/docs/pipeline-stages/builders/_index.md
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
  docs/data/maturity.json
Labels: cla: yes, priority/p0, size/M

#3202 Add example to `skaffold deploy`
  cmd/skaffold/app/cmd/deploy.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/XS

#3201 Remove trailing \n from download url
  cmd/skaffold/app/cmd/runner.go
Labels: cla: yes, size/XS

#3204 [doc] `debug` does not work with buildpack builder and maybe custom builder images too
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/M

#3205 [docs] few left overs from buildpacks PR and camel case
  docs/content/en/docs/design/config.md
  docs/content/en/docs/design/global-config.md
  docs/content/en/docs/environment/image-registries.md
  docs/content/en/docs/environment/kube-context.md
  docs/content/en/docs/environment/templating.md
  docs/content/en/docs/references/deprecation.md
  docs/content/en/docs/workflows/debug.md
  docs/content/en/docs/workflows/dev.md
Labels: cla: yes, priority/p0

#3206 Update splash page video
  docs/static/images/splash.mp4
Labels: cla: yes

#3207 Fixes landing page
  docs/content/en/_index.html
  docs/layouts/partials/hooks/head-end.html
  docs/static/stylesheets/font.css
  docs/static/stylesheets/landing.css
Labels: cla: yes, size/S

#3212 fixed a broken link
  DEVELOPMENT.md
Labels: cla: yes, size/XS

#3215 Fix Kubeclt typo in Init.md
  docs/content/en/docs/pipeline-stages/init.md
Labels: cla: yes, size/XS

#3213 Clean up grammar in log tailing documentation page
  docs/content/en/docs/pipeline-stages/log-tailing.md
Labels: cla: yes, size/XS

#3099 Get current namespace as default namespace for port forwards
  docs/content/en/docs/pipeline-stages/port-forwarding.md
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes, size/L

#2804 [proposal] Improve taggers
  docs/design_proposals/digest-tagger.md
Labels: cla: yes

#3007 Reuse gcr.io tokens
  pkg/skaffold/docker/authenticators.go
  pkg/skaffold/docker/remote.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/auth.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/options.go
  vendor/modules.txt
Labels: cla: yes, size/L

#3214 modified Deadline to Timeout
  hack/linter.sh
Labels: cla: yes, size/XS

#3239 Bump golangci-lint to v1.21.0
  hack/linter.sh
Labels: cla: yes, size/XS

#3241 Faster tests
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/misc/graceful_test.go
Labels: cla: yes, size/XS

#3237 proto generation: Set GOPROXY
  hack/proto/Dockerfile
Labels: cla: yes, size/XS

#3238 Don’t wait for the logs if the pod timed out
  pkg/skaffold/build/cluster/kaniko.go
Labels: cla: yes, size/XS

#3235 Move code next to where it’s used
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/S

#3200 Simplify the code to create a tarball
  pkg/skaffold/util/tar.go
Labels: cla: yes, size/L

#3232 Inline TarGz function
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/sources/upload.go
Labels: cla: yes, size/S

#3040 Support port-forward address bind with skaffold dev
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/pipeline-stages/port-forwarding.md
  docs/content/en/docs/references/api/grpc.md
  docs/content/en/schemas/v1.json
  integration/dev_test.go
  integration/port_forward_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/server/server.go
  pkg/skaffold/util/port.go
  pkg/skaffold/util/port_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#3234 Listing dependencies: remove duplication
  pkg/skaffold/build/build.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/dependencies.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/diagnose.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes, size/L

#3228 Fix skaffold build/deploy example
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/flags/build_output.go
  cmd/skaffold/app/flags/build_output_test.go
  docs/content/en/docs/references/cli/_index.md
  testutil/util.go
Labels: cla: yes, size/M

#3244 Fix schema
  docs/content/en/schemas/v1.json
  docs/content/en/schemas/v2alpha1.json
Labels: cla: yes, size/S

#3251 Add alias for old /docs/getting-started/
  docs/content/en/docs/install/_index.md
Labels: area/docs, cla: yes, size/XS

#3253 briandealwis to buildpacks ownership
  .github/CODEOWNERS
Labels: cla: yes, size/XS

#3233 Simplify code to get GCS/GCB clients
  pkg/skaffold/build/cluster/sources/gcs.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/gcp/client.go
Labels: cla: yes, size/M

#3203 [Buildpacks] Files should belong to the default, non-root, user
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/docker/containers.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/util/tar.go
  pkg/skaffold/util/tar_test.go
Labels: cla: yes, size/L

#3246 Support Buildpacks on Cloud Build
  docs/content/en/docs/_index.md
  docs/content/en/docs/design/_index.md
  docs/content/en/docs/pipeline-stages/builders/_index.md
  integration/examples/buildpacks/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/build/gcb/buildpacks.go
  pkg/skaffold/build/gcb/buildpacks_test.go
  pkg/skaffold/build/gcb/spec.go
Labels: cla: yes, size/L

#3245 Fix auto-project selection for GCB and Kaniko
  integration/build_test.go
  integration/testdata/gcb-default-repo/Dockerfile
  integration/testdata/gcb-default-repo/main.go
  integration/testdata/gcb-default-repo/skaffold.yaml
  integration/testdata/kaniko-default-repo/Dockerfile
  integration/testdata/kaniko-default-repo/main.go
  integration/testdata/kaniko-default-repo/skaffold.yaml
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/sources/gcs.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/gcb/cloud_build.go
Labels: cla: yes, size/L

#3083 [Custom] Support build command with env variables
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
Labels: cla: yes, size/S

#3255 Updating a few dependencies.
  go.mod
  go.sum
  hack/schemas/main.go
  hack/tools/go.sum
  vendor/github.com/google/go-containerregistry/pkg/v1/google/auth.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/v1/google/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/descriptor.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/go.mod
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/modules.txt
Labels: cla: yes

#3258 [Buildpacks] Support env variables on GCB
  pkg/skaffold/build/gcb/buildpacks.go
  pkg/skaffold/build/gcb/buildpacks_test.go
Labels: cla: yes, size/M

#3157 fix kaniko cache-dir
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/kaniko_test.go
Labels: cla: yes, size/XS

#3257 [Buildpacks/GCB] Use $CNB_USER_ID and $CNB_GROUP_ID
  pkg/skaffold/build/gcb/buildpacks.go
  pkg/skaffold/build/gcb/buildpacks_test.go
Labels: cla: yes, size/XS

#3265 Fix markdown to render table
  docs/content/en/docs/design/api.md
Labels: cla: yes, size/XS

#3252 Error instead of opening interactive prompt with --force init
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, pr/lgtm-nit, size/M

#3195 `debug` should replace existing ports or environment values
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
  pkg/skaffold/debug/transform_test.go
Labels: area/debug, cla: yes, kind/bug, pr/lgtm-nit, size/L

#3271 Bump kind to 0.6.0
  .travis.yml
  Makefile
  deploy/skaffold/Dockerfile
Labels: cla: yes, size/XS

#3276 add container spec args
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
Labels: cla: yes, size/S

#3273 fixed indents in skaffold.proto
  proto/skaffold.proto
Labels: cla: yes, size/XS

#3279 Add aliases to old docs, and remove exec permission
  docs/content/en/docs/_index.md
  docs/content/en/docs/design/_index.md
  docs/content/en/docs/design/config.md
  docs/content/en/docs/design/global-config.md
  docs/content/en/docs/environment/image-registries.md
  docs/content/en/docs/environment/kube-context.md
  docs/content/en/docs/environment/local-cluster.md
  docs/content/en/docs/environment/profiles.md
  docs/content/en/docs/environment/templating.md
  docs/content/en/docs/install/_index.md
  docs/content/en/docs/pipeline-stages/_index.md
  docs/content/en/docs/pipeline-stages/builders/_index.md
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
  docs/content/en/docs/pipeline-stages/deployers.md
  docs/content/en/docs/pipeline-stages/filesync.md
  docs/content/en/docs/pipeline-stages/port-forwarding.md
  docs/content/en/docs/pipeline-stages/taggers.md
  docs/content/en/docs/pipeline-stages/testers.md
  docs/content/en/docs/references/_index.md
  docs/content/en/docs/references/yaml/_index.html
  docs/content/en/docs/resources/_index.md
  docs/content/en/docs/tutorials/_index.md
  docs/content/en/docs/workflows/_index.md
  docs/content/en/docs/workflows/debug.md
Labels: area/docs, cla: yes

#3285 document skaffold debug & credits
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
Labels: cla: yes, size/XS

#3283 [doc] Add missing configuration to the git tagger
  docs/content/en/docs/pipeline-stages/taggers.md
Labels: cla: yes, size/XS

#3278 Fix two issues with profiles
  pkg/skaffold/config/options.go
  pkg/skaffold/config/options_test.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: cla: yes, size/M

#3291 fix table on api page
  docs/content/en/docs/design/api.md
  hack/tools/go.sum
Labels: cla: yes, size/XS

#3294 Remove older dependencies
  go.sum
Labels: cla: yes, size/XS

#3306 Bump default Kaniko image
  pkg/skaffold/constants/constants.go
Labels: cla: yes, size/XS

#3305 Simpler assertions
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/test/test_test.go
Labels: cla: yes, size/XS

#3308 Use test helper
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes, size/M

#3299 Improve error output when kompose fails
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/util/cmd.go
Labels: cla: yes, size/XS

#3304 Improve code that chooses random port for tests
  integration/rpc_test.go
Labels: cla: yes, size/XS

#3300 Fix typo in PR template
  .github/pull_request_template.md
Labels: cla: yes, size/XS

#3317 Add more assertion helpers
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/skaffold_test.go
  hack/versions/pkg/diff/godiff_test.go
  hack/versions/pkg/schema/comment_test.go
  integration/render_test.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/gcb/buildpacks_test.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/deploy/kubectl/namespace_test.go
  pkg/skaffold/deploy/resource/base_test.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/filemon/changes_test.go
  pkg/skaffold/filemon/monitor_test.go
  pkg/skaffold/schema/defaults/defaults_test.go
  testutil/util.go
Labels: cla: yes, size/L

#3315 fix docs for env vars in yaml
  docs/content/en/schemas/v2alpha1.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/S
