Repository GoogleContainerTools/skaffold, pull requests merged in 2019-03, with the labels that each got.

#1713 Improve documentation
  docs/content/en/docs/references/yaml/main.css
  docs/content/en/docs/references/yaml/main.js
  docs/content/en/schemas/v1alpha1.json
  docs/content/en/schemas/v1alpha2.json
  docs/content/en/schemas/v1alpha3.json
  docs/content/en/schemas/v1alpha4.json
  docs/content/en/schemas/v1alpha5.json
  docs/content/en/schemas/v1beta1.json
  docs/content/en/schemas/v1beta2.json
  docs/content/en/schemas/v1beta3.json
  docs/content/en/schemas/v1beta4.json
  docs/content/en/schemas/v1beta5.json
  docs/content/en/schemas/v1beta6.json
  hack/schemas/main.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta5/config.go
Labels: cla: yes

#1709 Fix bug in sync
  integration/examples/hot-reload/python/src/app.py
  integration/examples/test-file-sync/skaffold.yaml
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/sync/kubectl/kubectl.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes

#1715 Release v0.24.0
  CHANGELOG.md
  examples/annotated-skaffold.yaml
  examples/bazel/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/node/Dockerfile
  examples/hot-reload/node/src/server.js
  examples/hot-reload/python/Dockerfile
  examples/hot-reload/python/src/app.py
  examples/hot-reload/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
Labels: cla: yes

#1718 Fix typo in option name for 'enable-rpc'
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#1724 Improve `skaffold init` performance by not walking hidden dirs.
  cmd/skaffold/app/cmd/init.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: cla: yes

#1723 Bail out on docker build error
  pkg/skaffold/build/local/docker.go
Labels: cla: yes

#1722 Fix regression in sync
  pkg/skaffold/sync/kubectl/kubectl.go
Labels: cla: yes

#1716 Updated Install section
  README.md
Labels: cla: yes

#1725 Add --analyze flag to skaffold init
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#1730 Update go-containerregistry
  Gopkg.lock
  Gopkg.toml
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  vendor/github.com/google/go-containerregistry/pkg/authn/helper.go
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/name/registry.go
  vendor/github.com/google/go-containerregistry/pkg/v1/config.go
  vendor/github.com/google/go-containerregistry/pkg/v1/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/hash.go
  vendor/github.com/google/go-containerregistry/pkg/v1/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/compressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/uncompressed.go
  vendor/github.com/google/go-containerregistry/pkg/v1/partial/with.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/mount.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/bearer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/ping.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/transport.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/stream/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/layer.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/write.go
  vendor/github.com/google/go-containerregistry/pkg/v1/v1util/nop.go
  vendor/github.com/google/go-containerregistry/pkg/v1/v1util/verify.go
  vendor/github.com/google/go-containerregistry/pkg/v1/v1util/zip.go
Labels: cla: yes

#1729 Test that images that can’t be built are not pushed
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/local_test.go
  testutil/fake_image_api.go
Labels: cla: yes

#1731 Add missing newline
  pkg/skaffold/build/cache.go
Labels: cla: yes

#1735 Try to use the local docker to get the image config
  pkg/skaffold/sync/sync.go
Labels: cla: yes

#1743 Only go through images once for artifact caching
  pkg/skaffold/build/cache.go
  pkg/skaffold/build/cache_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
Labels: cla: yes

#1741 Improve artifact caching
  pkg/skaffold/build/cache.go
  pkg/skaffold/build/cache_test.go
  testutil/tmp.go
Labels: cla: yes

#1736 Upgrade Kaniko to 0.9.0
  pkg/skaffold/constants/constants.go
Labels: cla: yes

#1745 Nicer output
  cmd/skaffold/app/cmd/build.go
  pkg/skaffold/build/cache.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#1750 Simplify integration tests
  Makefile
  appveyor.yml
  integration/build_test.go
  integration/config_test.go
  integration/deploy_test.go
  integration/dev_test.go
  integration/examples/test-dev-job/k8s-job.yaml
  integration/examples/test-dev-job/skaffold.yaml
  integration/fix_test.go
  integration/init_test.go
  integration/main_test.go
  integration/rpc_test.go
  integration/run_test.go
  integration/sync_test.go
  integration/testdata/dev/Dockerfile
  integration/testdata/dev/k8s-job.yaml
  integration/testdata/dev/skaffold.yaml
  integration/testdata/file-sync/Dockerfile
  integration/testdata/file-sync/foo
  integration/testdata/file-sync/pod.yaml
  integration/testdata/file-sync/skaffold.yaml
  integration/testdata/fix/Dockerfile
  integration/testdata/plugin/gcb/leeroy-app/Dockerfile
  integration/testdata/plugin/gcb/leeroy-app/app.go
  integration/testdata/plugin/gcb/leeroy-app/kubernetes/deployment.yaml
  integration/testdata/plugin/gcb/leeroy-web/Dockerfile
  integration/testdata/plugin/gcb/leeroy-web/kubernetes/deployment.yaml
  integration/testdata/plugin/gcb/leeroy-web/web.go
  integration/testdata/plugin/gcb/skaffold.yaml
  integration/testdata/plugin/local/bazel/BUILD
  integration/testdata/plugin/local/bazel/WORKSPACE
  integration/testdata/plugin/local/bazel/k8s/k8s-pod.yaml
  integration/testdata/plugin/local/bazel/main.go
  integration/testdata/plugin/local/bazel/skaffold.yaml
  integration/testdata/plugin/local/docker/leeroy-app/Dockerfile
  integration/testdata/plugin/local/docker/leeroy-app/app.go
  integration/testdata/plugin/local/docker/leeroy-app/kubernetes/deployment.yaml
  integration/testdata/plugin/local/docker/leeroy-web/Dockerfile
  integration/testdata/plugin/local/docker/leeroy-web/kubernetes/deployment.yaml
  integration/testdata/plugin/local/docker/leeroy-web/web.go
  integration/testdata/plugin/local/docker/skaffold.yaml
  integration/util.go
  pkg/skaffold/kubernetes/wait.go
  test.sh
Labels: cla: yes

#1747 Simplify port choosing logic
  pkg/skaffold/kubernetes/port_forward.go
  pkg/skaffold/kubernetes/port_forward_test.go
  pkg/skaffold/util/port.go
Labels: cla: yes

#1727 make initContainer in localDir type of kaniko build param
  docs/content/en/schemas/v1beta6.json
  pkg/skaffold/build/kaniko/sources/localdir.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, config-change

#1752 Add logic for finding next available port for gRPC if provided one is in use
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
  integration/rpc_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/server.go
Labels: cla: yes

#1757 Regenerating schemas for v1beta6 and v1beta7
  docs/content/en/schemas/v1beta6.json
  docs/content/en/schemas/v1beta7.json
Labels: cla: yes

#1755 Improve caching
  pkg/skaffold/build/cache.go
  pkg/skaffold/build/cache_test.go
  pkg/skaffold/build/kaniko/run.go
  pkg/skaffold/plugin/environments/gcb/desc.go
  pkg/skaffold/plugin/environments/gcb/docker.go
  pkg/skaffold/plugin/environments/gcb/docker_test.go
Labels: cla: yes

#1763 added some extra logging for test failures for easier feedback
  test.sh
Labels: cla: yes

#1772 Upgrade Jib to 1.0.2
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
Labels: cla: yes

#1770 Don’t break pages that reference `annotated-skaffold.yaml`
  examples/annotated-skaffold.yaml
Labels: cla: yes

#1760 Remove duplication integration tests
  integration/build_test.go
  integration/config_test.go
  integration/deploy_test.go
  integration/dev_test.go
  integration/fix_test.go
  integration/init_test.go
  integration/rpc_test.go
  integration/run_test.go
  integration/skaffold/helper.go
  integration/sync_test.go
  integration/testdata/config/config.yaml
  integration/testdata/init/.gitignore
  integration/testdata/init/compose/.gitignore
  integration/testdata/init/compose/Dockerfile
  integration/testdata/init/compose/docker-compose.yaml
  integration/testdata/init/compose/main.go
  integration/testdata/init/hello/Dockerfile
  integration/testdata/init/hello/k8s-pod.yaml
  integration/testdata/init/hello/main.go
  integration/testdata/init/microservices/leeroy-app/Dockerfile
  integration/testdata/init/microservices/leeroy-app/app.go
  integration/testdata/init/microservices/leeroy-app/kubernetes/deployment.yaml
  integration/testdata/init/microservices/leeroy-web/Dockerfile
  integration/testdata/init/microservices/leeroy-web/kubernetes/deployment.yaml
  integration/testdata/init/microservices/leeroy-web/web.go
  integration/util.go
  testutil/util.go
Labels: cla: yes

#1777 Upgrade the linter
  cmd/skaffold/app/cmd/completion.go
  cmd/skaffold/app/cmd/runner.go
  hack/linter.sh
  pkg/skaffold/deploy/kubectl/labels.go
Labels: cla: yes

#1776 Improve `make test`
  test.sh
Labels: cla: yes

#1717 Refactor local builder docker code into plugins directory
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/plugin/builders/docker/builder.go
  pkg/skaffold/plugin/builders/docker/builder_test.go
  pkg/skaffold/plugin/builders/docker/docker.go
  pkg/skaffold/plugin/builders/docker/local.go
Labels: cla: yes

#1617 Issue 1178 helm secrets integration
  docs/content/en/schemas/v1beta6.json
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, config-change, needs-rebase

#1780 Add back tracking of forwarded ports to avoid race condition
  pkg/skaffold/event/server.go
  pkg/skaffold/kubernetes/port_forward.go
  pkg/skaffold/kubernetes/port_forward_test.go
  pkg/skaffold/util/port.go
Labels: cla: yes

#1785 Fix schema
  docs/content/en/schemas/v1beta6.json
  docs/content/en/schemas/v1beta7.json
Labels: cla: yes

#1782 adding more logs for webhook
  pkg/webhook/github/github.go
  pkg/webhook/kubernetes/deployment.go
  webhook/webhook.go
Labels: cla: yes

#1775 Try newer versions of Go
  .travis.yml
Labels: cla: yes

#1779 Refactor caching
  pkg/skaffold/build/cache.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/cache_test.go
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cache/save.go
  pkg/skaffold/build/kaniko/run.go
  pkg/skaffold/plugin/environments/gcb/desc.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#1786 Fix race in event logs
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/event/server.go
Labels: cla: yes

#1756 Add Initializer Interface to skaffold to support other deployers in skaffold init
  cmd/skaffold/app/cmd/init.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/kubectl/kubectl.go
  pkg/skaffold/initializer/kubectl/kubectl_test.go
  pkg/skaffold/initializer/util.go
  pkg/skaffold/initializer/util_test.go
  testutil/util.go
Labels: cla: yes

#1764 Add instructions to DEVELOPMENT.md for installing tools
  DEVELOPMENT.md
Labels: cla: yes

#1788 Fake k8s context for test
  pkg/skaffold/build/cache/cache_test.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes

#1789 Faster integration tests
  .travis.yml
  Makefile
  test.sh
Labels: cla: yes

#1791 Initialize LocalCluster in docker local builder plugin
  pkg/skaffold/plugin/builders/docker/local.go
Labels: cla: yes

#1793 added subcommands to the cli reference
  cmd/skaffold/man/man.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#1790 Make integration tests shorter and more stable
  .travis.yml
  DEVELOPMENT.md
  appveyor.yml
  deploy/skaffold/Dockerfile
  examples/README.md
  examples/bazel/skaffold.yaml
  examples/compose/main.go
  examples/kaniko-local/Dockerfile
  examples/kaniko-local/main.go
  examples/kaniko/Dockerfile
  examples/kaniko/main.go
  examples/tagging-with-environment-variables/Dockerfile
  examples/tagging-with-environment-variables/k8s-pod.yaml
  examples/tagging-with-environment-variables/main.go
  integration/examples/README.md
  integration/examples/annotated-skaffold.yaml
  integration/examples/bazel/skaffold.yaml
  integration/examples/compose/main.go
  integration/examples/kaniko-local/Dockerfile
  integration/examples/kaniko-local/main.go
  integration/examples/kaniko/Dockerfile
  integration/examples/kaniko/main.go
  integration/examples/tagging-with-environment-variables/Dockerfile
  integration/examples/tagging-with-environment-variables/k8s-pod.yaml
  integration/examples/tagging-with-environment-variables/main.go
  integration/run_test.go
  integration/skaffold/helper.go
  integration/testdata/dev/Dockerfile
  integration/testdata/file-sync/Dockerfile
  integration/testdata/fix/Dockerfile
  integration/testdata/fix/main.go
  integration/testdata/init/compose/main.go
  integration/testdata/kaniko-sub-folder/sub/Dockerfile
  integration/testdata/kaniko-sub-folder/sub/main.go
  integration/util.go
  pkg/skaffold/kubernetes/wait.go
  pkg/skaffold/kubernetes/wait_test.go
Labels: cla: yes

#1796 Support ctrl-c during tagging and cache checking
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#1799 Check for artifacts in cache in parallel
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
Labels: cla: yes

#1802 Remove debug code
  pkg/skaffold/docker/image_test.go
Labels: cla: yes

#1804 Initialize Artifact.Workspace to "." by default in plugin case too
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes

#1801 Fix race conditions and run tests with a race detector
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  test.sh
Labels: cla: yes

#1800 combined output for integration tests skaffold runner
  integration/fix_test.go
  integration/skaffold/helper.go
Labels: cla: yes

#1797 Refactor KanikoBuild into KanikoArtifact and Cluster
  docs/content/en/samples/builders/kaniko.yaml
  docs/content/en/schemas/v1beta7.json
  integration/examples/kaniko-local/skaffold.yaml
  integration/examples/kaniko/skaffold.yaml
  integration/run_test.go
  integration/testdata/kaniko-microservices/leeroy-app/Dockerfile
  integration/testdata/kaniko-microservices/leeroy-app/app.go
  integration/testdata/kaniko-microservices/leeroy-app/kubernetes/deployment.yaml
  integration/testdata/kaniko-microservices/leeroy-web/Dockerfile
  integration/testdata/kaniko-microservices/leeroy-web/kubernetes/deployment.yaml
  integration/testdata/kaniko-microservices/leeroy-web/web.go
  integration/testdata/kaniko-microservices/skaffold.yaml
  integration/testdata/kaniko-sub-folder/skaffold.yaml
  pkg/skaffold/build/kaniko/run.go
  pkg/skaffold/build/kaniko/run_test.go
  pkg/skaffold/build/kaniko/sources/gcs.go
  pkg/skaffold/build/kaniko/sources/localdir.go
  pkg/skaffold/build/kaniko/sources/sources.go
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/docker/context.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/parse_test.go
  pkg/skaffold/plugin/builders/docker/builder.go
  pkg/skaffold/plugin/environments/gcb/types.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta6/upgrade.go
  pkg/skaffold/schema/v1beta6/upgrade_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, config-change

#1646 Config upgrade: handle helm overrides
  docs/content/en/schemas/v1alpha2.json
  docs/content/en/schemas/v1alpha3.json
  docs/content/en/schemas/v1alpha4.json
  docs/content/en/schemas/v1alpha5.json
  docs/content/en/schemas/v1beta1.json
  docs/content/en/schemas/v1beta2.json
  docs/content/en/schemas/v1beta3.json
  docs/content/en/schemas/v1beta4.json
  docs/content/en/schemas/v1beta5.json
  docs/content/en/schemas/v1beta6.json
  docs/content/en/schemas/v1beta7.json
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/util/util.go
  pkg/skaffold/schema/util/util_test.go
  pkg/skaffold/schema/v1alpha2/config.go
  pkg/skaffold/schema/v1alpha2/upgrade_test.go
  pkg/skaffold/schema/v1alpha3/config.go
  pkg/skaffold/schema/v1alpha4/config.go
  pkg/skaffold/schema/v1alpha5/config.go
  pkg/skaffold/schema/v1beta1/config.go
  pkg/skaffold/schema/v1beta2/config.go
  pkg/skaffold/schema/v1beta3/config.go
  pkg/skaffold/schema/v1beta4/config.go
  pkg/skaffold/schema/v1beta5/config.go
  pkg/skaffold/schema/v1beta6/config.go
Labels: cla: yes

#1808 cut v0.25.0
  CHANGELOG.md
  deprecation-policy.md
  docs/content/en/schemas/v1beta7.json
  examples/bazel/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#1816 Debug integration tests
  integration/config_test.go
  integration/fix_test.go
  integration/run_test.go
  integration/skaffold/helper.go
  integration/testdata/jib/.gitignore
  integration/testdata/jib/.mvn/wrapper/MavenWrapperDownloader.java
  integration/testdata/jib/.mvn/wrapper/maven-wrapper.jar
  integration/testdata/jib/.mvn/wrapper/maven-wrapper.properties
  integration/testdata/jib/k8s/web.yaml
  integration/testdata/jib/mvnw
  integration/testdata/jib/mvnw.cmd
  integration/testdata/jib/pom.xml
  integration/testdata/jib/skaffold.yaml
  integration/testdata/jib/src/main/java/hello/Application.java
  integration/testdata/jib/src/main/java/hello/HelloController.java
  integration/util.go
Labels: cla: yes

#1810 Error if no Dockerfiles are found for skaffold init --analyze
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes

#1821 Check cached artifacts in parallel
  pkg/skaffold/build/cache/retrieve.go
Labels: cla: yes

#1818 Add total time for `skaffold build`
  cmd/skaffold/app/cmd/build.go
Labels: cla: yes

#1832 Check that samples are both in ./examples and ./integration/examples
  hack/check-samples.sh
  test.sh
Labels: cla: yes

#1830 Simplify upgrade code
  pkg/skaffold/schema/v1beta1/upgrade.go
  pkg/skaffold/schema/v1beta2/upgrade.go
  pkg/skaffold/schema/v1beta3/upgrade.go
  pkg/skaffold/schema/v1beta4/upgrade.go
  pkg/skaffold/schema/v1beta5/upgrade.go
  pkg/skaffold/schema/v1beta6/upgrade.go
Labels: cla: yes

#1829 Remove duplication in eventing
  pkg/skaffold/build/parallel.go
  pkg/skaffold/build/sequence.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/event/server.go
  pkg/skaffold/kubernetes/port_forward.go
Labels: cla: yes

#1827 Improve test coverage
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes

#1831 Fix Safari issue on skaffold.dev yaml reference
  docs/content/en/docs/references/yaml/_index.html
  docs/content/en/docs/references/yaml/main.js
Labels: cla: yes

#1828 Add unit tests for kustomize
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes

#1833 Fixing nit
  pkg/skaffold/schema/v1beta6/upgrade.go
Labels: cla: yes

#1817 Faster git tagger
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/git_commit_test.go
Labels: cla: yes

#1834 Increase integration tests timeout to 15minutes
  Makefile
Labels: cla: yes

#1813 Preserve sync subtree for '***'.
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes

#1820 Compute tags in parallel
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#1835 Basic unit test to go through all the cobra related code
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/completion.go
  cmd/skaffold/app/skaffold.go
  cmd/skaffold/app/skaffold_test.go
  cmd/skaffold/skaffold.go
Labels: cla: yes

#1843 Support 1.11+ as a kubectl version
  pkg/skaffold/deploy/kubectl/version.go
  pkg/skaffold/deploy/kubectl/version_test.go
Labels: cla: yes

#1845 fix Markdown rendering deprecation-policy.md
  deprecation-policy.md
Labels: cla: yes

#1846 Fix warning with `find` on TravisCI
  hack/check-samples.sh
Labels: cla: yes

#1840 Improve test coverage
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/validate.go
  pkg/skaffold/docker/validate_test.go
  pkg/skaffold/plugin/environments/gcb/desc_test.go
  pkg/skaffold/plugin/environments/gcb/jib_test.go
  test.sh
Labels: cla: yes

#1825 Add HTTP reverse proxy for gRPC server to expose REST API for event server
  Gopkg.lock
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
  hack/boilerplate/boilerplate.py
  integration/rpc_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/proto/skaffold.pb.go
  pkg/skaffold/event/proto/skaffold.pb.gw.go
  pkg/skaffold/event/proto/skaffold.proto
  pkg/skaffold/event/server.go
  pkg/skaffold/event/server_test.go
  vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
  vendor/github.com/golang/protobuf/protoc-gen-go/generator/generator.go
  vendor/github.com/golang/protobuf/protoc-gen-go/generator/internal/remap/remap.go
  vendor/github.com/golang/protobuf/protoc-gen-go/plugin/plugin.pb.go
  vendor/github.com/golang/protobuf/ptypes/struct/struct.pb.go
  vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/stream_chunk.pb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_httpbodyproto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_json.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_proto.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler_registry.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto2_convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/proto_errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/LICENSE
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/doc.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/pattern.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/readerfactory.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/trie.go
  vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go
  vendor/google.golang.org/genproto/protobuf/field_mask/field_mask.pb.go
Labels: cla: yes

#1826 Add React example app featuring hot module reload
  examples/react-reload/README.adoc
  examples/react-reload/app/.babelrc
  examples/react-reload/app/.dockerignore
  examples/react-reload/app/.gitignore
  examples/react-reload/app/Dockerfile
  examples/react-reload/app/k8s/pod.yaml
  examples/react-reload/app/package.json
  examples/react-reload/app/src/components/HelloWorld.js
  examples/react-reload/app/src/index.html
  examples/react-reload/app/src/main.js
  examples/react-reload/app/src/styles/HelloWorld.css
  examples/react-reload/app/webpack.config.js
  examples/react-reload/skaffold.yaml
  integration/examples/react-reload/README.adoc
  integration/examples/react-reload/app/.babelrc
  integration/examples/react-reload/app/.dockerignore
  integration/examples/react-reload/app/.gitignore
  integration/examples/react-reload/app/Dockerfile
  integration/examples/react-reload/app/k8s/pod.yaml
  integration/examples/react-reload/app/package.json
  integration/examples/react-reload/app/src/components/HelloWorld.js
  integration/examples/react-reload/app/src/index.html
  integration/examples/react-reload/app/src/main.js
  integration/examples/react-reload/app/src/styles/HelloWorld.css
  integration/examples/react-reload/app/webpack.config.js
  integration/examples/react-reload/skaffold.yaml
Labels: cla: yes

#1848 removing unnecessary exit from plugin processes
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/skaffold.go
  pkg/skaffold/build/plugin/core.go
  pkg/skaffold/plugin/builders/bazel/bazel.go
  pkg/skaffold/plugin/builders/docker/docker.go
Labels: cla: yes

#1858 Enhance hack/check-samples script
  hack/check-samples.sh
Labels: cla: yes

#1855 Add portName to the PortEvent payload of the event api
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/event/proto/skaffold.pb.go
  pkg/skaffold/event/proto/skaffold.proto
  pkg/skaffold/kubernetes/port_forward.go
  pkg/skaffold/kubernetes/port_forward_test.go
Labels: cla: yes

#1811 Refactor Wait Utils Into Watchers
  pkg/skaffold/kubernetes/wait.go
Labels: cla: yes

#1809 Add tests for skaffold init walk flow.
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  testutil/tmp.go
Labels: cla: yes

#1864 Verify patches and fail with a proper error message
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: cla: yes

#1871 removing goroutine leak
  pkg/skaffold/watch/triggers.go
Labels: cla: yes

#1863 Add missing env variables in CLI reference doc
  cmd/skaffold/man/man.go
  cmd/skaffold/man/man_test.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#1850 Don't expose ports to the outside and fix a race condition
  pkg/skaffold/event/server.go
  pkg/skaffold/util/port.go
  pkg/skaffold/util/port_test.go
Labels: cla: yes

#1875 Improve Doc’s Dockerfile
  deploy/webhook/Dockerfile
Labels: cla: yes

#1874 Fix go routine leak
  pkg/skaffold/watch/triggers.go
Labels: cla: yes

#1841 Fix skaffold build templating output and add tests
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#1368 Add integration testing and example for skipBuildDependencies option
  examples/helm-deployment-dependencies/Dockerfile
  examples/helm-deployment-dependencies/README.adoc
  examples/helm-deployment-dependencies/skaffold-helm/.helmignore
  examples/helm-deployment-dependencies/skaffold-helm/Chart.yaml
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/.helmignore
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/Chart.yaml
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/_helpers.tpl
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/deployment.yaml
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/ingress.yaml
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/service.yaml
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/values.yaml
  examples/helm-deployment-dependencies/skaffold-helm/requirements.yaml
  examples/helm-deployment-dependencies/skaffold-helm/templates/_helpers.tpl
  examples/helm-deployment-dependencies/skaffold-helm/templates/deployment.yaml
  examples/helm-deployment-dependencies/skaffold-helm/templates/ingress.yaml
  examples/helm-deployment-dependencies/skaffold-helm/templates/service.yaml
  examples/helm-deployment-dependencies/skaffold-helm/values.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  integration/examples/helm-deployment-dependencies/Dockerfile
  integration/examples/helm-deployment-dependencies/README.adoc
  integration/examples/helm-deployment-dependencies/skaffold-helm/.helmignore
  integration/examples/helm-deployment-dependencies/skaffold-helm/Chart.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/.helmignore
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/Chart.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/_helpers.tpl
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/deployment.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/ingress.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/service.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/values.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/requirements.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/templates/_helpers.tpl
  integration/examples/helm-deployment-dependencies/skaffold-helm/templates/deployment.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/templates/ingress.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/templates/service.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/values.yaml
  integration/examples/helm-deployment-dependencies/skaffold.yaml
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, needs-rebase

#1878 Add folders to tarballs
  pkg/skaffold/util/tar.go
  pkg/skaffold/util/tar_test.go
Labels: cla: yes

#1882 more docs for profiles
  deploy/docs/local-preview.sh
  docs/content/en/docs/how-tos/profiles/_index.md
  docs/content/en/samples/profiles/activations.yaml
  docs/content/en/samples/profiles/patches.yaml
  docs/content/en/schemas/v1beta8.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#1702 Add debugging support for Skaffold: `skaffold debug`
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/dev.go
  docs/content/en/docs/how-tos/_index.md
  docs/content/en/docs/how-tos/debug/_index.md
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/event/proto/skaffold.pb.go
  testutil/util.go
Labels: cla: yes

#1883 Improve manual installation instruction for windows
  .github/ISSUE_TEMPLATE.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  cmd/skaffold/app/cmd/build.go
  docs/README.md
  docs/content/en/docs/_index.md
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/docs/how-tos/deployers/_index.md
  docs/content/en/docs/how-tos/filesync/_index.md
  docs/content/en/docs/how-tos/profiles/_index.md
  docs/content/en/docs/how-tos/taggers/_index.md
  docs/content/en/docs/how-tos/templating/_index.md
  docs/content/en/docs/how-tos/testers/_index.md
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/tutorials/_index.md
  hack/release.sh
Labels: cla: yes

#1873 Fix unnecessary warning in caching
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/cache_test.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cache/save.go
  pkg/skaffold/build/cache/save_test.go
  pkg/skaffold/runner/runner.go
  testutil/fake_image_api.go
Labels: cla: yes

#1886 Revert "freeze v1beta7 config"
  docs/config.toml
  docs/content/en/schemas/v1beta7.json
  docs/content/en/schemas/v1beta8.json
  integration/examples/bazel/skaffold.yaml
  integration/examples/getting-started/skaffold.yaml
  integration/examples/helm-deployment/skaffold.yaml
  integration/examples/hot-reload/skaffold.yaml
  integration/examples/jib-multimodule/skaffold.yaml
  integration/examples/jib/skaffold.yaml
  integration/examples/kaniko-local/skaffold.yaml
  integration/examples/kaniko/skaffold.yaml
  integration/examples/kustomize/skaffold.yaml
  integration/examples/microservices/skaffold.yaml
  integration/examples/nodejs/skaffold.yaml
  integration/examples/react-reload/skaffold.yaml
  integration/examples/structure-tests/skaffold.yaml
  integration/examples/tagging-with-environment-variables/skaffold.yaml
  integration/testdata/build/skaffold.yaml
  integration/testdata/dev/skaffold.yaml
  integration/testdata/file-sync/skaffold.yaml
  integration/testdata/jib/skaffold.yaml
  integration/testdata/kaniko-microservices/skaffold.yaml
  integration/testdata/kaniko-sub-folder/skaffold.yaml
  integration/testdata/plugin/gcb/skaffold.yaml
  integration/testdata/plugin/local/bazel/skaffold.yaml
  integration/testdata/plugin/local/docker/skaffold.yaml
  integration/testdata/tagPolicy/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta6/upgrade.go
  pkg/skaffold/schema/v1beta6/upgrade_test.go
  pkg/skaffold/schema/v1beta7/config.go
  pkg/skaffold/schema/v1beta7/upgrade.go
  pkg/skaffold/schema/v1beta7/upgrade_test.go
  pkg/skaffold/schema/versions.go
Labels: cla: yes

#1888 cut v0.26.0
  CHANGELOG.md
Labels: cla: yes

#1894 Remove container-friendly flags for Java 8
  examples/jib-multimodule/project1/pom.xml
  examples/jib-multimodule/project2/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-multimodule/project1/pom.xml
  integration/examples/jib-multimodule/project2/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes
