Repository GoogleContainerTools/skaffold, pull requests merged in 2019-06, with the labels that each got.

#2006 Cross compile Skaffold, with CGO=1, using xgo
  Makefile
  deploy/cross/Dockerfile
Labels: cla: yes

#2212 Simplify schema upgrades: remove duplication
  pkg/skaffold/schema/v1alpha4/upgrade.go
  pkg/skaffold/schema/v1alpha5/upgrade.go
  pkg/skaffold/schema/v1beta10/upgrade.go
  pkg/skaffold/schema/v1beta7/upgrade.go
  pkg/skaffold/schema/v1beta8/upgrade.go
  pkg/skaffold/util/util.go
Labels: cla: yes

#2210 Faster Travis CI
  .travis.yml
Labels: cla: yes

#2209 Improve output for docker push
  pkg/skaffold/docker/image.go
Labels: cla: yes

#2179 Refactor cmd builder
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/commands/commands.go
  cmd/skaffold/app/cmd/commands_test.go
  cmd/skaffold/app/cmd/config.go
  cmd/skaffold/app/cmd/config/flags.go
  cmd/skaffold/app/cmd/config/list.go
  cmd/skaffold/app/cmd/config/set.go
  cmd/skaffold/app/cmd/config/unset.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/version.go
Labels: cla: yes

#2201 Add API build trigger
  integration/rpc_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/runner/context/context.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/server/endpoints.go
  pkg/skaffold/server/proto/skaffold.pb.go
  pkg/skaffold/server/proto/skaffold.pb.gw.go
  pkg/skaffold/server/proto/skaffold.proto
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
  pkg/skaffold/watch/triggers.go
  pkg/skaffold/watch/triggers_test.go
Labels: cla: yes

#2216 Revert "Improve output for docker push"
  pkg/skaffold/docker/image.go
Labels: cla: yes

#2193 Test helper to make tests less verbose
  cmd/skaffold/app/cmd/build_test.go
  pkg/skaffold/build/bazel/dependencies_test.go
  pkg/skaffold/build/custom/custom_test.go
  testutil/util.go
Labels: cla: yes

#2213 Make notify trigger the default trigger
  cmd/skaffold/app/cmd/dev.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/watch/triggers.go
  pkg/skaffold/watch/watch.go
Labels: cla: yes

#2214 Add CI on windows
  .travis.yml
  hack/schemas/main.go
  hack/schemas/main_test.go
Labels: cla: yes

#2219 Remove AppVeyor
  appveyor.yml
Labels: cla: yes

#2221 Fix master branch
  cmd/skaffold/man/man_test.go
Labels: cla: yes

#2186 Improve documentation for kaniko
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/schemas/v1beta11.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, kind/documentation

#2228 Restore defaulting to polling trigger
  cmd/skaffold/app/cmd/dev.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, priority/p0

#2232 v0.31.0 release
  CHANGELOG.md
Labels: cla: yes

#2230 Dep ensure
  Gopkg.lock
  vendor/github.com/hashicorp/go-hclog/LICENSE
  vendor/github.com/hashicorp/go-hclog/global.go
  vendor/github.com/hashicorp/go-hclog/int.go
  vendor/github.com/hashicorp/go-hclog/log.go
  vendor/github.com/hashicorp/go-hclog/nulllogger.go
  vendor/github.com/hashicorp/go-hclog/stacktrace.go
  vendor/github.com/hashicorp/go-hclog/stdlog.go
  vendor/github.com/hashicorp/go-plugin/LICENSE
  vendor/github.com/hashicorp/go-plugin/client.go
  vendor/github.com/hashicorp/go-plugin/discover.go
  vendor/github.com/hashicorp/go-plugin/error.go
  vendor/github.com/hashicorp/go-plugin/grpc_broker.go
  vendor/github.com/hashicorp/go-plugin/grpc_client.go
  vendor/github.com/hashicorp/go-plugin/grpc_controller.go
  vendor/github.com/hashicorp/go-plugin/grpc_server.go
  vendor/github.com/hashicorp/go-plugin/internal/proto/gen.go
  vendor/github.com/hashicorp/go-plugin/internal/proto/grpc_broker.pb.go
  vendor/github.com/hashicorp/go-plugin/internal/proto/grpc_controller.pb.go
  vendor/github.com/hashicorp/go-plugin/log_entry.go
  vendor/github.com/hashicorp/go-plugin/mtls.go
  vendor/github.com/hashicorp/go-plugin/mux_broker.go
  vendor/github.com/hashicorp/go-plugin/plugin.go
  vendor/github.com/hashicorp/go-plugin/process.go
  vendor/github.com/hashicorp/go-plugin/process_posix.go
  vendor/github.com/hashicorp/go-plugin/process_windows.go
  vendor/github.com/hashicorp/go-plugin/protocol.go
  vendor/github.com/hashicorp/go-plugin/rpc_client.go
  vendor/github.com/hashicorp/go-plugin/rpc_server.go
  vendor/github.com/hashicorp/go-plugin/server.go
  vendor/github.com/hashicorp/go-plugin/server_mux.go
  vendor/github.com/hashicorp/go-plugin/stream.go
  vendor/github.com/hashicorp/go-plugin/testing.go
  vendor/github.com/hashicorp/yamux/LICENSE
  vendor/github.com/hashicorp/yamux/addr.go
  vendor/github.com/hashicorp/yamux/const.go
  vendor/github.com/hashicorp/yamux/mux.go
  vendor/github.com/hashicorp/yamux/session.go
  vendor/github.com/hashicorp/yamux/stream.go
  vendor/github.com/hashicorp/yamux/util.go
  vendor/github.com/mitchellh/go-testing-interface/LICENSE
  vendor/github.com/mitchellh/go-testing-interface/testing.go
  vendor/github.com/mitchellh/go-testing-interface/testing_go19.go
  vendor/github.com/oklog/run/LICENSE
  vendor/github.com/oklog/run/group.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/health.go
Labels: cla: yes

#2236 remove webhook from coverage report
  codecov.yml
Labels: cla: yes

#2239 Add unit tests for WaitForPodSucceeded
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/kubernetes/wait.go
  pkg/skaffold/kubernetes/wait_test.go
Labels: cla: yes

#2238 add test for one method in diagnose.
  pkg/skaffold/docker/parse.go
  pkg/skaffold/runner/diagnose_test.go
Labels: cla: yes

#2246 Mark `debug` as alpha
  deprecation-policy.md
Labels: cla: yes

#2242 Improve code coverage
  cmd/skaffold/app/cmd/config/config_test.go
  cmd/skaffold/app/cmd/config/util.go
  cmd/skaffold/app/cmd/runner_test.go
  cmd/skaffold/man/man.go
  cmd/skaffold/man/man_test.go
  hack/schemas/main_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/context/context_test.go
  pkg/skaffold/runner/context/context.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/util/config_test.go
  pkg/skaffold/util/tar_non_windows_test.go
  pkg/skaffold/util/tar_test.go
  pkg/skaffold/util/util_test.go
  testutil/env.go
  testutil/tmp.go
  testutil/util.go
Labels: cla: yes

#2233 Expand values file paths prefixed with ~
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes

#2247 Add `debug` codeowners
  .github/CODEOWNERS
Labels: cla: yes

#2251 fix racey test
  pkg/skaffold/kubernetes/wait_test.go
Labels: cla: yes

#2252 fix static linking of linux binary
  Makefile
  deploy/cross/Dockerfile
Labels: cla: yes

#2259 Simpler Makefile
  Makefile
Labels: cla: yes

#2244 Implements `skaffold find-configs -d <dir>` command
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/find_configs.go
  cmd/skaffold/app/cmd/find_configs_test.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2253 another testcase for local builder
  pkg/skaffold/build/local/local_test.go
Labels: cla: yes

#2248 Upgrade golangci-lint to v1.17.1
  cmd/skaffold/app/cmd/build.go
  docs/content/en/docs/references/cli/_index.md
  hack/linter.sh
  pkg/skaffold/build/local/local_test.go
Labels: cla: yes

#2250 ability to `make integration` only on a chosen set of integration tests
  DEVELOPMENT.md
  Makefile
Labels: cla: yes

#2260 Add resources to Kaniko init container
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/build/cluster/sources/localdir_test.go
Labels: cla: yes

#2265 Bumping kustomize version fixes #2137
  deploy/skaffold/Dockerfile
Labels: cla: yes

#2266 cluster builder fails to detect insecure registries
  pkg/skaffold/build/cluster/types.go
Labels: cla: yes

#2285 Update debug owners
  .github/CODEOWNERS
Labels: cla: yes

#2275 adding tests for cluster builder
  pkg/skaffold/build/cluster/types_test.go
Labels: cla: yes

#2288 Docker is case sensitive about networks
  docs/content/en/schemas/v1beta10.json
  docs/content/en/schemas/v1beta11.json
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta10/config.go
  pkg/skaffold/schema/validation/validation.go
Labels: cla: yes

#2291 comment setup for codecov
  codecov.yml
Labels: cla: yes

#2270 Add K8sManagedBy function to labeller
  pkg/skaffold/runner/labeller.go
  pkg/skaffold/runner/labeller_test.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#2205 Add Python debugging support
  docs/content/en/docs/how-tos/debug/_index.md
  integration/debug_test.go
  integration/testdata/debug/kustomization.yaml
  integration/testdata/debug/nodejs/package.json
  integration/testdata/debug/npm/package.json
  integration/testdata/debug/python3/Dockerfile
  integration/testdata/debug/python3/app.py
  integration/testdata/debug/python3/k8s/pod.yaml
  integration/testdata/debug/python3/requirements.txt
  integration/testdata/debug/skaffold.yaml
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: area/debug, cla: yes

#2292 more debug codeowner-ship
  .github/CODEOWNERS
Labels: cla: yes

#2293 Fix codecov2
  codecov.yml
Labels: cla: yes

#2279 Fix config reload in skaffold dev
  cmd/skaffold/app/cmd/dev.go
  pkg/skaffold/runner/context/context.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
  pkg/skaffold/watch/triggers.go
  pkg/skaffold/watch/triggers_test.go
Labels: cla: yes

#2048 Add custom artifact type to cluster builder
  docs/content/en/docs/how-tos/builders/_index.md
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/cluster_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/local/custom.go
  pkg/skaffold/build/local/custom_test.go
  pkg/skaffold/constants/constants.go
Labels: build/custom, cla: yes

#2298 Remove the `config out of date` warning
  pkg/skaffold/schema/versions.go
Labels: cla: yes

#2272 Add resourceType and resourceName to PortForward event
  pkg/skaffold/constants/constants.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/kubernetes/port_forward.go
  pkg/skaffold/kubernetes/port_forward_test.go
  pkg/skaffold/server/proto/skaffold.pb.go
  pkg/skaffold/server/proto/skaffold.proto
Labels: cla: yes

#2300 Handle `eu.gcr.io` like `gcr.io` when replacing default image
  pkg/skaffold/util/image.go
  pkg/skaffold/util/image_test.go
Labels: cla: yes

#2305 cut release 0.32.0
  CHANGELOG.md
Labels: cla: yes

#2286 Optimized loading of Docker images into kind nodes
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/kind.go
  pkg/skaffold/runner/kind_test.go
Labels: cla: yes

#2299 Support buildArgs with `useDockerCLI=false` and Kaniko
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/kaniko_test.go
  pkg/skaffold/docker/auth_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/docker/parse.go
  testutil/fake_image_api.go
Labels: cla: yes

#2302 Jib builder should not reuse commands
  pkg/skaffold/build/local/jib_gradle.go
  pkg/skaffold/build/local/jib_maven.go
  pkg/skaffold/jib/jib.go
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_test.go
  pkg/skaffold/util/wrapper_unix.go
  pkg/skaffold/util/wrapper_windows.go
Labels: cla: yes

#2313 Update Kaniko
  pkg/skaffold/constants/constants.go
Labels: cla: yes

#2308 Add an integration test for Kaniko with a Target
  integration/run_test.go
  integration/testdata/kaniko-target/Dockerfile
  integration/testdata/kaniko-target/k8s-pod.yaml
  integration/testdata/kaniko-target/main.go
  integration/testdata/kaniko-target/skaffold.yaml
Labels: cla: yes

#2307 Refactor the SkaffoldRunner
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/runner_test.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/run.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#2309 Improve tests
  cmd/skaffold/app/cmd/find_configs_test.go
  cmd/skaffold/app/flags/build_output_test.go
  pkg/skaffold/build/bazel/dependencies_test.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/validate_test.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_test.go
  pkg/skaffold/runner/diagnose_test.go
  pkg/skaffold/schema/versions_test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/util/tar_test.go
  pkg/skaffold/util/util_test.go
  pkg/skaffold/util/wrapper_unix_test.go
  pkg/skaffold/util/wrapper_windows_test.go
  pkg/skaffold/watch/changes_test.go
  pkg/skaffold/watch/watch_test.go
  testutil/tmp.go
  testutil/util.go
Labels: cla: yes

#2316 Add scripts to test and generate files from proto
  hack/generate-proto.sh
  hack/proto/Dockerfile
  hack/test-generated-proto.sh
  pkg/skaffold/server/proto/skaffold.pb.go
  test.sh
Labels: cla: yes

#2297 Improve and test the notify trigger
  pkg/skaffold/watch/triggers.go
  pkg/skaffold/watch/watch_test.go
Labels: cla: yes

#2319 Skip flaky test
  pkg/skaffold/watch/watch_test.go
Labels: cla: yes

#2257 stop receiving the signals
  cmd/skaffold/app/cmd/signals.go
Labels: cla: yes

#2311 upgrade go bazel rules to in examples to fix bazel breaking release 0.18.6
  examples/bazel/.bazelrc
  examples/bazel/WORKSPACE
  integration/examples/bazel/.bazelrc
  integration/examples/bazel/WORKSPACE
  integration/testdata/custom/.bazelrc
  integration/testdata/custom/WORKSPACE
Labels: cla: yes

#2332 Add missing v1beta11 version
  pkg/skaffold/schema/samples_test.go
  pkg/skaffold/schema/versions.go
Labels: cla: yes

#2274 Refactor skaffold init for more flexible builder detection
  pkg/skaffold/docker/docker_init.go
  pkg/skaffold/docker/docker_init_test.go
  pkg/skaffold/docker/validate.go
  pkg/skaffold/docker/validate_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes

#2333 Kaniko: fix host path support
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/kaniko_test.go
Labels: cla: yes

#2328 Don’t always start the rpc server
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
Labels: cla: yes

#2215 Redesign port forwarding
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/how-tos/portforward/_index.md
  docs/content/en/schemas/v1beta12.json
  pkg/skaffold/config/options.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/kubernetes/port_forward.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/kubernetes/wait_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/schema/latest/config.go
  testutil/util.go
Labels: cla: yes

#2335 Move default labeller to deploy since it used in deployer.
  pkg/skaffold/deploy/labeller.go
  pkg/skaffold/deploy/labeller_test.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#2343 Update examples
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  integration/examples/google-cloud-build/skaffold.yaml
  integration/examples/helm-deployment-dependencies/skaffold.yaml
  integration/examples/helm-deployment/skaffold-int.yaml
  integration/helm_test.go
  integration/testdata/helm/.dockerignore
  integration/testdata/helm/Dockerfile
  integration/testdata/helm/skaffold-helm/.helmignore
  integration/testdata/helm/skaffold-helm/Chart.yaml
  integration/testdata/helm/skaffold-helm/templates/_helpers.tpl
  integration/testdata/helm/skaffold-helm/templates/deployment.yaml
  integration/testdata/helm/skaffold-helm/templates/ingress.yaml
  integration/testdata/helm/skaffold-helm/templates/service.yaml
  integration/testdata/helm/skaffold-helm/values.yaml
  integration/testdata/helm/skaffold.yaml
  integration/testdata/helm/static/index.html
  integration/testdata/helm/static/style.css
Labels: cla: yes

#2349 Kustomize: pick up patchesStrategicMerge changes
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes

#2347 Restart the dev loop when the skaffold config changes
  cmd/skaffold/app/cmd/dev.go
Labels: cla: yes

#2345 Validate port-forwards by attempting to bind to port
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
Labels: cla: yes

#2340 Fix handling of multi stage builds
  integration/testdata/build/multi-stage/Dockerfile
  integration/testdata/build/skaffold.yaml
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/syncmap_test.go
Labels: cla: yes

#2353 Add portforward diagram to docs
  docs/content/en/docs/how-tos/portforward/_index.md
  docs/static/images/portforward.png
Labels: cla: yes

#2363 Update Jib to 1.3.0
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes

#2338 Add status check flag
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/man/man.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#2362 Update toolchain and make sure versions are pinned
  deploy/skaffold/Dockerfile
Labels: cla: yes

#2336 Add support for user defined port forwarding
  docs/content/en/schemas/v1beta12.json
  integration/examples/microservices/leeroy-web/kubernetes/deployment.yaml
  integration/examples/microservices/skaffold.yaml
  pkg/skaffold/constants/constants.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes

#2361 Schemas: Make sure preferredOrder is in sync with field order in Go structs
  docs/content/en/schemas/v1beta10.json
  docs/content/en/schemas/v1beta11.json
  docs/content/en/schemas/v1beta12.json
  docs/content/en/schemas/v1beta8.json
  docs/content/en/schemas/v1beta9.json
  hack/schemas/main.go
  hack/schemas/testdata/inline/input.go
  hack/schemas/testdata/inline/output.json
Labels: cla: yes

#2367 Better error message for references that can’t be parsed
  pkg/skaffold/docker/remote.go
  pkg/skaffold/gcp/projectid.go
Labels: cla: yes

#2323 Improve the logs
  pkg/skaffold/kubernetes/log.go
  pkg/skaffold/kubernetes/log_test.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/dev.go
Labels: cla: yes
