Repository GoogleContainerTools/skaffold, pull requests merged in 2019-02, with the labels that each got.

#1576 Fix DEVELOPMENT.md fragment
  DEVELOPMENT.md
Labels: cla: yes

#1541 Better profiles
  Gopkg.lock
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/runner.go
  integration/examples/annotated-skaffold.yaml
  pkg/skaffold/config/options.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  vendor/github.com/krishicks/yaml-patch/LICENSE
  vendor/github.com/krishicks/yaml-patch/container.go
  vendor/github.com/krishicks/yaml-patch/node.go
  vendor/github.com/krishicks/yaml-patch/operation.go
  vendor/github.com/krishicks/yaml-patch/patch.go
  vendor/github.com/krishicks/yaml-patch/pathfinder.go
  vendor/github.com/krishicks/yaml-patch/placeholder_wrapper.go
Labels: cla: yes

#1579 Improve the Skaffold.dev documentation
  README.md
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/completion.go
  cmd/skaffold/app/cmd/config.go
  cmd/skaffold/app/cmd/config/list.go
  cmd/skaffold/app/cmd/config/set.go
  cmd/skaffold/app/cmd/config/unset.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/init.go
  deploy/docs/build.sh
  deploy/docs/preview.sh
  deprecation-policy.md
  docs/.DS_Store
  docs/content/en/docs/_index.md
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/how-tos/_index.md
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/docs/how-tos/deployers/_index.md
  docs/content/en/docs/how-tos/filesync/_index.md
  docs/content/en/docs/how-tos/portforward/_index.md
  docs/content/en/docs/how-tos/profiles/_index.md
  docs/content/en/docs/how-tos/taggers/_index.md
  docs/content/en/docs/how-tos/templating/_index.md
  docs/content/en/docs/how-tos/testers/_index.md
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
  docs/content/en/docs/resources/_index.md
  docs/static/favicons/android-144x144.png
  docs/static/favicons/android-192x192.png
  docs/static/favicons/android-36x36.png
  docs/static/favicons/android-48x48.png
  docs/static/favicons/android-72x72.png
  docs/static/favicons/android-96x96.png
  docs/static/favicons/apple-touch-icon-180x180.png
  docs/static/favicons/favicon-16x16.png
  docs/static/favicons/favicon-32x32.png
  docs/static/favicons/pwa-192x192.png
  docs/static/favicons/pwa-512x512.png
  docs/static/favicons/tile150x150.png
  docs/static/favicons/tile310x150.png
  docs/static/favicons/tile310x310.png
  docs/static/favicons/tile70x70.png
  docs/static/images/architecture.png
  docs/static/images/workflow.png
  docs/static/images/workflow_gcb.png
  docs/static/images/workflow_local.png
  examples/annotated-skaffold.yaml
  integration/examples/annotated-skaffold.yaml
  pkg/skaffold/deploy/kubectl/version.go
  pkg/skaffold/schema/versions.go
Labels: cla: yes, documentation

#1588 Allow user to specify custom kaniko image
  pkg/skaffold/build/kaniko/sources/sources.go
Labels: cla: yes

#1590 Remove stopped containers in make targets
  Makefile
Labels: cla: yes

#1591 Add --build-image option to build command
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/dev.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/filters.go
  pkg/skaffold/runner/filters_test.go
Labels: cla: yes

#1489 [kubectl] apply labels by patching yaml
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/labels.go
  pkg/skaffold/deploy/kubectl/labels_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/labels.go
Labels: cla: yes

#1575 Add missing tests for build/sequence.go
  pkg/skaffold/build/sequence_test.go
Labels: cla: yes

#1482 New tagging mechanism
  docs/content/en/docs/how-tos/templating/_index.md
  integration/examples/annotated-skaffold.yaml
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/desc.go
  pkg/skaffold/build/gcb/desc_test.go
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/jib.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/kaniko/kaniko.go
  pkg/skaffold/build/kaniko/run.go
  pkg/skaffold/build/local/bazel.go
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/jib.go
  pkg/skaffold/build/local/jib_gradle.go
  pkg/skaffold/build/local/jib_maven.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/build/sequence_test.go
  pkg/skaffold/build/tag/custom.go
  pkg/skaffold/build/tag/custom_test.go
  pkg/skaffold/build/tag/date_time.go
  pkg/skaffold/build/tag/date_time_test.go
  pkg/skaffold/build/tag/env_template.go
  pkg/skaffold/build/tag/env_template_test.go
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/build/tag/sha256.go
  pkg/skaffold/build/tag/sha256_test.go
  pkg/skaffold/build/tag/tag.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/docker/image_test.go
  testutil/fake_image_api.go
Labels: cla: yes

#1603 Upgrade to Kaniko v0.8.0
  pkg/skaffold/constants/constants.go
Labels: cla: yes

#1602 Remove unused constants
  pkg/skaffold/constants/constants.go
Labels: cla: yes

#1604 Ignore cache-from pull errors
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/tag/env_template.go
  pkg/skaffold/build/tag/env_template_test.go
  pkg/skaffold/deploy/kubectl/images.go
  pkg/skaffold/deploy/kubectl/images_test.go
  pkg/skaffold/warnings/warnings.go
Labels: cla: yes

#1607 fix docs build
  docs/content/en/docs/how-tos/taggers/_index.md
Labels: cla: yes

#1599 Improve documentation
  docs/content/en/docs/_index.md
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/how-tos/_index.md
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/docs/how-tos/deployers/_index.md
  docs/content/en/docs/how-tos/filesync/_index.md
  docs/content/en/docs/how-tos/portforward/_index.md
  docs/content/en/docs/how-tos/profiles/_index.md
  docs/content/en/docs/how-tos/taggers/_index.md
  docs/content/en/docs/how-tos/templating/_index.md
  docs/content/en/docs/how-tos/testers/_index.md
  docs/content/en/docs/references/_index.md
  docs/content/en/docs/resources/_index.md
  docs/content/en/docs/tutorials/_index.md
  docs/content/en/search.md
Labels: cla: yes, documentation

#1616 Fix regression from port forwarding
  pkg/skaffold/kubernetes/port_forward.go
  pkg/skaffold/kubernetes/port_forward_test.go
Labels: cla: yes

#1587 Check for new skaffold version when skaffold.yaml parsing fails
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/update/update.go
  pkg/webhook/kubernetes/deployment.go
Labels: cla: yes

#1613 Fix sub directory support with Kaniko and GCB
  integration/run_test.go
  integration/testdata/fix/Dockerfile
  integration/testdata/fix/k8s-pod.yaml
  integration/testdata/fix/main.go
  integration/testdata/fix/skaffold.yaml
  integration/testdata/gcb-sub-folder/k8s/pod.yaml
  integration/testdata/gcb-sub-folder/skaffold.yaml
  integration/testdata/gcb-sub-folder/sub/Dockerfile
  integration/testdata/gcb-sub-folder/sub/main.go
  integration/testdata/kaniko-sub-folder/k8s/pod.yaml
  integration/testdata/kaniko-sub-folder/skaffold.yaml
  integration/testdata/kaniko-sub-folder/sub/Dockerfile
  integration/testdata/kaniko-sub-folder/sub/main.go
  pkg/skaffold/docker/context.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/util/tar.go
  pkg/skaffold/util/tar_non_windows_test.go
  pkg/skaffold/util/tar_test.go
  testutil/util.go
Labels: cla: yes

#1584 adding scripts for preparing new config version
  hack/new_config_version/version.go
  hack/new_version.sh
Labels: cla: yes

#1620 Rollback Docker dependencies filtering based on target
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/parse_test.go
Labels: cla: yes

#1626 Handle env commands with multiple variable definitions (#1625)
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/parse_test.go
Labels: cla: yes

#1628 Adding a few tests for `skaffold build`
  integration/run_test.go
  integration/testdata/build/Dockerfile
  integration/testdata/build/multi-env/Dockerfile
  integration/testdata/build/multi-env/file1
  integration/testdata/build/multi-env/file2
  integration/testdata/build/skaffold.yaml
  integration/testdata/build/sub-directory/Dockerfile
  integration/testdata/build/sub-directory/file1
  integration/testdata/build/sub-directory/file2
  integration/testdata/build/targets/Dockerfile
  integration/testdata/build/targets/file1
  integration/testdata/build/targets/file2
  integration/testdata/build/targets/file3
Labels: cla: yes

#1637 Add short docs about automatic port-forwarding
  docs/content/en/docs/how-tos/portforward/_index.md
Labels: cla: yes

#1634 Don't push all tags when sha256 builds just one
  pkg/skaffold/build/tag/sha256.go
  pkg/skaffold/build/tag/sha256_test.go
Labels: cla: yes

#1630 Add more comments to the Config structs
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#1618 Add --color option
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/color/formatter.go
  pkg/skaffold/color/formatter_test.go
Labels: cla: yes

#1635 Add integration tests for taggers
  integration/run_test.go
  integration/testdata/tagPolicy/Dockerfile
  integration/testdata/tagPolicy/skaffold.yaml
Labels: cla: yes

#1644 Generate json schema
  Makefile
  hack/new_version.sh
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/versions.go
  pkg/skaffold/schema/versions_test.go
  schemas/main.go
  schemas/main_test.go
  schemas/v1alpha1.json
  schemas/v1alpha2.json
  schemas/v1alpha3.json
  schemas/v1alpha4.json
  schemas/v1alpha5.json
  schemas/v1beta1.json
  schemas/v1beta2.json
  schemas/v1beta3.json
  schemas/v1beta4.json
  schemas/v1beta5.json
Labels: cla: yes, wip

#1647 kubectl deployer: warn when pattern matches no file
  pkg/skaffold/util/util.go
Labels: cla: yes

#1642 Add `required` tags
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/yamltags/tags.go
  schemas/v1beta5.json
Labels: cla: yes

#1641 Optimise sync
  pkg/skaffold/sync/kubectl/kubectl.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/util/tar.go
Labels: cla: yes

#1609 Add custom build arguments in jib artifacts
  examples/annotated-skaffold.yaml
  integration/examples/annotated-skaffold.yaml
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, config-change

#1652 Improve comments and schema
  Gopkg.lock
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/schema/latest/config.go
  schemas/main.go
  schemas/v1alpha1.json
  schemas/v1alpha2.json
  schemas/v1alpha3.json
  schemas/v1alpha4.json
  schemas/v1alpha5.json
  schemas/v1beta1.json
  schemas/v1beta2.json
  schemas/v1beta3.json
  schemas/v1beta4.json
  schemas/v1beta5.json
  vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  vendor/github.com/shurcooL/sanitized_anchor_name/main.go
  vendor/gopkg.in/russross/blackfriday.v2/LICENSE.txt
  vendor/gopkg.in/russross/blackfriday.v2/block.go
  vendor/gopkg.in/russross/blackfriday.v2/doc.go
  vendor/gopkg.in/russross/blackfriday.v2/esc.go
  vendor/gopkg.in/russross/blackfriday.v2/html.go
  vendor/gopkg.in/russross/blackfriday.v2/inline.go
  vendor/gopkg.in/russross/blackfriday.v2/markdown.go
  vendor/gopkg.in/russross/blackfriday.v2/node.go
  vendor/gopkg.in/russross/blackfriday.v2/smartypants.go
Labels: cla: yes

#1655 cut v0.23.0
  CHANGELOG.md
  deprecation-policy.md
  examples/annotated-skaffold.yaml
  examples/bazel/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
Labels: cla: yes

#1661 first cut at jib doc
  docs/content/en/docs/how-tos/builders/_index.md
Labels: cla: yes

#1659 Generate annotated-skaffold.yaml
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles.go
  schemas/index.html
  schemas/main.css
  schemas/main.go
  schemas/main.js
  schemas/v1alpha1.json
  schemas/v1alpha2.json
  schemas/v1alpha3.json
  schemas/v1alpha4.json
  schemas/v1alpha5.json
  schemas/v1beta1.json
  schemas/v1beta2.json
  schemas/v1beta3.json
  schemas/v1beta4.json
  schemas/v1beta5.json
Labels: cla: yes

#1679 Update HUGO
  deploy/webhook/Dockerfile
Labels: cla: yes

#1676 Add example of a Jib-Maven multi-module project
  examples/jib-multimodule/.gitignore
  examples/jib-multimodule/.mvn/wrapper/MavenWrapperDownloader.java
  examples/jib-multimodule/.mvn/wrapper/maven-wrapper.jar
  examples/jib-multimodule/.mvn/wrapper/maven-wrapper.properties
  examples/jib-multimodule/README.adoc
  examples/jib-multimodule/k8s/web.yaml
  examples/jib-multimodule/mvnw
  examples/jib-multimodule/mvnw.cmd
  examples/jib-multimodule/pom.xml
  examples/jib-multimodule/project1/pom.xml
  examples/jib-multimodule/project1/src/main/java/hello/Application.java
  examples/jib-multimodule/project1/src/main/java/hello/HelloController.java
  examples/jib-multimodule/project2/pom.xml
  examples/jib-multimodule/project2/src/main/java/hello/Application.java
  examples/jib-multimodule/project2/src/main/java/hello/HelloController.java
  examples/jib-multimodule/skaffold.yaml
  integration/examples/jib-multimodule/.gitignore
  integration/examples/jib-multimodule/.mvn/wrapper/MavenWrapperDownloader.java
  integration/examples/jib-multimodule/.mvn/wrapper/maven-wrapper.jar
  integration/examples/jib-multimodule/.mvn/wrapper/maven-wrapper.properties
  integration/examples/jib-multimodule/README.adoc
  integration/examples/jib-multimodule/k8s/web.yaml
  integration/examples/jib-multimodule/mvnw
  integration/examples/jib-multimodule/mvnw.cmd
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-multimodule/project1/pom.xml
  integration/examples/jib-multimodule/project1/src/main/java/hello/Application.java
  integration/examples/jib-multimodule/project1/src/main/java/hello/HelloController.java
  integration/examples/jib-multimodule/project2/pom.xml
  integration/examples/jib-multimodule/project2/src/main/java/hello/Application.java
  integration/examples/jib-multimodule/project2/src/main/java/hello/HelloController.java
  integration/examples/jib-multimodule/skaffold.yaml
Labels: cla: yes

#1675 Generate skaffold references
  Makefile
  deprecation-policy.md
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/docs/how-tos/deployers/_index.md
  docs/content/en/docs/how-tos/profiles/_index.md
  docs/content/en/docs/how-tos/taggers/_index.md
  docs/content/en/docs/references/_index.md
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
  docs/content/en/docs/references/yaml/_index.html
  docs/content/en/docs/references/yaml/main.css
  docs/content/en/docs/references/yaml/main.js
  docs/content/en/schemas/v1alpha1.json
  docs/content/en/schemas/v1alpha2.json
  docs/content/en/schemas/v1alpha3.json
  docs/content/en/schemas/v1alpha4.json
  docs/content/en/schemas/v1alpha5.json
  docs/content/en/schemas/v1beta1.json
  docs/content/en/schemas/v1beta2.json
  docs/content/en/schemas/v1beta3.json
  docs/content/en/schemas/v1beta4.json
  docs/content/en/schemas/v1beta5.json
  docs/layouts/shortcodes/schema.html
  hack/new_version.sh
  hack/schemas/main.go
  hack/schemas/main_test.go
  integration/examples/annotated-skaffold.yaml
  integration/run_test.go
  pkg/skaffold/schema/latest/config.go
  schemas/index.html
Labels: cla: yes

#1680 Make the hot-reload example more exemplary
  integration/examples/hot-reload/node/Dockerfile
  integration/examples/hot-reload/node/src/server.js
  integration/examples/hot-reload/python/Dockerfile
  integration/examples/hot-reload/python/src/app.py
  integration/examples/hot-reload/skaffold.yaml
Labels: cla: yes

#1672 added default-repo to getting started
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/tutorials/_index.md
Labels: cla: yes

#1684 added logging to skaffold dev integration tests
  integration/run_test.go
Labels: cla: yes

#1678 Restructure integration tests
  integration/build_test.go
  integration/config_test.go
  integration/deploy_test.go
  integration/dev_test.go
  integration/fix_test.go
  integration/init_test.go
  integration/main_test.go
  integration/run_test.go
  integration/sync_test.go
  integration/util.go
Labels: cla: yes

#1656 Added local execution environment to docker builder plugin
  integration/examples/test-plugin/local/docker/leeroy-app/Dockerfile
  integration/examples/test-plugin/local/docker/leeroy-app/app.go
  integration/examples/test-plugin/local/docker/leeroy-app/kubernetes/deployment.yaml
  integration/examples/test-plugin/local/docker/leeroy-web/Dockerfile
  integration/examples/test-plugin/local/docker/leeroy-web/kubernetes/deployment.yaml
  integration/examples/test-plugin/local/docker/leeroy-web/web.go
  integration/examples/test-plugin/local/docker/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/build/docker/docker.go
Labels: cla: yes

#1686 Diagnose skaffold.yaml
  cmd/skaffold/app/cmd/diagnose.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#1687 Add a test for changing tests with a profile
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#1685 completion: add wrapper code to transform bash to zsh completion
  cmd/skaffold/app/cmd/completion.go
Labels: cla: yes

#1693 Handle pointers in profile overlay
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#1694 Build before
  integration/sync_test.go
Labels: cla: yes

#1673 Helm flags for Global, Install and Upgrade helm commands
  docs/content/en/schemas/v1beta6.json
  examples/annotated-skaffold.yaml
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#1699 Fix gke connection for Integration tests
  Makefile
  integration/main_test.go
Labels: cla: yes

#1632 Add artifact cache to track artifacts for faster restart
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/schemas/v1beta6.json
  pkg/skaffold/build/cache.go
  pkg/skaffold/build/cache_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/util/util.go
  testutil/fake_image_api.go
Labels: cla: yes

#1697 Fix default-repo handling for images with non-alphabetic characters
  pkg/skaffold/util/image.go
  pkg/skaffold/util/image_test.go
Labels: cla: yes

#1701 Fix schemas
  docs/content/en/docs/references/yaml/main.js
  docs/content/en/schemas/v1alpha1.json
  docs/content/en/schemas/v1alpha2.json
  docs/content/en/schemas/v1alpha3.json
  docs/content/en/schemas/v1alpha4.json
  docs/content/en/schemas/v1alpha5.json
  docs/content/en/schemas/v1beta1.json
  docs/content/en/schemas/v1beta2.json
  docs/content/en/schemas/v1beta3.json
  docs/content/en/schemas/v1beta4.json
  docs/content/en/schemas/v1beta5.json
  docs/content/en/schemas/v1beta6.json
  docs/layouts/shortcodes/schema.html
  hack/schemas/main.go
Labels: cla: yes

#1574 Add gRPC based event API
  Gopkg.lock
  Gopkg.toml
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/run.go
  docs/content/en/docs/references/cli/_index.md
  hack/boilerplate/boilerplate.py
  integration/rpc_test.go
  pkg/skaffold/build/bazel/bazel.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/parallel.go
  pkg/skaffold/build/parallel_test.go
  pkg/skaffold/build/sequence.go
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/proto/skaffold.pb.go
  pkg/skaffold/event/proto/skaffold.proto
  pkg/skaffold/event/server.go
  pkg/skaffold/kubernetes/port_forward.go
  pkg/skaffold/runner/runner.go
  vendor/github.com/golang/protobuf/proto/decode.go
  vendor/github.com/golang/protobuf/proto/deprecated.go
  vendor/github.com/golang/protobuf/proto/equal.go
  vendor/github.com/golang/protobuf/proto/extensions.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/message_set.go
  vendor/github.com/golang/protobuf/proto/pointer_reflect.go
  vendor/github.com/golang/protobuf/proto/pointer_unsafe.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/golang/protobuf/proto/table_marshal.go
  vendor/github.com/golang/protobuf/proto/table_unmarshal.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
  vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
  vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
  vendor/github.com/golang/protobuf/ptypes/empty/empty.pb.go
  vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
Labels: cla: yes, needs-rebase
