Repository GoogleContainerTools/skaffold, pull requests merged in 2019-07, with the labels that each got.

#2369 Upgrade kind to 0.4.0
  .travis.yml
  Makefile
  deploy/skaffold/Dockerfile
Labels: cla: yes

#2371 Add a test to Kaniko builder
  pkg/skaffold/build/cluster/sources/sources_test.go
Labels: cla: yes

#2375 Reduce the amount of logs
  deploy/skaffold/Dockerfile
Labels: cla: yes

#2342 Support Cluster config with a path
  integration/testdata/regressions/docker-config-path/skaffold.yaml
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/samples_test.go
Labels: cla: yes

#2382 Start API server only once
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/sequence_test.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
Labels: cla: yes

#2383 Increase test coverage on Jib Builder
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven_test.go
  testutil/util.go
Labels: cla: yes

#2378 Use goroutine for sync
  pkg/skaffold/sync/sync.go
Labels: cla: yes

#2386 match some more jib files in owners
  .github/CODEOWNERS
Labels: cla: yes

#2348 Fix support for URL manifests
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
Labels: cla: yes

#2352 Fix missing logs when kaniko exists immediately
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/logs.go
Labels: cla: yes

#2390 Jib Builder: add more tests
  pkg/skaffold/build/local/jib_gradle.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local.go
Labels: cla: yes

#2392 Configure linter to check for unclosed http body
  hack/linter.sh
  integration/rpc_test.go
Labels: cla: yes

#2391 Custom Builder: Fix bug when no deps specified
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes

#2312 Bazel: support sub directories
  pkg/skaffold/build/bazel/dependencies.go
  pkg/skaffold/build/bazel/dependencies_test.go
Labels: cla: yes

#2388 Fix schema doc
  docs/content/en/docs/references/yaml/_index.html
  docs/content/en/docs/references/yaml/main.js
  docs/content/en/schemas/v1alpha2.json
  docs/content/en/schemas/v1alpha3.json
  docs/content/en/schemas/v1alpha4.json
  docs/content/en/schemas/v1alpha5.json
  docs/content/en/schemas/v1beta1.json
  docs/content/en/schemas/v1beta10.json
  docs/content/en/schemas/v1beta11.json
  docs/content/en/schemas/v1beta12.json
  docs/content/en/schemas/v1beta2.json
  docs/content/en/schemas/v1beta3.json
  docs/content/en/schemas/v1beta4.json
  docs/content/en/schemas/v1beta5.json
  docs/content/en/schemas/v1beta6.json
  docs/content/en/schemas/v1beta7.json
  docs/content/en/schemas/v1beta8.json
  docs/content/en/schemas/v1beta9.json
  hack/schemas/main.go
  hack/schemas/main_test.go
  hack/schemas/testdata/integer/input.go
  hack/schemas/testdata/integer/output.json
Labels: cla: yes

#2394 cut v0.33.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/leeroy-web/kubernetes/deployment.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
Labels: cla: yes

#2389 Fix minor warnings on doc site
  docs/content/en/_index.html
  docs/static/stylesheets/tabs.css
Labels: cla: yes

#2399 Simplify test debug
  integration/debug_test.go
  integration/testdata/debug/nodejs/Dockerfile
  integration/testdata/debug/npm/Dockerfile
  integration/testdata/debug/python3/Dockerfile
Labels: cla: yes

#2354 Transfer control of dev loop from file watcher to dev listener
  integration/dev_test.go
  pkg/skaffold/filemon/changes.go
  pkg/skaffold/filemon/changes_test.go
  pkg/skaffold/filemon/monitor.go
  pkg/skaffold/filemon/monitor_test.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/changeset.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/runner/diagnose.go
  pkg/skaffold/runner/listen.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/trigger/triggers.go
  pkg/skaffold/trigger/triggers_test.go
  pkg/skaffold/watch/watch.go
Labels: cla: yes, needs-rebase

#2393 Move docker code where it belongs
  pkg/skaffold/build/local/bazel.go
  pkg/skaffold/docker/remote.go
Labels: cla: yes

#2396 Build with Go 1.12
  .travis.yml
  DEVELOPMENT.md
  deploy/skaffold/Dockerfile
  deploy/webhook/Dockerfile
  examples/compose/Dockerfile
  examples/getting-started/Dockerfile
  examples/google-cloud-build/Dockerfile
  examples/kaniko-local/Dockerfile
  examples/kaniko/Dockerfile
  examples/microservices/leeroy-app/Dockerfile
  examples/microservices/leeroy-web/Dockerfile
  examples/structure-tests/Dockerfile
  examples/tagging-with-environment-variables/Dockerfile
  integration/examples/compose/Dockerfile
  integration/examples/getting-started/Dockerfile
  integration/examples/google-cloud-build/Dockerfile
  integration/examples/kaniko-local/Dockerfile
  integration/examples/kaniko/Dockerfile
  integration/examples/microservices/leeroy-app/Dockerfile
  integration/examples/microservices/leeroy-web/Dockerfile
  integration/examples/structure-tests/Dockerfile
  integration/examples/tagging-with-environment-variables/Dockerfile
  integration/testdata/fix/Dockerfile
  integration/testdata/gcb-sub-folder/sub/Dockerfile
  integration/testdata/init/compose/Dockerfile
  integration/testdata/init/hello/Dockerfile
  integration/testdata/init/microservices/leeroy-app/Dockerfile
  integration/testdata/init/microservices/leeroy-web/Dockerfile
  integration/testdata/kaniko-microservices/leeroy-app/Dockerfile
  integration/testdata/kaniko-microservices/leeroy-web/Dockerfile
  integration/testdata/kaniko-sub-folder/sub/Dockerfile
  integration/testdata/kaniko-target/Dockerfile
Labels: cla: yes

#2269 Allow for remote kustomize bases
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes

#2402 Faster proto generation
  hack/generate-proto.sh
  hack/proto/Dockerfile
Labels: cla: yes

#2413 Fix Monitor test
  pkg/skaffold/filemon/monitor.go
  pkg/skaffold/filemon/monitor_test.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/runner/listen.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes

#2406 Better integration tests
  .travis.yml
  Makefile
  integration/dev_test.go
  integration/util.go
Labels: cla: yes

#2065 :sparkles: Add support for regexp in profile activation kubeContext
  docs/content/en/docs/how-tos/profiles/_index.md
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: cla: yes

#2415 Correctly migrate sync config in profiles
  pkg/skaffold/schema/v1beta9/upgrade.go
  pkg/skaffold/schema/v1beta9/upgrade_test.go
Labels: cla: yes

#2403 Feat(sync): skip sync on non-running pods
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes

#2424 Wait for parallel builds to be cancelled on error
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
  pkg/skaffold/build/parallel.go
Labels: cla: yes

#2428 Remove unused property
  integration/dev_test.go
Labels: cla: yes

#2419 Fix proto generation test
  hack/generate-proto.sh
  hack/test-generated-proto.sh
  integration/rpc_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/server/endpoints.go
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
  proto/skaffold.pb.go
  proto/skaffold.pb.gw.go
  proto/skaffold.proto
Labels: cla: yes

#2429 Fix script that creates a new version to make it work on osx
  hack/new_config_version/version.go
  hack/new_version.sh
  pkg/skaffold/schema/util/util.go
  pkg/skaffold/schema/v1beta10/upgrade_test.go
  pkg/skaffold/schema/v1beta11/upgrade_test.go
  pkg/skaffold/schema/v1beta9/upgrade_test.go
  pkg/skaffold/schema/versions.go
Labels: cla: yes

#2324 Improve skaffold help output
  Gopkg.lock
  Gopkg.toml
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/skaffold_test.go
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
  vendor/github.com/MakeNowJust/heredoc/LICENSE
  vendor/github.com/MakeNowJust/heredoc/heredoc.go
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/github.com/mitchellh/go-wordwrap/LICENSE.md
  vendor/github.com/mitchellh/go-wordwrap/wordwrap.go
  vendor/github.com/russross/blackfriday/LICENSE.txt
  vendor/github.com/russross/blackfriday/block.go
  vendor/github.com/russross/blackfriday/html.go
  vendor/github.com/russross/blackfriday/inline.go
  vendor/github.com/russross/blackfriday/latex.go
  vendor/github.com/russross/blackfriday/markdown.go
  vendor/github.com/russross/blackfriday/smartypants.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubectl/pkg/util/interrupt/interrupt.go
  vendor/k8s.io/kubectl/pkg/util/templates/command_groups.go
  vendor/k8s.io/kubectl/pkg/util/templates/markdown.go
  vendor/k8s.io/kubectl/pkg/util/templates/normalizers.go
  vendor/k8s.io/kubectl/pkg/util/templates/templater.go
  vendor/k8s.io/kubectl/pkg/util/templates/templates.go
  vendor/k8s.io/kubectl/pkg/util/term/resize.go
  vendor/k8s.io/kubectl/pkg/util/term/resizeevents.go
  vendor/k8s.io/kubectl/pkg/util/term/resizeevents_windows.go
  vendor/k8s.io/kubectl/pkg/util/term/term.go
  vendor/k8s.io/kubectl/pkg/util/term/term_writer.go
Labels: cla: yes

#2434 Improve `skaffold help`
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/config.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/find_configs.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/man/man.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2418 Update dev guide with regards to integration tests
  DEVELOPMENT.md
Labels: cla: yes

#2417 Test regexp usage in profiles activation
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: cla: yes

#2420 Add support for kustomization resources (#2416)
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes

#2423 Watch namespaces for each Helm release
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/runner/context/context.go
  pkg/skaffold/runner/util/util.go
  pkg/skaffold/runner/util/util_test.go
Labels: cla: yes

#2283 Kaniko proxy
  docs/content/en/schemas/v1beta13.json
  hack/generate-proto.sh
  pkg/skaffold/build/cluster/sources/localdir_test.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/schema/latest/config.go
  proto/skaffold.pb.go
Labels: !! config-change !!, cla: yes

#2445 Set out on the root command
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/commands_test.go
  cmd/skaffold/app/cmd/completion.go
  cmd/skaffold/app/cmd/config.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/find_configs.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/version.go
Labels: cla: yes

#2441 Pruning should happen after Cleanup
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/dev_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_util.go
Labels: cla: yes

#2427 The user is now able to disable RPC in dev mode
  cmd/skaffold/app/cmd/cmd.go
  integration/rpc_test.go
Labels: cla: yes

#2438 Add resync/rebuild directly in monitor callback
  pkg/skaffold/runner/changeset.go
  pkg/skaffold/runner/dev.go
Labels: cla: yes

#2436 Add back /v1/event_log endpoint for events
  integration/rpc_test.go
  pkg/skaffold/server/endpoints.go
  proto/skaffold.pb.go
  proto/skaffold.pb.gw.go
  proto/skaffold.proto
Labels: cla: yes, needs-rebase

#2446 Fix proto generation and testing
  hack/generate-proto.sh
  hack/proto/Dockerfile
  hack/test-generated-proto.sh
Labels: cla: yes

#2437 Add a `metadata.name` field to skaffold.yaml
  docs/content/en/schemas/v1beta13.json
  pkg/skaffold/schema/latest/config.go
Labels: !! config-change !!, cla: yes

#2439 Support alternative Kustomization config filenames (#2422)
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes

#2327 Update skaffold init --analyze to handle more builder types
  cmd/skaffold/app/cmd/init.go
  pkg/skaffold/docker/docker_init.go
  pkg/skaffold/docker/docker_init_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes

#2449 Test Sync mode with both triggers
  integration/sync_test.go
Labels: cla: yes

#2359 Add deployment health check implementation
  cmd/skaffold/app/cmd/flags.go
  integration/deploy_test.go
  integration/run_test.go
  integration/testdata/unstable-deployment/Dockerfile
  integration/testdata/unstable-deployment/README.adoc
  integration/testdata/unstable-deployment/hello
  integration/testdata/unstable-deployment/incorrect-deployment.yaml
  integration/testdata/unstable-deployment/skaffold.yaml
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/runner.go
  testutil/cmd_helper.go
Labels: cla: yes, needs-rebase

#2452 Simplify caching
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
  testutil/fake_image_api.go
Labels: cla: yes

#2456 [caching] Simpler code and fixing nits
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/schema/v1beta10/config.go
  pkg/skaffold/schema/v1beta11/config.go
  pkg/skaffold/schema/v1beta12/config.go
  pkg/skaffold/schema/v1beta6/config.go
  pkg/skaffold/schema/v1beta7/config.go
  pkg/skaffold/schema/v1beta8/config.go
  pkg/skaffold/schema/v1beta9/config.go
  pkg/skaffold/util/util.go
Labels: cla: yes

#2455 Upgrade go-containerregistry
  Gopkg.lock
  Gopkg.toml
  pkg/skaffold/docker/remote.go
  vendor/github.com/google/go-containerregistry/pkg/internal/retry/retry.go
  vendor/github.com/google/go-containerregistry/pkg/name/digest.go
  vendor/github.com/google/go-containerregistry/pkg/name/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/platform.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/check.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/delete.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/descriptor.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/index.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/list.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/basic.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/error.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/retry.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
Labels: cla: yes

#2453 Support --reproducible for Kaniko build
  docs/content/en/schemas/v1beta13.json
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/kaniko_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#2461 Better mock for docker.ImageID
  pkg/skaffold/docker/image_test.go
  testutil/fake_image_api.go
Labels: cla: yes

#2454 Add `options` command to show global flags
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2467 Improve the logs when there's no skaffold.yaml
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/runner.go
Labels: cla: yes

#2480 Upgrade to Jib 1.4.0
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes

#2482 Default to notify trigger
  cmd/skaffold/app/cmd/dev.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2476 File output flag for writing built images to a specified file
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2483 Add `skaffold config` examples
  cmd/skaffold/app/cmd/config.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2487 Upgrade go container registry to remove spurious logs
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go
  vendor/github.com/google/go-containerregistry/pkg/logs/logs.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/options.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
Labels: cla: yes

#2470 Revisited artifact caching
  integration/build_test.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/cache_test.go
  pkg/skaffold/build/cache/details.go
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cache/save.go
  pkg/skaffold/build/cache/save_test.go
  pkg/skaffold/build/cache/types.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/gcb/desc.go
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/local/jib_gradle.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/docker/reference.go
  pkg/skaffold/docker/reference_test.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/diagnose.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/schema/latest/config.go
  testutil/fake_image_api.go
Labels: cla: yes

#2490 Little increase to Code coverage
  pkg/skaffold/util/env_template.go
  pkg/skaffold/util/env_template_test.go
Labels: cla: yes

#2489 Add a few more examples to commands with -—help
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/commands_test.go
  cmd/skaffold/app/cmd/config.go
  cmd/skaffold/app/cmd/run.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2494 Simpler faster find configs
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/commands_test.go
  cmd/skaffold/app/cmd/find_configs.go
  cmd/skaffold/app/cmd/find_configs_test.go
Labels: cla: yes

#2499 Set statuscheck to false.
  cmd/skaffold/app/cmd/flags.go
  integration/deploy_test.go
Labels: cla: yes

#2501 Propagate special error on configuration change
  cmd/skaffold/app/cmd/dev_test.go
  pkg/skaffold/runner/listen.go
Labels: cla: yes

#2477 Fix port forwarding in dev loop
  integration/skaffold/helper.go
  integration/white_box_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/util/port.go
Labels: cla: yes

#2506 Release v0.34.0
  CHANGELOG.md
  cmd/skaffold/app/cmd/dev_test.go
  examples/bazel/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
Labels: cla: yes

#2504 Travis CI: integration stage -> job
  .travis.yml
Labels: cla: yes

#2515 Move test.sh to hack folder
  Makefile
  hack/test.sh
Labels: cla: yes

#2517 Remove duplicate go version
  .travis.yml
Labels: cla: yes

#2450 Expose control API for builds, syncs, and deploys
  cmd/skaffold/app/cmd/dev.go
  docs/content/en/docs/references/cli/_index.md
  integration/dev_test.go
  integration/rpc_test.go
  integration/sync_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/changeset.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/intent.go
  pkg/skaffold/runner/listen.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/server/endpoints.go
  pkg/skaffold/server/server.go
  pkg/skaffold/trigger/triggers.go
  pkg/skaffold/trigger/triggers_test.go
  proto/skaffold.pb.go
  proto/skaffold.pb.gw.go
  proto/skaffold.proto
Labels: cla: yes

#2518 Longer deadline for linters
  hack/linter.sh
Labels: cla: yes

#2527 Fix linter issues
  hack/linter.sh
  pkg/skaffold/build/tag/date_time_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/docker/client_test.go
  pkg/skaffold/docker/docker_init_test.go
  pkg/skaffold/kubernetes/log_test.go
  pkg/skaffold/runner/intent.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#2513 Remove unused code
  pkg/skaffold/color/formatter.go
  pkg/skaffold/color/formatter_test.go
Labels: cla: yes

#2532 Simpler code
  pkg/skaffold/runner/intent.go
Labels: cla: yes

#2514 Better message when a container is terminated
  pkg/skaffold/kubernetes/log.go
Labels: cla: yes

#2088 Add configuration option for sync inference [3/3]
  docs/content/en/docs/how-tos/filesync/_index.md
  docs/content/en/samples/filesync/filesync-infer.yaml
  docs/content/en/samples/filesync/filesync-manual.yaml
  docs/content/en/schemas/v1beta13.json
  docs/design_proposals/sync-improvements.md
  examples/react-reload/skaffold.yaml
  integration/sync_test.go
  integration/testdata/file-sync/Dockerfile
  integration/testdata/file-sync/foo
  integration/testdata/file-sync/skaffold-infer.yaml
  integration/testdata/file-sync/skaffold-manual.yaml
  pkg/skaffold/docker/parse.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: !! config-change !!, cla: yes

#2520 Use test helpers
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/local/bazel_test.go
  pkg/skaffold/debug/transform_python_test.go
  pkg/skaffold/deploy/kubectl/images_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry_test.go
  pkg/skaffold/kubernetes/wait_test.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/version/version_test.go
  testutil/util.go
  testutil/util_test.go
Labels: cla: yes

#2122 Improve Maven/Jib multimodule builds between Minikube and remote clusters
  CHANGELOG.md
  docs/content/en/docs/how-tos/builders/_index.md
  integration/build_test.go
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-multimodule/project1/pom.xml
  integration/examples/jib-multimodule/project2/pom.xml
  integration/examples/jib/pom.xml
  integration/run_test.go
  integration/skaffold/helper.go
  integration/testdata/jib/pom.xml
  integration/testdata/jib/skaffold.yaml
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/jib/jib.go
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_test.go
Labels: build/jib, cla: yes

#2540 Add a quicktest Makefile target
  Makefile
Labels: cla: yes

#2539 Let the user specify a path and a secret name
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta11/config.go
  pkg/skaffold/schema/v1beta12/config.go
Labels: cla: yes

#2538 Make sure logs are not intermixed
  pkg/skaffold/kubernetes/log.go
  pkg/skaffold/kubernetes/log_test.go
Labels: cla: yes

#2544 Make Jib test projects more lightweight
  integration/diagnose_test.go
  integration/testdata/debug/jib/pom.xml
  integration/testdata/debug/jib/src/main/java/hello/Application.java
  integration/testdata/debug/jib/src/main/java/hello/HelloController.java
  integration/testdata/jib/pom.xml
  integration/testdata/jib/src/main/java/hello/Application.java
  integration/testdata/jib/src/main/java/hello/HelloController.java
Labels: cla: yes

#2549 Add a jibGradle sample
  examples/jib-gradle/.gitignore
  examples/jib-gradle/build.gradle
  examples/jib-gradle/gradle/wrapper/gradle-wrapper.jar
  examples/jib-gradle/gradle/wrapper/gradle-wrapper.properties
  examples/jib-gradle/gradlew
  examples/jib-gradle/gradlew.bat
  examples/jib-gradle/k8s/web.yaml
  examples/jib-gradle/settings.gradle
  examples/jib-gradle/skaffold.yaml
  examples/jib-gradle/src/main/groovy/example/micronaut/Application.groovy
  examples/jib-gradle/src/main/groovy/example/micronaut/HelloController.groovy
  examples/jib-gradle/src/main/resources/application.yml
  examples/jib-gradle/src/main/resources/logback.xml
  integration/examples/jib-gradle/.gitignore
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-gradle/gradle/wrapper/gradle-wrapper.jar
  integration/examples/jib-gradle/gradle/wrapper/gradle-wrapper.properties
  integration/examples/jib-gradle/gradlew
  integration/examples/jib-gradle/gradlew.bat
  integration/examples/jib-gradle/k8s/web.yaml
  integration/examples/jib-gradle/settings.gradle
  integration/examples/jib-gradle/skaffold.yaml
  integration/examples/jib-gradle/src/main/groovy/example/micronaut/Application.groovy
  integration/examples/jib-gradle/src/main/groovy/example/micronaut/HelloController.groovy
  integration/examples/jib-gradle/src/main/resources/application.yml
  integration/examples/jib-gradle/src/main/resources/logback.xml
Labels: cla: yes

#2543 Monitor kubectl logs when port forwarding and retry on error
  integration/dev_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
Labels: cla: yes

#2552 cut release v0.34.1
  CHANGELOG.md
Labels: cla: yes

#2497 Starting a refactoring around RunContext and Docker local/remote Api
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/runner_test.go
  cmd/skaffold/app/tips/tips.go
  integration/build_test.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/cluster_test.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/local/custom_test.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/config/options_test.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/image_util.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/remote_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/runner/context/context.go
  pkg/skaffold/runner/diagnose_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/runner/util/util.go
  pkg/skaffold/runner/util/util_test.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/trigger/triggers_test.go
Labels: cla: yes

#2564 Simplify Sync code
  cmd/skaffold/app/cmd/runner.go
  integration/build_test.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/cluster_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/custom_test.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/image_util.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/sync/kubectl.go
  pkg/skaffold/sync/kubectl/kubectl.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/sync/types.go
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/trigger/triggers.go
  pkg/skaffold/trigger/triggers_test.go
Labels: cla: yes

#2537 Minor changes to kubectl and kustomize deployers
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/transformations.go
  pkg/skaffold/util/util.go
Labels: cla: yes

#2563 Simplify FakeAPIClient
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/docker/image_test.go
  testutil/fake_image_api.go
Labels: cla: yes

#2565 Make all embedded fields on runner private
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/cleanup.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/diagnose.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/prune.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes

#2276 Add Jib detection to skaffold init
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/jib/jib_init.go
  pkg/skaffold/jib/jib_init_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#2572 Fix linter deadline
  hack/linter.sh
  hack/test.sh
Labels: cla: yes

#2566 Retry port forwarding when we see forwarding-related errors from kubectl
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
Labels: cla: yes

#2568 Bring back applying labels to services deployed with helm
  integration/dev_test.go
  integration/testdata/gke_loadbalancer/Dockerfile
  integration/testdata/gke_loadbalancer/loadbalancer-helm/Chart.yaml
  integration/testdata/gke_loadbalancer/loadbalancer-helm/templates/k8s.yaml
  integration/testdata/gke_loadbalancer/loadbalancer-helm/values.yaml
  integration/testdata/gke_loadbalancer/main.go
  integration/testdata/gke_loadbalancer/skaffold.yaml
  pkg/skaffold/deploy/labels.go
Labels: cla: yes

#2577 Negotiate docker API version when creating minikube docker client
  pkg/skaffold/docker/client.go
Labels: cla: yes

#2548 Improve Jib support on gcb
  examples/jib-multimodule/.mvn/wrapper/maven-wrapper.properties
  examples/jib/.mvn/wrapper/maven-wrapper.properties
  integration/examples/jib-multimodule/.mvn/wrapper/maven-wrapper.properties
  integration/examples/jib/.mvn/wrapper/maven-wrapper.properties
  integration/run_test.go
  integration/testdata/debug/jib/.mvn/wrapper/maven-wrapper.properties
  integration/testdata/debug/skaffold.yaml
  integration/testdata/jib-gradle/.gitignore
  integration/testdata/jib-gradle/build.gradle
  integration/testdata/jib-gradle/gradle/wrapper/gradle-wrapper.jar
  integration/testdata/jib-gradle/gradle/wrapper/gradle-wrapper.properties
  integration/testdata/jib-gradle/gradlew
  integration/testdata/jib-gradle/gradlew.bat
  integration/testdata/jib-gradle/k8s/web.yaml
  integration/testdata/jib-gradle/skaffold.yaml
  integration/testdata/jib-gradle/src/main/java/hello/Application.java
  integration/testdata/jib/.mvn/wrapper/maven-wrapper.properties
  integration/testdata/jib/skaffold.yaml
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/desc.go
  pkg/skaffold/build/gcb/desc_test.go
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/jib.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/gcb/spec.go
  pkg/skaffold/build/gcb/spec_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#2579 [linters] Use vendored dependencies. Don’t download them.
  hack/golangci.yml
  hack/linter.sh
Labels: cla: yes

#2570 Faster tests
  cmd/skaffold/app/cmd/runner_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/docker/remote_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/kubernetes/wait_test.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/update/update.go
Labels: cla: yes

#2580 Remove duplication around Go modules settings
  .travis.yml
  Makefile
  deploy/webhook/Dockerfile
  hack/test.sh
Labels: cla: yes

#2188 Add ability to pass an explicit registry value to Helm charts
  docs/content/en/schemas/v1beta13.json
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/docker/reference.go
  pkg/skaffold/schema/latest/config.go
Labels: !! config-change !!, cla: yes

#2509 Refactor: Use new `kubectl.CLI` util to shell out to `kubectl`
  integration/white_box_test.go
  pkg/skaffold/build/cluster/cluster_test.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/kubectl/cli.go
  pkg/skaffold/kubectl/cli_test.go
  pkg/skaffold/kubectl/version.go
  pkg/skaffold/kubectl/version_test.go
  pkg/skaffold/kubernetes/log.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/kind.go
  pkg/skaffold/runner/kind_test.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/sync/kubectl.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/types.go
Labels: cla: yes
