Repository GoogleContainerTools/skaffold, pull requests merged in 2019-08, with the labels that each got.

#2593 Cleaner kubectl `port-forward` retry logic
  integration/dev_test.go
  integration/white_box_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/util/port.go
  pkg/skaffold/util/port_test.go
Labels: cla: yes

#2589 Fix handling of whitelisted directories in dockerignore
  pkg/skaffold/docker/dependencies.go
  pkg/skaffold/docker/dependencies_test.go
Labels: cla: yes

#2601 Cleaner port forward retry
  integration/dev_test.go
  integration/white_box_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/util/port.go
  pkg/skaffold/util/port_test.go
Labels: cla: yes

#2592 Make sure we mute/unmute logs at the correct times
  pkg/skaffold/kubernetes/log.go
  pkg/skaffold/runner/dev.go
Labels: cla: yes

#2604 cut v0.35.0
  CHANGELOG.md
  examples/jib-multimodule/pom.xml
  examples/jib-multimodule/project1/pom.xml
  examples/jib-multimodule/project2/pom.xml
  examples/jib/pom.xml
  examples/react-reload/skaffold.yaml
Labels: cla: yes

#2602 Make sure we mute/unmute logs at the correct times
  pkg/skaffold/kubernetes/log.go
  pkg/skaffold/runner/dev.go
Labels: cla: yes

#2607 build master only on travis CI
  .travis.yml
Labels: cla: yes

#2600 Update .travis.yml
  .travis.yml
Labels: cla: yes

#2610 fix travis build + docs whitespaces to trigger build
  .travis.yml
  docs/content/en/docs/how-tos/builders/_index.md
Labels: cla: yes

#2364 Update skaffold init --artifact to use JSON structs instead of paths
  cmd/skaffold/app/cmd/init.go
  docs/content/en/docs/references/cli/_index.md
  integration/init_test.go
  pkg/skaffold/docker/docker_init.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes

#2616 Make skaffold-generate pipeline command hidden
  cmd/skaffold/app/cmd/generate_pipeline.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2617 refactor code used by pkg/skaffold/runner/generate_pipeline.go
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/generate_pipeline_test.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/generate_pipeline/profile_test.go
  pkg/skaffold/runner/generate_pipeline.go
Labels: cla: yes

#2591 Add flag `status-check-deadline` instead of default 10 minutes
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/schemas/v1beta13.json
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/versions.go
  pkg/skaffold/schema/versions_test.go
  vendor/k8s.io/utils/pointer/OWNERS
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: cla: yes

#2614 Watch all artifact workspaces, including those outside of the working directory
  pkg/skaffold/trigger/triggers.go
  pkg/skaffold/trigger/triggers_test.go
Labels: cla: yes

#2611 Fix issue with remote Kustomizations in dev mode. (#2581)
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes

#2624 Add missing digest when setting helm image tag
  pkg/skaffold/deploy/helm.go
Labels: cla: yes

#2573 docker auth: use GetAllCredentials() to use credHelpers
  pkg/skaffold/docker/auth.go
Labels: cla: yes

#2258 Fix remoteManifests
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/images.go
  pkg/skaffold/deploy/kubectl/visitor.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/kubectl/cli.go
Labels: cla: yes

#2622 Fix kaniko permissions with generate-pipeline command
  integration/testdata/generate_pipeline/existing_oncluster/expectedPipeline.yaml
  integration/testdata/generate_pipeline/existing_other/expectedPipeline.yaml
  integration/testdata/generate_pipeline/no_profiles/expectedPipeline.yaml
  pkg/skaffold/generate_pipeline/constants.go
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/generate_pipeline/profile_test.go
  pkg/skaffold/pipeline/task.go
  pkg/skaffold/pipeline/task_test.go
  pkg/skaffold/runner/generate_pipeline.go
Labels: cla: yes

#2621 Set artifact caching on by default
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/cache_test.go
  integration/dev_test.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
Labels: cla: yes

#2623 Add port forwarding integration test
  integration/dev_test.go
  integration/port_forward_test.go
  integration/white_box_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
Labels: cla: yes

#2609 Select resources by UUID label
  go.mod
  go.sum
  pkg/skaffold/deploy/labeller.go
  pkg/skaffold/deploy/labeller_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/portforwarder.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/modules.txt
Labels: cla: yes

#2640 Collect namespaces of deployed resources.
  go.mod
  go.sum
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/namespace_test.go
  pkg/skaffold/deploy/kubectl/namespaces.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/util.go
  pkg/skaffold/deploy/util_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/notification.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/runcontext/context_test.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/runner/timings.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/go-cmp/cmp/report_text.go
  vendor/modules.txt
Labels: cla: yes

#2555 Add CLI flag `--config` for configuring the global config location
  cmd/skaffold/app/cmd/config/list.go
  cmd/skaffold/app/cmd/config/list_test.go
  cmd/skaffold/app/cmd/config/set.go
  cmd/skaffold/app/cmd/config/set_test.go
  cmd/skaffold/app/cmd/config/unset.go
  cmd/skaffold/app/cmd/config/util.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/runner.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/config/global_config.go
  pkg/skaffold/config/options.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes

#2638 Link task resources in generate-pipeline output
  integration/testdata/generate_pipeline/existing_oncluster/expectedPipeline.yaml
  integration/testdata/generate_pipeline/existing_other/expectedPipeline.yaml
  integration/testdata/generate_pipeline/no_profiles/expectedPipeline.yaml
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/generate_pipeline_test.go
  pkg/skaffold/pipeline/task.go
  pkg/skaffold/pipeline/task_test.go
Labels: cla: yes

#2648 Add constructor for creating portForwardEntry
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
Labels: cla: yes

#2652 Use pointers for connection listeners so they can be closed properly
  pkg/skaffold/event/event.go
Labels: cla: yes

#2651 Don't look up services in all namespaces.
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
Labels: cla: yes

#2447 Add CLI option `--kube-context` to override the kubecontext in Skaffold
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/dev_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/kubernetes/client.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/context/context_test.go
Labels: cla: yes, kokoro:run

#2644 Removed broken link, since the page doesn't exists anymore
  docs/content/en/docs/getting-started/_index.md
Labels: cla: yes

#2597 Pass minikube docker configuration to container-structure-test
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/test/structure/types.go
  pkg/skaffold/test/structure/types_test.go
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/test/types.go
  testutil/cmd_helper.go
  testutil/util.go
Labels: cla: yes

#2384 Design proposal for configurable kubecontext
  docs/design_proposals/configurable-kubecontext.md
Labels: cla: yes, kind/design discussion

#2590 Merge global and context-specific array settings in Skaffold config
  docs/content/en/docs/concepts/_index.md
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
Labels: cla: yes

#2658 catchup release with master
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/references/cli/_index.md
  docs/design_proposals/configurable-kubecontext.md
  integration/dev_test.go
  integration/testdata/generate_pipeline/existing_oncluster/expectedPipeline.yaml
  integration/testdata/generate_pipeline/existing_other/expectedPipeline.yaml
  integration/testdata/generate_pipeline/no_profiles/expectedPipeline.yaml
  pkg/skaffold/config/options.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/event/event.go
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/generate_pipeline_test.go
  pkg/skaffold/kubernetes/client.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/context/context_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/pipeline/task.go
  pkg/skaffold/pipeline/task_test.go
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/test/structure/types.go
  pkg/skaffold/test/structure/types_test.go
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/test/types.go
  testutil/cmd_helper.go
  testutil/util.go
Labels: cla: yes

#2649 Add unit test for LoadOrStore
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
Labels: cla: yes

#2662 fix warning when overlaying profiles
  pkg/skaffold/schema/profiles.go
Labels: cla: yes

#2663 cut v0.36.0
  CHANGELOG.md
Labels: cla: yes

#2666 merge back release/v0.36.0
  CHANGELOG.md
Labels: cla: yes

#2659 Turn RPC State forwardedPorts into map keyed by the local port
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes

#2682 Update community section of README
  README.md
Labels: cla: yes

#2582 refactor: Add upgrade utility to handle all pipelines in a SkaffoldConfig
  pkg/skaffold/schema/util/upgrade_pipelines.go
  pkg/skaffold/schema/util/upgrade_pipelines_test.go
  pkg/skaffold/schema/v1beta8/upgrade.go
  pkg/skaffold/schema/v1beta9/upgrade.go
Labels: cla: yes

#2661 Add unit tests to kubectl forwarder
  go.mod
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
Labels: cla: yes

#2686 Add struct for generate_pipeline to keep track of related data
  integration/testdata/generate_pipeline/existing_oncluster/expectedPipeline.yaml
  integration/testdata/generate_pipeline/existing_other/expectedPipeline.yaml
  integration/testdata/generate_pipeline/no_profiles/expectedPipeline.yaml
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/generate_pipeline_test.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/runner/generate_pipeline.go
Labels: cla: yes

#2691 Improve logging warning when enountering profile field of unhandled type
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/yamltags/tags.go
  pkg/skaffold/yamltags/tags_test.go
Labels: cla: yes

#2703 Fix call to newPortForwardEntry constructor in kubectl_forwarder_test
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
Labels: cla: yes

#2655 Remove time sensitive tests
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, meta/test-flake

#2707 more debugging for kubectl portforward
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
Labels: cla: yes

#2667 Implement exponential backoff for retrieving cloud build status
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/types.go
Labels: cla: yes

#2598 docs: clarify that tagged images in manifests are not replaced
  docs/content/en/docs/how-tos/deployers/_index.md
Labels: cla: yes

#2710 fix development guide link
  DEVELOPMENT.md
Labels: cla: yes

#2711 Update cache-artifacts option usage language to reflect new default
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2712 Bazel query should specify --output
  pkg/skaffold/build/bazel/dependencies.go
  pkg/skaffold/build/bazel/dependencies_test.go
Labels: cla: yes

#2696 Document Docker buildArgs as templated field
  .gitignore
  docs/content/en/docs/how-tos/templating/_index.md
Labels: cla: yes

#2695 Directs "Download" button to Quickstart
  docs/content/en/_index.html
Labels: cla: yes

#2723 Add UPSTREAM_CLIENT_TYPE user agent environment variable to kaniko pod
  pkg/skaffold/build/cluster/sources/gcs.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/build/cluster/sources/localdir_test.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
Labels: cla: yes

#2735 Don't panic when dockerConfig isn't provided
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/cluster_test.go
Labels: cla: yes

#2725 Print the output of failed integration tests
  integration/deploy_test.go
  integration/dev_test.go
  integration/diagnose_test.go
  integration/helm_test.go
  integration/port_forward_test.go
  integration/run_test.go
  integration/skaffold/helper.go
Labels: cla: yes, needs-rebase

#2727 Improve manifest splitting.
  pkg/skaffold/deploy/kubectl/manifests.go
  pkg/skaffold/deploy/kubectl/manifests_test.go
Labels: cla: yes

#2729 List manifests in the order given by the user
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: cla: yes

#2737 Pass extra env to the Docker CLI
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/docker_test.go
Labels: cla: yes

#2731 Use active gcloud credentials for executing cloudbuild when available
  go.sum
  pkg/skaffold/build/cluster/sources/gcs.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/gcp/auth.go
  pkg/skaffold/gcp/client.go
  pkg/skaffold/sources/upload.go
Labels: cla: yes

#2748 Turn Jib init plugin names into a proper enum type
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/jib/jib.go
  pkg/skaffold/jib/jib_init.go
  pkg/skaffold/jib/jib_init_test.go
  pkg/skaffold/jib/jib_test.go
Labels: cla: yes

#2758 Print the kubectl version only if there’s a warning
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
Labels: cla: yes

#2756 On windows, set -rwxr-xr-x-- on files in build context
  pkg/skaffold/util/tar.go
Labels: cla: yes

#2763 Release v0.37.0
  CHANGELOG.md
Labels: cla: yes

#2761 Keep built artifacts always in their original order.
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/util.go
  pkg/skaffold/build/util_test.go
  pkg/skaffold/runner/dev_test.go
Labels: cla: yes

#2759 Indent deploy phase output
  go.mod
  go.sum
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
  vendor/github.com/segmentio/textio/.gitignore
  vendor/github.com/segmentio/textio/LICENSE
  vendor/github.com/segmentio/textio/README.md
  vendor/github.com/segmentio/textio/go.mod
  vendor/github.com/segmentio/textio/io.go
  vendor/github.com/segmentio/textio/prefix.go
  vendor/github.com/segmentio/textio/tree.go
  vendor/modules.txt
Labels: cla: yes

#2755 Validate image names when config is read
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes

#2754 Apply port forward config from profiles
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#2764 Merge back release/v0.37.0 branch to master
  CHANGELOG.md
Labels: cla: yes

#2692 Refactor generate_pipeline code to support multiple configs
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/generate_pipeline_test.go
  pkg/skaffold/generate_pipeline/tasks.go
  pkg/skaffold/generate_pipeline/tasks_test.go
  pkg/skaffold/runner/generate_pipeline.go
Labels: cla: yes

#2765 npm audit fix on examples
  examples/nodejs/backend/package-lock.json
  examples/nodejs/backend/package.json
  integration/examples/nodejs/backend/package-lock.json
  integration/examples/nodejs/backend/package.json
Labels: cla: yes

#2752 Allow users to override the run-id
  integration/run_test.go
  pkg/skaffold/runner/new.go
Labels: cla: yes

#2743 Add logs when listing files to be watched
  pkg/skaffold/runner/dev.go
Labels: cla: yes

#2769 more npm audit fix
  examples/hot-reload/node/package-lock.json
  examples/hot-reload/node/package.json
  integration/examples/hot-reload/node/package-lock.json
  integration/examples/hot-reload/node/package.json
Labels: cla: yes

#2734 fix clientset in-cluster
  integration/build_test.go
  integration/dev_test.go
  integration/testdata/skaffold-in-cluster/Dockerfile
  integration/testdata/skaffold-in-cluster/README.md
  integration/testdata/skaffold-in-cluster/build-step/k8s-job.yaml
  integration/testdata/skaffold-in-cluster/build-step/kustomization.yaml
  integration/testdata/skaffold-in-cluster/build-step/skaffold-rbac.yaml
  integration/testdata/skaffold-in-cluster/skaffold.yaml
  integration/testdata/skaffold-in-cluster/test-build/Dockerfile
  integration/util.go
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/context/context_test.go
  testutil/util.go
Labels: cla: yes

#2701 Update documentation on Templated fields
  docs/content/en/docs/how-tos/templating/_index.md
Labels: cla: yes

#2777 comment out nodes debugging
  Makefile
  integration/util.go
Labels: cla: yes

#2771 Make sure logs from parallel custom builds are not interleaved
  integration/testdata/custom/build.sh
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
Labels: cla: yes

#2778 fix rolebinding parsing
  pkg/skaffold/deploy/kubectl/manifests.go
  pkg/skaffold/deploy/kubectl/manifests_test.go
  pkg/skaffold/initializer/kubectl/kubectl_test.go
Labels: cla: yes
