Repository GoogleContainerTools/skaffold, pull requests merged in 2019-10, with the labels that each got.

#2929 handle StatusCheck Events implementation logic.
  go.mod
  go.sum
  pkg/skaffold/deploy/resource.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#2944 Reset State on Build
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/server/endpoints.go
Labels: cla: yes, size/M

#2966 remove duplicate status check
  pkg/skaffold/event/event.go
Labels: cla: yes, size/XS

#2855 Push once
  go.mod
  go.sum
  pkg/skaffold/build/local/docker_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  testutil/fake_image_api.go
Labels: cla: yes

#2958 Specifying artifact location i.e locally or remote
  pkg/skaffold/build/cache/retrieve.go
Labels: cla: yes, size/XS

#2943 Implement 'skaffold render' for kubectl deployer
  integration/render_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl_test.go
Labels: cla: yes, size/L

#2934 Fix Flake TestPollResourceStatus/resource_stabilizes by removing sleep from test.
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/XS

#2945 reset deploy state
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/server/endpoints.go
Labels: cla: yes, size/M

#2976 Add skip tls verify option to kaniko builder
  docs/content/en/schemas/v1beta16.json
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/kaniko_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#2975 Add PullSecretMountPath to ClusterDetails
  docs/content/en/schemas/v1beta16.json
  pkg/skaffold/build/cluster/sources/localdir_test.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/M

#2956 Properly tag images with digest when using helm
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/S

#2982 Don't assume string keys in helm charts
  pkg/skaffold/deploy/kubectl/images.go
  pkg/skaffold/deploy/kubectl/labels.go
  pkg/skaffold/deploy/kubectl/matcher.go
  pkg/skaffold/deploy/kubectl/namespaces.go
  pkg/skaffold/deploy/kubectl/visitor.go
  pkg/skaffold/deploy/kubectl/visitor_test.go
Labels: cla: yes, size/M

#2984 link validation in docs
  docs/config.toml
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/concepts/architecture/_index.md
  docs/content/en/docs/concepts/modes/_index.md
  docs/content/en/docs/concepts/pipeline/_index.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/how-tos/_index.md
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/docs/how-tos/deployers/_index.md
  docs/content/en/docs/how-tos/profiles/_index.md
  docs/content/en/docs/how-tos/taggers/_index.md
  docs/content/en/docs/how-tos/templating/_index.md
  docs/content/en/docs/references/_index.md
  docs/content/en/docs/resources/_index.md
Labels: cla: yes

#2510 Add option to override kubecontext from `skaffold.yaml`
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/runner.go
  docs/content/en/schemas/v1beta16.json
  hack/check-samples.sh
  integration/examples/profiles/README.adoc
  integration/examples/profiles/hello-service/Dockerfile
  integration/examples/profiles/hello-service/k8s-pod.yaml
  integration/examples/profiles/hello-service/main.go
  integration/examples/profiles/skaffold.yaml
  integration/examples/profiles/world-service/Dockerfile
  integration/examples/profiles/world-service/k8s-pod.yaml
  integration/examples/profiles/world-service/main.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/context/context_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#2836 Support YAML anchors in skaffold.yaml (key must start with a dot)
  docs/content/en/docs/references/yaml/_index.html
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions.go
  testutil/checks.go
Labels: cla: yes

#2988 Tiny typo fix for build output in skaffold deploy
  cmd/skaffold/app/cmd/deploy.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/XS

#2989 rename imageList to podSelector
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/S

#3004 [custom] Test error case
  pkg/skaffold/build/custom/dependencies_test.go
Labels: cla: yes, size/XS

#3003 go mod tidy
  go.mod
  go.sum
Labels: cla: yes, size/XS

#2977 Add small pr guidelines
  DEVELOPMENT.md
  docs/community/small-prs.md
Labels: cla: yes, size/M

#2999 Fix versions used in examples
  examples/buildpacks/skaffold.yaml
  hack/check-samples.sh
  hack/versions/cmd/latest/version.go
  hack/versions/cmd/latest_released/version.go
  integration/examples/buildpacks/skaffold.yaml
  integration/examples/profiles/skaffold.yaml
Labels: cla: yes, size/M

#3002 List all builders in doc
  docs/content/en/docs/_index.md
  docs/content/en/docs/concepts/architecture/_index.md
  docs/content/en/docs/how-tos/builders/_index.md
Labels: cla: yes, size/M

#2998 Download pack like the other packages
  deploy/skaffold/Dockerfile
Labels: cla: yes, size/XS

#3001 Bump Hugo to 0.58.3
  deploy/webhook/Dockerfile
Labels: cla: yes, size/XS

#3005 Extract code that handles graceful termination
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
  pkg/skaffold/build/misc/graceful.go
  pkg/skaffold/build/misc/graceful_test.go
Labels: cla: yes, size/L

#2997 Simpler code for GCB dependencies
  pkg/skaffold/build/gcb/types.go
Labels: cla: yes, size/S

#2995 Refactor `setDefaults` code
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes, size/L

#3019 add survey link and reword community office hours
  README.md
Labels: cla: yes, size/M

#3018 Bump golangci-lint to v1.20.0
  hack/golangci.yml
  hack/linter.sh
Labels: cla: yes, size/XS

#3015 Fix sample’s version
  hack/check-samples.sh
  integration/examples/kustomize/skaffold-kustomize-args.yaml
Labels: cla: yes, size/XS

#2932 Add Pod Status when pod is pending by going through pending container
  pkg/skaffold/kubernetes/status_check.go
  pkg/skaffold/kubernetes/status_check_test.go
Labels: cla: yes, size/L

#3014 Pass the context
  cmd/skaffold/app/cmd/diagnose.go
  pkg/skaffold/runner/diagnose.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/XS

#3017 moving deprecation policy to skaffold.dev
  CHANGELOG.md
  deprecation-policy.md
  docs/content/en/docs/references/deprecation/_index.md
  docs/design_proposals/README.md
  docs/design_proposals/design-proposal-template.md
Labels: cla: yes, size/L

#2978 Add file sync to Event and State APIs
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#3028 Custom artifact depends by default on the whole workspace
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes, size/XS

#3027 Strip the debugging information
  Makefile
Labels: cla: yes, size/XS

#3026 add links to docs which are present
  docs/content/en/docs/references/deprecation/_index.md
Labels: cla: yes, size/L

#3029 [docs] readd exceptions in deprecation policy
  docs/content/en/docs/references/_index.md
  docs/content/en/docs/references/deprecation/_index.md
Labels: cla: yes, size/XS

#3033 Fix check flake by not using Github API
  hack/versions/pkg/version/version.go
  pkg/skaffold/update/update.go
Labels: cla: yes, size/M

#3031 Docs Splash Page Update
  docs/content/en/docs/_index.md
Labels: cla: yes, size/M

#2974 Fix bugs in insecure registries for kaniko
  integration/build_test.go
  integration/testdata/kaniko-insecure-registry/app/Dockerfile
  integration/testdata/kaniko-insecure-registry/app/main.go
  integration/testdata/kaniko-insecure-registry/app/skaffold.yaml
  integration/testdata/kaniko-insecure-registry/insecure-registry/Dockerfile
  integration/testdata/kaniko-insecure-registry/insecure-registry/config.yaml
  integration/testdata/kaniko-insecure-registry/insecure-registry/reg.yaml
  integration/testdata/kaniko-insecure-registry/skaffold.yaml
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/kaniko_test.go
  pkg/skaffold/constants/constants.go
Labels: cla: yes, size/L

#3034 support clause
  README.md
Labels: cla: yes, size/S

#2992 Add page about kube-context handling in docs concepts section
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/concepts/kube_context/_index.md
Labels: cla: yes, size/M

#3038 Cut v0.40.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/expectedPipeline.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profiles/README.adoc
  examples/profiles/hello-service/Dockerfile
  examples/profiles/hello-service/k8s-pod.yaml
  examples/profiles/hello-service/main.go
  examples/profiles/skaffold.yaml
  examples/profiles/world-service/Dockerfile
  examples/profiles/world-service/k8s-pod.yaml
  examples/profiles/world-service/main.go
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#3049 Fix `skaffold deploy --tail`
  integration/deploy_test.go
  integration/skaffold/helper.go
  integration/testdata/deploy-hello-tail/k8s/pod.yaml
  integration/testdata/deploy-hello-tail/skaffold.yaml
  pkg/skaffold/runner/build_deploy.go
Labels: cla: yes, size/M

#3042 Use a switch instead of if
  pkg/skaffold/build/cache/hash.go
Labels: cla: yes, size/S

#3046 Warn about unused configs
  pkg/skaffold/initializer/init.go
Labels: cla: yes, size/XS

#3045 Fix remove patch in Profiles
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: cla: yes, size/XS

#3054 remove Container Was Terminated message
  pkg/skaffold/kubernetes/log.go
Labels: cla: yes, size/XS

#3030 getting started -> quickstart
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/install/_index.md
  docs/content/en/docs/quickstart/_index.md
Labels: cla: yes, size/XL

#3058 [Bazel] Target must end with .tar
  docs/content/en/docs/how-tos/builders/_index.md
  pkg/skaffold/build/local/bazel.go
  pkg/skaffold/build/local/bazel_test.go
  testutil/fake_image_api.go
Labels: cla: yes, size/L

#3059 Don’t print bazel slow warnings more than once.
  pkg/skaffold/build/bazel/dependencies.go
Labels: cla: yes, size/XS

#3063 a windows build file
  hack/build.bat
Labels: cla: yes, size/M

#2919 Add HaTS and Opt-In Feedback links
  README.md
  docs/config.toml
  docs/content/en/docs/quickstart/_index.md
  docs/content/en/docs/resources/_index.md
  docs/content/en/docs/resources/feedback/_index.md
  docs/content/en/docs/tutorials/_index.md
Labels: cla: yes, size/M

#3069 [kaniko] Stop printing the logs on ctrl-c
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/logs.go
Labels: cla: yes, size/S

#3011 display survey prompt which points to survey url
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: cla: yes, size/L

#3066 [Cache] Ignore file not found
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/hash_test.go
Labels: cla: yes, needs-rebase, size/S

#3065 Warn when default or provided port not available for API Server
  pkg/skaffold/server/server.go
Labels: cla: yes, needs-rebase, size/XS

#3064 Make all docs have TOC on the right hand side.
  docs/content/en/docs/concepts/modes/_index.md
  docs/content/en/docs/how-tos/buildpacks/_index.md
  docs/content/en/docs/references/deprecation/_index.md
  docs/layouts/partials/toc.html
Labels: cla: yes, size/M

#3067 generate docs for proto
  docs/content/en/docs/references/api/_index.md
  hack/generate-proto.sh
  hack/proto/Dockerfile
  hack/test-generated-proto.sh
Labels: cla: yes, size/L

#3079 Docs updates
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/render.go
  docs/content/en/docs/design/_index.md
  docs/content/en/docs/design/config.md
  docs/content/en/docs/design/global-config.md
  docs/content/en/docs/environment/image-registries.md
  docs/content/en/docs/environment/kube-context.md
  docs/content/en/docs/environment/local-cluster.md
  docs/content/en/docs/environment/templating.md
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/docs/pipeline-stages/deployers.md
  docs/content/en/docs/pipeline-stages/filesync.md
  docs/content/en/docs/pipeline-stages/port-forwarding.md
  docs/content/en/docs/pipeline-stages/taggers.md
  docs/content/en/docs/pipeline-stages/testers.md
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
  docs/content/en/docs/references/deprecation/_index.md
  docs/content/en/docs/resources/_index.md
  docs/content/en/docs/workflows/debug.md
  docs/design_proposals/configurable-kubecontext.md
  examples/microservices/README.adoc
  integration/examples/microservices/README.adoc
  integration/util.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl/visitor.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/kubectl/kubectl.go
  pkg/skaffold/kubernetes/client.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/schema/v1alpha1/upgrade.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/util/util.go
  pkg/webhook/kubernetes/deployment.go
  pkg/webhook/kubernetes/service.go
  testutil/kubecontext.go
Labels: cla: yes, size/L

#3070 Interrupt skaffold init with ctrl-c
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, size/M

#3076 Rename custom/buildpacks sample config
  docs/content/en/docs/tutorials/buildpacks.md
  docs/content/en/samples/builders/custom-buildpacks/build.sh
  docs/content/en/samples/builders/custom-buildpacks/skaffold.yaml
Labels: cla: yes

#3080 move pr template instructions to comments
  .github/pull_request_template.md
Labels: cla: yes, size/XS

#3093 Upgrade Jib to 1.7.0
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib-gradle/build.gradle
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#3086 Fix `—force=false`
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/config/options_test.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, size/M

#3072 add event api integration for deploy health check
  pkg/skaffold/deploy/status_check.go
Labels: cla: yes, size/S

#3085 [Custom] Clearer message when image was not built
  pkg/skaffold/build/local/custom.go
Labels: cla: yes, size/S

#3091 `skaffold build` shouldn’t print the tags used in deployments
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/deploy.go
Labels: cla: yes, size/S

#3095 Remove priyawadhwa as maintainer
  .github/CODEOWNERS
  MAINTAINERS
Labels: cla: yes, size/S

#2991 kube-context design proposal: add note about the implementation status
  docs/design_proposals/configurable-kubecontext.md
Labels: cla: yes, size/XS

#3092 Clarify debug docs for deprecated Workload APIs
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/XS

#3062 Improve skaffold init file traversal
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, size/L

#3103 Align kubectl/kustomize cleanup output with deploy output
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
Labels: cla: yes, size/XS

#3104 Fix typo
  pkg/skaffold/deploy/kustomize.go
Labels: cla: yes, size/XS

#3105 Remove logs before building and testing
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
Labels: cla: yes, size/S

#3013 Adding ephemeralstorage and ResourceStorage for kaniko pods
  docs/content/en/schemas/v1beta17.json
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta16/upgrade.go
Labels: cla: yes, size/M

#3009 Integrate file sync events into dev command
  integration/sync_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/dev_test.go
Labels: cla: yes, size/L

#3084 [Custom] [Deprecation] Use $IMAGE instead of $IMAGES
  docs/content/en/docs/pipeline-stages/builders.md
  docs/content/en/docs/references/deprecation/_index.md
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
  pkg/skaffold/constants/constants.go
Labels: cla: yes, size/M

#3102 Log durations instead of always printing them
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/modules.txt
Labels: cla: yes, needs-rebase, size/M

#3101 Close the bracket in documentation
  docs/content/en/docs/environment/templating.md
Labels: cla: yes, size/XS

#3120 Add heuristics to speed up Jib check in skaffold init
  pkg/skaffold/jib/jib_init.go
  pkg/skaffold/jib/jib_init_test.go
Labels: cla: yes, size/M

#3130 release v0.41.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#3134 Fix broken link to installation guide
  README.md
Labels: cla: yes, size/XS

#3135 fix install links
  docs/content/en/_index.html
Labels: cla: yes, size/XS

#3055 Delegate release notes to external tool
  hack/.gitignore
  hack/release.sh
  hack/release_notes/listpullreqs.go
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: cla: yes, size/L

#3107 Prepare cli-go to accept `--kubeconfig` setting
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/config/options.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/context/context_test.go
Labels: cla: yes, size/M

#3140 Don’t need race detection/code coverage
  hack/new_version.sh
Labels: cla: yes, size/XS

#3144 Fixes a broken link to the Profiles page
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/XS

#3127 Fixed issue with tagging of insecure registries.
  pkg/skaffold/docker/remote.go
Labels: cla: yes, size/XS

#3112 document activation of multiple profiles
  docs/content/en/docs/environment/profiles.md
  examples/profile-patches/README.adoc
  examples/profile-patches/base-service/Dockerfile
  examples/profile-patches/base-service/k8s-pod.yaml
  examples/profile-patches/base-service/main.go
  examples/profile-patches/hello-service/Dockerfile
  examples/profile-patches/hello-service/k8s-pod.yaml
  examples/profile-patches/hello-service/main.go
  examples/profile-patches/skaffold.yaml
  examples/profile-patches/world-service/Dockerfile
  examples/profile-patches/world-service/k8s-pod.yaml
  examples/profile-patches/world-service/main.go
  integration/examples/profile-patches/README.adoc
  integration/examples/profile-patches/base-service/Dockerfile
  integration/examples/profile-patches/base-service/k8s-pod.yaml
  integration/examples/profile-patches/base-service/main.go
  integration/examples/profile-patches/hello-service/Dockerfile
  integration/examples/profile-patches/hello-service/k8s-pod.yaml
  integration/examples/profile-patches/hello-service/main.go
  integration/examples/profile-patches/skaffold.yaml
  integration/examples/profile-patches/world-service/Dockerfile
  integration/examples/profile-patches/world-service/k8s-pod.yaml
  integration/examples/profile-patches/world-service/main.go
Labels: cla: yes, size/L

#3145 Rework skaffold.dev splash page
  docs/.DS_Store
  docs/.firebaserc
  docs/config.toml
  docs/content/en/_index.html
  docs/layouts/partials/footer.html
  docs/layouts/partials/hooks/head-end.html
  docs/layouts/partials/navbar.html
  docs/layouts/shortcodes/blocks/feature4.html
  docs/layouts/shortcodes/blocks/testimonial-section.html
  docs/layouts/shortcodes/blocks/values-section.html
  docs/static/favicons/android-144x144.png
  docs/static/favicons/android-192x192.png
  docs/static/favicons/android-36x36.png
  docs/static/favicons/android-48x48.png
  docs/static/favicons/android-512x512.png
  docs/static/favicons/android-72x72.png
  docs/static/favicons/android-96x96.png
  docs/static/favicons/apple-touch-icon-180x180.png
  docs/static/favicons/apple-touch-icon.png
  docs/static/favicons/favicon-16x16.png
  docs/static/favicons/favicon-32x32.png
  docs/static/favicons/favicon.ico
  docs/static/favicons/pwa-192x192.png
  docs/static/favicons/pwa-512x512.png
  docs/static/favicons/tile150x150.png
  docs/static/favicons/tile310x150.png
  docs/static/favicons/tile310x310.png
  docs/static/favicons/tile70x70.png
  docs/static/images/forgerock.png
  docs/static/images/quora.png
  docs/static/images/skaffold-logo-white.png
  docs/static/images/skaffold-square.png
  docs/static/images/skaffold.png
  docs/static/images/splash.mp4
  docs/static/images/tng.png
  docs/static/javascripts/fade.js
  docs/static/stylesheets/button.css
  docs/static/stylesheets/colors.css
  docs/static/stylesheets/font.css
  go.mod
Labels: cla: yes
