Repository GoogleContainerTools/skaffold, pull requests merged in 2019-04, with the labels that each got.

#1898 Upgrade golangci-lint to v1.16.0
  hack/linter.sh
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes

#1860 Fix flakes with rpc integration test
  integration/rpc_test.go
Labels: cla: yes

#1400 Remove intermediate images and containers from local builds by default
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/dev.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/build/build.go
  pkg/skaffold/build/cache.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/cache_test.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cache/save_test.go
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/build/plugin/plugin.go
  pkg/skaffold/build/plugin/plugin_test.go
  pkg/skaffold/build/prebuilt.go
  pkg/skaffold/config/options.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_util.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/plugin/builders/bazel/builder.go
  pkg/skaffold/plugin/builders/bazel/local.go
  pkg/skaffold/plugin/builders/docker/builder.go
  pkg/skaffold/plugin/builders/docker/local.go
  pkg/skaffold/plugin/environments/gcb/types.go
  pkg/skaffold/plugin/shared/client.go
  pkg/skaffold/plugin/shared/server.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/sync/sync.go
Labels: cla: yes, needs-rebase

#1838 Adding a design proposal template and README.
  docs/design_proposals/README.md
  docs/design_proposals/design-proposal-template.md
Labels: cla: yes

#1903 Undo fmt.Fprint -> color.White.Fprint
  pkg/skaffold/kubernetes/log.go
Labels: cla: yes

#1895 Configure Jib builds to use plain progress updates
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/plugin/environments/gcb/jib_test.go
Labels: cla: yes

#1904 fixing non-oneof inline struct handling in schemas
  docs/content/en/schemas/v1beta8.json
  hack/schemas/main.go
  hack/schemas/main_test.go
  hack/schemas/testdata/inline-anyof/input.go
  hack/schemas/testdata/inline-anyof/output.json
  hack/schemas/testdata/inline-hybrid/input.go
  hack/schemas/testdata/inline-hybrid/output.json
  hack/schemas/testdata/inline/input.go
  hack/schemas/testdata/inline/output.json
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1alpha1/config.go
  pkg/skaffold/schema/v1alpha2/config.go
  pkg/skaffold/schema/v1alpha3/config.go
  pkg/skaffold/schema/v1alpha4/config.go
  pkg/skaffold/schema/v1alpha5/config.go
  pkg/skaffold/schema/v1beta1/config.go
  pkg/skaffold/schema/v1beta2/config.go
  pkg/skaffold/schema/v1beta3/config.go
  pkg/skaffold/schema/v1beta4/config.go
  pkg/skaffold/schema/v1beta5/config.go
  pkg/skaffold/schema/v1beta6/config.go
  pkg/skaffold/yamltags/tags.go
  pkg/skaffold/yamltags/tags_test.go
Labels: cla: yes

#1891 Improve helm examples
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/configmap.yaml
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/deployment.yaml
  examples/helm-deployment-dependencies/skaffold-helm/templates/configmap.yaml
  examples/helm-deployment-dependencies/skaffold-helm/templates/deployment.yaml
  examples/helm-deployment/.dockerignore
  examples/helm-deployment/Dockerfile
  examples/helm-deployment/skaffold-helm/templates/deployment.yaml
  examples/helm-deployment/skaffold-helm/templates/ingress.yaml
  examples/helm-deployment/skaffold-helm/values.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-deployment/static/index.html
  examples/helm-deployment/static/style.css
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/configmap.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/deployment.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/templates/configmap.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/templates/deployment.yaml
  integration/examples/helm-deployment/.dockerignore
  integration/examples/helm-deployment/Dockerfile
  integration/examples/helm-deployment/skaffold-helm/templates/deployment.yaml
  integration/examples/helm-deployment/skaffold-helm/templates/ingress.yaml
  integration/examples/helm-deployment/skaffold-helm/values.yaml
  integration/examples/helm-deployment/skaffold.yaml
  integration/examples/helm-deployment/static/index.html
  integration/examples/helm-deployment/static/style.css
Labels: cla: yes

#1881 Validate pipeline config
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/util/util.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes

#1899 extracting Pipeline from SkaffoldConfig
  .gitignore
  cmd/skaffold/app/cmd/runner.go
  docs/content/en/docs/references/yaml/main.js
  docs/content/en/schemas/v1beta8.json
  hack/schemas/main.go
  hack/schemas/testdata/inline-anyof/output.json
  hack/schemas/testdata/inline-hybrid/output.json
  hack/schemas/testdata/inline/output.json
  pkg/skaffold/initializer/init.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/latest/upgrade.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/v1beta7/upgrade.go
  pkg/skaffold/schema/v1beta7/upgrade_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/schema/versions.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#1913 remove inline structs from schema
  docs/content/en/schemas/v1alpha1.json
  docs/content/en/schemas/v1alpha2.json
  docs/content/en/schemas/v1alpha3.json
  docs/content/en/schemas/v1alpha4.json
  docs/content/en/schemas/v1alpha5.json
  docs/content/en/schemas/v1beta1.json
  docs/content/en/schemas/v1beta2.json
  docs/content/en/schemas/v1beta3.json
  docs/content/en/schemas/v1beta4.json
  docs/content/en/schemas/v1beta5.json
  docs/content/en/schemas/v1beta6.json
  docs/content/en/schemas/v1beta7.json
  docs/content/en/schemas/v1beta8.json
  hack/schemas/main.go
  hack/schemas/testdata/inline-anyof/output.json
  hack/schemas/testdata/inline-hybrid/output.json
  hack/schemas/testdata/inline/output.json
Labels: cla: yes

#1683 feat: specify the resource requirements for the kaniko pod
  docs/content/en/schemas/v1beta8.json
  pkg/skaffold/build/kaniko/sources/sources.go
  pkg/skaffold/build/kaniko/sources/sources_test.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta6/upgrade_test.go
  pkg/skaffold/schema/v1beta7/upgrade.go
  pkg/skaffold/schema/v1beta7/upgrade_test.go
  testutil/util.go
Labels: cla: yes, config-change, needs-rebase

#1922 Remove duplicate cache code
  docs/content/en/schemas/v1beta8.json
  pkg/skaffold/build/cache.go
Labels: cla: yes

#1923 Minor doc updates
  DEVELOPMENT.md
  examples/jib/README.adoc
Labels: cla: yes, needs-rebase

#1940 ctx->runCtx
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/build/plugin/plugin.go
  pkg/skaffold/build/plugin/plugin_test.go
  pkg/skaffold/build/prebuilt.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/event/event.go
  pkg/skaffold/plugin/builders/bazel/builder.go
  pkg/skaffold/plugin/builders/docker/builder.go
  pkg/skaffold/plugin/environments/gcb/types.go
  pkg/skaffold/plugin/shared/build.go
  pkg/skaffold/plugin/shared/client.go
  pkg/skaffold/plugin/shared/server.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/test/test.go
Labels: cla: yes

#1944 remove runcontext creation from gcb builder path
  pkg/skaffold/plugin/builders/docker/builder.go
  pkg/skaffold/plugin/environments/gcb/types.go
Labels: cla: yes

#1952 Prepare release v0.27.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/README.adoc
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
Labels: cla: yes

#1939 Full validation for `required` and `oneOf` config fields
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/runner.go
  docs/content/en/schemas/v1beta8.json
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/schema/versions.go
  pkg/skaffold/yamltags/tags.go
  pkg/skaffold/yamltags/tags_test.go
Labels: cla: yes

#1956 Always configure which command runs
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/run.go
Labels: cla: yes

#1926 Fix syncing for Jib
  pkg/skaffold/jib/jib.go
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_non_windows_test.go
  pkg/skaffold/jib/jib_test.go
  pkg/skaffold/jib/jib_windows_test.go
Labels: cla: yes

#1947 Fix error message when the `skaffold.yaml` is not found
  cmd/skaffold/app/cmd/cmd_test.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/runner_test.go
  pkg/skaffold/util/config.go
  pkg/skaffold/util/config_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
  testutil/util.go
Labels: cla: yes

#1970 Add documentation for local development setups
  docs/content/en/docs/concepts/_index.md
Labels: cla: yes

#1959 Add some documentation for container structure tests
  docs/content/en/docs/how-tos/testers/_index.md
  docs/content/en/samples/testers/structureTest.yaml
  docs/content/en/samples/testers/test.yaml
  docs/content/en/samples/testers/testProfile.yaml
  pkg/skaffold/schema/samples_test.go
Labels: cla: yes

#1973 Add documentation for insecure registries
  docs/content/en/docs/concepts/_index.md
Labels: cla: yes

#1971 Fix panic when upgrading configurations with patches
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/util/util.go
  pkg/skaffold/schema/util/util_test.go
  pkg/skaffold/schema/v1beta5/config.go
  pkg/skaffold/schema/v1beta6/config.go
  pkg/skaffold/schema/v1beta7/config.go
  pkg/skaffold/schema/v1beta8/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes

#1976 Use `RunOrFailOutput` instead of `RunOrFail` to see the error logs in test
  integration/run_test.go
Labels: cla: yes

#1568 Add `--force` command line option to run and deploy sub-commands
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, needs-rebase

#1984 Don't run GCB example on structure tests
  examples/google-cloud-build/Dockerfile
  examples/google-cloud-build/README.adoc
  examples/google-cloud-build/k8s-pod.yaml
  examples/google-cloud-build/main.go
  examples/google-cloud-build/skaffold.yaml
  integration/examples/google-cloud-build/Dockerfile
  integration/examples/google-cloud-build/README.adoc
  integration/examples/google-cloud-build/k8s-pod.yaml
  integration/examples/google-cloud-build/main.go
  integration/examples/google-cloud-build/skaffold.yaml
  integration/examples/structure-tests/skaffold.yaml
  integration/run_test.go
Labels: cla: yes

#1985 Update codeowners and maintainers
  .github/CODEOWNERS
  MAINTAINERS
Labels: cla: yes

#1982 Add contributing docs for making a config change
  DEVELOPMENT.md
Labels: cla: yes

#1994 Add start on filesync doc
  docs/content/en/docs/how-tos/filesync/_index.md
Labels: cla: yes

#1993 Improve Skaffold-Jib docs for Maven multi-module projects
  docs/content/en/docs/how-tos/builders/_index.md
Labels: cla: yes

#1990 Remove docker plugin and revert to original code structure
  cmd/skaffold/app/skaffold.go
  integration/run_test.go
  integration/testdata/plugin/gcb/leeroy-app/Dockerfile
  integration/testdata/plugin/gcb/leeroy-app/app.go
  integration/testdata/plugin/gcb/leeroy-app/kubernetes/deployment.yaml
  integration/testdata/plugin/gcb/leeroy-web/Dockerfile
  integration/testdata/plugin/gcb/leeroy-web/kubernetes/deployment.yaml
  integration/testdata/plugin/gcb/leeroy-web/web.go
  integration/testdata/plugin/gcb/skaffold.yaml
  integration/testdata/plugin/local/bazel/BUILD
  integration/testdata/plugin/local/bazel/WORKSPACE
  integration/testdata/plugin/local/bazel/k8s/k8s-pod.yaml
  integration/testdata/plugin/local/bazel/main.go
  integration/testdata/plugin/local/bazel/skaffold.yaml
  integration/testdata/plugin/local/docker/leeroy-app/Dockerfile
  integration/testdata/plugin/local/docker/leeroy-app/app.go
  integration/testdata/plugin/local/docker/leeroy-app/kubernetes/deployment.yaml
  integration/testdata/plugin/local/docker/leeroy-web/Dockerfile
  integration/testdata/plugin/local/docker/leeroy-web/kubernetes/deployment.yaml
  integration/testdata/plugin/local/docker/leeroy-web/web.go
  integration/testdata/plugin/local/docker/skaffold.yaml
  pkg/skaffold/build/bazel/dependencies.go
  pkg/skaffold/build/bazel/dependencies_test.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/desc.go
  pkg/skaffold/build/gcb/desc_test.go
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/jib.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/bazel.go
  pkg/skaffold/build/local/bazel_test.go
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/plugin/core.go
  pkg/skaffold/build/plugin/plugin.go
  pkg/skaffold/build/plugin/plugin_test.go
  pkg/skaffold/plugin/builders/bazel/bazel.go
  pkg/skaffold/plugin/builders/bazel/builder.go
  pkg/skaffold/plugin/builders/bazel/builder_test.go
  pkg/skaffold/plugin/builders/bazel/local.go
  pkg/skaffold/plugin/builders/docker/builder.go
  pkg/skaffold/plugin/builders/docker/builder_test.go
  pkg/skaffold/plugin/builders/docker/docker.go
  pkg/skaffold/plugin/builders/docker/local.go
  pkg/skaffold/plugin/shared/build.go
  pkg/skaffold/plugin/shared/client.go
  pkg/skaffold/plugin/shared/server.go
  pkg/skaffold/plugin/shared/shared.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#1997 fix show some option in skaffold delete #1995
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/delete.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, kokoro:run

#1987 Include runtime dependencies for taggers in `gcr.io/k8s-skaffold/skaffold`
  Gopkg.lock
  Gopkg.toml
  deploy/skaffold/Dockerfile
  integration/build_test.go
  integration/skaffold/helper.go
  integration/testdata/tagPolicy/skaffold.yaml
  pkg/skaffold/build/tag/date_time.go
  vendor/4d63.com/tz/LICENSE
  vendor/4d63.com/tz/tz.go
  vendor/4d63.com/tz/zoneinfo.go
Labels: cla: yes

#2013 Fix typo
  docs/content/en/docs/getting-started/_index.md
Labels: cla: yes

#2015 Rename SkaffoldPipeline to SkaffoldConfig
  docs/content/en/schemas/v1alpha1.json
  docs/content/en/schemas/v1alpha2.json
  docs/content/en/schemas/v1alpha3.json
  docs/content/en/schemas/v1alpha4.json
  docs/content/en/schemas/v1alpha5.json
  docs/content/en/schemas/v1beta1.json
  docs/content/en/schemas/v1beta2.json
  docs/content/en/schemas/v1beta3.json
  docs/content/en/schemas/v1beta4.json
  docs/content/en/schemas/v1beta5.json
  docs/content/en/schemas/v1beta6.json
  docs/content/en/schemas/v1beta7.json
  pkg/skaffold/initializer/init.go
  pkg/skaffold/schema/v1alpha1/config.go
  pkg/skaffold/schema/v1alpha1/upgrade.go
  pkg/skaffold/schema/v1alpha1/upgrade_test.go
  pkg/skaffold/schema/v1alpha2/config.go
  pkg/skaffold/schema/v1alpha2/upgrade.go
  pkg/skaffold/schema/v1alpha2/upgrade_test.go
  pkg/skaffold/schema/v1alpha3/config.go
  pkg/skaffold/schema/v1alpha3/upgrade.go
  pkg/skaffold/schema/v1alpha3/upgrade_test.go
  pkg/skaffold/schema/v1alpha4/config.go
  pkg/skaffold/schema/v1alpha4/upgrade.go
  pkg/skaffold/schema/v1alpha4/upgrade_test.go
  pkg/skaffold/schema/v1alpha5/config.go
  pkg/skaffold/schema/v1alpha5/upgrade.go
  pkg/skaffold/schema/v1alpha5/upgrade_test.go
  pkg/skaffold/schema/v1beta1/config.go
  pkg/skaffold/schema/v1beta1/upgrade.go
  pkg/skaffold/schema/v1beta1/upgrade_test.go
  pkg/skaffold/schema/v1beta2/config.go
  pkg/skaffold/schema/v1beta2/upgrade.go
  pkg/skaffold/schema/v1beta2/upgrade_test.go
  pkg/skaffold/schema/v1beta3/config.go
  pkg/skaffold/schema/v1beta3/upgrade.go
  pkg/skaffold/schema/v1beta3/upgrade_test.go
  pkg/skaffold/schema/v1beta4/config.go
  pkg/skaffold/schema/v1beta4/upgrade.go
  pkg/skaffold/schema/v1beta4/upgrade_test.go
  pkg/skaffold/schema/v1beta5/config.go
  pkg/skaffold/schema/v1beta5/upgrade.go
  pkg/skaffold/schema/v1beta5/upgrade_test.go
  pkg/skaffold/schema/v1beta6/config.go
  pkg/skaffold/schema/v1beta6/upgrade.go
  pkg/skaffold/schema/v1beta6/upgrade_test.go
  pkg/skaffold/schema/v1beta7/config.go
  pkg/skaffold/schema/v1beta7/upgrade.go
  pkg/skaffold/schema/v1beta7/upgrade_test.go
  pkg/skaffold/schema/v1beta8/upgrade_test.go
  pkg/skaffold/schema/versions.go
Labels: cla: yes

#2012 Remove unused instructions from Makefile
  Makefile
Labels: cla: yes

#2014 Don’t fetch the same config twice
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  testutil/fake_image_api.go
Labels: cla: yes

#2017 Remove some dead code
  pkg/skaffold/color/formatter.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/schema/v1alpha1/upgrade.go
Labels: cla: yes

#1744 Reduce overhead of Jib builder
  .gitignore
  pkg/skaffold/jib/jib.go
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_test.go
Labels: cla: yes

#2023 adding JIB codeowners
  CODEOWNERS
Labels: cla: yes

#2025 fix codeowners duplication
  .github/CODEOWNERS
  CODEOWNERS
Labels: cla: yes

#2026 Add more github shields
  README.md
Labels: cla: yes

#1902 Git tagger variants (Tags, CommitSha, AbbrevCommitSha)
  docs/content/en/schemas/v1beta9.json
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta8/upgrade.go
Labels: cla: yes

#2030 Remove upgrade to v1beta10
  docs/content/en/schemas/v1beta9.json
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta8/upgrade.go
  pkg/skaffold/schema/v1beta8/upgrade_test.go
  pkg/skaffold/schema/v1beta9/config.go
  pkg/skaffold/schema/v1beta9/upgrade.go
  pkg/skaffold/schema/v1beta9/upgrade_test.go
  pkg/skaffold/schema/versions.go
Labels: cla: yes

#2033 Add hidden flag `--force-colors` to always print color codes
  cmd/skaffold/app/cmd/cmd.go
  pkg/skaffold/color/formatter.go
Labels: cla: yes

#2029 cut v0.28.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
Labels: cla: yes

#2034 fixing codeowners + the changelog for v0.28.0
  .github/CODEOWNERS
  CHANGELOG.md
Labels: cla: yes

#2032 Correctly parse env-var for multi-valued flags
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/init.go
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes

#2011 Support kubectl deploy absolute manifest files
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/util/util.go
Labels: cla: yes

#1844 Design proposal for sync improvements
  docs/design_proposals/sync-improvements.md
Labels: cla: yes, kind/design discussion

#1960 Attaching os standard error and out stream to the copy command
  pkg/skaffold/sync/sync.go
Labels: cla: yes

#2036 Add option to configure the networking stack in docker build
  docs/content/en/schemas/v1beta10.json
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta9/upgrade.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes

#2027 fix double space
  pkg/skaffold/jib/jib.go
Labels: cla: yes

#2037 Refactor kaniko builder to cluster builder
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/kaniko_test.go
  pkg/skaffold/build/cluster/logs.go
  pkg/skaffold/build/cluster/logs_test.go
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/build/cluster/sources/gcs.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#1912 Allow environment variables to be used in docker build argument
  docs/content/en/schemas/v1beta10.json
  integration/examples/nodejs/backend/Dockerfile
  integration/examples/nodejs/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/build/gcb/desc.go
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/parse_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes
