Repository GoogleContainerTools/skaffold, pull requests merged in 2019-09, with the labels that each got.

#2772 Improve helm deployer
  examples/helm-deployment-dependencies/skaffold-helm/values.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold-helm/values.yaml
  examples/helm-deployment/skaffold.yaml
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/labels.go
Labels: cla: yes

#2673 Upgrade Jib to 1.5.0
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib-gradle/build.gradle
  integration/testdata/jib/pom.xml
Labels: cla: yes

#2641 Update _index.md
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
Labels: cla: yes, kokoro:run

#2789 Update kind to v0.5.1
  .travis.yml
  Makefile
Labels: cla: yes

#2790 Update alpine to 3.10
  deploy/skaffold/Dockerfile
  deploy/webhook/Dockerfile
  examples/compose/Dockerfile
  examples/getting-started/Dockerfile
  examples/google-cloud-build/Dockerfile
  examples/hot-reload/python/Dockerfile
  examples/kaniko-local/Dockerfile
  examples/kaniko/Dockerfile
  examples/microservices/leeroy-app/Dockerfile
  examples/microservices/leeroy-web/Dockerfile
  examples/structure-tests/Dockerfile
  examples/tagging-with-environment-variables/Dockerfile
  hack/proto/Dockerfile
  integration/examples/compose/Dockerfile
  integration/examples/getting-started/Dockerfile
  integration/examples/google-cloud-build/Dockerfile
  integration/examples/hot-reload/python/Dockerfile
  integration/examples/kaniko-local/Dockerfile
  integration/examples/kaniko/Dockerfile
  integration/examples/microservices/leeroy-app/Dockerfile
  integration/examples/microservices/leeroy-web/Dockerfile
  integration/examples/structure-tests/Dockerfile
  integration/examples/tagging-with-environment-variables/Dockerfile
  integration/testdata/debug/python3/Dockerfile
  integration/testdata/fix/Dockerfile
  integration/testdata/gcb-sub-folder/sub/Dockerfile
  integration/testdata/gke_loadbalancer/Dockerfile
  integration/testdata/init/compose/Dockerfile
  integration/testdata/init/hello/Dockerfile
  integration/testdata/init/microservices/leeroy-app/Dockerfile
  integration/testdata/init/microservices/leeroy-web/Dockerfile
  integration/testdata/kaniko-microservices/leeroy-app/Dockerfile
  integration/testdata/kaniko-microservices/leeroy-web/Dockerfile
  integration/testdata/kaniko-sub-folder/sub/Dockerfile
  integration/testdata/kaniko-target/Dockerfile
Labels: cla: yes

#2785 Improve fake commands handling
  pkg/skaffold/build/bazel/dependencies_test.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/local/bazel_test.go
  pkg/skaffold/build/local/docker_test.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/docker/client_test.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_init_test.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_test.go
  pkg/skaffold/kubectl/cli_test.go
  pkg/skaffold/kubectl/version_test.go
  pkg/skaffold/runner/kind_test.go
  pkg/skaffold/test/structure/types_test.go
  pkg/skaffold/test/test_test.go
  testutil/cmd_helper.go
  testutil/util.go
Labels: cla: yes

#2794 Fix spurious logs when dev loop is restarted
  pkg/skaffold/kubernetes/log.go
Labels: cla: yes

#2788 Update Hugo to 0.57.2
  deploy/webhook/Dockerfile
Labels: cla: yes, needs-rebase

#2792 Print the tags actually used in deployments
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#2793 [EnvTemplate] Fail fast
  pkg/skaffold/build/tag/env_template.go
  pkg/skaffold/build/tag/env_template_test.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/runner/build_deploy.go
Labels: cla: yes

#2784 [skaffold deploy] A tag must be provided for every image
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/deploy_test.go
  cmd/skaffold/app/tips/tips.go
  integration/deploy_test.go
  integration/run_test.go
  integration/testdata/unstable-deployment/Dockerfile
  integration/testdata/unstable-deployment/README.adoc
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, needs-rebase

#2722 Allow users to specify --namespace flag for tasks generated by generate-pipeline
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/generate_pipeline/profile_test.go
  pkg/skaffold/generate_pipeline/tasks.go
  pkg/skaffold/generate_pipeline/tasks_test.go
  pkg/skaffold/runner/generate_pipeline.go
Labels: cla: yes

#2782 Warn helm users when image tags are not used
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes

#2786 Limit concurrent builds on Cluster and GCB builders
  docs/content/en/schemas/v1beta14.json
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/parallel.go
  pkg/skaffold/build/parallel_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#2796 Single way of mocking Kubernetes client/dynamic client
  integration/util.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/kubernetes/client.go
  pkg/skaffold/kubernetes/log.go
  pkg/skaffold/kubernetes/owner.go
  pkg/skaffold/kubernetes/owner_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/sync/sync.go
  pkg/webhook/kubernetes/deployment.go
  pkg/webhook/kubernetes/service.go
Labels: cla: yes, kokoro:run

#2801 Small random fixes to tests and code
  cmd/skaffold/app/cmd/fix_test.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
  pkg/skaffold/docker/docker_init_test.go
  pkg/skaffold/docker/reference.go
  pkg/skaffold/docker/reference_test.go
  pkg/skaffold/kubectl/cli.go
Labels: cla: yes

#2802 Remove misleading log
  pkg/skaffold/sync/sync.go
Labels: cla: yes

#2805 increasing unit test timeout to 90s
  hack/test.sh
Labels: cla: yes

#2783 Skip secret creation/check
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/build/cluster/secret_test.go
Labels: cla: yes

#2803 skaffold init can be interrupted when kompose is running
  cmd/skaffold/app/cmd/init.go
  pkg/skaffold/initializer/init.go
Labels: cla: yes, kokoro:run

#2810 Split the concepts section into several sub-pages
  docs/content/en/docs/concepts/_index.md
  docs/content/en/docs/concepts/architecture/_index.md
  docs/content/en/docs/concepts/config/_index.md
  docs/content/en/docs/concepts/image_repositories/_index.md
  docs/content/en/docs/concepts/local_development/_index.md
  docs/content/en/docs/concepts/modes/_index.md
  docs/content/en/docs/concepts/pipeline/_index.md
  docs/content/en/docs/concepts/workflow/_index.md
Labels: cla: yes

#2819 remove unused values helm example
  examples/helm-deployment/skaffold-helm/values.yaml
  integration/examples/helm-deployment/skaffold-helm/values.yaml
Labels: cla: yes

#2773 Improve `skaffold init` behaviour when tags are used in manifests
  integration/init_test.go
  integration/testdata/init/ignore-tags/Dockerfile
  integration/testdata/init/ignore-tags/k8s-pod.yaml
  integration/testdata/init/ignore-tags/main.go
  pkg/skaffold/deploy/kubectl/images.go
  pkg/skaffold/deploy/kubectl/images_test.go
  pkg/skaffold/initializer/init.go
Labels: cla: yes

#2815 Simplify doDev()
  pkg/skaffold/runner/dev.go
Labels: cla: yes

#2825 Revert "Add --config-files flag for generate-pipeline command"
  cmd/skaffold/app/cmd/generate_pipeline.go
  integration/generate_pipeline_test.go
  integration/testdata/generate_pipeline/existing_oncluster/expectedPipeline.yaml
  integration/testdata/generate_pipeline/existing_other/expectedPipeline.yaml
  integration/testdata/generate_pipeline/multiple_configs/expectedPipeline.yaml
  integration/testdata/generate_pipeline/multiple_configs/expectedSkaffold.yaml
  integration/testdata/generate_pipeline/multiple_configs/skaffold.yaml
  integration/testdata/generate_pipeline/multiple_configs/sub-app/skaffold.yaml
  integration/testdata/generate_pipeline/no_profiles/expectedPipeline.yaml
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/tasks.go
  pkg/skaffold/runner/generate_pipeline.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes

#2824 Fix portforward flake
  integration/dev_test.go
Labels: cla: yes

#2823 skaffold trace -> kaniko debug
  pkg/skaffold/build/cluster/logs.go
  pkg/skaffold/build/cluster/logs_test.go
Labels: cla: yes

#2799 fix flake in in-cluster build
  integration/build_test.go
  integration/util.go
  testutil/util.go
Labels: cla: yes

#2829 Simplify TestBuildInCluster
  integration/build_test.go
  testutil/util.go
Labels: cla: yes

#2831 Artifact caching is on by default
  integration/dev_test.go
  integration/port_forward_test.go
Labels: cla: yes

#2798 Improve versioning
  hack/new_config_version/version.go
  hack/new_version.sh
Labels: cla: yes, priority/p0

#2822 add example for skaffold generate-pipeline
  examples/generate-pipeline/Dockerfile
  examples/generate-pipeline/README.adoc
  examples/generate-pipeline/k8s-pod.yaml
  examples/generate-pipeline/main.go
  examples/generate-pipeline/skaffold.yaml
  integration/examples/generate-pipeline/Dockerfile
  integration/examples/generate-pipeline/README.adoc
  integration/examples/generate-pipeline/expectedPipeline.yaml
  integration/examples/generate-pipeline/expectedSkaffold.yaml
  integration/examples/generate-pipeline/k8s-pod.yaml
  integration/examples/generate-pipeline/main.go
  integration/examples/generate-pipeline/skaffold.yaml
  integration/generate_pipeline_test.go
Labels: cla: yes

#2671 Design proposal for integrationtest command
  docs/design_proposals/integrationtest-command.md
Labels: cla: yes, kind/design discussion

#2841 Ignore codecov.io upload errors
  Makefile
Labels: cla: yes

#2839 Only activate `env: "KEY="` for empty environment variable value, clearly document pattern behavior
  docs/content/en/schemas/v1beta14.json
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: cla: yes

#2828 Improve runner
  pkg/skaffold/runner/changeset.go
  pkg/skaffold/runner/dev.go
Labels: cla: yes

#2845 add deploy stabilize timer
  pkg/skaffold/runner/deploy.go
Labels: cla: yes

#2846 refactor pollDeploymentRolloutStatus
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes

#2811 Print status check summary when a status check is completed.
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
Labels: cla: yes

#2708 Add Kaniko builder to GCB
  docs/content/en/schemas/v1beta14.json
  examples/gcb-kaniko/Dockerfile
  examples/gcb-kaniko/README.adoc
  examples/gcb-kaniko/k8s-pod.yaml
  examples/gcb-kaniko/main.go
  examples/gcb-kaniko/skaffold.yaml
  integration/examples/gcb-kaniko/Dockerfile
  integration/examples/gcb-kaniko/README.adoc
  integration/examples/gcb-kaniko/k8s-pod.yaml
  integration/examples/gcb-kaniko/main.go
  integration/examples/gcb-kaniko/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/build/gcb/kaniko.go
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/gcb/spec.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions_test.go
Labels: !! config-change !!, build/kaniko, cla: yes

#2838 [doc-style]/Sorting out the tools list follow the workflow picture.
  README.md
Labels: cla: yes

#2847 Add `Deployment` resource struct.
  integration/run_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes

#2854 Always add image flag to jib builders in skaffold init
  pkg/skaffold/jib/jib_init.go
  pkg/skaffold/jib/jib_init_test.go
Labels: cla: yes

#2851 Add Resource.Status object and remove sync.Map
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/status.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes

#2853 Upgrade golangci-lint to v1.18.0
  hack/linter.sh
Labels: cla: yes

#2060 Prepare to Add functionality to Replacer interface to restrict setting labels on certain kinds.
  pkg/skaffold/deploy/kubectl/images.go
  pkg/skaffold/deploy/kubectl/labels.go
  pkg/skaffold/deploy/kubectl/matcher.go
  pkg/skaffold/deploy/kubectl/matcher_test.go
  pkg/skaffold/deploy/kubectl/namespaces.go
  pkg/skaffold/deploy/kubectl/visitor.go
  pkg/skaffold/deploy/kubectl/visitor_test.go
Labels: cla: yes

#2808 Unify jibMaven and jibGradle blocks into jib with auto detection
  deprecation-policy.md
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/schemas/v1beta14.json
  integration/examples/jib-gradle/skaffold.yaml
  integration/examples/jib-multimodule/README.adoc
  integration/examples/jib-multimodule/skaffold.yaml
  integration/examples/jib/README.adoc
  integration/examples/jib/skaffold.yaml
  integration/testdata/debug/skaffold.yaml
  integration/testdata/jib-gradle/skaffold.yaml
  integration/testdata/jib/skaffold.yaml
  pkg/skaffold/build/gcb/jib.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/gcb/spec.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/jib_gradle.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/generate_pipeline/profile_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/jib/jib.go
  pkg/skaffold/jib/jib_gradle.go
  pkg/skaffold/jib/jib_gradle_test.go
  pkg/skaffold/jib/jib_init.go
  pkg/skaffold/jib/jib_init_test.go
  pkg/skaffold/jib/jib_maven.go
  pkg/skaffold/jib/jib_maven_test.go
  pkg/skaffold/jib/jib_test.go
  pkg/skaffold/runner/diagnose.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta13/upgrade.go
  pkg/skaffold/schema/v1beta13/upgrade_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: cla: yes, kokoro:run

#2861 add tests for `Status.String` method.
  pkg/skaffold/deploy/resource/status_test.go
Labels: cla: yes

#2864 Fail PR if it has a structural schema change in a released version
  hack/check-schema-changes.sh
  hack/checks.sh
  hack/versions/cmd/schema_check/check.go
  hack/versions/pkg/diff/godiff.go
  hack/versions/pkg/diff/godiff_test.go
  hack/versions/pkg/schema/check.go
  hack/versions/pkg/schema/git.go
  hack/versions/pkg/version.go
Labels: cla: yes

#2878 Upgrade jib to 1.6.0
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib-gradle/build.gradle
  integration/testdata/jib/pom.xml
Labels: cla: yes

#2880 fix typo - remove extra quotes in schema change detector
  hack/versions/pkg/schema/check.go
Labels: cla: yes

#2882 rename hack/versions/cmd/new/new.go to hack/versions/cmd/new/version.go
  hack/versions/cmd/new/version.go
Labels: cla: yes

#2884 Fix build script for doc generation.
  deploy/docs/build.sh
Labels: cla: yes

#2883 fix new version scenario in schema change detector
  hack/versions/pkg/schema/check.go
Labels: cla: yes

#2890 Removing testing version dependent skaffold config test in examples
  integration/examples/generate-pipeline/expectedSkaffold.yaml
  integration/generate_pipeline_test.go
Labels: cla: yes

#2834 add render interface to deployers which is not implemented
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes

#2866 Print deployment status after every 0.5 seconds.
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes

#2891 Upgrade jib to 1.6.1
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib-gradle/build.gradle
  integration/testdata/jib/pom.xml
Labels: cla: yes

#2871 kustomize build args part 2
  docs/content/en/schemas/v1beta15.json
  integration/examples/kustomize/README.adoc
  integration/examples/kustomize/skaffold-kustomize-args.yaml
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta14/upgrade.go
Labels: cla: yes

#2892 Small refactors
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes

#2893 Add buildpacks example to be referenced in buildpacks docs
  deploy/skaffold/Dockerfile
  examples/buildpacks/README.adoc
  examples/buildpacks/build.sh
  examples/buildpacks/go.mod
  examples/buildpacks/k8s-pod.yaml
  examples/buildpacks/main.go
  examples/buildpacks/skaffold.yaml
  integration/build_test.go
  integration/examples/buildpacks/README.adoc
  integration/examples/buildpacks/build.sh
  integration/examples/buildpacks/go.mod
  integration/examples/buildpacks/k8s-pod.yaml
  integration/examples/buildpacks/main.go
  integration/examples/buildpacks/skaffold.yaml
Labels: cla: yes

#2668 init: Add default config name
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes

#2879 Add docs and tutorial for buildpacks
  docs/content/en/docs/how-tos/builders/_index.md
  docs/content/en/docs/how-tos/buildpacks/_index.md
  docs/content/en/samples/buildpacks/build.sh
  docs/content/en/samples/buildpacks/skaffold.yaml
Labels: cla: yes

#2886 Add graceful termination for custom builders
  pkg/skaffold/build/custom/custom.go
  pkg/skaffold/build/custom/custom_test.go
Labels: cla: yes

#2896 [Refactor] Move pollDeploymentStatus to resource.Deployment.CheckStatus
  pkg/skaffold/deploy/resource.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes

#2907 Fix test flake TestPollResourceStatus
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes

#2913 Add missing T.Helper() in testutil.Check* as required
  testutil/util.go
Labels: cla: yes

#2914 Add Jib-Gradle support for Kotlin buildscripts
  pkg/skaffold/jib/jib.go
  pkg/skaffold/jib/jib_init.go
  pkg/skaffold/jib/jib_init_test.go
  pkg/skaffold/jib/jib_test.go
Labels: cla: yes

#2894 add github pull request template
  .github/pull_request_template.md
  DEVELOPMENT.md
Labels: cla: yes

#2910 Optional pull secret
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#2905 Refactor Deployment common functions in to a Base struct in prep to pod
  pkg/skaffold/deploy/resource.go
  pkg/skaffold/deploy/resource/base.go
  pkg/skaffold/deploy/resource/base_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes

#2916 add protos for status check
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes

#2924 added support for interface type in schema check
  hack/versions/pkg/diff/godiff.go
  hack/versions/pkg/diff/godiff_test.go
Labels: cla: yes, size/S

#2895 Add `setFiles` to `HelmDeploy.HelmRelease` skaffold config which will be add `--set-files` argument to helm CLI
  docs/content/en/schemas/v1beta15.json
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#2931 added release comments manually
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1alpha1/config.go
  pkg/skaffold/schema/v1alpha2/config.go
  pkg/skaffold/schema/v1alpha3/config.go
  pkg/skaffold/schema/v1alpha4/config.go
  pkg/skaffold/schema/v1alpha5/config.go
  pkg/skaffold/schema/v1beta1/config.go
  pkg/skaffold/schema/v1beta10/config.go
  pkg/skaffold/schema/v1beta11/config.go
  pkg/skaffold/schema/v1beta12/config.go
  pkg/skaffold/schema/v1beta13/config.go
  pkg/skaffold/schema/v1beta14/config.go
  pkg/skaffold/schema/v1beta2/config.go
  pkg/skaffold/schema/v1beta3/config.go
  pkg/skaffold/schema/v1beta4/config.go
  pkg/skaffold/schema/v1beta5/config.go
  pkg/skaffold/schema/v1beta6/config.go
  pkg/skaffold/schema/v1beta7/config.go
  pkg/skaffold/schema/v1beta8/config.go
  pkg/skaffold/schema/v1beta9/config.go
Labels: cla: yes, size/S

#2928 Add pod resource with no status check implemented.
  pkg/skaffold/deploy/resource/pod.go
  pkg/skaffold/deploy/resource/pod_test.go
Labels: cla: yes, size/L

#2926 Include build args in cache hash generation
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/hash_test.go
Labels: cla: yes, kind/bug, priority/p1, size/L

#2887 Fix helm deployer with imageStrategy helm and fix test runner
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes

#2936 fix flake TestGetSetFileValues
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/XS

#2927 Bump golangci-lint to v0.19.0
  pkg/skaffold/schema/v1alpha2/upgrade.go
  pkg/skaffold/schema/v1alpha3/upgrade.go
  pkg/skaffold/schema/v1alpha4/upgrade.go
  pkg/skaffold/schema/v1alpha5/upgrade.go
  pkg/skaffold/schema/v1beta1/upgrade.go
  pkg/skaffold/schema/v1beta10/upgrade.go
  pkg/skaffold/schema/v1beta11/upgrade.go
  pkg/skaffold/schema/v1beta12/upgrade.go
  pkg/skaffold/schema/v1beta13/upgrade.go
  pkg/skaffold/schema/v1beta14/upgrade.go
  pkg/skaffold/schema/v1beta2/upgrade.go
  pkg/skaffold/schema/v1beta3/upgrade.go
  pkg/skaffold/schema/v1beta4/upgrade.go
  pkg/skaffold/schema/v1beta5/upgrade.go
  pkg/skaffold/schema/v1beta6/upgrade.go
  pkg/skaffold/schema/v1beta7/upgrade.go
  pkg/skaffold/schema/v1beta8/upgrade.go
  pkg/skaffold/schema/v1beta9/upgrade.go
  pkg/skaffold/sync/sync.go
Labels: cla: yes, size/L

#2937 add better docs for recreate pods
  docs/content/en/schemas/v1beta15.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/XS

#2942 Add unimplemented 'skaffold render' command
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/render.go
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/render.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes, size/L

#2930 Change final status check error message to be more concise.
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/M

#2917 adding release comment management to all config.go
  hack/release.sh
  hack/versions/cmd/mark_latest_released/main.go
  hack/versions/cmd/new/version.go
  hack/versions/cmd/update_comments/main.go
  hack/versions/pkg/schema/comment.go
  hack/versions/pkg/schema/comment_test.go
Labels: cla: yes, size/L

#2899 Update DEVELOPMENT.md with new config change instructions.
  DEVELOPMENT.md
Labels: cla: yes

#2954 cut v0.39.0
  CHANGELOG.md
  deprecation-policy.md
  examples/bazel/skaffold.yaml
  examples/buildpacks/README.adoc
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/README.adoc
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L
