Repository GoogleContainerTools/skaffold, pull requests merged in 2019-12, with the labels that each got.

#3325 Fix links
  docs/content/en/docs/tutorials/custom-builder.md
Labels: cla: yes, size/XS

#3334 Running tests already builds everything
  .travis.yml
Labels: cla: yes, lgtm, size/XS

#3333 Slightly faster builds
  examples/hot-reload/node/Dockerfile
  examples/nodejs/backend/Dockerfile
  examples/react-reload/app/Dockerfile
  integration/examples/hot-reload/node/Dockerfile
  integration/examples/nodejs/backend/Dockerfile
  integration/examples/react-reload/app/Dockerfile
  integration/testdata/debug/nodejs/Dockerfile
  integration/testdata/debug/npm/Dockerfile
Labels: cla: yes, lgtm, size/S

#3328 Change SyncMap supported types check style
  pkg/skaffold/build/local/local.go
Labels: cla: yes, lgtm, size/XS

#3329 Add timings
  hack/checks.sh
Labels: cla: yes, lgtm, size/XS

#3338 Use default value
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
Labels: cla: yes, pr/lgtm, size/S

#3339 fix some samples v1beta15 -> v2alpha1
  examples/custom/README.adoc
  integration/examples/custom/README.adoc
  integration/examples/kustomize/skaffold-kustomize-args.yaml
  integration/testdata/kaniko-insecure-registry/app/skaffold.yaml
  integration/testdata/kaniko-insecure-registry/skaffold.yaml
Labels: cla: yes, size/S

#3298 Fix kind 0.6.0 support
  Makefile
  docs/content/en/docs/environment/local-cluster.md
  integration/dev_test.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/kind.go
  pkg/skaffold/runner/kind_test.go
Labels: cla: yes, pr/lgtm, size/M

#3331 Don’t need to install go
  .travis.yml
Labels: cla: yes, pr/lgtm, size/XS

#3332 Simplify proto generation
  hack/generate-proto.sh
  hack/proto/Dockerfile
  hack/test-generated-proto.sh
Labels: cla: yes, pr/lgtm, size/M

#3335 Add timings to integration job
  Makefile
Labels: cla: yes, pr/lgtm, size/XS

#3330 Remove unused targets
  Makefile
Labels: cla: yes, pr/lgtm, size/S

#3337 Simpler code
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
Labels: cla: yes, pr/lgtm, size/M

#3336 Script to list the top 20 Slowest tests
  hack/slowtests.sh
Labels: cla: yes, pr/lgtm, size/M

#3348 Faster integration tests
  Makefile
  deploy/skaffold/Dockerfile
Labels: cla: yes, size/S

#3341 Cache expensive Go compilation and linting
  .travis.yml
Labels: cla: yes, size/S

#3354 Move credits code to its own package
  .gitignore
  cmd/skaffold/app/cmd/credits.go
  cmd/skaffold/app/cmd/credits/export.go
  cmd/skaffold/app/cmd/credits/fs.go
  cmd/skaffold/app/cmd/credits/fs_dummy.go
Labels: cla: yes, size/M

#3359 package-lock.json is required for npm ci
  examples/react-reload/app/package-lock.json
Labels: cla: yes

#3363 Fix Control API endpoint table rendering
  docs/content/en/docs/design/api.md
Labels: area/docs, cla: yes, meta/docs-preview, size/XS

#3357 Bump kind to v0.6.1
  .travis.yml
  deploy/skaffold/Dockerfile
  docs/content/en/docs/environment/local-cluster.md
Labels: cla: yes, size/XS

#3362 Reorganize builders into subfolders of 'build'
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/bazel/build_test.go
  pkg/skaffold/build/bazel/types.go
  pkg/skaffold/build/buildpacks/build.go
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/metadata.go
  pkg/skaffold/build/buildpacks/types.go
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/custom/build.go
  pkg/skaffold/build/custom/script.go
  pkg/skaffold/build/custom/script_test.go
  pkg/skaffold/build/custom/types.go
  pkg/skaffold/build/dependencies.go
  pkg/skaffold/build/gcb/jib.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/jib/build.go
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/init.go
  pkg/skaffold/build/jib/init_test.go
  pkg/skaffold/build/jib/jib.go
  pkg/skaffold/build/jib/jib_non_windows_test.go
  pkg/skaffold/build/jib/jib_test.go
  pkg/skaffold/build/jib/jib_windows_test.go
  pkg/skaffold/build/jib/maven.go
  pkg/skaffold/build/jib/maven_test.go
  pkg/skaffold/build/jib/types.go
  pkg/skaffold/build/local/custom_test.go
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/jib_gradle.go
  pkg/skaffold/build/local/jib_gradle_test.go
  pkg/skaffold/build/local/jib_maven.go
  pkg/skaffold/build/local/jib_maven_test.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes

#3358 Simplify handling of GCP only tests
  integration/build_test.go
  integration/cache_test.go
  integration/config_test.go
  integration/debug_test.go
  integration/deploy_test.go
  integration/dev_test.go
  integration/diagnose_test.go
  integration/fix_test.go
  integration/generate_pipeline_test.go
  integration/helm_test.go
  integration/init_test.go
  integration/port_forward_test.go
  integration/render_test.go
  integration/rpc_test.go
  integration/run_test.go
  integration/sync_test.go
  integration/util.go
Labels: cla: yes, size/L

#3355 Add commands to list/print json schemas
  .gitignore
  Makefile
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/schema.go
  cmd/skaffold/app/cmd/schema/fs.go
  cmd/skaffold/app/cmd/schema/fs_dummy.go
  cmd/skaffold/app/cmd/schema/list.go
  cmd/skaffold/app/cmd/schema/list_test.go
  cmd/skaffold/app/cmd/schema/print.go
  cmd/skaffold/app/cmd/schema/print_test.go
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
  hack/gen_statik.sh
Labels: cla: yes, size/L

#3373 Better output for go test
  .travis.yml
  Makefile
  deploy/skaffold/Dockerfile
  hack/gotest.sh
  hack/slowtests.sh
  hack/test.sh
Labels: cla: yes, size/L

#3366 Open in cloud code
  docs/static/images/open-cloud-code.png
  examples/bazel/README.md
  examples/buildpacks/README.md
  examples/compose/README.md
  examples/custom/README.md
  examples/gcb-kaniko/README.md
  examples/generate-pipeline/README.md
  examples/getting-started/README.md
  examples/google-cloud-build/README.md
  examples/helm-deployment-dependencies/README.md
  examples/helm-deployment/README.md
  examples/hot-reload/README.md
  examples/jib-gradle/README.md
  examples/jib-multimodule/README.md
  examples/jib/README.md
  examples/kaniko-local/README.md
  examples/kaniko/README.md
  examples/kustomize/README.md
  examples/microservices/README.md
  examples/nodejs/README.md
  examples/profile-patches/README.md
  examples/profiles/README.md
  examples/react-reload/README.md
  examples/structure-tests/README.md
  examples/tagging-with-environment-variables/README.md
  integration/examples/bazel/README.md
  integration/examples/buildpacks/README.md
  integration/examples/compose/README.md
  integration/examples/custom/README.md
  integration/examples/gcb-kaniko/README.md
  integration/examples/generate-pipeline/README.md
  integration/examples/getting-started/README.md
  integration/examples/google-cloud-build/README.md
  integration/examples/helm-deployment-dependencies/README.md
  integration/examples/helm-deployment/README.md
  integration/examples/hot-reload/README.md
  integration/examples/jib-gradle/README.md
  integration/examples/jib-multimodule/README.md
  integration/examples/jib/README.md
  integration/examples/kaniko-local/README.md
  integration/examples/kaniko/README.md
  integration/examples/kustomize/README.md
  integration/examples/microservices/README.md
  integration/examples/nodejs/README.md
  integration/examples/profile-patches/README.md
  integration/examples/profiles/README.md
  integration/examples/react-reload/README.md
  integration/examples/structure-tests/README.md
  integration/examples/tagging-with-environment-variables/README.md
Labels: cla: yes

#3374 Update Go version for cross compilation
  deploy/cross/Dockerfile
Labels: cla: yes, size/XS

#3379 Support FROM “scratch”
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/parse_test.go
Labels: cla: yes

#3381 Revert "Add “Open in Google Cloud Code” button to every example (#3366)"
  docs/static/images/open-cloud-code.png
  examples/bazel/README.md
  examples/buildpacks/README.md
  examples/compose/README.md
  examples/custom/README.md
  examples/gcb-kaniko/README.md
  examples/generate-pipeline/README.md
  examples/getting-started/README.md
  examples/google-cloud-build/README.md
  examples/helm-deployment-dependencies/README.md
  examples/helm-deployment/README.md
  examples/hot-reload/README.md
  examples/jib-gradle/README.md
  examples/jib-multimodule/README.md
  examples/jib/README.md
  examples/kaniko-local/README.md
  examples/kaniko/README.md
  examples/kustomize/README.md
  examples/microservices/README.md
  examples/nodejs/README.md
  examples/profile-patches/README.md
  examples/profiles/README.md
  examples/react-reload/README.md
  examples/structure-tests/README.md
  examples/tagging-with-environment-variables/README.md
  integration/examples/bazel/README.md
  integration/examples/buildpacks/README.md
  integration/examples/compose/README.md
  integration/examples/custom/README.md
  integration/examples/gcb-kaniko/README.md
  integration/examples/generate-pipeline/README.md
  integration/examples/getting-started/README.md
  integration/examples/google-cloud-build/README.md
  integration/examples/helm-deployment-dependencies/README.md
  integration/examples/helm-deployment/README.md
  integration/examples/hot-reload/README.md
  integration/examples/jib-gradle/README.md
  integration/examples/jib-multimodule/README.md
  integration/examples/jib/README.md
  integration/examples/kaniko-local/README.md
  integration/examples/kaniko/README.md
  integration/examples/kustomize/README.md
  integration/examples/microservices/README.md
  integration/examples/nodejs/README.md
  integration/examples/profile-patches/README.md
  integration/examples/profiles/README.md
  integration/examples/react-reload/README.md
  integration/examples/structure-tests/README.md
  integration/examples/tagging-with-environment-variables/README.md
Labels: cla: yes

#3282 Default to gcloud auth
  pkg/skaffold/docker/auth.go
  pkg/skaffold/gcp/auth.go
  pkg/skaffold/gcp/auth_test.go
Labels: cla: yes, size/L

#3377 Extract code that computes Fully Qualified tags
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/util.go
  pkg/skaffold/docker/image_test.go
Labels: cla: yes, size/M

#3380 Upgrade to Go 1.13
  .travis.yml
  DEVELOPMENT.md
  deploy/cross/Dockerfile
  deploy/skaffold/Dockerfile
  deploy/webhook/Dockerfile
  go.mod
  go.sum
  hack/tools/go.mod
Labels: cla: yes, size/S

#3390 Apply resource labels in the deployer
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/runner/new.go
Labels: cla: yes, size/S

#3393 Faster unit tests
  hack/schemas/main.go
  pkg/skaffold/build/misc/graceful.go
  pkg/skaffold/build/misc/graceful_test.go
  pkg/skaffold/build/parallel_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/util/port_test.go
Labels: cla: yes, size/L

#3397 document IDE setup
  DEVELOPMENT.md
Labels: cla: yes, size/S

#3394 Skaffold init recognises nodeJS projects built with Buildpacks
  cmd/skaffold/app/cmd/init.go
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, pr/lgtm, size/L

#3389 Add env vars to kaniko specs
  docs/content/en/schemas/v2alpha1.json
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#3313 Use --set-string for helm image values
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/S

#3016 add a resourceCounter to track pods
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/L

#3326 Cause debug to skip unmarshallable yamls
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/debug_test.go
Labels: cla: yes, pr/lgtm-nit, size/S

#3402 Revert "Upgrade to 1.13"
  .travis.yml
  DEVELOPMENT.md
  deploy/cross/Dockerfile
  deploy/skaffold/Dockerfile
  deploy/webhook/Dockerfile
  go.mod
  go.sum
  hack/tools/go.mod
Labels: cla: yes, size/S

#3404 Better check for valid Kubernetes manifests
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/kubectl/kubectl.go
  pkg/skaffold/initializer/kubectl/kubectl_test.go
  pkg/skaffold/initializer/util.go
  pkg/skaffold/initializer/util_test.go
Labels: cla: yes, size/L

#3407 Convert git tag into proper docker tag
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/git_commit_test.go
Labels: cla: yes, pr/lgtm-nit, size/M

#3410 Integration test: check the output of `skaffold init`
  integration/init_test.go
  integration/testdata/init/compose/skaffold.yaml
  integration/testdata/init/hello/skaffold.yaml
  integration/testdata/init/ignore-tags/skaffold.yaml
  integration/testdata/init/microservices/skaffold.yaml
Labels: cla: yes, pr/lgtm-nit, size/M

#3412 Upgrade to Go 1.13
  .travis.yml
  DEVELOPMENT.md
  deploy/cross/Dockerfile
  deploy/skaffold/Dockerfile
  deploy/webhook/Dockerfile
  go.mod
  hack/tools/go.mod
Labels: cla: yes, pr/lgtm, size/S

#3263 Add --port-forward to skaffold run
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/port_forward_test.go
  pkg/skaffold/runner/build_deploy.go
Labels: cla: yes, pr/lgtm, size/M

#3413 Setup kind and build the docker image in //
  .travis.yml
Labels: cla: yes, size/XS

#3406 Simplify skaffold init code
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
  pkg/skaffold/build/jib/init.go
  pkg/skaffold/build/jib/init_test.go
  pkg/skaffold/docker/docker_init.go
  pkg/skaffold/docker/docker_init_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, pr/lgtm-nit, size/XL

#3414 fix wait logic in TestWaitForPodSucceeded
  pkg/skaffold/kubernetes/wait_test.go
Labels: cla: yes, size/XS

#3418 Add `—port-forward` to `skaffold deploy`
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/XS

#3417 Logger’s start time should be set before deploy
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/portforwarder.go
Labels: cla: yes, size/M

#3419 fix docker/docker reference
  go.mod
  go.sum
Labels: cla: yes, size/XS

#3420 No buffering of test output
  hack/gotest.sh
Labels: cla: yes, size/XS

#3422 Remove packages that are already installed
  deploy/skaffold/Dockerfile
Labels: cla: yes, size/XS

#3423 Upgrade a few CLI tools
  deploy/skaffold/Dockerfile
Labels: cla: yes, size/S

#3426 Release v1.1.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks/go.mod
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/app/package-lock.json
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#3425 Cache Gradle downloads and Go build cache
  .travis.yml
  Makefile
Labels: cla: yes, size/XS

#3437 Commit annoying go.sum
  go.sum
Labels: cla: yes, size/XS

#3460 Track changes of transitive BUILD files
  pkg/skaffold/build/bazel/dependencies.go
  pkg/skaffold/build/bazel/dependencies_test.go
Labels: cla: yes, size/XS
