Repository GoogleContainerTools/skaffold, pull requests merged in 2020-04, with the labels that each got.

#3894 Use new name for the linter’s cache
  .travis.yml
Labels: cla: yes, size/XS

#3906 disable jib gradle in skaffold init by default
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  pkg/skaffold/build/jib/init.go
  pkg/skaffold/build/jib/init_test.go
  pkg/skaffold/initializer/analyze/analyze.go
  pkg/skaffold/initializer/analyze/analyze_test.go
  pkg/skaffold/initializer/analyze/builder.go
  pkg/skaffold/initializer/config/config.go
Labels: cla: yes, size/M

#3892 Better status check
  pkg/skaffold/deploy/resource/base.go
  pkg/skaffold/deploy/resource/base_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
Labels: cla: yes, size/M

#3852 Fix GCB build failure for multi-module Jib projects
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/jib.go
  pkg/skaffold/build/gcb/jib_test.go
Labels: cla: yes, size/L

#3900 fix deployment stabilize max deadline logic to ignore if d.Spec.Deadline is kubernetes default.
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/XS

#3721 kustomize dependencies include environment files (#3720)
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, size/M

#3912 cut v1.7.0
  CHANGELOG.md
  examples/hot-reload/node/package-lock.json
  examples/hot-reload/node/package.json
  examples/microservices/README.md
Labels: cla: yes, size/M

#3919 Disable Python detector's use of PYTHON_VERSION
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
Labels: cla: yes, size/XS

#3901 Add Kustomize example with an image built by skaffold
  integration/examples/getting-started-kustomize/Dockerfile
  integration/examples/getting-started-kustomize/README.md
  integration/examples/getting-started-kustomize/deployment.yaml
  integration/examples/getting-started-kustomize/kustomization.yaml
  integration/examples/getting-started-kustomize/main.go
  integration/examples/getting-started-kustomize/patch.yaml
  integration/examples/getting-started-kustomize/skaffold.yaml
  integration/run_test.go
Labels: cla: yes, size/M

#3924 Update docs to point to new 2020 roadmap
  docs/content/en/docs/resources/_index.md
Labels: cla: yes, size/XS

#3885 Refactoring on filepath.Walk
  cmd/skaffold/app/cmd/find_configs.go
  hack/versions/cmd/new/version.go
  hack/versions/cmd/update_comments/main.go
  pkg/skaffold/build/jib/jib.go
  pkg/skaffold/build/list/list.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/docker/dependencies.go
  pkg/skaffold/docker/dockerignore.go
  pkg/skaffold/docker/syncmap.go
  pkg/skaffold/schema/samples_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/walk/walk.go
  testutil/tmp.go
  vendor/github.com/karrick/godirwalk/go.mod
Labels: cla: yes, size/XL

#3914 fix: correctly set namespace when checking for an existing helm release via skaffold deploy
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/L

#3930 Update error message to use `are` since `manifests` is plural
  pkg/skaffold/initializer/deploy/init.go
Labels: cla: yes, size/XS

#3941 hack/new_version.sh must process `skaffold init` tests too
  hack/versions/cmd/new/version.go
Labels: cla: yes, size/XS

#3931 Simplify Debug Transformer interface and allow Apply to fail on images
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
Labels: cla: yes, size/XXL

#3949 Improve Debug's Go docs
  docs/content/en/docs/workflows/debug.md
Labels: area/docs, cla: yes, kokoro:run, size/S

#3950 Update VS Code Go launch snippet
  docs/content/en/docs/workflows/debug.md
Labels: area/docs, cla: yes, size/S

#3833 Whitelist recursively transformable kinds.
  pkg/skaffold/deploy/kubectl/namespace_test.go
  pkg/skaffold/deploy/kubectl/visitor.go
  pkg/skaffold/deploy/kubectl/visitor_test.go
Labels: cla: yes, size/L

#3954 Add error codes to event api to send error codes to Skaffold Event API
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/errors/errors.go
  pkg/skaffold/event/event.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#3956 Update pack image to v0.10.0
  deploy/buildpacks/publish.sh
Labels: cla: yes, size/XS

#3971 Upgrade Jib to 2.2.0
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib-sync/build.gradle
  integration/testdata/jib-sync/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#3975 Cut v1.8.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#3972 Move StripTags to tag package and expose as util function
  pkg/skaffold/build/tag/util.go
  pkg/skaffold/build/tag/util_test.go
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/util.go
Labels: cla: yes, size/L

#3989 Improve GCB docs to include a table of properties
  docs/content/en/docs/pipeline-stages/builders/docker.md
  docs/content/en/docs/pipeline-stages/builders/jib.md
Labels: cla: yes, size/S

#3987 ResourceType is of type string
  docs/content/en/schemas/v1.json
  docs/content/en/schemas/v1beta12.json
  docs/content/en/schemas/v1beta13.json
  docs/content/en/schemas/v1beta14.json
  docs/content/en/schemas/v1beta15.json
  docs/content/en/schemas/v1beta16.json
  docs/content/en/schemas/v1beta17.json
  docs/content/en/schemas/v2alpha1.json
  docs/content/en/schemas/v2alpha2.json
  docs/content/en/schemas/v2alpha3.json
  docs/content/en/schemas/v2alpha4.json
  docs/content/en/schemas/v2beta1.json
  docs/content/en/schemas/v2beta2.json
  hack/schemas/main.go
Labels: cla: yes, size/M

#3964 [json schema] When we don’t know a field’s type, let’s leave it empty
  docs/content/en/schemas/v1.json
  docs/content/en/schemas/v1beta10.json
  docs/content/en/schemas/v1beta11.json
  docs/content/en/schemas/v1beta12.json
  docs/content/en/schemas/v1beta13.json
  docs/content/en/schemas/v1beta14.json
  docs/content/en/schemas/v1beta15.json
  docs/content/en/schemas/v1beta16.json
  docs/content/en/schemas/v1beta17.json
  docs/content/en/schemas/v1beta5.json
  docs/content/en/schemas/v1beta6.json
  docs/content/en/schemas/v1beta7.json
  docs/content/en/schemas/v1beta8.json
  docs/content/en/schemas/v1beta9.json
  docs/content/en/schemas/v2alpha1.json
  docs/content/en/schemas/v2alpha2.json
  docs/content/en/schemas/v2alpha3.json
  docs/content/en/schemas/v2alpha4.json
  docs/content/en/schemas/v2beta1.json
  docs/content/en/schemas/v2beta2.json
  hack/schemas/main.go
Labels: cla: yes, size/S

#3969 Fix examples for debug
  examples/compose/Dockerfile
  examples/gcb-kaniko/Dockerfile
  examples/generate-pipeline/Dockerfile
  examples/getting-started/Dockerfile
  examples/google-cloud-build/Dockerfile
  examples/kaniko/Dockerfile
  examples/microservices/leeroy-app/Dockerfile
  examples/microservices/leeroy-web/Dockerfile
  examples/profile-patches/base-service/Dockerfile
  examples/profile-patches/hello-service/Dockerfile
  examples/profile-patches/world-service/Dockerfile
  examples/profiles/hello-service/Dockerfile
  examples/profiles/world-service/Dockerfile
  examples/structure-tests/Dockerfile
  examples/tagging-with-environment-variables/Dockerfile
  integration/examples/compose/Dockerfile
  integration/examples/gcb-kaniko/Dockerfile
  integration/examples/generate-pipeline/Dockerfile
  integration/examples/getting-started/Dockerfile
  integration/examples/google-cloud-build/Dockerfile
  integration/examples/kaniko/Dockerfile
  integration/examples/microservices/leeroy-app/Dockerfile
  integration/examples/microservices/leeroy-web/Dockerfile
  integration/examples/profile-patches/base-service/Dockerfile
  integration/examples/profile-patches/hello-service/Dockerfile
  integration/examples/profile-patches/world-service/Dockerfile
  integration/examples/profiles/hello-service/Dockerfile
  integration/examples/profiles/world-service/Dockerfile
  integration/examples/structure-tests/Dockerfile
  integration/examples/tagging-with-environment-variables/Dockerfile
Labels: cla: yes, size/M

#3973 Add docs for configuring helm project with skaffold
  docs/content/en/docs/pipeline-stages/deployers.md
  docs/content/en/docs/pipeline-stages/deployers/_index.md
  docs/content/en/docs/pipeline-stages/deployers/helm.md
  docs/content/en/docs/pipeline-stages/deployers/kubectl.md
  docs/content/en/docs/pipeline-stages/deployers/kustomize.md
Labels: cla: yes, size/L

#3992 install docs: use "install" and "choco -y"
  docs/content/en/docs/install/_index.md
Labels: cla: yes, size/S

#3962 Produce a clear error when the Dockerfile is deleted while running `skaffold dev`
  pkg/skaffold/docker/parse.go
  pkg/skaffold/filemon/monitor.go
  pkg/skaffold/runner/listen.go
  pkg/skaffold/runner/listen_test.go
Labels: cla: yes, size/L

#3993 fix a nilpointer when running status_check_Test
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/XS

#3999 Fail fast if the Dockerfile can’t be found
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/docker_test.go
  pkg/skaffold/docker/dependencies.go
  pkg/skaffold/docker/dependencies_test.go
Labels: cla: yes, size/M

#3997 Simplify error messages
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/parallel.go
  pkg/skaffold/build/sequence.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/runner/build_deploy.go
Labels: cla: yes, size/M

#3985 Always use the RunId overridden with an env var
  pkg/skaffold/config/options.go
  pkg/skaffold/config/options_test.go
  pkg/skaffold/deploy/labeller.go
  pkg/skaffold/deploy/labeller_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/version/version.go
Labels: cla: yes, size/L

#3984 Changing test config invalidates the build cache
  pkg/skaffold/runner/new.go
Labels: cla: yes, size/S

#4006 Use less memory for linting
  hack/linter.sh
Labels: cla: yes, size/XS

#4004 Mock test to make it 4s faster
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/M

#3983 Run container-structure-test on remote images
  pkg/skaffold/runner/new.go
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/test/types.go
Labels: cla: yes, size/L

#3998 Fail fast with clear message if Docker is not started
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/local_test.go
  testutil/fake_image_api.go
Labels: cla: yes, size/M

#4009 Use Go 1.14.2 to prevent SIGILL: illegal instruction on macOS
  deploy/cross/Dockerfile
Labels: cla: yes, size/XS

#3996 Fail when cache check should have succeeded
  pkg/skaffold/build/cache/retrieve.go
Labels: cla: yes, size/XS

#3976 Validate generated json schema
  go.mod
  go.sum
  hack/schemas/main_test.go
  vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonpointer/README.md
  vendor/github.com/xeipuuv/gojsonpointer/pointer.go
  vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonreference/README.md
  vendor/github.com/xeipuuv/gojsonreference/reference.go
  vendor/github.com/xeipuuv/gojsonschema/.gitignore
  vendor/github.com/xeipuuv/gojsonschema/.travis.yml
  vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonschema/README.md
  vendor/github.com/xeipuuv/gojsonschema/draft.go
  vendor/github.com/xeipuuv/gojsonschema/errors.go
  vendor/github.com/xeipuuv/gojsonschema/format_checkers.go
  vendor/github.com/xeipuuv/gojsonschema/glide.yaml
  vendor/github.com/xeipuuv/gojsonschema/go.mod
  vendor/github.com/xeipuuv/gojsonschema/go.sum
  vendor/github.com/xeipuuv/gojsonschema/internalLog.go
  vendor/github.com/xeipuuv/gojsonschema/jsonContext.go
  vendor/github.com/xeipuuv/gojsonschema/jsonLoader.go
  vendor/github.com/xeipuuv/gojsonschema/locales.go
  vendor/github.com/xeipuuv/gojsonschema/result.go
  vendor/github.com/xeipuuv/gojsonschema/schema.go
  vendor/github.com/xeipuuv/gojsonschema/schemaLoader.go
  vendor/github.com/xeipuuv/gojsonschema/schemaPool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaReferencePool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaType.go
  vendor/github.com/xeipuuv/gojsonschema/subSchema.go
  vendor/github.com/xeipuuv/gojsonschema/types.go
  vendor/github.com/xeipuuv/gojsonschema/utils.go
  vendor/github.com/xeipuuv/gojsonschema/validation.go
  vendor/modules.txt
Labels: cla: yes, size/XXL

#4010 Gracefully shutdown RPC servers.
  pkg/skaffold/server/server.go
Labels: cla: yes, size/S

#4015 Fix nodemon versions
  examples/hot-reload/node/package-lock.json
  examples/hot-reload/node/package.json
  examples/nodejs/backend/package-lock.json
  examples/nodejs/backend/package.json
  integration/examples/hot-reload/node/package-lock.json
  integration/examples/hot-reload/node/package.json
  integration/examples/nodejs/backend/package-lock.json
  integration/examples/nodejs/backend/package.json
Labels: cla: yes

#3990 Support --default-repo=‘’ to erase the value from global config
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/init_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/config/types.go
  pkg/skaffold/config/types_test.go
  pkg/skaffold/config/util.go
  pkg/skaffold/runner/build_deploy.go
Labels: cla: yes, size/L

#4017 Add test for GetDefaultRepo
  pkg/skaffold/config/util_test.go
Labels: cla: yes, size/M

#4014 Adding Brian as a maintainer
  .github/CODEOWNERS
Labels: cla: yes, size/XS

#3966 Initial draft for sending skaffold metrics using metadata event
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  integration/rpc_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/sequence_test.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/event/util.go
  pkg/skaffold/event/util_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/new.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XXL

#4020 Update to Helm 3 in builder image
  Makefile
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/S

#3939 Update 2020 Roadmap
  ROADMAP.md
Labels: cla: yes, size/M

#4012 Add codes for error types and detect terminated containers
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/diag/validator/resource.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XL

#4024 For upgrades, direct users to the GitHub release page
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/constants/constants.go
Labels: cla: yes, size/S

#4023 [kaniko] Better error message when upload fails
  pkg/skaffold/build/cluster/kaniko.go
Labels: cla: yes, size/S

#4016 Support `skaffold fix —version skaffold/v1`
  cmd/skaffold/app/cmd/find_configs.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/fix_test.go
  cmd/skaffold/app/cmd/runner.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/runner/generate_pipeline.go
  pkg/skaffold/schema/latest/upgrade.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/samples_test.go
  pkg/skaffold/schema/versions.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/L

#4019 When a tagger fails, use a fallback tagger
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/runner/build_deploy.go
Labels: cla: yes, size/M

#3979 skaffold render --output takes GCS file path
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/util.go
  pkg/skaffold/util/gsutil.go
  pkg/skaffold/util/gsutil_test.go
Labels: cla: yes, size/L

#4021 Use NODEJS_VERSION and NODE_ENV in detection
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
Labels: cla: yes, size/S

#4031 Fail fast when k8s is not reachable
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/dev_test.go
Labels: cla: yes, size/M

#4030 Remove dead code for schema upgrades
  pkg/skaffold/schema/v1/upgrade.go
  pkg/skaffold/schema/v1beta14/upgrade.go
  pkg/skaffold/schema/v1beta15/upgrade.go
  pkg/skaffold/schema/v1beta16/upgrade.go
  pkg/skaffold/schema/v1beta17/upgrade.go
  pkg/skaffold/schema/v2alpha3/upgrade.go
  pkg/skaffold/schema/v2alpha4/upgrade.go
  pkg/skaffold/schema/v2beta1/upgrade.go
  pkg/skaffold/schema/v2beta2/upgrade.go
Labels: cla: yes, size/M

#4034 Add CLI option `--profile-auto-activation` to allow disabling automatic profile activation.
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: cla: yes, size/L

#4039 Add a dry-run to `skaffold build`
  cmd/skaffold/app/cmd/build.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
Labels: cla: yes, size/M

#4041 Fix typo
  .github/pull_request_template.md
Labels: cla: yes, size/XS

#4042 Fail fast if minikube is used but not started
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
  pkg/skaffold/runner/new.go
Labels: cla: yes, size/S

#3733 Add a new survey command to show Skaffold User Survey form url.
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/config/set.go
  cmd/skaffold/app/cmd/survey.go
  docs/content/en/docs/references/cli/_index.md
  go.mod
  go.sum
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
  vendor/github.com/pkg/browser/LICENSE
  vendor/github.com/pkg/browser/README.md
  vendor/github.com/pkg/browser/browser.go
  vendor/github.com/pkg/browser/browser_darwin.go
  vendor/github.com/pkg/browser/browser_linux.go
  vendor/github.com/pkg/browser/browser_openbsd.go
  vendor/github.com/pkg/browser/browser_unsupported.go
  vendor/github.com/pkg/browser/browser_windows.go
  vendor/modules.txt
Labels: cla: yes, size/L

#4043 Support Google Cloud Build logging options
  docs/content/en/schemas/v2beta3.json
  pkg/skaffold/build/gcb/spec.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#4040 Replace local tags warning with debug log and documentation
  docs/content/en/docs/pipeline-stages/taggers.md
  pkg/skaffold/runner/deploy.go
Labels: cla: yes, size/M

#4050 Disable status check for integration test
  integration/rpc_test.go
Labels: cla: yes, size/XS

#4026 Enable debugging of Buildpacks
  integration/rpc_test.go
  pkg/skaffold/debug/cnb.go
  pkg/skaffold/debug/cnb_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_test.go
Labels: cla: yes, size/L

#4053 Handle port forwarding rules in sequence
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
Labels: cla: yes, size/XS

#4027 Skip podspecs that already have a debug.cloud.google.com/config annotation
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
Labels: cla: yes, size/S

#4061 Remove dead code
  pkg/skaffold/apiversion/apiversion.go
  pkg/skaffold/apiversion/apiversion_test.go
Labels: cla: yes, size/S

#4063 Use the same variable names as in other tests
  hack/versions/pkg/diff/godiff_test.go
  hack/versions/pkg/schema/comment_test.go
  pkg/skaffold/initializer/build/builders_test.go
Labels: cla: yes, size/L

#4060 Simplify code
  cmd/skaffold/skaffold.go
Labels: cla: yes, size/XS

#4062 Use t.CheckNoError(err)
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/kubernetes/generator/generate_test.go
Labels: cla: yes, size/S

#4064 Use test helpers
  hack/versions/pkg/diff/godiff_test.go
  hack/versions/pkg/schema/comment_test.go
Labels: cla: yes, size/S

#4067 Inline steps
  pkg/skaffold/build/gcb/kaniko.go
Labels: cla: yes, size/XS

#4068 Shorter code
  pkg/skaffold/build/util.go
Labels: cla: yes, size/XS

#4071 Move config code where it belongs
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/debugging.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/S

#4069 go mod tidy
  go.mod
  vendor/modules.txt
Labels: cla: yes, size/XS

#4072 Use zero value for arrays
  cmd/skaffold/app/flags/image.go
  hack/schemas/main.go
  pkg/diag/diag.go
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/skaffold/deploy/util.go
  pkg/skaffold/deploy/util_test.go
  pkg/skaffold/event/util.go
  pkg/skaffold/initializer/deploy/kubectl_test.go
  pkg/skaffold/kubernetes/util.go
  pkg/skaffold/util/cmd_test.go
  testutil/cmd_helper.go
Labels: cla: yes, size/M

#4073 Don’t globally set log level in tests
  hack/versions/pkg/diff/godiff_test.go
  pkg/skaffold/kubernetes/context/context_test.go
Labels: cla: yes, size/XS

#4066 Always use the same import alias
  cmd/skaffold/app/cmd/config/list_test.go
  integration/build_cluster_test.go
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/diag/validator/resource.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/kubectl/visitor.go
  pkg/skaffold/generate_pipeline/tasks.go
  pkg/skaffold/generate_pipeline/tasks_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/kubernetes/util.go
  pkg/skaffold/kubernetes/wait.go
  pkg/skaffold/kubernetes/watcher.go
  pkg/skaffold/pipeline/task.go
  pkg/skaffold/pipeline/task_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/L

#4065 Simplify test helper
  pkg/skaffold/runner/runner_test.go
  testutil/checks.go
Labels: cla: yes, size/S

#4070 Change default buildpacks
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
  docs/content/en/samples/builders/buildpacks.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  integration/examples/buildpacks-node/skaffold.yaml
  integration/examples/buildpacks/skaffold.yaml
Labels: cla: yes, size/S

#4075 Inline function
  pkg/skaffold/util/cmd_test.go
Labels: cla: yes, size/XS

#4078 Clarify which containers log tailing works with
  docs/content/en/docs/pipeline-stages/log-tailing.md
Labels: cla: yes
