Repository GoogleContainerTools/skaffold, pull requests merged in 2020-02, with the labels that each got.

#3628 customizable jib feature minimum requirements
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/maven.go
  pkg/skaffold/build/jib/maven_test.go
  pkg/skaffold/build/jib/sync.go
  pkg/skaffold/build/jib/sync_test.go
Labels: cla: yes, size/L

#3632 Bump golangci to 1.23.2
  hack/linter.sh
Labels: cla: yes, size/XS

#3629 Update pack image to v0.8.1
  deploy/buildpacks/publish.sh
Labels: cla: yes, size/S

#3636 Small refactor of debugging code and improve internal doc
  docs/content/en/docs/workflows/debug.md
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/transform.go
Labels: cla: yes, size/M

#3637 Rename ArtifactImage -> Artifact in `debug`
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  docs/content/en/docs/workflows/debug.md
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/event/event.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#3641 Update CHANGELOG.md
  CHANGELOG.md
Labels: cla: yes, size/XS

#3634 Version can be in the process of being released
  hack/versions/cmd/latest/version.go
  hack/versions/cmd/latest_released/version.go
  hack/versions/cmd/new/version.go
  hack/versions/cmd/update_comments/main.go
  hack/versions/pkg/schema/check.go
  hack/versions/pkg/schema/version.go
  hack/versions/pkg/version/version.go
Labels: cla: yes, size/S

#3657 fix nilpointer with skaffold init --skip-build
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/analyze_test.go
Labels: cla: yes, size/M

#3658 Fix npe when resetting status check state
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
Labels: cla: yes, size/M

#3651 Disable all colors in Buildpacks’s output when not in a terminal
  go.mod
  go.sum
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/logger.go
Labels: cla: yes, size/S

#3660 a hidden flag for simpler access to new init format
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/json.go
  pkg/skaffold/initializer/json_test.go
Labels: cla: yes, size/M

#3643 retry pruning when skaffold could not prune local images due running containers
  pkg/skaffold/docker/image.go
Labels: cla: yes, size/S

#3670 [refactor] move k8s-related utility functions to kubernetes package
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/initializer/kubectl.go
  pkg/skaffold/initializer/kubectl_test.go
  pkg/skaffold/kubernetes/util.go
  pkg/skaffold/kubernetes/util_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: cla: yes, refactor, size/L

#3669 [refactor] move shared initializer config to separate package
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/analyze_test.go
  pkg/skaffold/initializer/config/config.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, refactor, size/L

#3673 [refactor] move config util function to schema package
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/kubectl.go
  pkg/skaffold/schema/versions.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/L

#3674 [refactor] move prompting logic to separate package
  pkg/skaffold/initializer/builders.go
  pkg/skaffold/initializer/builders_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/prompt/prompt.go
Labels: cla: yes, size/S

#3671 enable finding alternative builders nested under Jib projects
  pkg/skaffold/initializer/analyze_test.go
  pkg/skaffold/initializer/builders.go
Labels: cla: yes, size/S

#3675 [refactor] move deploy related init code to deploy package
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/analyze_test.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/deploy/init.go
  pkg/skaffold/initializer/deploy/kubectl.go
  pkg/skaffold/initializer/deploy/kubectl_test.go
  pkg/skaffold/initializer/init.go
Labels: cla: yes, size/M

#3676 [refactor] move build and analyze related code into separate packages
  pkg/skaffold/initializer/analyze/analyze.go
  pkg/skaffold/initializer/analyze/analyze_test.go
  pkg/skaffold/initializer/analyze/builder.go
  pkg/skaffold/initializer/analyze/config.go
  pkg/skaffold/initializer/analyze/config_test.go
  pkg/skaffold/initializer/analyze/directory.go
  pkg/skaffold/initializer/analyze/kubernetes.go
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/json.go
  pkg/skaffold/initializer/build/json_test.go
  pkg/skaffold/initializer/build/set.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/init.go
Labels: cla: yes, refactor, size/XL

#3682 [refactor] make DoInit() a proper controller
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/cli.go
  pkg/skaffold/initializer/build/init.go
  pkg/skaffold/initializer/build/json.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/build/util.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/deploy/init.go
  pkg/skaffold/initializer/init.go
Labels: cla: yes, refactor

#3683 Better `nodejs` sample
  examples/nodejs/backend/Dockerfile
  examples/nodejs/backend/package.json
  examples/nodejs/skaffold.yaml
  integration/examples/nodejs/backend/Dockerfile
  integration/examples/nodejs/backend/package.json
  integration/examples/nodejs/skaffold.yaml
Labels: cla: yes, size/M

#3667 Add pkg/diag new package for diagnostics only library
  .travis.yml
  Makefile
  Makefile.diag
  hack/gotest.sh
  pkg/diag/version/version.go
  pkg/diag/version/version_test.go
Labels: cla: yes, size/L

#3696 Allow 'make test' to work for users who do not have jq installed
  hack/gotest.sh
Labels: cla: yes, size/S

#3698 go.mod: upgrade google/go-cmp to v0.4.0
  go.mod
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/modules.txt
Labels: cla: yes, size/XS

#3663 Support kustomize "extended" patches. #2909
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, kokoro:run, size/M

#3684 Add 2020 Roadmap
  ROADMAP.md
Labels: cla: yes, size/M

#3691 hidden --minikube-profile flag
  cmd/skaffold/app/cmd/flags.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/config/options.go
  pkg/skaffold/config/util.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
Labels: cla: yes, size/M

#3704 move unused pod validator code to pkg/diag
  go.sum
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
Labels: cla: yes, size/XS

#3687 Reduce default status check deadline to 2 mins
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/M

#3707 Update Jib to 2.0.0
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#3710 Fix broken link
  DEVELOPMENT.md
Labels: cla: yes, size/XS

#3709 Simpler code dealing with durations
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/trigger/triggers_test.go
Labels: cla: yes, size/M

#3706 Faster Makefile
  Makefile
Labels: cla: yes, size/M

#3713 add missing lines to go.sum
  go.sum
Labels: cla: yes, size/XS

#3714 v1.4.0 Release
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#3716 Revert "Faster Makefile"
  Makefile
Labels: cla: yes, size/M

#3717 skip large files during skaffold init
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  docs/content/en/docs/pipeline-stages/init.md
  pkg/skaffold/initializer/analyze/analyze.go
  pkg/skaffold/initializer/analyze/analyze_test.go
  pkg/skaffold/initializer/analyze/kubernetes.go
  pkg/skaffold/initializer/config/config.go
Labels: cla: yes, size/M

#3715 report actual copy error when syncing files to containers
  pkg/skaffold/sync/sync.go
Labels: cla: yes, size/XS

#3723 Link config management doc
  DEVELOPMENT.md
Labels: cla: yes, size/XS

#3722 Fix analyze update check
  cmd/skaffold/app/cmd/cmd.go
  pkg/skaffold/update/update.go
Labels: cla: yes, size/S

#3730 More explicit command checking in helm unit tests
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  testutil/cmd_helper.go
Labels: cla: yes, size/L

#3728 Upgrade Jib to 2.1.0
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/jib/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#3729 Refactor helm deployer to prepare for helm3 support
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/XL

#3727 Run buildpacks integration test with kind
  integration/run_test.go
Labels: cla: yes, size/S

#3731 Add support for parsing helm version
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  testutil/cmd_helper.go
Labels: cla: yes, size/M

#3639 unhide status check and on by default.
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/dev_test.go
  integration/run_test.go
Labels: cla: yes, size/S

#3743 helm chart packaging: improve errors, logic & testability
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/M

#3747 [Docs] status check docs change to mention its turned on by default.
  docs/content/en/docs/workflows/ci-cd.md
Labels: cla: yes, size/XS

#3738 Add helm3 support to the helm deployer
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/L

#3750 helm_test: Fix version20 input to match reality, remove version21rc
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/S

#3752 Support inferred sync on Custom artifacts with a Dockerfile
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/S

#3724 Faster make v2
  Makefile
  deploy/skaffold/Dockerfile
Labels: cla: yes, size/M

#3754 Support go Templates in Custom Builder commands
  docs/content/en/docs/pipeline-stages/builders/custom.md
  pkg/skaffold/build/custom/script.go
  pkg/skaffold/build/custom/script_test.go
  pkg/skaffold/build/misc/env.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/util/env_template.go
  pkg/skaffold/util/env_template_test.go
Labels: cla: yes, size/L

#3758 skaffold init and buildpacks: skip dependencies
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
Labels: cla: yes, size/M

#3645 Wire up debug events
  integration/debug_test.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/kubernetes/debugging/container_manager.go
  pkg/skaffold/kubernetes/debugging/container_manager_test.go
  pkg/skaffold/runner/debugging.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/L

#3759 This code is only used by tests
  pkg/skaffold/initializer/build/cli.go
  pkg/skaffold/initializer/build/init.go
  pkg/skaffold/initializer/build/util.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
Labels: cla: yes, size/M

#3757 Use heroku/color for our colors
  cmd/skaffold/app/cmd/cmd.go
  go.mod
  go.sum
  pkg/skaffold/build/parallel.go
  pkg/skaffold/build/parallel_test.go
  pkg/skaffold/color/formatter.go
  pkg/skaffold/color/formatter_test.go
  pkg/skaffold/kubernetes/colorpicker_test.go
Labels: cla: yes, size/L
