Repository GoogleContainerTools/skaffold, pull requests merged in 2020-09, with the labels that each got.

#4744 Use the newer notation for integration tests
  integration/dev_test.go
  integration/render_test.go
  integration/run_test.go
  integration/sync_test.go
  integration/util.go
Labels: cla: yes, size/M

#4742 Minikube cluster detection followup
  pkg/skaffold/cluster/minikube.go
  pkg/skaffold/cluster/minikube_test.go
Labels: cla: yes, size/L

#4750 Fix 4748: Panic with skaffold dev
  pkg/skaffold/trigger/triggers.go
  pkg/skaffold/trigger/triggers_test.go
Labels: cla: yes, size/M

#4754 Leverage Config interfaces to simplify tests
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/cluster_test.go
  pkg/skaffold/build/cluster/secret_test.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/gcb/buildpacks_test.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/gcb/spec_test.go
  pkg/skaffold/build/local/docker_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kpt_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/diagnose/diagnose_test.go
  pkg/skaffold/kubectl/cli_test.go
  pkg/skaffold/runner/runcontext/context_test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/trigger/triggers_test.go
Labels: cla: yes, size/XXL

#4756 Release v1.14.0
  CHANGELOG.md
  examples/bazel/WORKSPACE
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/goose.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, draft-release, size/L

#4759 Remove some duplication in unit tests
  pkg/skaffold/build/bazel/build_test.go
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/buildpacks/fetcher_test.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/jib_test.go
  pkg/skaffold/build/jib/maven_test.go
  pkg/skaffold/build/local/docker_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/test/test_test.go
Labels: cla: yes, size/M

#4760 Pass a context to DefaultAuthHelper.GetAllConfigs()
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/docker/auth.go
  pkg/skaffold/docker/auth_test.go
  pkg/skaffold/docker/image.go
Labels: cla: yes, size/L

#4758 Surface error for render
  pkg/skaffold/deploy/helm.go
Labels: cla: yes, size/XS

#4619 Expand home directory for setFiles in helm deployment
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/S

#4768 Pass correct build args to `CreateDockerTarContext`
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/docker/context.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/image.go
Labels: cla: yes, size/S

#4487 Clarify usage of ArtifactOverrides, ImageStrategy
  docs/content/en/schemas/v2beta6.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/S

#4764 Re-enable survey prompt
  cmd/skaffold/app/cmd/cmd.go
  integration/housekeeping_messages_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: cla: yes, size/S

#4774 Fix issue with schema doc changes
  docs/content/en/schemas/v2beta6.json
  docs/content/en/schemas/v2beta8.json
Labels: cla: yes, size/S

#4775 Enable golint checks for linux/arm64
  hack/install_golint.sh
Labels: cla: yes, size/XS

#4776 Bump http-proxy from 1.18.0 to 1.18.1 in examples/react-reload and integration/examples/react-reload
  examples/react-reload/app/package-lock.json
  integration/examples/react-reload/app/package-lock.json
Labels: cla: yes, size/XS

#4772 Fixup `debug` doc references
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/S

#4765 Add option for helm deployments to create namespace
  docs/content/en/schemas/v2beta8.json
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#4779 Make flag order deterministic for helm's `--setFiles`
  pkg/skaffold/deploy/helm.go
Labels: cla: yes, size/M

#4777 npm-update in examples/react-reload
  examples/react-reload/app/package-lock.json
  examples/react-reload/app/package.json
  integration/examples/react-reload/app/package-lock.json
  integration/examples/react-reload/app/package.json
Labels: cla: yes

#3891 Try to import docker images before falling back to building
  docs/content/en/schemas/v2beta8.json
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/details.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#4795 Return error for invalid dockerfile instruction "COPY" with no arguments
  pkg/skaffold/docker/parse.go
Labels: cla: yes, size/XS

#4790 Make FakeAPIClient threadsafe
  pkg/skaffold/build/buildpacks/fetcher_test.go
  pkg/skaffold/build/local/local_test.go
  testutil/fake_image_api.go
Labels: cla: yes, size/L

#4800 Pin autoprefixer version at 9.8.6 for docs
  deploy/webhook/Dockerfile
Labels: cla: yes, size/XS

#4781 Update quickstart to add reference to `--default-repo`
  docs/content/en/docs/quickstart/_index.md
Labels: cla: yes, size/S

#4626 Increase the duration between survey prompts
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
Labels: cla: yes, size/XS

#4799 [kpt deployer] Improve skaffold.yaml docs.
  docs/content/en/schemas/v2beta8.json
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#4802 Fix TestPluginType_IsKnown unit test
  pkg/skaffold/build/jib/jib_test.go
Labels: cla: yes, size/XS

#4778 skaffold deploy -t flag
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/deploy_test.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/build/tag/util.go
  pkg/skaffold/build/tag/util_test.go
Labels: cla: yes, size/L

#4374 Support configuring default namespace for kubectl/kustomize deployers
  docs/content/en/docs/environment/templating.md
  docs/content/en/schemas/v2beta8.json
  integration/port_forward_test.go
  integration/render_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/kubectl/cli.go
  pkg/skaffold/kubectl/cli_test.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/load_images_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/new_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/sync/types.go
  testutil/checks.go
Labels: cla: yes, size/XL

#4732 Adds support for `debug` for Helm
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/filter.go
  cmd/skaffold/app/cmd/filter_test.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/workflows/debug.md
  integration/debug_test.go
  integration/filter_test.go
  integration/skaffold/helper.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
  testutil/tmp.go
Labels: cla: yes, size/XL

#4803 [kpt deployer] Add "local-config" annotation to kpt fn configs.
  go.mod
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
  vendor/modules.txt
Labels: cla: yes, size/L

#4734 Add option to skaffold run similar to "skaffold build -b"
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/run_test.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/M

#4810 Skip cluster integration tests if changes only in docs folder
  .travis.yml
Labels: cla: yes, size/XS

#4798 Ensure Windows console color enablement
  pkg/skaffold/color/formatter.go
Labels: cla: yes, size/XS

#4731 Support docker build --secret flag
  docs/content/en/schemas/v2beta8.json
  hack/schemas/main.go
  integration/testdata/build/secret/Dockerfile
  integration/testdata/build/secret/mysecret.txt
  integration/testdata/build/secret/skaffold.yaml
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#4484 Add fallback to kubectl kustomize if kustomize binary isn't present
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, size/L

#4755 Pass docker.Config instead of InsecureRegistries
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/bazel/build_test.go
  pkg/skaffold/build/bazel/types.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/details.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/custom/build.go
  pkg/skaffold/build/custom/dependencies.go
  pkg/skaffold/build/custom/types.go
  pkg/skaffold/build/dependencies.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/jib.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/maven.go
  pkg/skaffold/build/jib/maven_test.go
  pkg/skaffold/build/jib/types.go
  pkg/skaffold/build/local/docker.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/context.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/dependencies.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_util.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/docker/remote_test.go
  pkg/skaffold/docker/syncmap.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/render.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/XL

#4805 Document how to disable autosync for buildpacks
  docs/content/en/docs/pipeline-stages/filesync.md
Labels: cla: yes, size/M

#4822 Disable codecov annotations by default
  codecov.yml
Labels: cla: yes, size/XS

#4794 Add design proposal for supporting dependencies between build artifacts
  deploy/webhook/Dockerfile
  docs/design_proposals/artifact-dependencies.md
Labels: cla: yes, size/L

#4817 Fix `skaffold build | skaffold deploy` with `SKAFFOLD_DEFAULT_REPO` rewrites image name twice
  pkg/skaffold/docker/default_repo.go
  pkg/skaffold/docker/default_repo_test.go
Labels: cla: yes, size/S

#4819 [kpt deployer] Customize the manipulated resource directory.
  docs/content/en/schemas/v2beta8.json
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#4829 Fix `skaffold filter` to handle multiple yaml documents
  cmd/skaffold/app/cmd/filter.go
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/kubernetes/manifest/manifests.go
  pkg/skaffold/kubernetes/manifest/manifests_test.go
Labels: cla: yes, size/L

#4830 Add Cloud Shell for simpler Quickstart
  docs/content/en/docs/quickstart/_index.md
Labels: cla: yes, size/S

#4834 Release v1.15.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, draft-release, size/L

#4792 Prune prev images on build/run/{dev iteration start}
  go.mod
  go.sum
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/prune.go
  pkg/skaffold/build/local/prune_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/docker/image.go
  testutil/fake_image_api.go
  vendor/github.com/dustin/go-humanize/.travis.yml
  vendor/github.com/dustin/go-humanize/LICENSE
  vendor/github.com/dustin/go-humanize/README.markdown
  vendor/github.com/dustin/go-humanize/big.go
  vendor/github.com/dustin/go-humanize/bigbytes.go
  vendor/github.com/dustin/go-humanize/bytes.go
  vendor/github.com/dustin/go-humanize/comma.go
  vendor/github.com/dustin/go-humanize/commaf.go
  vendor/github.com/dustin/go-humanize/ftoa.go
  vendor/github.com/dustin/go-humanize/humanize.go
  vendor/github.com/dustin/go-humanize/number.go
  vendor/github.com/dustin/go-humanize/ordinals.go
  vendor/github.com/dustin/go-humanize/si.go
  vendor/github.com/dustin/go-humanize/times.go
  vendor/modules.txt
Labels: cla: yes, size/XL

#4833 Update mute-logs to not print output upon failure of build/deploy step
  pkg/skaffold/build/logfile.go
  pkg/skaffold/build/logfile_test.go
  pkg/skaffold/deploy/util/logfile.go
  pkg/skaffold/deploy/util/logfile_test.go
  pkg/skaffold/runner/deploy.go
Labels: cla: yes, size/M
