Repository GoogleContainerTools/skaffold, pull requests merged in 2020-07, with the labels that each got.

#4423 Debug pull error
  Makefile
Labels: cla: yes, size/XS

#4420 go mod tidy && go mod vendor
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/XS

#4424 Fix grpc doc
  docs/content/en/docs/references/api/grpc.md
  proto/markdown.tmpl
  proto/skaffold.proto
Labels: cla: yes

#4427 Simplify assertions
  pkg/skaffold/build/jib/sync_test.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/schema/v2beta3/upgrade_test.go
Labels: cla: yes, size/S

#4422 Lenient parsing of `minikube docker-env`
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
Labels: cla: yes, size/S

#4416 Move diagnose code out of the runner
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/diagnose/diagnose_test.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/L

#4426 Move dependabot config where it belongs
  .github/dependabot.yml
Labels: cla: yes

#4421 Ignore comments in `minikuke docker-env` output
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
Labels: cla: yes, size/S

#4433 Fix dependabot config
  .github/dependabot.yml
Labels: cla: yes, size/M

#4436 #3047 Fixed nil pointer to persister
  pkg/skaffold/kubernetes/context/context.go
Labels: cla: yes, size/XS

#4440 Support inline patchesStrategicMerge patches
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, size/M

#4415 Update install instructions and add gcloud
  docs/content/en/docs/install/_index.md
Labels: cla: yes, size/M

#4442 Debug supports `/bin/sh -c` and `/bin/bash -c` command-lines
  integration/testdata/debug/python3/Dockerfile
  pkg/skaffold/debug/cnb.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_test.go
Labels: cla: yes, size/L

#4350 Skaffold modules design proposal
  docs/design_proposals/modules.md
Labels: cla: yes, size/S

#4453 Support custom Worker Pool on GCB
  docs/content/en/schemas/v2beta6.json
  pkg/skaffold/build/gcb/spec.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/S

#4451 When pulling images and authentication fails, first try anonymous pull
  pkg/skaffold/build/buildpacks/fetcher.go
  pkg/skaffold/build/buildpacks/fetcher_test.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/docker/image.go
  testutil/fake_image_api.go
Labels: cla: yes, size/L

#3586 Skaffold run support new parameter '--render-output' with '--render-only
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/render_test.go
  integration/run_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
Labels: cla: yes, size/L

#4465 Link Typo
  docs/content/en/docs/pipeline-stages/init.md
Labels: cla: yes, size/XS

#4468 make sure status code error code is propogated to devloopEndEvent
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XL

#4469 Release v1.12.1
  CHANGELOG.md
Labels: cla: yes, size/S

#4460 Use runCtx.Namespaces to get deployments for status checks
  pkg/skaffold/deploy/status_check.go
Labels: cla: yes, size/S

#4471 Map container status PodInitializing to STATUSCHECK_SUCCESS
  pkg/diag/validator/pod.go
Labels: cla: yes, size/XS

#4458 Fix example for generate-pipeline to use "latest" as image tag
  examples/generate-pipeline/expectedPipeline.yaml
  integration/examples/generate-pipeline/expectedPipeline.yaml
  integration/generate_pipeline_test.go
  integration/testdata/generate_pipeline/existing_oncluster/expectedPipeline.yaml
  integration/testdata/generate_pipeline/existing_other/expectedPipeline.yaml
  integration/testdata/generate_pipeline/multiple_configs/expectedPipeline.yaml
  integration/testdata/generate_pipeline/no_profiles/expectedPipeline.yaml
Labels: cla: yes, size/M

#4472 add tests for a container in a pod being in terminated state
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
Labels: cla: yes, size/M

#4474 Update pack to v0.12.0
  deploy/buildpacks/publish.sh
  go.mod
  go.sum
  vendor/github.com/buildpacks/pack/README.md
  vendor/github.com/buildpacks/pack/build.go
  vendor/github.com/buildpacks/pack/internal/builder/lifecycle.go
  vendor/modules.txt
Labels: cla: yes, size/XS

#4481 Simplify remote image code
  pkg/skaffold/build/jib/jib.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/docker/remote_test.go
Labels: cla: yes, size/L

#4478 Support deprecated extensions/v1beta1 workload resources
  pkg/skaffold/deploy/kubectl/visitor.go
  pkg/skaffold/deploy/kubectl/visitor_test.go
Labels: cla: yes, size/M

#4488 Add Agones custom kinds to the Allow-List
  pkg/skaffold/deploy/kubectl/visitor.go
Labels: cla: yes, size/XS

#4490 Use less offensive wording
  integration/port_forward_test.go
  pkg/skaffold/docker/authenticators.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
Labels: cla: yes, kokoro:force-run, size/S

#4492 Error on invalid artifact workspace
  pkg/skaffold/schema/samples_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes, size/M

#4495 Sample has incorrect syntax for buildpacks
  docs/content/en/samples/builders/buildpacks.yaml
Labels: cla: yes, size/XS

#4508 Disable update check and survey prompt in non-interactive mode
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, july-chill

#4526 Shorter error message
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
Labels: cla: yes, size/XS

#4503 Fix documentation for Helm `artifactOverride`
  docs/content/en/schemas/v2beta6.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/XS

#4513 fix: remove the dev override of the force flag
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/S

#4510 SKAFFOLD_UPDATE_CHECK should also be a global flag
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/constants/constants.go
  pkg/skaffold/update/update.go
  pkg/skaffold/update/update_test.go
Labels: cla: yes, size/M

#4496 Refactor Tag: GenerateTag method and GenerateFQIN function
  pkg/skaffold/build/tag/custom.go
  pkg/skaffold/build/tag/custom_test.go
  pkg/skaffold/build/tag/date_time.go
  pkg/skaffold/build/tag/date_time_test.go
  pkg/skaffold/build/tag/env_template.go
  pkg/skaffold/build/tag/env_template_test.go
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/build/tag/sha256.go
  pkg/skaffold/build/tag/sha256_test.go
  pkg/skaffold/build/tag/tag.go
  pkg/skaffold/build/tag/tag_test.go
  pkg/skaffold/runner/build_deploy.go
Labels: cla: yes, size/XL

#4511 Allow deeply nested property definition for Helm properties
  docs/content/en/schemas/v2beta6.json
  integration/examples/helm-deployment-dependencies/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/util/util.go
  pkg/skaffold/schema/util/util_test.go
Labels: cla: yes, size/L

#4536 Failing to override value should be fatal
  testutil/util.go
Labels: cla: yes

#4499 Remove labels from builders and deployers
  integration/helm_test.go
  integration/render_test.go
  pkg/skaffold/build/build.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/build/tag/custom.go
  pkg/skaffold/build/tag/date_time.go
  pkg/skaffold/build/tag/env_template.go
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/sha256.go
  pkg/skaffold/build/tag/tag.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/labels.go
  pkg/skaffold/deploy/kubectl/labels_test.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/labeller.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/notification.go
  pkg/skaffold/runner/render.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/L

#4538 Fix flaky test
  cmd/skaffold/app/skaffold_test.go
Labels: cla: yes, size/XS

#4509 Add `deploy.logs` section to skaffold.yaml
  docs/content/en/schemas/v2beta6.json
  pkg/skaffold/kubernetes/log.go
  pkg/skaffold/kubernetes/log_test.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, july-chill, size/L

#4541 Fix flaky test
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
Labels: cla: yes, size/M

#4544 Improve error messages for flaky test
  pkg/skaffold/util/port_test.go
Labels: cla: yes, size/S

#4507 Update k3d cli 'load image' to 'image import' (#4498)
  pkg/skaffold/runner/load_images.go
  pkg/skaffold/runner/load_images_test.go
Labels: cla: yes, size/S

#4527 Update buildpacks.md to reflect change in schema
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
Labels: cla: yes, size/XS

#4543 Update cross compilation image
  deploy/cross/Dockerfile
Labels: cla: yes, size/XS

#4545 Include k3d 3.0.0 in Skaffold image
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/S

#4540 Further simplifications of label-related code
  integration/render_test.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/labels.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/labeller.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes, size/L

#4552 Reduce volume of debug-level logging
  pkg/skaffold/config/util.go
  pkg/skaffold/yamltags/tags.go
Labels: cla: yes, size/XS

#4550 Added functions to util package for new tagging feature.
  pkg/skaffold/build/tag/tag_template.go
  pkg/skaffold/build/tag/tag_template_test.go
Labels: cla: yes, size/L

#4561 Skip flaky test
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
Labels: cla: yes, size/XS

#4556 Better error management and a few cosmetic changes
  pkg/skaffold/kubectl/exec_windows.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
Labels: cla: yes, size/M

#4558 Field should be private
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/flags_test.go
Labels: cla: yes, size/S

#4559 Remove redundant field
  pkg/skaffold/deploy/kustomize.go
Labels: cla: yes, size/XS

#4530 Add suppress-logs flag
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
Labels: cla: yes, size/S

#4475 Get digest of multi-arch images
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/docker/remote_test.go
Labels: cla: yes, size/L

#4531 Wait for pending deletions to complete before a deploy
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/kubectl/cli.go
  testutil/cmd_helper.go
Labels: cla: yes, size/L

#4568 Ignore "" namespaces in collectHelmReleasesNamespaces
  pkg/skaffold/runner/util/util.go
  pkg/skaffold/runner/util/util_test.go
Labels: cla: yes, size/XS

#4572 Improve wait for deletions
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, size/L

#4560 Extract event handling from Deploy()
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/notification.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
Labels: cla: yes, size/L

#4575 Fix compilation errors
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, size/S

#4533 Deprecating EnvTemplate's use of {{.IMAGE_NAME}}
  integration/testdata/tagPolicy/skaffold.yaml
  pkg/skaffold/build/tag/tag.go
  pkg/skaffold/build/tag/tag_test.go
Labels: cla: yes, size/M

#4582 Remove duplicated replica count.
  examples/helm-deployment/charts/templates/deployment.yaml
  integration/examples/helm-deployment/charts/templates/deployment.yaml
Labels: cla: yes, size/XS

#4584 Fail when k8s client can’t be obtained
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/labels.go
Labels: cla: yes, size/S

#4583 Add more debugging logs to helm
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/util.go
Labels: cla: yes, size/XS

#4532 Docs to accommodate the deprecation of envTemplate's use of {{.IMAGE_NAME}}
  docs/content/en/docs/pipeline-stages/taggers.md
  docs/content/en/samples/taggers/envTemplate.yaml
  docs/content/en/samples/templating/env.yaml
  docs/content/en/schemas/v2beta6.json
  examples/tagging-with-environment-variables/README.md
  examples/tagging-with-environment-variables/skaffold.yaml
  integration/examples/tagging-with-environment-variables/README.md
  integration/examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#4585 (minor) fix vendoring
  vendor/github.com/google/go-containerregistry/pkg/v1/random/doc.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/image.go
  vendor/github.com/google/go-containerregistry/pkg/v1/random/index.go
  vendor/modules.txt
Labels: cla: yes, size/XS

#4563 Add helper to create log files
  pkg/skaffold/logfile/logfile.go
  pkg/skaffold/logfile/logfile_test.go
Labels: cla: yes, size/L

#4528 Support short build logs
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/build/logfile.go
  pkg/skaffold/build/logfile_test.go
  pkg/skaffold/build/parallel.go
  pkg/skaffold/build/parallel_test.go
  pkg/skaffold/build/sequence.go
  pkg/skaffold/build/sequence_test.go
Labels: cla: yes, size/L

#4567 Tag template tagger
  pkg/skaffold/build/tag/env_template.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/build/tag/tag_template.go
  pkg/skaffold/build/tag/tag_template_test.go
Labels: cla: yes, size/L

#4594 Improve muted logs mechanism
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/build/logfile.go
  pkg/skaffold/build/logfile_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/config/types.go
  pkg/skaffold/config/types_test.go
  pkg/skaffold/logfile/logfile.go
  pkg/skaffold/logfile/logfile_test.go
Labels: cla: yes, size/L

#4595 Muted test logs
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/test/types.go
Labels: cla: yes, size/M

#4587 Use read-only getters on RunContext
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/kubectl/cli.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/debugging.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/generate_pipeline.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/runner/render.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/sync/types.go
  pkg/skaffold/test/test.go
  pkg/skaffold/trigger/triggers.go
Labels: cla: yes, size/L

#4566 Log when values are taken from global config file
  pkg/skaffold/config/util.go
Labels: cla: yes, size/S

#4590 Use alternative service port-forwarding scheme
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
Labels: cla: yes, size/L

#4600 Skip logging first error from parsing Helm release info
  pkg/skaffold/deploy/util.go
Labels: cla: yes, size/XS

#4602 Add support for muting deploy logs
  pkg/skaffold/deploy/logfile.go
  pkg/skaffold/deploy/logfile_test.go
  pkg/skaffold/runner/deploy.go
Labels: cla: yes, size/L

#4591 add debug logs and don't return on first terminated state
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XL

#4608 prune empty namespaces from runCtx
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/runcontext/context_test.go
Labels: cla: yes, size/S

#4588 TagTemplate Feature w/ Docs
  docs/content/en/docs/pipeline-stages/taggers.md
  docs/content/en/samples/taggers/customTemplate.yaml
  docs/content/en/schemas/v2beta6.json
  pkg/skaffold/build/tag/custom_template.go
  pkg/skaffold/build/tag/custom_template_test.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/build/tag/tag_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/new_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v2beta5/upgrade.go
Labels: candidate-release, cla: yes, size/L

#4609 Ask for notification of os.Interrupt
  cmd/skaffold/app/signals.go
Labels: candidate-release, cla: yes, size/XS

#4610 Prune deployment status updated without any pod statuses
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/M
