Repository GoogleContainerTools/skaffold, pull requests merged in 2020-01, with the labels that each got.

#3462 Add --target parameter with kaniko on Google Cloud Build
  pkg/skaffold/build/gcb/kaniko.go
  pkg/skaffold/build/gcb/kaniko_test.go
Labels: cla: yes, size/XS

#3458 Spelling
  .github/pull_request_template.md
  CHANGELOG.md
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/cmd/flags_test.go
  cmd/skaffold/app/flags/image_test.go
  docs/content/en/docs/design/api.md
  docs/content/en/docs/pipeline-stages/deployers.md
  docs/content/en/docs/pipeline-stages/taggers.md
  docs/content/en/docs/references/api/_index.md
  docs/content/en/docs/references/deprecation.md
  docs/content/en/docs/resources/_index.md
  docs/content/en/docs/workflows/dev.md
  docs/design_proposals/digest-tagger.md
  docs/design_proposals/event-api-v2.md
  docs/design_proposals/kaniko-proxy-setting.md
  integration/examples/jib-multimodule/.mvn/wrapper/MavenWrapperDownloader.java
  integration/examples/jib/.mvn/wrapper/MavenWrapperDownloader.java
  integration/helm_test.go
  integration/skaffold/helper.go
  integration/testdata/debug/jib/.mvn/wrapper/MavenWrapperDownloader.java
  integration/testdata/jib/.mvn/wrapper/MavenWrapperDownloader.java
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/resource.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/docker/authenticators.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/docker/reference_test.go
  pkg/skaffold/filemon/changes_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry_test.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/v1alpha5/upgrade_test.go
Labels: cla: yes, kokoro:run

#3436 Fix `skaffold credits`
  .gitignore
  cmd/skaffold/app/cmd/credits/export.go
  cmd/skaffold/app/cmd/credits/fs_dummy.go
  cmd/skaffold/app/cmd/schema/fs.go
  cmd/skaffold/app/cmd/schema/fs_dummy.go
  cmd/skaffold/app/cmd/schema/print.go
  cmd/skaffold/app/cmd/schema/print_test.go
  cmd/skaffold/app/cmd/statik/fs.go
  hack/gen_statik.sh
  integration/credits_test.go
  integration/schema_test.go
  integration/skaffold/helper.go
Labels: cla: yes, size/L

#3465 Upgrade golangci-lint to v1.22.2
  hack/linter.sh
Labels: cla: yes, size/XS

#3464 Move man generation to hack folder
  hack/generate-man.sh
  hack/man/man.go
  hack/man/man_test.go
Labels: cla: yes

#3430 Use the kind that’s inside skaffold-builder
  .travis.yml
  Makefile
Labels: cla: yes, size/S

#3435 Update Bazel sample
  examples/bazel/WORKSPACE
  integration/examples/bazel/WORKSPACE
Labels: cla: yes, size/M

#3466 Update lit-html
  docs/content/en/docs/references/yaml/main.css
  docs/content/en/docs/references/yaml/main.js
Labels: cla: yes, size/XS

#3469 helm deployer: Remove duplication
  pkg/skaffold/deploy/helm.go
Labels: cla: yes, size/S

#3432 Use ko instead of buildpacks for the custom builder
  deploy/skaffold/Dockerfile
  docs/content/en/docs/tutorials/custom-builder.md
  docs/content/en/samples/builders/custom-buildpacks/build.sh
  docs/content/en/samples/builders/custom-buildpacks/skaffold.yaml
  examples/custom/README.md
  examples/custom/build.sh
  examples/custom/go.mod
  examples/custom/k8s/pod.yaml
  examples/custom/skaffold.yaml
  integration/build_test.go
  integration/examples/custom/README.md
  integration/examples/custom/build.sh
  integration/examples/custom/go.mod
  integration/examples/custom/k8s/pod.yaml
  integration/examples/custom/skaffold.yaml
Labels: cla: yes, size/L

#3474 Add gradle/maven sync parts + restructure tests
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/jib.go
  pkg/skaffold/build/jib/maven.go
  pkg/skaffold/build/jib/maven_test.go
Labels: cla: yes, size/L

#3478 Rename jib args functions
  pkg/skaffold/build/gcb/jib.go
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/maven.go
  pkg/skaffold/build/jib/maven_test.go
Labels: cla: yes, size/S

#3441 [buildpacks] Refactor code to simplify #3395
  pkg/skaffold/build/buildpacks/build.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/docker/image_util.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/M

#3439 Fix sync infer when COPY destination contains an env variable
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/syncmap_test.go
Labels: cla: yes, size/M

#3470 Remove false warnings when deploying multiple releases
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/M

#3471 Support parallel local builds (defaults to sequential)
  docs/content/en/schemas/v2alpha2.json
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/M

#3110 Implement render for kustomize
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
Labels: cla: yes, size/L

#3480 Remove Kaniko build context.
  docs/content/en/docs/pipeline-stages/builders/docker.md
  docs/content/en/samples/builders/kaniko.yaml
  docs/content/en/schemas/v2alpha2.json
  integration/examples/kaniko-local/README.md
  integration/examples/kaniko-local/skaffold.yaml
  integration/examples/kaniko/README.md
  integration/examples/kaniko/k8s-pod.yaml
  integration/examples/kaniko/skaffold.yaml
  integration/run_test.go
  integration/testdata/generate_pipeline/existing_oncluster/expectedSkaffold.yaml
  integration/testdata/generate_pipeline/existing_oncluster/skaffold.yaml
  integration/testdata/generate_pipeline/existing_other/expectedSkaffold.yaml
  integration/testdata/generate_pipeline/multiple_configs/expectedSkaffold.yaml
  integration/testdata/generate_pipeline/multiple_configs/skaffold.yaml
  integration/testdata/generate_pipeline/no_profiles/expectedSkaffold.yaml
  integration/testdata/kaniko-default-repo/skaffold.yaml
  integration/testdata/kaniko-insecure-registry/skaffold.yaml
  integration/testdata/kaniko-microservices/skaffold.yaml
  integration/testdata/kaniko-sub-folder/skaffold.yaml
  integration/testdata/kaniko-target/skaffold.yaml
  integration/testdata/skaffold-in-cluster/skaffold.yaml
  pkg/skaffold/build/cluster/sources/gcs.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/build/cluster/sources/localdir_test.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/generate_pipeline/profile_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v2alpha1/upgrade.go
  pkg/skaffold/schema/v2alpha1/upgrade_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/L

#3450 SyncMap is a matter of artifact type, not builder
  pkg/skaffold/build/build.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/docker/syncmap.go
  pkg/skaffold/docker/syncmap_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/diagnose.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/L

#3481 Kaniko: Cancel log streaming when pod fails to complete
  pkg/skaffold/build/cluster/kaniko.go
Labels: cla: yes, size/XS

#3483 Use unique key for jib caches
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/jib.go
  pkg/skaffold/build/jib/jib_test.go
  pkg/skaffold/build/jib/maven.go
Labels: cla: yes, size/M

#3504 Build Go projects with Buildpacks
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
Labels: cla: yes, size/S

#3495 Demonstrate inferred sync
  examples/hot-reload/skaffold.yaml
  integration/examples/hot-reload/skaffold.yaml
Labels: cla: yes, size/S

#3494 Add missing package-lock.json files
  examples/react-reload/app/package-lock.json
  integration/examples/react-reload/app/package-lock.json
Labels: cla: yes

#3456 Exclude CRD schema from transformation, fix #1737.
  pkg/skaffold/deploy/kubectl/images.go
  pkg/skaffold/deploy/kubectl/images_test.go
  pkg/skaffold/deploy/kubectl/labels.go
  pkg/skaffold/deploy/kubectl/labels_test.go
  pkg/skaffold/deploy/kubectl/matcher.go
  pkg/skaffold/deploy/kubectl/matcher_test.go
  pkg/skaffold/deploy/kubectl/namespace_test.go
  pkg/skaffold/deploy/kubectl/namespaces.go
  pkg/skaffold/deploy/kubectl/visitor.go
  pkg/skaffold/deploy/kubectl/visitor_test.go
Labels: cla: yes, size/XL

#3455 Simplify kaniko after we removed the GCS build context
  docs/content/en/schemas/v2alpha2.json
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/kaniko_test.go
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/build/cluster/sources/localdir.go
  pkg/skaffold/build/cluster/sources/localdir_test.go
  pkg/skaffold/build/cluster/sources/sources.go
  pkg/skaffold/build/cluster/sources/sources_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/XXL

#3503 Use pack CLI to build on GCB
  deploy/buildpacks/Dockerfile
  deploy/buildpacks/publish.sh
  docs/content/en/schemas/v2alpha2.json
  pkg/skaffold/build/gcb/buildpacks.go
  pkg/skaffold/build/gcb/buildpacks_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/L

#3111 Related to #2849: Allows ValuesFiles to be templatable
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/M

#3501 Use origin/master as baseline for schema version check
  hack/check-schema-changes.sh
  hack/versions/pkg/schema/check.go
  hack/versions/pkg/schema/git.go
Labels: cla: yes, size/M

#3499 Dockerfile detector will only check files containing "Dockerfile" in the name
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, size/M

#3507 Kind 0.7.0
  deploy/skaffold/Dockerfile
  pkg/skaffold/config/util.go
Labels: cla: yes, size/XS

#3509 Move default images next to where they are used
  pkg/skaffold/constants/constants.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes, size/M

#3510 This test can run on Travis, with kind
  integration/run_test.go
Labels: cla: yes, size/S

#3391 Add forwarding deployer muxer to enable multiple deployers
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/util.go
Labels: cla: yes, size/L

#3511 Allow 2020 copyright year
  hack/boilerplate/boilerplate.py
Labels: cla: yes, size/XS

#3392 Enable multiple deployers in `skaffold.yaml`
  docs/content/en/docs/pipeline-stages/deployers.md
  docs/content/en/schemas/v2alpha2.json
  integration/run_test.go
  integration/testdata/debug/skaffold.yaml
  integration/testdata/deploy-multiple/kubectl/Dockerfile
  integration/testdata/deploy-multiple/kubectl/k8s-pod.yaml
  integration/testdata/deploy-multiple/kubectl/main.go
  integration/testdata/deploy-multiple/kustomize/k8s-pod.yaml
  integration/testdata/deploy-multiple/kustomize/kustomization.yaml
  integration/testdata/deploy-multiple/skaffold.yaml
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, pr/lgtm, size/XL

#3488 Clarify GCP service account and secret creation
  examples/kaniko/README.md
Labels: cla: yes, size/S

#3513 Remove a few more references to gcr.io/k8s-skaffold
  docs/content/en/docs/quickstart/_index.md
  docs/content/en/docs/tutorials/_index.md
  examples/README.md
  integration/examples/README.md
Labels: cla: yes, size/L

#3514 [doc] There’s no `gcsBucket` config anymore
  integration/examples/kaniko/README.md
Labels: cla: yes, size/XS

#3492 [doc] Supported builders matrix
  docs/content/en/docs/pipeline-stages/builders/_index.md
Labels: cla: yes, size/M

#3491 [doc] Improve documentation for concurrency settings.
  docs/content/en/docs/pipeline-stages/builders/_index.md
  docs/content/en/schemas/v2alpha2.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, needs-rebase, size/M

#3517 fix licenses path
  hack/generate-statik.sh
Labels: cla: yes, size/XS

#3518 fix licenses path
  hack/generate-statik.sh
Labels: cla: yes, size/XS

#3520 cut v1.2.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/expectedPipeline.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/.mvn/wrapper/MavenWrapperDownloader.java
  examples/jib-multimodule/skaffold.yaml
  examples/jib/.mvn/wrapper/MavenWrapperDownloader.java
  examples/jib/skaffold.yaml
  examples/kaniko-local/README.md
  examples/kaniko-local/skaffold.yaml
  examples/kaniko/README.md
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#3523 Fix typo in taggers.md
  docs/content/en/docs/pipeline-stages/taggers.md
Labels: cla: yes, size/XS

#3515 Add Ruby/Rack application example with hot reload
  examples/ruby/README.md
  examples/ruby/backend/Dockerfile
  examples/ruby/backend/Gemfile
  examples/ruby/backend/Gemfile.lock
  examples/ruby/backend/app.rb
  examples/ruby/backend/config.ru
  examples/ruby/k8s/deployment.yaml
  examples/ruby/skaffold.yaml
  integration/examples/ruby/README.md
  integration/examples/ruby/backend/Dockerfile
  integration/examples/ruby/backend/Gemfile
  integration/examples/ruby/backend/Gemfile.lock
  integration/examples/ruby/backend/app.rb
  integration/examples/ruby/backend/config.ru
  integration/examples/ruby/k8s/deployment.yaml
  integration/examples/ruby/skaffold.yaml
Labels: cla: yes, size/L

#3521 breaking apart init logic
  pkg/skaffold/initializer/builders.go
  pkg/skaffold/initializer/configs.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/json.go
  pkg/skaffold/initializer/kompose.go
Labels: cla: yes, size/XL

#3526 move set->sortedset in its own file
  pkg/skaffold/initializer/builders.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/set.go
Labels: cla: yes, size/M

#3525 introduced analysis struct to simplify init walk logic
  pkg/skaffold/initializer/configs.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, size/M

#3522 Remove duplicate sample.
  examples/kaniko-local/Dockerfile
  examples/kaniko-local/README.md
  examples/kaniko-local/k8s-pod.yaml
  examples/kaniko-local/main.go
  examples/kaniko-local/skaffold.yaml
  integration/examples/kaniko-local/Dockerfile
  integration/examples/kaniko-local/README.md
  integration/examples/kaniko-local/k8s-pod.yaml
  integration/examples/kaniko-local/main.go
  integration/examples/kaniko-local/skaffold.yaml
Labels: cla: yes, needs-rebase, size/L

#3528 skip-build shouldn't detect builders
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/kubectl/kubectl_test.go
Labels: cla: yes, size/XS

#3531 init refactor/clearer k8s manifest parsing
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/initializer/kubectl/kubectl.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: cla: yes, size/M

#3535 Typo
  pkg/skaffold/update/update.go
Labels: cla: yes, size/XS

#3533 [init refactor] introducing init analyzers
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/builders.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/prompt.go
Labels: cla: yes, size/XL

#3536 Be pedantic with imports
  cmd/skaffold/app/cmd/diagnose.go
  go.sum
  hack/checks.sh
  hack/pedantic-imports.sh
  hack/versions/cmd/new/version.go
  hack/versions/cmd/update_comments/main.go
  hack/versions/pkg/diff/godiff.go
  hack/versions/pkg/diff/godiff_test.go
  hack/versions/pkg/version.go
  hack/versions/pkg/version/version.go
  pkg/skaffold/build/buildpacks/logger.go
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/generate_pipeline_test.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/generate_pipeline/tasks.go
  pkg/skaffold/generate_pipeline/tasks_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/kubernetes/client.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/owner_test.go
  pkg/skaffold/runner/generate_pipeline.go
  pkg/skaffold/schema/v1beta6/upgrade_test.go
  pkg/webhook/gcs/gcs.go
  webhook/webhook.go
Labels: cla: yes, pr/lgtm-nit, size/L

#3539 Fix schema versions in a few samples
  examples/buildpacks-node/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/ruby/skaffold.yaml
  hack/check-samples.sh
  integration/examples/buildpacks-node/skaffold.yaml
  integration/examples/kustomize/skaffold-kustomize-args.yaml
  integration/examples/ruby/skaffold.yaml
Labels: cla: yes, size/S

#3538 [init refactor] cleanup on analyzers and moving things into a single package
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/builders.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/kubectl.go
  pkg/skaffold/initializer/kubectl_test.go
  pkg/skaffold/initializer/util.go
  pkg/skaffold/initializer/util_test.go
Labels: cla: yes, size/L

#3489 Add common jib sync code for processing syncmap
  pkg/skaffold/build/jib/sync.go
  pkg/skaffold/build/jib/sync_test.go
Labels: cla: yes, pr/changes-requested, size/L

#3496 Empty, non-nil `sync` = sync all the files and infer destination
  docs/content/en/schemas/v2alpha3.json
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#3542 [init refactor] organize tests
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/analyze_test.go
  pkg/skaffold/initializer/builders.go
  pkg/skaffold/initializer/builders_test.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/json_test.go
  pkg/skaffold/initializer/kompose_test.go
  pkg/skaffold/initializer/prompt.go
  pkg/skaffold/initializer/util.go
  pkg/skaffold/initializer/util_test.go
Labels: cla: yes, size/XXL

#3548 Add verbosity flag to go tests on travis
  .travis.yml
  Makefile
Labels: cla: yes, size/XS

#3550 [init refactor] doinit tests
  cmd/skaffold/app/cmd/init_test.go
  cmd/skaffold/app/cmd/testdata/init/.gitignore
  cmd/skaffold/app/cmd/testdata/init/hello/Dockerfile
  cmd/skaffold/app/cmd/testdata/init/hello/k8s-pod.yaml
  cmd/skaffold/app/cmd/testdata/init/hello/main.go
  cmd/skaffold/app/cmd/testdata/init/hello/skaffold.yaml
  cmd/skaffold/app/cmd/testdata/init/ignore-tags/Dockerfile
  cmd/skaffold/app/cmd/testdata/init/ignore-tags/k8s-pod.yaml
  cmd/skaffold/app/cmd/testdata/init/ignore-tags/main.go
  cmd/skaffold/app/cmd/testdata/init/ignore-tags/skaffold.yaml
  cmd/skaffold/app/cmd/testdata/init/microservices/leeroy-app/Dockerfile
  cmd/skaffold/app/cmd/testdata/init/microservices/leeroy-app/app.go
  cmd/skaffold/app/cmd/testdata/init/microservices/leeroy-app/kubernetes/deployment.yaml
  cmd/skaffold/app/cmd/testdata/init/microservices/leeroy-web/Dockerfile
  cmd/skaffold/app/cmd/testdata/init/microservices/leeroy-web/kubernetes/deployment.yaml
  cmd/skaffold/app/cmd/testdata/init/microservices/leeroy-web/web.go
  cmd/skaffold/app/cmd/testdata/init/microservices/skaffold.yaml
  examples/microservices/skaffold.yaml
  integration/init_test.go
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/analyze_test.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/kubectl.go
Labels: cla: yes

#3512 Add kubectl config flag to disable validation
  docs/content/en/schemas/v2alpha3.json
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, pr/changes-requested, size/M

#3556 Prepare for support for other types of pod
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
Labels: cla: yes, size/S

#3560 Add unit test for `findRunImage`
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/metadata.go
  pkg/skaffold/build/buildpacks/metadata_test.go
Labels: cla: yes, pr/lgtm-nit, size/L

#3557 Create tar with parents
  pkg/skaffold/util/tar.go
  pkg/skaffold/util/tar_test.go
Labels: cla: yes, size/M

#3561 [init refactor] more tests for DoInit
  cmd/skaffold/app/cmd/init_test.go
  testutil/util.go
Labels: cla: yes, size/L

#3564 Encode artifact image-name and container WORKDIR in container debug info
  docs/content/en/docs/workflows/debug.md
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
Labels: cla: yes, size/L

#3547 Add integration points for jib auto sync.
  pkg/skaffold/build/jib/sync.go
  pkg/skaffold/build/jib/sync_test.go
Labels: cla: yes, size/L

#3569 Show test output for failed tests, remove -v flag
  .travis.yml
  Makefile
  hack/gotest.sh
Labels: cla: yes, size/S

#3570 Update link to comment 13/23 -> 25
  DEVELOPMENT.md
Labels: cla: yes, size/XS

#3572 migrate Deployment from extensions/v1beta1 to apps/v1
  integration/testdata/helm/skaffold-helm/templates/deployment.yaml
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/S

#3562 golangci-lint 1.23.1 + autoupgrade
  hack/linter.sh
Labels: cla: yes, size/XS

#3573 [init refactor] move e2e unit tests to initializer package from cmd
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/testdata/init/.gitignore
  pkg/skaffold/initializer/testdata/init/hello/Dockerfile
  pkg/skaffold/initializer/testdata/init/hello/k8s-pod.yaml
  pkg/skaffold/initializer/testdata/init/hello/main.go
  pkg/skaffold/initializer/testdata/init/hello/skaffold.yaml
  pkg/skaffold/initializer/testdata/init/ignore-tags/Dockerfile
  pkg/skaffold/initializer/testdata/init/ignore-tags/k8s-pod.yaml
  pkg/skaffold/initializer/testdata/init/ignore-tags/main.go
  pkg/skaffold/initializer/testdata/init/ignore-tags/skaffold.yaml
  pkg/skaffold/initializer/testdata/init/microservices/leeroy-app/Dockerfile
  pkg/skaffold/initializer/testdata/init/microservices/leeroy-app/app.go
  pkg/skaffold/initializer/testdata/init/microservices/leeroy-app/kubernetes/deployment.yaml
  pkg/skaffold/initializer/testdata/init/microservices/leeroy-web/Dockerfile
  pkg/skaffold/initializer/testdata/init/microservices/leeroy-web/kubernetes/deployment.yaml
  pkg/skaffold/initializer/testdata/init/microservices/leeroy-web/web.go
  pkg/skaffold/initializer/testdata/init/microservices/skaffold.yaml
Labels: cla: yes

#3574 Fixes the command for switching to getting-started dir after cloning
  docs/content/en/docs/quickstart/_index.md
Labels: cla: yes, size/XS

#3576 Automatically handle —no-pull option on `pack`.
  docs/content/en/schemas/v2alpha3.json
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/metadata.go
  pkg/skaffold/build/buildpacks/metadata_test.go
  pkg/skaffold/build/buildpacks/pulled_images.go
  pkg/skaffold/build/buildpacks/pulled_images_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#3575 no error in skaffold init if pre-existing skaffold.yaml is different from target file
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/analyze_test.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/init_test.go
  testutil/util.go
Labels: cla: yes

#3578 Use json.Encoder for skaffold init
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/json.go
  pkg/skaffold/initializer/json_test.go
Labels: cla: yes, size/S

#3580 restoring microservices/skaffold.yaml
  examples/microservices/skaffold.yaml
  hack/check-samples.sh
Labels: cla: yes, size/M

#3577 init/no manifest analyze
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  pkg/skaffold/initializer/builders_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/testdata/init/hello-no-manifest/Dockerfile
  pkg/skaffold/initializer/testdata/init/hello-no-manifest/main.go
  pkg/skaffold/initializer/testdata/init/hello-no-manifest/skaffold.yaml
Labels: cla: yes

#3587 Fix test expectation
  pkg/skaffold/initializer/init_test.go
Labels: cla: yes, size/XS

#3553 Update cli tools
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, pr/lgtm, size/S

#3555 Auto sync with Buildpacks
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/metadata.go
  pkg/skaffold/build/buildpacks/metadata_test.go
  pkg/skaffold/build/buildpacks/types.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/docker/image_util.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/XL

#3589 Fix invalid package comments
  pkg/skaffold/apiversion/apiversion.go
  pkg/skaffold/apiversion/apiversion_test.go
  pkg/skaffold/debug/transform.go
Labels: cla: yes, size/XS

#3584 Support specific buildpacks for buildpack artifact
  docs/content/en/schemas/v2alpha3.json
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#3287 Implements setting environment variable in kaniko pod #3227
  docs/content/en/schemas/v2alpha3.json
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, needs-rebase, size/XXL

#3591 Simpler artifact hasher
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/M

#3592 Kaniko docs
  docs/content/en/docs/pipeline-stages/builders/docker.md
Labels: cla: yes, kokoro:run, size/XS

#3593 Update pack to v0.7.0
  deploy/buildpacks/publish.sh
Labels: cla: yes, size/XS

#3579 init/manifest flag
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/initializer/deploy_init.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/testdata/init/allcli/skaffold.yaml
Labels: cla: yes, size/L

#3122 Design proposal for new Debug Events
  docs/design_proposals/debug-events.md
Labels: cla: yes, kind/design discussion, size/L

#3595 Include unrecognized builder in error
  pkg/skaffold/initializer/builders.go
Labels: cla: yes, size/XS

#3597 Fix nil pointer dereference when no account is set on gcloud.
  pkg/skaffold/docker/authenticators.go
  pkg/skaffold/docker/authenticators_test.go
Labels: cla: yes, size/L

#3599 Add a (hidden) flag to set default buildpacks builder
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
  pkg/skaffold/initializer/analyze.go
  pkg/skaffold/initializer/analyze_test.go
  pkg/skaffold/initializer/builders.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/init.go
  testutil/util.go
Labels: cla: yes, size/L

#3601 Bump pack CLI to 0.8.0
  deploy/buildpacks/publish.sh
Labels: cla: yes, size/XS

#3600 Update pack dependency
  go.mod
  go.sum
  vendor/github.com/buildpacks/imgutil/image.go
  vendor/github.com/buildpacks/imgutil/local/local.go
  vendor/github.com/buildpacks/imgutil/remote/remote.go
  vendor/github.com/buildpacks/pack/CODEOWNERS
  vendor/github.com/buildpacks/pack/Makefile
  vendor/github.com/buildpacks/pack/build.go
  vendor/github.com/buildpacks/pack/client.go
  vendor/github.com/buildpacks/pack/go.mod
  vendor/github.com/buildpacks/pack/go.sum
  vendor/github.com/buildpacks/pack/internal/app/image.go
  vendor/github.com/buildpacks/pack/internal/app/run.go
  vendor/github.com/buildpacks/pack/internal/blob/downloader.go
  vendor/github.com/buildpacks/pack/internal/build/build.go
  vendor/github.com/buildpacks/pack/internal/build/phase.go
  vendor/github.com/buildpacks/pack/internal/builder/builder.go
  vendor/github.com/buildpacks/pack/internal/builder/compat.go
  vendor/github.com/buildpacks/pack/internal/builder/lifecycle.go
  vendor/github.com/buildpacks/pack/internal/builder/metadata.go
  vendor/github.com/buildpacks/pack/internal/cache/image_cache.go
  vendor/github.com/buildpacks/pack/internal/cache/volume_cache.go
  vendor/github.com/buildpacks/pack/internal/container/run.go
  vendor/github.com/buildpacks/pack/internal/dist/dist.go
  vendor/github.com/buildpacks/pack/internal/image/factory.go
  vendor/github.com/buildpacks/pack/internal/image/fetcher.go
  vendor/github.com/buildpacks/pack/logging/logging.go
  vendor/github.com/buildpacks/pack/run.go
  vendor/modules.txt
Labels: cla: yes, size/XS

#2901 Initial auto sync support design doc
  docs/design_proposals/sync-auto-support.md
Labels: cla: yes, size/L

#2946 Random secret postfixes for kaniko
  cmd/skaffold/app/cmd/credits/statik/statik.go
  docs/content/en/schemas/v2alpha3.json
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#3602 [bp] Use the same Docker client than Skaffold
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/docker/image.go
Labels: cla: yes, size/S

#3603 Don’t complain if other files are not checked in
  hack/check-skaffold-builder.sh
Labels: cla: yes, size/XS

#3604 Fix TestGracefulBuilCancel flake
  pkg/skaffold/build/misc/graceful_test.go
Labels: cla: yes, size/XS

#3605 Avoid nil pointer dereference
  integration/rpc_test.go
Labels: cla: yes, size/XS

#3606 Support —-buildpack flags on GCB
  pkg/skaffold/build/gcb/buildpacks.go
  pkg/skaffold/build/gcb/buildpacks_test.go
Labels: cla: yes, size/S

#3607 Better output for Docker commands
  pkg/skaffold/docker/image.go
Labels: cla: yes, size/S

#3608 Try use the Google hosted mirror of Maven Central
  Makefile
  hack/maven/settings.xml
Labels: cla: yes, size/S

#3558 Add labels to render
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/render_test.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/runner/render.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes, size/L

#3611 Better detection of terminals.
  go.mod
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/color/formatter.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/util/term.go
  pkg/skaffold/util/term_test.go
Labels: cla: yes, size/L

#3612 [doc] Fix urls
  docs/content/en/docs/pipeline-stages/log-tailing.md
Labels: cla: yes, size/XS

#3616 Release notes and example updates for 1.3.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#3609 Define new debug event
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XL

#3620 fix broken skaffold.yaml reference
  docs/content/en/schemas/v2alpha3.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/XS

#3012 Add display prompt config
  pkg/skaffold/config/global_config.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
Labels: cla: yes, size/L

#3625 Upgrade pack
  go.mod
  go.sum
  pkg/skaffold/build/buildpacks/lifecycle.go
  vendor/github.com/buildpacks/pack/go.mod
  vendor/github.com/buildpacks/pack/go.sum
  vendor/github.com/buildpacks/pack/internal/build/phases.go
  vendor/github.com/buildpacks/pack/internal/builder/lifecycle.go
  vendor/github.com/buildpacks/pack/internal/image/fetcher.go
  vendor/modules.txt
Labels: cla: yes, size/S

#3626 Revert "Merge pull request #3433 from dgageot/faster-skaffold-builder"
  Makefile
  deploy/cloudbuild-release.yaml
  deploy/cloudbuild.yaml
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
  hack/check-skaffold-builder.sh
  hack/checks.sh
  hack/skaffold-deps-sha1.sh
Labels: cla: yes, size/L

#3627 release notes for patch release v1.3.1
  CHANGELOG.md
Labels: cla: yes, size/XS
