Repository GoogleContainerTools/skaffold, pull requests merged in 2020-06, with the labels that each got.

#4284 Minor renames and change in the container status message.
  pkg/diag/validator/pod.go
Labels: cla: yes, size/XS

#4242 Add validations to Control API for Auto Triggers
  docs/content/en/docs/design/api.md
  integration/dev_test.go
  integration/sync_test.go
  pkg/skaffold/server/endpoints.go
  pkg/skaffold/server/server.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#4278 Make IMAGE_REPO and IMAGE_TAG templated values in custom build and helm deploy
  integration/examples/templated-fields/README.md
  integration/examples/templated-fields/build.sh
  integration/examples/templated-fields/charts/Chart.yaml
  integration/examples/templated-fields/charts/templates/deployment.yaml
  integration/examples/templated-fields/charts/values.yaml
  integration/examples/templated-fields/go.mod
  integration/examples/templated-fields/main.go
  integration/examples/templated-fields/skaffold.yaml
  pkg/skaffold/build/custom/script.go
  pkg/skaffold/build/custom/script_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/L

#4291 Update Bazel configuration
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
  examples/bazel/WORKSPACE
  integration/examples/bazel/WORKSPACE
Labels: cla: yes, size/M

#4290 Rename `buildpack` config to `buildpacks`
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
  docs/content/en/schemas/v2beta5.json
  integration/examples/buildpacks-node/skaffold.yaml
  integration/examples/buildpacks/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v2beta4/upgrade.go
  pkg/skaffold/schema/v2beta4/upgrade_test.go
Labels: cla: yes, size/S

#4281 apply namespace from command first when cleaning up helm release
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/M

#4222 move field reported to changed
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/resource/status.go
Labels: cla: yes, size/M

#4223 Initial prototype for pod health check hook up
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/resource/status.go
  pkg/skaffold/deploy/resource/status_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/L

#4292 Change codecov thresholds to avoid noise
  codecov.yml
Labels: cla: yes, size/M

#4294 Use "helm version --client" to avoid connecting to cluster
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/M

#4297 Fix dependabot config
  .dependabot/config.yml
Labels: cla: yes, size/M

#4299 Copy the security fix applied by dependabot
  integration/examples/react-reload/app/package-lock.json
Labels: cla: yes, size/XS

#4298 Use pack’s code for reading project descriptors
  go.mod
  go.sum
  pkg/skaffold/build/buildpacks/lifecycle.go
  vendor/github.com/buildpacks/pack/common.go
  vendor/github.com/buildpacks/pack/go.mod
  vendor/github.com/buildpacks/pack/golangci.yaml
  vendor/github.com/buildpacks/pack/internal/registry/registry.go
  vendor/github.com/buildpacks/pack/project/project.go
  vendor/modules.txt
Labels: cla: yes, size/XS

#4280 add annotations feature to kaniko pod
  docs/content/en/schemas/v2beta5.json
  examples/kaniko/skaffold.yaml
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/S

#4306 hook up showing survey prompt if not taken or recently prompted
  cmd/skaffold/app/cmd/cmd.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: Q2-OKR, cla: yes, size/L

#4300 Setup Github Actions for testing release binary against linux and darwin
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
  Makefile
  integration/dev_test.go
Labels: cla: yes, size/L

#4304 Make the `analyse` code a bit easier to read.
  pkg/skaffold/initializer/analyze/analyze.go
Labels: cla: yes, size/M

#4193 Skaffold render solely perform the manifests hydration
  cmd/skaffold/app/cmd/render.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/util.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/render.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/L

#4313 Update GCP Buildpacks builder image references to :v1
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
  docs/content/en/docs/pipeline-stages/filesync.md
  docs/content/en/samples/builders/buildpacks.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  integration/examples/buildpacks-node/skaffold.yaml
  integration/examples/buildpacks/skaffold.yaml
  pkg/skaffold/schema/v2beta4/upgrade_test.go
Labels: cla: yes, size/S

#4312 Add user-friendly validation of builder/artifact compatibility
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/dependencies.go
  pkg/skaffold/build/gcb/spec.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/misc/artifact_type.go
  pkg/skaffold/build/misc/artifact_type_test.go
  pkg/skaffold/schema/validation/validation.go
Labels: cla: yes, size/L

#4315 Release v1.11.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/README.md
  examples/templated-fields/build.sh
  examples/templated-fields/charts/Chart.yaml
  examples/templated-fields/charts/templates/deployment.yaml
  examples/templated-fields/charts/values.yaml
  examples/templated-fields/go.mod
  examples/templated-fields/main.go
  examples/templated-fields/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#4307 [DRAFT] add pod events to diagnostics.
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: Q2-OKR, cla: yes, size/L

#4303 Add pod logs for terminated container in status check.
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/diag/validator/resource.go
  pkg/diag/validator/resource_test.go
  pkg/skaffold/deploy/resource/deployment.go
Labels: Q2-OKR, cla: yes, size/L

#4309 `Skaffold init` supports Python projects with Buildpacks
  integration/examples/buildpacks-python/Procfile
  integration/examples/buildpacks-python/README.md
  integration/examples/buildpacks-python/k8s/web.yaml
  integration/examples/buildpacks-python/requirements.txt
  integration/examples/buildpacks-python/skaffold.yaml
  integration/examples/buildpacks-python/web.py
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
Labels: cla: yes, size/L

#4319 Support mktemp on older Macs
  examples/templated-fields/build.sh
  hack/check-samples.sh
  hack/generate-statik.sh
  hack/install_golint.sh
  hack/test-generated-proto.sh
  integration/examples/templated-fields/build.sh
Labels: cla: yes, size/S

#4326 Debug should report CNB_APP_DIR as working directory for buildpacks images
  pkg/skaffold/debug/cnb.go
  pkg/skaffold/debug/cnb_test.go
  pkg/skaffold/debug/transform.go
Labels: cla: yes, size/M

#4323 #4322: Fix render not fully overwriting output files.
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/util.go
Labels: cla: yes, size/S

#4318 `skaffold init` supports Java/Buildpacks projects
  integration/examples/buildpacks-java/README.md
  integration/examples/buildpacks-java/k8s/web.yaml
  integration/examples/buildpacks-java/pom.xml
  integration/examples/buildpacks-java/skaffold.yaml
  integration/examples/buildpacks-java/src/main/java/hello/Application.java
  integration/examples/buildpacks-java/src/main/java/hello/HelloController.java
  integration/run_test.go
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
Labels: cla: yes

#4330 change 0 code for unknown error
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#4338 Consolidate individual reviewers into skaffold-team
  .github/CODEOWNERS
  MAINTAINERS
Labels: size/S

#4337 Fix propagation of buildpacks working directory
  pkg/skaffold/debug/cnb.go
  pkg/skaffold/debug/cnb_test.go
Labels: cla: yes, size/XS

#3567 Add option to render manifest from previous build result
  .dockerignore
  Makefile
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/render.go
  docs/content/en/docs/references/cli/_index.md
  integration/render_test.go
  integration/skaffold/helper.go
  integration/testdata/render/build-output.json
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/render.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes, size/XL

#4325 Automate release steps post changelog PR merge.
  .github/workflows/draft-release.yml
Labels: cla: yes, size/M

#4341 [Docs] add an example for global config
  docs/content/en/docs/design/global-config.md
  docs/content/en/samples/config/globalConfig.yaml
  pkg/skaffold/schema/samples_test.go
Labels: cla: yes, pr/on-call, size/XS

#4344 Disable Java Buildpacks test
  integration/run_test.go
Labels: cla: yes, size/S

#4333 fetch events correctly by adding v1 group version kind to runtime schema
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#4334 chore: use setValues not values in helm docs example
  docs/content/en/docs/pipeline-stages/deployers/helm.md
Labels: cla: yes, size/XS

#4339 Add status code to resource check event.
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XL

#4345 [buildpacks] `debug` detect direct processes with `/bin/sh -c ...`
  pkg/skaffold/debug/cnb.go
  pkg/skaffold/debug/cnb_test.go
Labels: cla: yes, size/M

#4346 Minor clean up to debug tests
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
  pkg/skaffold/debug/transform_test.go
Labels: cla: yes, size/M

#4336 Fix `skaffold fix --version`
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/fix_test.go
Labels: cla: yes, size/M

#4089 Enable file-watching for `debug`
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/debug_test.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, needs-rebase, size/L

#4353 Allow configuring skaffold binary location for integration tests
  integration/skaffold/helper.go
Labels: cla: yes, size/XS

#4343 Only test images that were built
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
Labels: cla: yes, size/M

#4359 Print Custom Builder command
  pkg/skaffold/build/custom/script.go
Labels: cla: yes, size/XS

#4355 Improve the error message when a released schema is changed
  hack/check-schema-changes.sh
  hack/versions/pkg/schema/check.go
  hack/versions/pkg/schema/version.go
Labels: cla: yes, size/M

#4365 Restore buildpacks-java integration test
  integration/run_test.go
Labels: cla: yes, size/S

#4360 `debug` nodejs results can result in duplicated environment variables
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
Labels: cla: yes, size/M

#3945 Add debugHelpersRegistry property
  cmd/skaffold/app/cmd/config/set_test.go
  pkg/skaffold/config/global_config.go
  pkg/skaffold/config/util.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python_test.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/transformations.go
Labels: cla: yes, size/L

#4369 Tweaks to `debug` docs
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/S

#4316 Skaffold deploy hydrated manifests
  cmd/skaffold/app/cmd/deploy.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl_test.go
  pkg/skaffold/deploy/util.go
Labels: cla: yes, size/L

#4373 Fix port forwarding on Windows
  pkg/skaffold/kubectl/cli.go
  pkg/skaffold/kubectl/cli_test.go
  pkg/skaffold/kubectl/exec.go
  pkg/skaffold/kubectl/exec_windows.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
Labels: cla: yes, size/L

#4352 Extend `skaffold debug` integration tests to buildpacks
  integration/debug_test.go
  integration/testdata/debug/README.md
  integration/testdata/debug/go/Dockerfile
  integration/testdata/debug/go/app.go
  integration/testdata/debug/go/k8s/pod.yaml
  integration/testdata/debug/java/.gitignore
  integration/testdata/debug/java/.mvn/wrapper/MavenWrapperDownloader.java
  integration/testdata/debug/java/.mvn/wrapper/maven-wrapper.jar
  integration/testdata/debug/java/.mvn/wrapper/maven-wrapper.properties
  integration/testdata/debug/java/k8s/web.yaml
  integration/testdata/debug/java/mvnw
  integration/testdata/debug/java/mvnw.cmd
  integration/testdata/debug/java/pom.xml
  integration/testdata/debug/java/scripts/check-jdwp.sh
  integration/testdata/debug/java/src/main/java/hello/Application.java
  integration/testdata/debug/jib/pom.xml
  integration/testdata/debug/kustomization.yaml
  integration/testdata/debug/nodejs/Procfile
  integration/testdata/debug/nodejs/k8s/pod.yaml
  integration/testdata/debug/npm/k8s/pod.yaml
  integration/testdata/debug/npm/project.toml
  integration/testdata/debug/python3/Procfile
  integration/testdata/debug/python3/k8s/pod.yaml
  integration/testdata/debug/skaffold.yaml
  integration/util.go
Labels: cla: yes

#4364 add suggestion protos and hook up with Event API
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/errors/errors.go
  pkg/skaffold/event/event.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XXL

#4375 `debug` now supports buildpacks-produced images
  docs/content/en/docs/pipeline-stages/builders/buildpacks.md
Labels: cla: yes, size/S

#4372 create a constant for pushing image and use that to parse error codes
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/errors/buildProblems.go
  pkg/skaffold/errors/err_map.go
  pkg/skaffold/errors/errors_test.go
Labels: cla: yes, in progress, size/S

#4387 Fix proto generation
  hack/proto/Dockerfile
Labels: cla: yes, size/XS

#4385 Add json output to `skaffold schema list`
  cmd/skaffold/app/cmd/schema.go
  cmd/skaffold/app/cmd/schema/list.go
  cmd/skaffold/app/cmd/schema/list_test.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/M

#4381 Fix docs and error message about pullSecretPath
  docs/content/en/docs/pipeline-stages/builders/docker.md
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/schema/defaults/defaults.go
Labels: cla: yes, size/XS

#4367 Move jib sync testdata to `integration/examples`
  integration/examples/jib-sync/.gitignore
  integration/examples/jib-sync/.mvn/wrapper/MavenWrapperDownloader.java
  integration/examples/jib-sync/.mvn/wrapper/maven-wrapper.jar
  integration/examples/jib-sync/.mvn/wrapper/maven-wrapper.properties
  integration/examples/jib-sync/README.md
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/goose.yaml
  integration/examples/jib-sync/gradle/wrapper/gradle-wrapper.jar
  integration/examples/jib-sync/gradle/wrapper/gradle-wrapper.properties
  integration/examples/jib-sync/gradlew
  integration/examples/jib-sync/gradlew.bat
  integration/examples/jib-sync/k8s/pod.yaml
  integration/examples/jib-sync/mvnw
  integration/examples/jib-sync/mvnw.cmd
  integration/examples/jib-sync/pom.xml
  integration/examples/jib-sync/skaffold-gradle.yaml
  integration/examples/jib-sync/skaffold-maven.yaml
  integration/examples/jib-sync/src/main/java/hello/Application.java
  integration/examples/jib-sync/src/main/java/hello/HelloController.java
  integration/examples/jib-sync/src/main/jib/direct-file
  integration/sync_test.go
  integration/testdata/jib-sync/pom.xml
Labels: cla: yes

#4384 gracefull shutdown RPC even when build is in error
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/commands.go
  pkg/skaffold/server/server.go
Labels: cla: yes, size/M

#4383 Add suggestion code and suggestions to known build problems
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/runner.go
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/errors/buildProblems.go
  pkg/skaffold/errors/buildProblems_test.go
  pkg/skaffold/errors/err_map.go
  pkg/skaffold/errors/errors.go
  pkg/skaffold/errors/errors_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XL

#4379 Fix `skaffold init` for java projects.
  pkg/skaffold/initializer/analyze/analyze_test.go
  pkg/skaffold/initializer/analyze/builder.go
Labels: cla: yes, size/L

#4349 'skaffold init' for Kustomize projects generates profiles for each overlay
  cmd/skaffold/app/cmd/init.go
  docs/content/en/docs/pipeline-stages/init.md
  docs/content/en/docs/references/cli/_index.md
  examples/getting-started-kustomize/deployment.yaml
  integration/examples/getting-started-kustomize/app/Dockerfile
  integration/examples/getting-started-kustomize/app/main.go
  integration/examples/getting-started-kustomize/base/deployment.yaml
  integration/examples/getting-started-kustomize/base/kustomization.yaml
  integration/examples/getting-started-kustomize/kustomization.yaml
  integration/examples/getting-started-kustomize/overlays/dev/deployment.yaml
  integration/examples/getting-started-kustomize/overlays/dev/kustomization.yaml
  integration/examples/getting-started-kustomize/overlays/prod/deployment.yaml
  integration/examples/getting-started-kustomize/overlays/prod/kustomization.yaml
  integration/examples/getting-started-kustomize/overlays/staging/deployment.yaml
  integration/examples/getting-started-kustomize/overlays/staging/kustomization.yaml
  integration/examples/getting-started-kustomize/patch.yaml
  integration/examples/getting-started-kustomize/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/initializer/analyze/analyze.go
  pkg/skaffold/initializer/analyze/kustomize.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/deploy/init.go
  pkg/skaffold/initializer/deploy/kubectl.go
  pkg/skaffold/initializer/deploy/kubectl_test.go
  pkg/skaffold/initializer/deploy/kustomize.go
  pkg/skaffold/initializer/deploy/kustomize_test.go
  pkg/skaffold/initializer/init.go
Labels: cla: yes

#4390 Refactor Add proto.ActionableErr to diag.Resource and deploy.Resource.Status
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/diag/validator/resource.go
  pkg/diag/validator/resource_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/resource/status.go
  pkg/skaffold/deploy/resource/status_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XL

#4393 Add suggestions for container errors and k8 infra errors
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/download/http.go
  pkg/diag/download/http_test.go
  pkg/diag/recommender/container_errors.go
  pkg/diag/recommender/custom.go
  pkg/diag/recommender/custom_test.go
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/diag/validator/recommender.go
  pkg/skaffold/deploy/status_check.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/XL

#4394 Release v1.12.0
  CHANGELOG.md
  examples/buildpacks-java/README.md
  examples/buildpacks-java/k8s/web.yaml
  examples/buildpacks-java/pom.xml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-java/src/main/java/hello/Application.java
  examples/buildpacks-java/src/main/java/hello/HelloController.java
  examples/buildpacks-python/Procfile
  examples/buildpacks-python/README.md
  examples/buildpacks-python/k8s/web.yaml
  examples/buildpacks-python/requirements.txt
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks-python/web.py
  examples/getting-started-kustomize/app/Dockerfile
  examples/getting-started-kustomize/app/main.go
  examples/getting-started-kustomize/base/deployment.yaml
  examples/getting-started-kustomize/base/kustomization.yaml
  examples/getting-started-kustomize/kustomization.yaml
  examples/getting-started-kustomize/overlays/dev/deployment.yaml
  examples/getting-started-kustomize/overlays/dev/kustomization.yaml
  examples/getting-started-kustomize/overlays/prod/deployment.yaml
  examples/getting-started-kustomize/overlays/prod/kustomization.yaml
  examples/getting-started-kustomize/overlays/staging/deployment.yaml
  examples/getting-started-kustomize/overlays/staging/kustomization.yaml
  examples/getting-started-kustomize/patch.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/jib-sync/.gitignore
  examples/jib-sync/.mvn/wrapper/MavenWrapperDownloader.java
  examples/jib-sync/.mvn/wrapper/maven-wrapper.jar
  examples/jib-sync/.mvn/wrapper/maven-wrapper.properties
  examples/jib-sync/README.md
  examples/jib-sync/build.gradle
  examples/jib-sync/goose.yaml
  examples/jib-sync/gradle/wrapper/gradle-wrapper.jar
  examples/jib-sync/gradle/wrapper/gradle-wrapper.properties
  examples/jib-sync/gradlew
  examples/jib-sync/gradlew.bat
  examples/jib-sync/k8s/pod.yaml
  examples/jib-sync/mvnw
  examples/jib-sync/mvnw.cmd
  examples/jib-sync/pom.xml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib-sync/src/main/java/hello/Application.java
  examples/jib-sync/src/main/java/hello/HelloController.java
  examples/jib-sync/src/main/jib/direct-file
Labels: cla: yes, draft-release

#4380 cleanup context paths at examples/microservices skaffold.yml
  examples/microservices/skaffold.yaml
  integration/examples/microservices/skaffold.yaml
Labels: cla: yes, size/S

#4395 Add skaffold.dev docs for jib auto sync.
  docs/content/en/docs/pipeline-stages/filesync.md
Labels: cla: yes, size/S

#4398 Installing jq is not needed on TravisCI
  .travis.yml
Labels: cla: yes, size/XS

#4400 Run integration tests on kind 0.8.1
  Makefile
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/XS

#4405 Bump rack from 2.1.1 to 2.1.4
  integration/examples/ruby/backend/Gemfile.lock
Labels: cla: yes, size/XS

#4406 `skaffold init` skips vendor and node_modules folders
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
  pkg/skaffold/initializer/analyze/analyze.go
  pkg/skaffold/initializer/analyze/analyze_test.go
Labels: cla: yes, size/M

#4408 `skaffold init` supports different exit codes
  cmd/skaffold/skaffold.go
  docs/content/en/docs/pipeline-stages/init.md
  integration/init_test.go
  integration/testdata/init/no-builder/service.yaml
  pkg/skaffold/initializer/analyze/config.go
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/cli.go
  pkg/skaffold/initializer/build/init.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/deploy/init.go
  pkg/skaffold/initializer/deploy/kubectl.go
  pkg/skaffold/initializer/deploy/kustomize.go
  pkg/skaffold/initializer/errors/errors.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/testdata/init/no-builder/service.yaml
Labels: cla: yes, size/L

#4407 Retry starting the rpc servers
  pkg/skaffold/server/server.go
Labels: cla: yes, size/M

#4414 Fix unit test
  cmd/skaffold/app/cmd/runner_test.go
Labels: cla: yes, size/XS
