Repository GoogleContainerTools/skaffold, pull requests merged in 2020-08, with the labels that each got.

#4611 Release v1.13.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, draft-release, size/L

#4625 Clarify 'survey' command text
  cmd/skaffold/app/cmd/survey.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/survey/survey.go
Labels: cla: yes, size/S

#4629 Disable survey prompt until the next release
  pkg/skaffold/survey/survey.go
Labels: cla: yes, size/S

#4621 Fix CustomTagger docs
  docs/content/en/docs/references/yaml/main.js
  docs/content/en/schemas/v2beta6.json
  hack/schemas/main.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/yamltags/tags.go
Labels: cla: yes, meta/docs-preview, size/M

#4631 Release v1.13.1
  CHANGELOG.md
Labels: cla: yes, draft-release

#4622 Explicitly specify commands that should show surveys and update messages post execution
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/commands_test.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/run.go
  integration/housekeeing_messages_test.go
  testutil/util.go
Labels: cla: yes, size/M

#4241 Target k3d in integration tests
  .travis.yml
  Makefile
  integration/dev_test.go
  integration/util.go
Labels: cla: yes, size/L

#4618 Install specific Bazel version and Skaffold version for nightly linux and darwin integration tests.
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
Labels: cla: yes, size/M

#4646 skip test TestHouseKeepingMessagesShownForDev until 1.14.0
  integration/housekeeing_messages_test.go
Labels: cla: yes, size/XS

#4635 Dependabot fix done explicitly
  examples/react-reload/app/package-lock.json
  integration/examples/react-reload/app/package-lock.json
Labels: cla: yes, size/XS

#4644 Make event handling sequential and set the correct timestamp
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
Labels: cla: yes, size/L

#4650 Remove unused goose.yaml
  integration/examples/jib-sync/goose.yaml
Labels: cla: yes, size/S

#4639 Update jib to 2.5.x
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#4655 Send update-check message to stderr
  cmd/skaffold/app/cmd/cmd.go
Labels: cla: yes, size/XS

#4656 Enable auto sync mode for Buildpacks artifacts
  docs/content/en/docs/pipeline-stages/filesync.md
  integration/examples/buildpacks-java/skaffold.yaml
  integration/examples/buildpacks-node/skaffold.yaml
  integration/examples/buildpacks/skaffold.yaml
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes, size/S

#4664 Add support for reloading kustomize components.
  pkg/skaffold/deploy/kustomize.go
Labels: cla: yes, size/XS

#4682 Kpt Deployer Skeleton
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
Labels: cla: yes, size/L

#4679 Improve error message when skaffold config not found
  cmd/skaffold/app/cmd/runner.go
Labels: cla: yes, size/XS

#4683 Return deployment status code when status check can't retrieve pods from cluster
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status_check_test.go
Labels: cla: yes, size/S

#4689 Kpt Deployer Config
  docs/content/en/schemas/v2beta7.json
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/new_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v2beta6/upgrade.go
Labels: cla: yes, size/L

#4678 Fix bazel integration tests on Github Actions
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
  integration/examples/bazel/WORKSPACE
  integration/util.go
Labels: cla: yes, size/M

#4684 Simpify devLoopEvent message text
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
Labels: cla: yes, size/S

#4686 Update maintainers and add kpt codeowners
  .github/CODEOWNERS
  MAINTAINERS
Labels: cla: yes, size/S

#4657 Move context validation to build phase so as to not interfere with deploy
  integration/deploy_test.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/schema/samples_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes, size/L

#4691 Kpt Deployer applyDir implementation and tests
  docs/content/en/schemas/v2beta7.json
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#4694 small changes to kpt deployer docs and ordering
  docs/content/en/schemas/v2beta7.json
  pkg/skaffold/runner/new.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/S

#4688 fix WSL path check to be case insensitive
  pkg/skaffold/docker/client.go
Labels: cla: yes, size/XS

#4698 Remove remote rules
  pkg/diag/download/http.go
  pkg/diag/download/http_test.go
  pkg/diag/recommender/custom.go
  pkg/diag/recommender/custom_test.go
  pkg/diag/validator/pod.go
  pkg/skaffold/deploy/status_check.go
Labels: cla: yes, size/L

#4696 Kpt Deployer Dependencies() implementation and tests
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
Labels: cla: yes, size/L

#4697 Kpt Deployer Cleanup() implementation and tests
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
Labels: cla: yes, size/M

#4703 Kpt Deployer Dependencies Unittests
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
Labels: cla: yes, size/XS

#4705 Suppress clutter from docker-credential-gcloud error messages
  pkg/skaffold/docker/image.go
Labels: cla: yes, size/S

#4707 v1.13.2 Release
  CHANGELOG.md
Labels: cla: yes, size/S

#4636 Update log-tailing.md
  docs/content/en/docs/pipeline-stages/log-tailing.md
Labels: cla: yes, size/XS

#4712 Use ParseTolerant to parse Helm version because of missing patch version
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/M

#4715 Add explicit tests for Helm version parsing
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/M

#4716 drop codecov patch threshold to 40%
  codecov.yml
Labels: cla: yes, size/XS

#4699 Add .NET Core container debugging support
  docs/content/en/docs/workflows/debug.md
  integration/debug_test.go
  integration/testdata/debug/.gitignore
  integration/testdata/debug/kustomization.yaml
  integration/testdata/debug/netcore/Dockerfile
  integration/testdata/debug/netcore/k8s/pod.yaml
  integration/testdata/debug/netcore/src/HelloWorld/Controllers/HomeController.cs
  integration/testdata/debug/netcore/src/HelloWorld/HelloWorld.csproj
  integration/testdata/debug/netcore/src/HelloWorld/Program.cs
  integration/testdata/debug/netcore/src/HelloWorld/Startup.cs
  integration/testdata/debug/netcore/src/HelloWorld/appsettings.json
  integration/testdata/debug/skaffold.yaml
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_netcore.go
  pkg/skaffold/debug/transform_netcore_test.go
Labels: cla: yes, size/L

#4720 Move kubernetes client into its own package
  integration/util.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/build/cluster/secret_test.go
  pkg/skaffold/deploy/labels.go
  pkg/skaffold/deploy/labels_test.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/kubernetes/client/client.go
  pkg/skaffold/kubernetes/owner.go
  pkg/skaffold/kubernetes/owner_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/kubernetes/watcher.go
  pkg/skaffold/kubernetes/watcher_test.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  pkg/webhook/kubernetes/deployment.go
  pkg/webhook/kubernetes/service.go
Labels: cla: yes, size/L

#4719 Add Kustomize Hydration to Kpt Deployer's Render method
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
Labels: cla: yes, size/L

#4721 Move `DetectWSL` function into util package
  pkg/skaffold/docker/client.go
  pkg/skaffold/util/wsl.go
Labels: cla: yes, size/M

#4723 Kpt Deployer Deploy() Implementation/Tests
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
Labels: cla: yes, size/L

#4704 Add SKAFFOLD_CMDLINE environment variable to pass command-line
  cmd/skaffold/app/skaffold.go
  cmd/skaffold/app/skaffold_test.go
Labels: cla: yes, size/M

#4701 Identify minikube cluster for any profile name
  pkg/skaffold/build/local/docker_test.go
  pkg/skaffold/cluster/minikube.go
  pkg/skaffold/cluster/minikube_test.go
  pkg/skaffold/config/util.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: cla: yes, size/L

#4728 Change kpt deployer doc from Beta to Alpha
  docs/content/en/schemas/v2beta7.json
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/S

#4690 add pod initialization logic in diag and follow up some minor reporting changes.
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/resource/logfile.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/deploy/status_check_test.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/runner.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: area/status-check, cla: yes, size/XL

#4736 Extending Workflow for Kpt Deployer (accepting additional arguments)
  docs/content/en/schemas/v2beta7.json
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kpt_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#4735 Add test for using helm setFiles
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/S

#4741 Fix slow tests
  pkg/skaffold/test/test_test.go
Labels: cla: yes, size/M

#4740 Fix slow test
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
Labels: cla: yes, size/S

#4739 Bump golangci lint v1.30.0
  hack/golangci-lint.sh
  hack/golangci.yml
  hack/linters.sh
  hack/pedantic-imports.sh
  integration/rpc_test.go
  pkg/skaffold/initializer/analyze/analyze_test.go
  pkg/skaffold/kubernetes/client/client.go
  pkg/skaffold/schema/v1beta5/upgrade_test.go
Labels: cla: yes, size/M

#4598 Introduce Config interfaces
  cmd/skaffold/app/cmd/runner_test.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/jib/types.go
  pkg/skaffold/build/local/docker_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
  pkg/skaffold/deploy/kpt.go
  pkg/skaffold/deploy/kubectl.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kustomize.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status_check.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/generate_pipeline/generate_pipeline.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/kubectl/cli.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/generate_pipeline.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/sync/types.go
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/trigger/triggers.go
Labels: cla: yes, size/L

#4603 Handle ctrl-c in the middle of GetAllAuthConfigs()
  pkg/skaffold/docker/image.go
Labels: cla: yes, size/S

#4743 Rename NewFromRunContext() to NewCLI()
  integration/port_forward_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/kubectl/cli.go
  pkg/skaffold/kubectl/cli_test.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/load_images_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/S
