Repository GoogleContainerTools/skaffold, pull requests merged in 2020-03, with the labels that each got.

#3761 Add profile option to RunBuilder in test helper
  integration/skaffold/helper.go
Labels: cla: yes, size/S

#3703 Autogenerate k8s manifests in skaffold init
  cmd/skaffold/app/cmd/init.go
  integration/init_test.go
  integration/testdata/init/.gitignore
  integration/testdata/init/hello/Dockerfile
  integration/testdata/init/hello/deployment.yaml.expected
  integration/testdata/init/hello/hello.go
  integration/testdata/init/microservices/leeroy-app/Dockerfile
  integration/testdata/init/microservices/leeroy-app/app.go
  integration/testdata/init/microservices/leeroy-web/Dockerfile
  integration/testdata/init/microservices/leeroy-web/web.go
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/cli.go
  pkg/skaffold/initializer/build/init.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/build/util.go
  pkg/skaffold/initializer/config/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/deploy/init.go
  pkg/skaffold/initializer/deploy/kubectl.go
  pkg/skaffold/initializer/deploy/kubectl_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/prompt/prompt.go
  pkg/skaffold/kubernetes/generator/generate.go
  pkg/skaffold/kubernetes/generator/generate_test.go
  pkg/skaffold/kubernetes/generator/template.go
Labels: cla: yes, size/XL

#3774 fix wording
  docs/content/en/docs/workflows/ci-cd.md
Labels: cla: yes, size/XS

#3680 Allow Sync for non-root containers-hotreload example
  examples/hot-reload/k8s/node.yaml
  examples/hot-reload/k8s/python.yaml
  examples/hot-reload/node/Dockerfile
  examples/hot-reload/node/package.json
  examples/hot-reload/python/Dockerfile
  examples/hot-reload/skaffold.yaml
  integration/examples/hot-reload/k8s/node.yaml
  integration/examples/hot-reload/k8s/python.yaml
  integration/examples/hot-reload/node/Dockerfile
  integration/examples/hot-reload/node/package.json
  integration/examples/hot-reload/python/Dockerfile
  integration/examples/hot-reload/skaffold.yaml
Labels: cla: yes, size/XS

#3777 Bump golangci-lint to 1.23.7
  hack/linter.sh
  pkg/skaffold/deploy/deploy_mux_test.go
Labels: cla: yes, size/M

#3783 Binaries for linux-arm #2068
  Makefile
  Makefile.diag
Labels: cla: yes, size/XS

#3779 Allow custom go-licenses binary when building
  hack/generate-statik.sh
Labels: cla: yes, size/XS

#3782 Revert "unhide status check and on by default. "
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/dev_test.go
  integration/run_test.go
Labels: cla: yes, size/S

#3785 Shorter PR template
  .github/pull_request_template.md
Labels: cla: yes, size/M

#3794 Bump puma from 4.3.1 to 4.3.3
  integration/examples/ruby/backend/Gemfile.lock
Labels: cla: yes, size/XS

#3787 Applied namespace to Cleanup and getArgs
  pkg/skaffold/deploy/helm.go
  pkg/skaffold/deploy/helm_test.go
Labels: cla: yes, size/M

#3788 v1.5.0 Release
  CHANGELOG.md
Labels: cla: yes, size/M

#3742 [Diagnostics] Add validator interface. Add resource interface and PodValidator
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/diag/validator/resource.go
  pkg/diag/validator/validator.go
Labels: cla: yes, size/L

#3804 Also clean up statik files
  Makefile
Labels: cla: yes, size/XS

#3805 Fix ko sample
  examples/custom/build.sh
  integration/examples/custom/build.sh
Labels: cla: yes, size/XS

#3806 Upgrade kompose to 1.21.0
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/XS

#3803 Normalize capitalization for types while port forwarding
  pkg/skaffold/kubernetes/portforward/port_forward_entry.go
  pkg/skaffold/kubernetes/portforward/port_forward_entry_test.go
Labels: cla: yes, size/S

#3775 Go 1.14
  .travis.yml
  DEVELOPMENT.md
  Makefile
  Makefile.diag
  deploy/cross/Dockerfile
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
  deploy/webhook/Dockerfile
  go.mod
  go.sum
  hack/build.bat
  hack/generate-statik.sh
  hack/tools/go.mod
  hack/tools/vendor/modules.txt
  vendor/modules.txt
Labels: cla: yes, size/L

#3732 add flag --survey to set to set/unset disable survey prompt
  cmd/skaffold/app/cmd/config/flags.go
  cmd/skaffold/app/cmd/config/set.go
  cmd/skaffold/app/cmd/config/set_test.go
Labels: cla: yes, size/L

#3792 unhide status check and on by default
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/dev_test.go
  integration/run_test.go
Labels: !! do-not-merge !!, cla: yes, pr/blocked, size/S

#3382 Add new Auto sync option
  .travis.yml
  docs/content/en/schemas/v2beta1.json
  integration/sync_test.go
  integration/testdata/jib-sync/.gitignore
  integration/testdata/jib-sync/.mvn/wrapper/MavenWrapperDownloader.java
  integration/testdata/jib-sync/.mvn/wrapper/maven-wrapper.jar
  integration/testdata/jib-sync/.mvn/wrapper/maven-wrapper.properties
  integration/testdata/jib-sync/build.gradle
  integration/testdata/jib-sync/gradle/wrapper/gradle-wrapper.jar
  integration/testdata/jib-sync/gradle/wrapper/gradle-wrapper.properties
  integration/testdata/jib-sync/gradlew
  integration/testdata/jib-sync/gradlew.bat
  integration/testdata/jib-sync/k8s/pod.yaml
  integration/testdata/jib-sync/mvnw
  integration/testdata/jib-sync/mvnw.cmd
  integration/testdata/jib-sync/pom.xml
  integration/testdata/jib-sync/skaffold.yaml
  integration/testdata/jib-sync/src/main/java/hello/Application.java
  integration/testdata/jib-sync/src/main/java/hello/HelloController.java
  integration/testdata/jib-sync/src/main/jib/direct-file
  pkg/skaffold/build/jib/sync.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, pr/lgtm, size/M

#3818 Fix TestWaitForPodSucceeded flake
  pkg/skaffold/kubernetes/wait.go
  pkg/skaffold/kubernetes/wait_test.go
Labels: cla: yes, size/XS

#3786 cleanup common flags + better -f description
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/init.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/M

#3819 Cross compile for linux-arm
  Makefile
Labels: cla: yes, size/S

#3820 Fix `make quicktest`
  Makefile
  hack/gotest.sh
Labels: cla: yes, size/S

#3807 Fix this integration test on minikube
  integration/build_test.go
Labels: cla: yes, size/XS

#3815 Use new t.Cleanup() to simplify tests
  integration/build_cluster_test.go
  integration/build_test.go
  integration/cache_test.go
  integration/config_test.go
  integration/debug_test.go
  integration/deploy_test.go
  integration/dev_test.go
  integration/fix_test.go
  integration/helm_test.go
  integration/init_test.go
  integration/port_forward_test.go
  integration/rpc_test.go
  integration/run_test.go
  integration/skaffold/helper.go
  integration/sync_test.go
  integration/util.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/jib_test.go
  pkg/skaffold/build/jib/maven_test.go
  pkg/skaffold/build/jib/sync_test.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/kustomize_test.go
  pkg/skaffold/initializer/deploy/kubectl_test.go
  pkg/skaffold/test/test_test.go
  pkg/skaffold/util/config_test.go
  pkg/skaffold/util/util_test.go
  testutil/env.go
  testutil/tmp.go
  testutil/util.go
Labels: cla: yes, size/L

#3825 Simplify code that finds the artifact's type
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
  pkg/skaffold/build/jib/init.go
  pkg/skaffold/build/jib/init_test.go
  pkg/skaffold/docker/docker_init.go
  pkg/skaffold/docker/docker_init_test.go
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/util.go
Labels: cla: yes, size/L

#3832 Add dependabot config file
  .dependabot/config.yml
Labels: cla: yes, size/S

#3827 Fix `skaffold debug` panic with nodejs
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
Labels: cla: yes, size/M

#3837 Support Dockerfile.dockerignore
  pkg/skaffold/docker/dependencies.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/syncmap.go
  pkg/skaffold/docker/syncmap_test.go
Labels: cla: yes, kokoro:run, size/M

#3840 Fix issues in `skaffold init`
  pkg/skaffold/docker/docker_init.go
  pkg/skaffold/initializer/analyze/analyze.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/kubernetes/util.go
  pkg/skaffold/schema/versions.go
Labels: cla: yes, size/S

#3845 cut v1.6.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/app/package-lock.json
  examples/react-reload/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/M

#3851 Revert "Cross compile for linux-arm"
  Makefile
Labels: cla: yes, size/S

#3854 upgrade hugo + small fixes
  deploy/webhook/Dockerfile
  docs/config.toml
  docs/content/en/docs/references/_index.md
Labels: cla: yes, size/XS

#3856 Fix doc link to local cluster info
  docs/content/en/docs/environment/_index.md
Labels: area/docs, cla: yes, size/XS

#3853 Format `go test` output with Go rather than bash and jq
  hack/gotest.sh
  hack/tests/main.go
Labels: cla: yes, size/L

#3842 Cobra context
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/commands_test.go
  cmd/skaffold/app/cmd/config/list.go
  cmd/skaffold/app/cmd/config/list_test.go
  cmd/skaffold/app/cmd/config/set.go
  cmd/skaffold/app/cmd/config/set_test.go
  cmd/skaffold/app/cmd/config/unset.go
  cmd/skaffold/app/cmd/credits/export.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/find_configs.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/generate_pipeline.go
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/schema.go
  cmd/skaffold/app/cmd/schema/list.go
  cmd/skaffold/app/cmd/schema/list_test.go
  cmd/skaffold/app/cmd/version.go
  cmd/skaffold/app/signals.go
  cmd/skaffold/app/signals_test.go
  cmd/skaffold/app/skaffold.go
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/modules.txt
Labels: cla: yes, size/L

#3858 [examples] upgrade nodejs example dependencies
  examples/hot-reload/node/package-lock.json
  examples/hot-reload/node/package.json
  examples/react-reload/app/package-lock.json
  integration/examples/hot-reload/node/package-lock.json
  integration/examples/react-reload/app/package-lock.json
Labels: cla: yes, size/XS

#3857 [docs] [release] fix firebase-tools version
  deploy/webhook/Dockerfile
Labels: cla: yes, size/XS

#3859 Fix go test helper
  hack/tests/main.go
Labels: cla: yes, size/S

#3867 Fix of documentation issue #3266 microservices example is broken
  examples/microservices/README.md
Labels: cla: yes, size/XS

#3866 Show compilation errors
  hack/tests/main.go
Labels: cla: yes, size/S

#3865 Master Keychain
  pkg/skaffold/docker/authenticators.go
  pkg/skaffold/docker/authenticators_test.go
  pkg/skaffold/docker/remote.go
Labels: cla: yes, size/M

#3874 Update debug-events design proposal status
  docs/design_proposals/debug-events.md
Labels: cla: yes, size/XS

#3875 Rework debug docs
  docs/content/en/docs/workflows/debug.md
Labels: area/debug, area/docs, cla: yes, size/L

#3880 Fix console output for internal Jib tasks/goals
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/init.go
  pkg/skaffold/build/jib/init_test.go
  pkg/skaffold/build/jib/maven.go
  pkg/skaffold/build/jib/maven_test.go
Labels: cla: yes, size/L

#3876 Bump GolangCI-Lint to v1.24.0
  hack/linter.sh
  pkg/skaffold/runner/util/util_test.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/XS

#3869 Fix possible nil dereference
  integration/rpc_test.go
Labels: cla: yes, size/S

#3877 Wait for the logs to be printed
  hack/tests/main.go
Labels: cla: yes, size/XS

#3870 Simplify Kaniko error message
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/kubernetes/wait.go
Labels: cla: yes, size/XS

#3878 Support globs in custom/buildpacks builder deps
  examples/custom/skaffold.yaml
  integration/examples/custom/skaffold.yaml
  pkg/skaffold/build/buildpacks/dependencies.go
  pkg/skaffold/build/buildpacks/dependencies_test.go
  pkg/skaffold/build/custom/dependencies.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/list/list.go
Labels: cla: yes, size/L

#3888 Use less memory for linting
  hack/linter.sh
Labels: cla: yes, size/XS
