Repository GoogleContainerTools/skaffold, pull requests merged in 2020-12, with the labels that each got.

#5059 add docker build distinct error codes
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/docker/docker_test.go
  pkg/skaffold/build/docker/errors.go
  pkg/skaffold/build/docker/errors_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/errors/err_def.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: area/errors, cla: yes

#5058 Add skaffold meter struct
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/yamltags/tags.go
  pkg/skaffold/yamltags/tags_test.go
Labels: cla: yes, size/L

#5070 Add distinct error codes for all deploy errors
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/deploy/error/errors.go
  pkg/skaffold/deploy/helm/args.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/errors.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/errors.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/errors.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/errors/err_def.go
  pkg/skaffold/errors/errors.go
  pkg/skaffold/kubernetes/manifest/errors.go
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/kubernetes/manifest/labels.go
  pkg/skaffold/kubernetes/manifest/transformations.go
  pkg/skaffold/kubernetes/manifest/util.go
  pkg/skaffold/runner/deploy.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: area/errors, cla: yes

#5080 Change default kaniko image to `gcr.io/k8s-skaffold/skaffold-helpers/busybox` from `busybox`
  pkg/skaffold/constants/constants.go
Labels: cla: yes, size/XS

#5092 Release v1.17.1
  CHANGELOG.md
Labels: cla: yes, draft-release, size/M

#5046 Add the IgnoreChanges flag to the GitTagger config
  docs/content/en/schemas/v2beta10.json
  pkg/skaffold/build/tag/custom_template.go
  pkg/skaffold/build/tag/git_commit.go
  pkg/skaffold/build/tag/git_commit_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/new_test.go
  pkg/skaffold/schema/latest/config.go
Labels: !! config-change !!, !! do-not-merge !!, cla: yes, size/L

#5097 Transition from Github Actions ::add-path
  .github/workflows/draft-release.yml
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
Labels: cla: yes, size/XS

#5082 Add port forwarding config when generating manifests through init
  integration/testdata/init/hello/deployment.yaml.expected
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/cli.go
  pkg/skaffold/initializer/build/init.go
  pkg/skaffold/initializer/config.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/kubernetes/generator/generate.go
  pkg/skaffold/kubernetes/generator/generate_test.go
  pkg/skaffold/kubernetes/generator/template.go
Labels: cla: yes, size/M

#5098 fix the config schema
  docs/content/en/schemas/v2beta10.json
  docs/content/en/schemas/v2beta11.json
Labels: cla: yes, size/S

#5084 Re-add colors to buildpacks and docker cli output
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/color/formatter.go
  pkg/skaffold/color/formatter_test.go
Labels: cla: yes, size/M

#5083 Fix integration test flakes
  integration/deploy_test.go
  integration/port_forward_test.go
  integration/run_test.go
  integration/skaffold/helper.go
  integration/sync_test.go
Labels: cla: yes, size/M

#5107 Remove return result from RunBackground
  integration/skaffold/helper.go
Labels: cla: yes, size/XS

#5100 Capture deployers in skaffold meter struct
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/yamltags/tags.go
  pkg/skaffold/yamltags/tags_test.go
Labels: cla: yes, size/M

#5121 Recompute docker dependencies across dev loops.
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/custom/dependencies.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/dependencies.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/docker/context.go
  pkg/skaffold/docker/context_test.go
  pkg/skaffold/docker/dependencies.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/util/store.go
Labels: cla: yes, size/L

#5105 Capture Errors and dev iterations metrics
  pkg/skaffold/errors/errors.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/runner/dev.go
Labels: cla: yes, size/M

#5119 Upgrade Jib versions to 2.7.0 in examples and integration tests
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#5088 enabling using another container's network stack on build process
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/runner_test.go
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  docs/content/en/schemas/v2beta11.json
  examples/getting-started/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/L

#5117 Making a util to hold the common cmd functionality
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/util.go
  cmd/skaffold/app/cmd/util_test.go
Labels: cla: yes, size/L

#5124 remove wsl detection logic
  pkg/skaffold/cluster/minikube.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/util/wsl.go
Labels: cla: yes, size/M

#5052 fix: buildkit build
  go.mod
  go.sum
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/docker/docker_test.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/util/term.go
  testutil/cmd_helper.go
Labels: cla: yes, size/M

#5069 [Refactor] Fail at helm initialization when helm client version is less than 3.0.0.
  integration/render_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/new_test.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes, size/L

#5039 Create a custom unmarshler for Volumes and VolumeMounts to fix #4175
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/util/yaml.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/L

#5078 issue #5076 Skaffold support for docker build '--squash' flag
  docs/content/en/schemas/v2beta11.json
  integration/testdata/build/squash/Dockerfile
  integration/testdata/build/squash/skaffold.yaml
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, needs-rebase, size/M

#5129 update AlecAivazis/survey to v2
  go.mod
  go.sum
  pkg/skaffold/initializer/prompt/prompt.go
Labels: cla: yes, size/XS

#5111 add user prompt for selecting ports when using --XXenableManifestGeneration with skaffold init
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/cli.go
  pkg/skaffold/initializer/build/init.go
  pkg/skaffold/initializer/build/init_test.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/prompt/prompt.go
  pkg/skaffold/kubernetes/generator/generate.go
  pkg/skaffold/kubernetes/generator/generate_test.go
  pkg/skaffold/kubernetes/generator/template.go
Labels: cla: yes, size/L

#5125 Add flag to save events to a file
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/server/server.go
Labels: cla: yes, size/L

#5120 Capture enum flags
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/commands_test.go
  cmd/skaffold/app/cmd/config.go
  cmd/skaffold/app/cmd/credits.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/filter.go
  cmd/skaffold/app/cmd/find_configs.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/generate_pipeline.go
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/schema.go
  cmd/skaffold/app/cmd/version.go
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/instrumentation/meter.go
Labels: cla: yes, size/L

#5131 Deleting unexpected lines
  examples/getting-started/skaffold.yaml
Labels: cla: yes, size/XS

#5134 [refactor] move StringSet code into pkg/skaffold/util
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/util/stringset.go
Labels: cla: yes

#5135 write metrics to file
  cmd/skaffold/skaffold.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/meter_test.go
Labels: cla: yes, size/L

#5137 remove last traces of vendor
  deploy/webhook/Dockerfile
Labels: cla: yes, size/XS

#5026 [KPT CODELAB] (2/3) kpt config validation
  codelab/01_kpt-validate/README.md
  codelab/01_kpt-validate/resources/validation-pipeline/fn-pipeline.yaml
  codelab/01_kpt-validate/tutorial.md
Labels: cla: yes, size/L

#5138 Fix `skaffold debug` for helm charts with skaffold config file other than default `skaffold.yaml`
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/types/types.go
Labels: cla: yes, size/S

#5146 fix usage of set-env in Github integration actions
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
Labels: cla: yes, size/XS

#5141 new init prompt function and helper functions
  pkg/skaffold/initializer/prompt/prompt.go
  pkg/skaffold/initializer/prompt/prompt_test.go
  pkg/skaffold/initializer/util/util.go
  pkg/skaffold/initializer/util/util_test.go
Labels: cla: yes, size/L

#5142 replace our user input handling with survey package
  pkg/skaffold/initializer/prompt/prompt.go
  pkg/skaffold/initializer/prompt/prompt_test.go
Labels: cla: yes, size/L

#5151 remove last trace of ::set-env
  .github/workflows/integration-darwin.yml
Labels: cla: yes, size/XS

#5028 [KPT CODELAB] (3/3) kpt deployment & pruning
  codelab/02_kpt-deploy/README.md
  codelab/02_kpt-deploy/resources/sample-app/config/frontend/kustomization.yaml
  codelab/02_kpt-deploy/resources/sample-app/config/kustomization.yaml
  codelab/02_kpt-deploy/tutorial.md
Labels: cla: yes, size/L

#5152 Unhide XXenableManifestGeneration for skaffold init, remove unnecessary print line
  cmd/skaffold/app/cmd/init.go
  docs/content/en/docs/references/cli/_index.md
  integration/init_test.go
  pkg/skaffold/initializer/build/util.go
  pkg/skaffold/initializer/prompt/prompt.go
Labels: cla: yes, size/S

#5118 Adding new test command
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/test.go
  cmd/skaffold/app/cmd/util.go
  cmd/skaffold/app/cmd/util_test.go
  cmd/skaffold/app/tips/tips.go
  docs/content/en/docs/references/cli/_index.md
  integration/skaffold/helper.go
  integration/test_test.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/L

#5154 enable `detect-minikube` by default.
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/S

#5155 add transparent init function
  pkg/skaffold/initializer/transparent.go
  pkg/skaffold/initializer/transparent_test.go
Labels: cla: yes, size/L

#5157 Embed metrics credentials and upload metrics if they are present
  .gitignore
  cmd/skaffold/app/cmd/schema/print_test.go
  cmd/skaffold/app/secret/statik/fs.go
  go.mod
  go.sum
  hack/generate-statik.sh
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/meter_test.go
  testutil/fake_fs.go
Labels: cla: yes, size/L

#5170 Render uses Helm templated values-file
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/S

#5156 [Refactor] Move FSNotify trigger into a separate package
  pkg/skaffold/trigger/fsnotify/trigger.go
  pkg/skaffold/trigger/fsnotify/trigger_test.go
  pkg/skaffold/trigger/fsnotify/workdir.go
  pkg/skaffold/trigger/triggers.go
  pkg/skaffold/trigger/triggers_test.go
Labels: cla: yes, size/L

#5165 fix: lookup image id with tag rather than name during tryImport
  pkg/skaffold/build/cache/lookup.go
Labels: cla: yes, size/XS

#5158 Fail Helm deployments early with missing templated values
  docs/content/en/schemas/v2beta11.json
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/util/env_template.go
  pkg/skaffold/util/env_template_test.go
  testutil/cmd_helper.go
Labels: cla: yes, size/L

#5174 Rename BuildAndTest() method to Build()
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/run_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/M

#5168 Set meter.Command before an error could occur with createNewRunner
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/util/stringset.go
Labels: cla: yes, size/M

#5169 Add more unit tests for creating metrics, fix bug related to unmarshalling flags
  go.mod
  go.sum
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/meter_test.go
Labels: cla: yes, size/L

#5182 Profile with multiple activations should be processed only once.
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: cla: yes, size/S

#5181 Add flag that prints timestamps in skaffold logs.
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/S
