Repository GoogleContainerTools/skaffold, pull requests merged in 2021-07, with the labels that each got.

#6114 Fix couldn't start notify trigger in multi-config projects
  pkg/skaffold/trigger/fsnotify/trigger.go
Labels: cla: yes, size/S

#6115 Fix 5774: Allow iterative status checks
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/pipeline-stages/deployers/_index.md
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/workflows/ci-cd.md
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: cla: yes, size/L

#6118 Associate `StatusCheckSubtaskEvent`s with `Deploy` phase
  pkg/skaffold/event/v2/status_check.go
Labels: cla: yes, size/XS

#6121 [Refactor] Move log stream utility out of pkg/skaffold/kubernetes
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/log/stream/stream.go
  pkg/skaffold/log/stream/stream_test.go
Labels: cla: yes, size/L

#6124 Move cluster image loading logic into Deployer
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/kubernetes/loader/load.go
  pkg/skaffold/kubernetes/loader/load_test.go
  pkg/skaffold/loader/loader.go
  pkg/skaffold/loader/loader_mux.go
  pkg/skaffold/loader/provider.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/apply.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/load_images.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: cla: yes, size/XL

#6140 Create SECURITY.md
  README.md
  SECURITY.md
Labels: cla: yes, size/S

#6130 Bump puma from 4.3.5 to 4.3.8 in integration/examples/ruby/backend
  integration/examples/ruby/backend/Gemfile.lock
Labels: cla: yes, size/XS

#6131 Configure dependabot to monitor skaffold go.mod and github-actions
  .github/dependabot.yml
Labels: cla: yes, size/M

#6139 Set specific permissions for workflows
  .github/workflows/draft-release.yml
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
Labels: cla: yes, size/S

#6138 Make completion work again
  cmd/skaffold/app/cmd/cmd.go
Labels: cla: yes, size/M

#6125 Move cluster availability check into Deployers
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/kubernetes/util.go
  pkg/skaffold/runner/v1/apply.go
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/M

#6135 Fetch namespaces at time of sync
  pkg/skaffold/sync/provider.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/S

#6155 Update Skaffold dependencies
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/S

#6159 hooks: add hooks schema, some interface refactor
  docs/content/en/schemas/v2beta19.json
  pkg/skaffold/build/build.go
  pkg/skaffold/build/builder_mux_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L

#6085 [v2] 1. Remove the latest/v2 schema dependencies.
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes, size/XXL

#6089 [v2] 2. Update v2 with new UX
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/generate_test.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/renderer_test.go
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes, size/XXL

#6164 change ptypes call to timestamppb to fix linters
  pkg/skaffold/event/event.go
  pkg/skaffold/event/v2/event.go
Labels: cla: yes, size/S

#6146 Simplify `--timestamps` output
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/skaffold.go
  pkg/skaffold/build/result.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
Labels: cla: yes, size/L

#6066 working cloud profiler export for skaffold
  cmd/skaffold/skaffold.go
  go.mod
  go.sum
Labels: cla: yes, size/S

#6144 [v2] Add events and handler for render stage
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/constants/constants.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/event_test.go
  pkg/skaffold/event/v2/metadata.go
  pkg/skaffold/event/v2/metadata_test.go
  pkg/skaffold/event/v2/render.go
  pkg/skaffold/event/v2/render_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/XXL

#6143 [v2] Add generator for k8sRaw, kustomize, kpt manifests
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/generate_test.go
  pkg/skaffold/render/renderer/renderer.go
Labels: cla: yes, size/L

#6167 Simplify `BuildSubtaskEvent` ID setting/handling
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/event/v2/build.go
  pkg/skaffold/runner/build.go
Labels: cla: yes, size/S

#6169 Update Jib docs with some advanced usage examples
  docs/content/en/docs/pipeline-stages/builders/jib.md
Labels: cla: yes, size/S

#6068 [v2 refactoring proposal] Decouple the runner creation from v1 schema
  cmd/skaffold/app/cmd/apply.go
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/debug_test.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/diagnose_test.go
  cmd/skaffold/app/cmd/filter.go
  cmd/skaffold/app/cmd/generate_pipeline.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/run_test.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/test.go
  pkg/skaffold/parser/config.go
  pkg/skaffold/parser/config_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/v1/generate_pipeline.go
  pkg/skaffold/runner/v2/generate_pipeline.go
Labels: cla: yes, planning/Q3-21, size/L

#6171 Disable k3d integration tests
  .travis.yml
Labels: cla: yes, size/M

#6160 hooks: `sync` refactor
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/runner_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/sync/syncer_mux.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/M

#6168 Update Jib build plugin versions after 3.1.2 release
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#6172 feat: add hooks schema
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes, size/M

#6176 Doc tweaks
  docs/content/en/docs/install/_index.md
  docs/content/en/docs/quickstart/_index.md
  docs/content/en/docs/resources/_index.md
Labels: cla: yes, size/L

#6179 Move kubectl CLI from Runner to Deployer
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/log/provider.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/runner.go
  pkg/skaffold/sync/provider.go
Labels: cla: yes, size/M

#6163 hooks: add hooks execution environment variables
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/hooks/env.go
  pkg/skaffold/hooks/env_test.go
  pkg/skaffold/runner/runcontext/context.go
  testutil/util.go
Labels: cla: yes, size/L

#6175 [cherry-pick] Add v2 events for renderer.
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/constants/constants.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/event_test.go
  pkg/skaffold/event/v2/metadata.go
  pkg/skaffold/event/v2/metadata_test.go
  pkg/skaffold/event/v2/render.go
  pkg/skaffold/event/v2/render_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/XXL

#6186 design proposal to show user survey other than Hats
  docs/design_proposals/user_survey_hooks.md
Labels: cla: yes, size/L

#6185 Add survey config and framework to show feature surveys to skaffold users.
  cmd/skaffold/app/cmd/survey.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/constants/constants.go
  pkg/skaffold/survey/config.go
  pkg/skaffold/survey/config_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: cla: yes, size/L

#6181 Propagate kaniko environment to GCB
  pkg/skaffold/build/gcb/kaniko.go
  pkg/skaffold/build/gcb/kaniko_test.go
Labels: cla: yes, size/S

#6157 Added template expansion for helm chart version (#5709)
  docs/content/en/docs/environment/templating.md
  pkg/skaffold/deploy/helm/args.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/M

#6187 refactor ShouldDisplaySurveyPrompt from config package to survey
  cmd/skaffold/app/cmd/cmd.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
  pkg/skaffold/timeutil/util.go
  pkg/skaffold/timeutil/util_test.go
Labels: cla: yes, size/L

#6191 refactor: Read globalConfig instead of kubecontext config for survey config
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: cla: yes, size/L

#6192 Don't update survey prompt if survey prompt is not shown to stdout
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: cla: yes, size/M

#6193 refactor rename method UpdateHaTSSurveyTaken
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/survey/survey.go
Labels: cla: yes, size/XS

#6194 Fix survey active logic
  pkg/skaffold/survey/config.go
  pkg/skaffold/survey/config_test.go
Labels: cla: yes, size/M

#6136 Replace missing template values with empty string
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/util/env_template.go
  pkg/skaffold/util/env_template_test.go
Labels: cla: yes, size/M

#6190 [refactor] Remove Provider Interface
  integration/render_test.go
  pkg/skaffold/access/provider.go
  pkg/skaffold/debug/provider.go
  pkg/skaffold/deploy/component/kubernetes/accessor_test.go
  pkg/skaffold/deploy/component/kubernetes/component.go
  pkg/skaffold/deploy/component/kubernetes/debugger_test.go
  pkg/skaffold/deploy/component/kubernetes/monitor_test.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/loader/provider.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/status/provider.go
  pkg/skaffold/sync/kubectl.go
  pkg/skaffold/sync/provider.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/XL

#6188 Check release workflow
  .github/workflows/draft-release.yml
Labels: cla: yes, size/M

#6196 Add logic to show user survey in DisplaySurveyPrompt flow.
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/survey.go
  pkg/skaffold/config/global_config.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/survey/config.go
  pkg/skaffold/survey/config_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: cla: yes, size/L

#6170 Track deployment namespaces in Deployer
  pkg/skaffold/access/access.go
  pkg/skaffold/access/access_mux.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/debugger_mux.go
  pkg/skaffold/deploy/component/kubernetes/accessor_test.go
  pkg/skaffold/deploy/component/kubernetes/component.go
  pkg/skaffold/deploy/component/kubernetes/debugger_test.go
  pkg/skaffold/deploy/component/kubernetes/monitor_test.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/deploy/util/util_test.go
  pkg/skaffold/kubernetes/debugging/container_manager.go
  pkg/skaffold/kubernetes/debugging/container_manager_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/log/log.go
  pkg/skaffold/log/logger_mux.go
  pkg/skaffold/log/provider.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/notification.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
  pkg/skaffold/runner/util/util.go
  pkg/skaffold/runner/util/util_test.go
  pkg/skaffold/runner/v1/apply.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/runner_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/XL

#6202 Update feature maturities
  docs/data/maturity.json
Labels: cla: yes

#6204 release: v1.28.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes

#6117 [Docker Deployer] Add initial implementation of Docker Deployer
  docs/content/en/schemas/v2beta19.json
  integration/diagnose_test.go
  integration/examples/docker-deploy/Dockerfile
  integration/examples/docker-deploy/README.md
  integration/examples/docker-deploy/main.go
  integration/examples/docker-deploy/skaffold.yaml
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/schema/validation/samples_test.go
Labels: cla: yes, size/XL

#6214 Bump docker deploy config version to v2beta20
  docs/content/en/schemas/v2beta19.json
  docs/content/en/schemas/v2beta20.json
  integration/examples/docker-deploy/skaffold.yaml
Labels: cla: yes

#6177 hooks: implement build lifecycle hooks
  docs/content/en/schemas/v2beta20.json
  integration/examples/lifecycle-hooks/Dockerfile
  integration/examples/lifecycle-hooks/README.md
  integration/examples/lifecycle-hooks/hook.bat
  integration/examples/lifecycle-hooks/hook.sh
  integration/examples/lifecycle-hooks/k8s-pod.yaml
  integration/examples/lifecycle-hooks/main.go
  integration/examples/lifecycle-hooks/skaffold.yaml
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/hooks/build.go
  pkg/skaffold/hooks/build_test.go
  pkg/skaffold/hooks/host.go
  pkg/skaffold/hooks/host_test.go
  pkg/skaffold/hooks/types.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/XL

#6221 Remove Status Check task event, have Deploy task event contain status…
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes

#6213 Add --wait=false flag to skaffold cleanup kubectl delete to speedup the phase
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
Labels: cla: yes

#6226 Add prefix field to `ApplicationLogEvent`s
  pkg/skaffold/event/v2/application_logs.go
  pkg/skaffold/log/stream/stream.go
  pkg/skaffold/log/stream/stream_test.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes

#6222 Select color from ColorPicker using image instead of pod
  cmd/skaffold/app/cmd/util.go
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/util.go
  pkg/skaffold/kubernetes/colorpicker.go
  pkg/skaffold/kubernetes/colorpicker_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/output/color.go
  pkg/skaffold/output/colorpicker.go
  pkg/skaffold/tag/util/util.go
  pkg/skaffold/tag/util/util_test.go
Labels: cla: yes

#6211 added support for kaniko pushretry
  docs/content/en/schemas/v2beta20.json
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/kaniko/args.go
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes

#6227 Strip all formatting logic from LogAggregator into Formatter interface
  pkg/skaffold/kubernetes/logger/formatter.go
  pkg/skaffold/kubernetes/logger/formatter_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/log/formatter.go
  pkg/skaffold/log/stream/stream.go
  pkg/skaffold/log/stream/stream_test.go
  pkg/skaffold/output/colorpicker.go
Labels: cla: yes

#6208 Remove unneeded `Origin` field from `SkaffoldLogEvent`
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/event/v2/logger.go
  pkg/skaffold/event/v2/logger_test.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/v1/deploy.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes

#6220 hooks: implement sync phase lifecycle hooks (host and container)
  docs/content/en/schemas/v2beta20.json
  integration/examples/lifecycle-hooks/Dockerfile
  integration/examples/lifecycle-hooks/README.md
  integration/examples/lifecycle-hooks/hello.txt
  integration/examples/lifecycle-hooks/main.go
  integration/examples/lifecycle-hooks/skaffold.yaml
  pkg/skaffold/hooks/build_test.go
  pkg/skaffold/hooks/container.go
  pkg/skaffold/hooks/container_test.go
  pkg/skaffold/hooks/host_test.go
  pkg/skaffold/hooks/sync.go
  pkg/skaffold/hooks/sync_test.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/sync/sync.go
Labels: cla: yes

#6230 [v2] Update UX naming based on the feedback.
  pkg/skaffold/render/renderer/renderer_test.go
  pkg/skaffold/render/transform/transform.go
  pkg/skaffold/render/transform/transform_test.go
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes

#6218 Strip `out/` prefix from SHA checksum files
  Makefile
Labels: cla: yes

#6244 [v2] Add proto errors for kpt deployer v2
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  go.sum
  pkg/skaffold/deploy/v2/kpt/errors.go
  pkg/skaffold/deploy/v2/kpt/kpt.go
  pkg/skaffold/deploy/v2/kpt/kpt_test.go
  pkg/skaffold/schema/latest/v2/config.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes

#6237 [cherry-pick] [v2] Update UX naming based on the feedback. (#6230)
  pkg/skaffold/render/renderer/renderer_test.go
  pkg/skaffold/render/transform/transform.go
  pkg/skaffold/render/transform/transform_test.go
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes

#6232 [v2] Enable renderer in v2 Runner
  integration/test_test.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
  pkg/skaffold/runner/v2/new.go
  pkg/skaffold/runner/v2/render.go
  pkg/skaffold/runner/v2/runner.go
  pkg/skaffold/runner/v2/runner_test.go
Labels: cla: yes

#6210 add flag `sync-remote-cache`
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/init_test.go
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/config/repo_cache.go
  pkg/skaffold/config/repo_cache_test.go
  pkg/skaffold/git/errors.go
  pkg/skaffold/git/gitutil.go
  pkg/skaffold/git/gitutil_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes

#6241 Retrieve initial namespaces when creating Deployer
  integration/deploy_test.go
  integration/dev_test.go
  integration/run_test.go
  integration/sync_test.go
  integration/util.go
  pkg/skaffold/deploy/deploy_problems_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/types/types.go
  pkg/skaffold/deploy/util/namespaces.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes

#6215 Fix switched container/pod names in app log event
  pkg/skaffold/event/v2/application_logs.go
  pkg/skaffold/event/v2/application_logs_test.go
Labels: cla: yes

#6247 [cherry-pick] Fix Workdir error when --filename flag is used.
  pkg/skaffold/runner/runcontext/v2/context.go
  pkg/skaffold/runner/runcontext/v2/context_test.go
Labels: cla: yes

#6234 Set output event context in cache check, tag generation, status check, port forward
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/runner/build.go
Labels: cla: yes

#6250 Add `logrus` hook for sending `SkaffoldLogEvent`s
  cmd/skaffold/app/cmd/cmd.go
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/event/v2/logger.go
  pkg/skaffold/event/v2/logger_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes

#6252 [v2] Set v2 default renderer and deployer config.
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/parser/config_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes

#6256 Revert "[cherry-pick] Fix Workdir error when --filename flag is used. "
  pkg/skaffold/runner/runcontext/v2/context.go
  pkg/skaffold/runner/runcontext/v2/context_test.go
Labels: cla: yes

#6238 Make skaffold reproducible
  Makefile
Labels: cla: yes

#6201 Added developer journey tutorial
  docs/content/en/docs/tutorials/developer-journey.md
  examples/dev-journey-buildpacks/k8s/web.yaml
  examples/dev-journey-buildpacks/pom.xml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/dev-journey-buildpacks/src/main/java/hello/Application.java
  examples/dev-journey-buildpacks/src/main/java/hello/HelloController.java
  examples/dev-journey-buildpacks/start.sh
  examples/dev-journey-buildpacks/tutorial.md
  integration/examples/dev-journey-buildpacks/k8s/web.yaml
  integration/examples/dev-journey-buildpacks/pom.xml
  integration/examples/dev-journey-buildpacks/skaffold.yaml
  integration/examples/dev-journey-buildpacks/src/main/java/hello/Application.java
  integration/examples/dev-journey-buildpacks/src/main/java/hello/HelloController.java
  integration/examples/dev-journey-buildpacks/start.sh
  integration/examples/dev-journey-buildpacks/tutorial.md
Labels: cla: yes, size/S

#6266 Add ContainerTracker for tracking deployed docker containers
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/docker/tracker/tracker.go
  pkg/skaffold/docker/tracker/tracker_test.go
Labels: cla: yes

#6275 Remove log tail test for nodejs example
  integration/run_test.go
Labels: cla: yes, size/XS

#6274 `git fetch` origin/main before `make checks`
  .travis.yml
Labels: cla: yes, size/XS

#6276 Port `DebuggingContainerEvent`s from API V1 to V2
  pkg/skaffold/event/v2/debugging.go
  pkg/skaffold/event/v2/debugging_test.go
  pkg/skaffold/kubernetes/debugging/container_manager.go
  pkg/skaffold/kubernetes/debugging/container_manager_test.go
Labels: cla: yes, size/L

#6265 Implement Logger for Docker Deployer
  integration/examples/docker-deploy/README.md
  integration/examples/docker-deploy/bert/Dockerfile
  integration/examples/docker-deploy/bert/main.go
  integration/examples/docker-deploy/ernie/Dockerfile
  integration/examples/docker-deploy/ernie/main.go
  integration/examples/docker-deploy/skaffold.yaml
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/logger/formatter.go
  pkg/skaffold/docker/logger/formatter_test.go
  pkg/skaffold/docker/logger/log.go
  pkg/skaffold/docker/logger/log_test.go
Labels: cla: yes, size/L

#6261 [v2] Enable `skaffold dev`
  hack/versions/pkg/schema/check.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/deploy/v2/kpt/kpt.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/renderer_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/runcontext/v2/context.go
  pkg/skaffold/runner/runcontext/v2/context_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/v2/cleanup.go
  pkg/skaffold/runner/v2/deploy.go
  pkg/skaffold/runner/v2/deploy_test.go
  pkg/skaffold/runner/v2/dev.go
  pkg/skaffold/runner/v2/dev_test.go
  pkg/skaffold/runner/v2/load_images.go
  pkg/skaffold/runner/v2/load_images_test.go
  pkg/skaffold/runner/v2/new.go
  pkg/skaffold/runner/v2/render.go
  pkg/skaffold/runner/v2/runner.go
  pkg/skaffold/runner/v2/runner_test.go
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes, size/XXL

#6280 Update deps and restore k3d tests
  .travis.yml
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/M

#6270 [v2] Enable the helm in `.manifests.generate` (bypass kpt fn)
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes, size/L

#6277 [v2] Add renderer manifests as dependencies
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/generate_test.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/runner/timings_test.go
  pkg/skaffold/runner/v2/dev.go
  pkg/skaffold/runner/v2/runner_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes, size/XL

#6269 fix remote branch lookup
  pkg/skaffold/git/gitutil.go
  pkg/skaffold/git/gitutil_test.go
Labels: cla: yes

#6295 Prefix port forward links with `http://`
  pkg/skaffold/kubernetes/portforward/entry_manager.go
Labels: cla: yes, size/XS

#6296 Remove skaffoldLogs endpoint, consolidate into events endpoint
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/logger_test.go
  pkg/skaffold/server/v2/endpoints.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.pb.gw.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/L

#6272 Add state to event handler to track `logrus` output events
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/logger.go
Labels: cla: yes, size/S

#6294 skip manifest validation for default `kubectl deployer`
  pkg/skaffold/schema/validation/validation.go
Labels: cla: yes, size/XS

#6299 Fix tail false but still log issue
  pkg/skaffold/kubernetes/logger/log.go
Labels: cla: yes, size/XS

#6304 Bump cloud.google.com/go 0.84.0 => 0.88.0
  go.mod
  go.sum
Labels: cla: yes, size/XS

#6305 Bump github.com/bmatcuk/doublestar v1.2.4 => v1.3.4
  go.mod
  go.sum
Labels: cla: yes, size/XS

#6306 Revert "Add state to event handler to track `logrus` output events"
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/logger.go
Labels: cla: yes, size/S

#6311 Pin `go-licenses` version to avoid go 1.16.x dependencies
  hack/generate-statik.sh
Labels: cla: yes, size/XS

#6309 Add `logrus.Logger` return type on `WithEventContext()`
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/S

#6313 Give `logrus.Hook` implementation information about task and subtask
  cmd/skaffold/app/cmd/cmd.go
  pkg/skaffold/event/v2/logger.go
Labels: !! do-not-merge !!, cla: yes, size/S

#6318 Bump github.com/go-git/go-git/v5 v5.0.0 => v5.4.2
  go.mod
  go.sum
Labels: cla: yes, size/XS

#6317 Bump github.com/AlecAivazis/survey/v2 v2.2.14 => v2.2.15
  go.mod
  go.sum
Labels: cla: yes, size/XS

#6319 Bump google.golang.org/api v0.50.0 => v0.51.0
  go.mod
  go.sum
Labels: cla: yes, size/XS

#6320 Bump github.com/google/uuid v1.1.2 => v1.3.0
  go.mod
  go.sum
Labels: cla: yes, size/XS

#6303 Implement port forwarding for Docker deployer
  docs/content/en/schemas/v2beta20.json
  integration/diagnose_test.go
  integration/examples/react-reload-docker/README.md
  integration/examples/react-reload-docker/app/.babelrc
  integration/examples/react-reload-docker/app/.dockerignore
  integration/examples/react-reload-docker/app/.gitignore
  integration/examples/react-reload-docker/app/Dockerfile
  integration/examples/react-reload-docker/app/package.json
  integration/examples/react-reload-docker/app/src/components/HelloWorld.js
  integration/examples/react-reload-docker/app/src/index.html
  integration/examples/react-reload-docker/app/src/main.js
  integration/examples/react-reload-docker/app/src/styles/HelloWorld.css
  integration/examples/react-reload-docker/app/webpack.config.js
  integration/examples/react-reload-docker/k8s/deployment.yaml
  integration/examples/react-reload-docker/skaffold.yaml
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/docker/port.go
  pkg/skaffold/deploy/docker/port_test.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/logger/formatter_test.go
  pkg/skaffold/docker/tracker/tracker.go
  pkg/skaffold/docker/tracker/tracker_test.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/schema/validation/samples_test.go
  pkg/skaffold/schema/validation/validation.go
Labels: cla: yes, size/XL

#6331 fix: kubeContext override via flag
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/XS

#6328 Implement file sync for Docker deployer
  integration/examples/react-reload-docker/skaffold.yaml
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/sync/docker.go
  pkg/skaffold/sync/docker_test.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/L

#6330 add documentation for `lifecycle hooks`
  docs/content/en/docs/pipeline-stages/_index.md
  docs/content/en/docs/pipeline-stages/lifecycle-hooks.md
  docs/data/maturity.json
Labels: cla: yes, size/L

#6298 [v2] remove unused v2 flag
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
Labels: cla: yes, size/S

#6297 [v2] Enable kubectl deployer in v2.
  integration/render_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/v2/kpt/kpt.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/v2/new.go
Labels: cla: yes, size/L
