Repository GoogleContainerTools/skaffold, pull requests merged in 2021-05, with the labels that each got.

#5770 disable housekeeping messages for render
  cmd/skaffold/app/cmd/render.go
Labels: cla: yes, size/XS

#5757 update otel libs from v0.13.0 -> v0.20.0
  go.mod
  go.sum
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
Labels: cla: yes, size/L

#5765 Add `skaffold inspect` command
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/config.go
  cmd/skaffold/app/cmd/inspect.go
  cmd/skaffold/app/cmd/inspect_modules.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/inspect/modules.go
  pkg/skaffold/inspect/modules_test.go
  pkg/skaffold/inspect/output.go
  pkg/skaffold/inspect/types.go
  pkg/skaffold/parser/config.go
  pkg/skaffold/parser/types.go
Labels: cla: yes, size/L

#5725 Ensure working JVM before enabling Jib actions to avoid hangs
  integration/build_test.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/jib/init.go
  pkg/skaffold/build/jib/jib.go
  pkg/skaffold/build/jib/jvm.go
  pkg/skaffold/build/jib/jvm_test.go
Labels: cla: yes, size/L

#5718 bring back error coloring
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/skaffold.go
  pkg/skaffold/color/formatter.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/util/tar.go
  pkg/skaffold/util/tar_test.go
  pkg/skaffold/util/term.go
  pkg/skaffold/util/term_test.go
Labels: cla: yes, size/L

#5786 Emit TaskEvent protos for Test phase
  pkg/skaffold/runner/tester.go
Labels: cla: yes, size/XS

#5648 Fix setting helm `--setFiles` for Windows
  pkg/skaffold/deploy/helm/args.go
  pkg/skaffold/deploy/helm/args_test.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/L

#5779 move profile verification higher up the stack
  cmd/skaffold/app/cmd/runner_test.go
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/parser/config.go
  pkg/skaffold/parser/config_test.go
  pkg/skaffold/schema/errors/errors.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes

#5780 [V3] (part 1) Change runner/v3 to runner/v2. Update v3 flag to v2
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/runner/v2/apply.go
  pkg/skaffold/runner/v2/cleanup.go
  pkg/skaffold/runner/v2/deploy.go
  pkg/skaffold/runner/v2/dev.go
  pkg/skaffold/runner/v2/generate_pipeline.go
  pkg/skaffold/runner/v2/render.go
  pkg/skaffold/runner/v2/runner.go
Labels: area/v3, cla: yes, size/M

#5578 Default digest source to 'remote' in render
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/render.go
  docs/content/en/docs/references/cli/_index.md
  integration/apply_test.go
  integration/debug_test.go
  integration/filter_test.go
  integration/render_test.go
  integration/run_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/render.go
Labels: cla: yes, size/L

#5653 Don't add skaffold labels by default in render, and deprecate the --add-skaffold-labels flag
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/deprecation.md
Labels: cla: yes, size/S

#5791 Resolve all filepaths to absolute in 'skaffold diagnose'
  cmd/skaffold/app/cmd/diagnose.go
  pkg/skaffold/config/options.go
  pkg/skaffold/diagnose/diagnose_test.go
  pkg/skaffold/parser/config.go
Labels: cla: yes, size/XS

#5783 Emit deploy subtask events for API V2
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/event/v2/deploy.go
  pkg/skaffold/event/v2/deploy_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/new_test.go
Labels: cla: yes, size/L

#5752 Update _index.md
  docs/content/en/docs/pipeline-stages/_index.md
Labels: cla: yes, size/XS

#5777 Update examples/typescript w/ recommended ENV=production info
  examples/typescript/README.md
  integration/examples/typescript/README.md
Labels: cla: yes, size/XS

#5772 typo-fix
  docs/content/en/docs/pipeline-stages/builders/custom.md
Labels: cla: yes, size/XS

#5781 [v3] (part 2) Move the v1 runner components to `pkg/skaffold/runner/v1`.
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/builder.go
  pkg/skaffold/runner/changeset.go
  pkg/skaffold/runner/intent.go
  pkg/skaffold/runner/listen.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/tester.go
  pkg/skaffold/runner/v1/apply.go
  pkg/skaffold/runner/v1/build_deploy_test.go
  pkg/skaffold/runner/v1/cleanup.go
  pkg/skaffold/runner/v1/debugging.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/dev_test.go
  pkg/skaffold/runner/v1/generate_pipeline.go
  pkg/skaffold/runner/v1/load_images.go
  pkg/skaffold/runner/v1/load_images_test.go
  pkg/skaffold/runner/v1/logger.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/new_test.go
  pkg/skaffold/runner/v1/portforwarder.go
  pkg/skaffold/runner/v1/render.go
  pkg/skaffold/runner/v1/runner.go
  pkg/skaffold/runner/v1/runner_test.go
  pkg/skaffold/runner/v2/runner.go
Labels: area/v3, cla: yes, size/XL

#5730 Default to empty secret path for Kaniko to use Workload Identity credentials
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
Labels: cla: yes, size/S

#5741 Simplify update check
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/cmd_test.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/prompt.go
  pkg/skaffold/util/http.go
  pkg/skaffold/util/http_test.go
  pkg/skaffold/version/version.go
  pkg/skaffold/version/version_test.go
Labels: cla: yes, size/L

#5801 Fix flake: Don't rely on variable `allProblems` in test
  pkg/skaffold/build/build_problems.go
  pkg/skaffold/build/build_problems_test.go
  pkg/skaffold/deploy/deploy_problems.go
  pkg/skaffold/deploy/deploy_problems_test.go
  pkg/skaffold/errors/errors.go
  pkg/skaffold/errors/problem.go
  pkg/skaffold/errors/problem_catalog.go
  pkg/skaffold/initializer/init_problems.go
  pkg/skaffold/initializer/init_problems_test.go
Labels: cla: yes, size/L

#5776 Use default deployer in 'skaffold apply'
  integration/apply_test.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/new_test.go
Labels: cla: yes, size/M

#5809 Embed Logger inside Deployer
  integration/render_test.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/kubernetes/colorpicker.go
  pkg/skaffold/kubernetes/colorpicker_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/log/log.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/new_test.go
  pkg/skaffold/runner/v1/runner_test.go
  pkg/skaffold/update/foo
Labels: cla: yes, size/L

#5808 Add support for Port forwarding with namespaces with Templated Fields
  docs/content/en/docs/environment/templating.md
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
Labels: cla: yes, size/M

#5825 Add kpt v1.0.0-alpha.2 to Skaffold image
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/S

#5804 Avoid aliasing in image configuration
  pkg/skaffold/debug/debug.go
Labels: cla: yes, size/S

#5829 emit applicationLogEvents on event endpoint
  pkg/skaffold/event/v2/application_logs.go
  pkg/skaffold/event/v2/application_logs_test.go
  pkg/skaffold/kubernetes/logger/log.go
Labels: cla: yes, size/M

#5826 Embed PortForwarder in Deployer, rename to ResourcePreviewer
  integration/render_test.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/preview/preview.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/new_test.go
  pkg/skaffold/runner/v1/portforwarder.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: cla: yes, size/L

#5828 Expose --event-log-file to render, apply, and test
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/S

#5823 [v3] add design doc for the new render and deploy
  docs/design_proposals/images/basic-workflow.png
  docs/design_proposals/images/builtin-render.png
  docs/design_proposals/images/cmd-lifecycle.png
  docs/design_proposals/images/deploy-cmd.png
  docs/design_proposals/images/deploy-operation.png
  docs/design_proposals/images/deployer-enabled-ops.png
  docs/design_proposals/images/helm-migration.png
  docs/design_proposals/images/helm-phase2.png
  docs/design_proposals/images/helm-step1.png
  docs/design_proposals/images/helm-step2.png
  docs/design_proposals/images/helm-step3.png
  docs/design_proposals/images/kpt-managed-mode.png
  docs/design_proposals/images/kustomize-migration.png
  docs/design_proposals/images/kustomize-phase2.png
  docs/design_proposals/images/new-workflow.png
  docs/design_proposals/images/render-cmd.png
  docs/design_proposals/new-render-and-deploy.md
Labels: cla: yes

#5846 propagate profiles across imported configs by default; disable using `propagate-profiles` flag
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/design/config.md
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/parser/config.go
  pkg/skaffold/parser/config_test.go
Labels: cla: yes, size/L

#5848 add explicit error code `UNKNOWN_API_VERSION`
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/schema/errors/errors.go
  pkg/skaffold/schema/versions.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes

#5858 Fix 5840
  integration/render_test.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/kubernetes/colorpicker.go
  pkg/skaffold/kubernetes/colorpicker_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/preview/preview.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/logger.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/new_test.go
  pkg/skaffold/runner/v1/portforwarder.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: cla: yes, size/XL

#5859 release: v1.24.1
  CHANGELOG.md
Labels: cla: yes, size/M

#5861 fix: setting default deployer definition
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes, size/M

#5759 Debug support for pydevd, new --protocols debug flag
  cmd/skaffold/app/cmd/debug.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_netcore.go
  pkg/skaffold/debug/transform_netcore_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
Labels: cla: yes, planning/Q2-21, size/L

#5868 Move application logs to their own endpoint for API V2
  pkg/skaffold/event/v2/application_logs_test.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/server/v2/endpoints.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.pb.gw.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/L

#5872 Fix yaml reference rendering for object-type examples
  docs/content/en/docs/references/yaml/main.js
Labels: area/yaml-docs, cla: yes, size/XS

#5883 Add .NET .csproj detection to init for buildpacks
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
Labels: cla: yes, size/XS

#5881 Update go-containerregistry to 0.5.1
  go.mod
  go.sum
Labels: cla: yes, size/XS

#5891 Failing to delete source archive should not fail GCB builds
  pkg/skaffold/build/gcb/cloud_build.go
Labels: cla: yes, size/S

#5890 Refactor metrics prompt functions and change `color` package name
  .gitignore
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/find_configs.go
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/generate_pipeline.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/tips/tips.go
  cmd/skaffold/skaffold.go
  hack/versions/cmd/new/version.go
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/maven.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/result.go
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/util/logfile.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/generate_pipeline/profile.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/prompt/prompt.go
  pkg/skaffold/instrumentation/prompt/prompt_test.go
  pkg/skaffold/kubernetes/colorpicker.go
  pkg/skaffold/kubernetes/colorpicker_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/output/color.go
  pkg/skaffold/output/color_test.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/generate_pipeline.go
  pkg/skaffold/runner/v1/load_images.go
  pkg/skaffold/runner/v1/render.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/test/custom/custom.go
  pkg/skaffold/test/test_factory.go
  pkg/skaffold/trigger/fsnotify/trigger.go
  pkg/skaffold/trigger/triggers.go
Labels: cla: yes, size/L

#5882 Update pack 0.18.1
  deploy/buildpacks/Dockerfile
  deploy/buildpacks/publish.sh
  deploy/buildpacks/third_party/entrypoint.sh
  go.mod
  go.sum
Labels: cla: yes, size/M

#5876 Schemas should emit type=object for object
  docs/content/en/schemas/v1.json
  docs/content/en/schemas/v1alpha1.json
  docs/content/en/schemas/v1alpha2.json
  docs/content/en/schemas/v1alpha3.json
  docs/content/en/schemas/v1alpha4.json
  docs/content/en/schemas/v1alpha5.json
  docs/content/en/schemas/v1beta1.json
  docs/content/en/schemas/v1beta10.json
  docs/content/en/schemas/v1beta11.json
  docs/content/en/schemas/v1beta12.json
  docs/content/en/schemas/v1beta13.json
  docs/content/en/schemas/v1beta14.json
  docs/content/en/schemas/v1beta15.json
  docs/content/en/schemas/v1beta16.json
  docs/content/en/schemas/v1beta17.json
  docs/content/en/schemas/v1beta2.json
  docs/content/en/schemas/v1beta3.json
  docs/content/en/schemas/v1beta4.json
  docs/content/en/schemas/v1beta5.json
  docs/content/en/schemas/v1beta6.json
  docs/content/en/schemas/v1beta7.json
  docs/content/en/schemas/v1beta8.json
  docs/content/en/schemas/v1beta9.json
  docs/content/en/schemas/v2alpha1.json
  docs/content/en/schemas/v2alpha2.json
  docs/content/en/schemas/v2alpha3.json
  docs/content/en/schemas/v2alpha4.json
  docs/content/en/schemas/v2beta1.json
  docs/content/en/schemas/v2beta10.json
  docs/content/en/schemas/v2beta11.json
  docs/content/en/schemas/v2beta12.json
  docs/content/en/schemas/v2beta13.json
  docs/content/en/schemas/v2beta14.json
  docs/content/en/schemas/v2beta15.json
  docs/content/en/schemas/v2beta16.json
  docs/content/en/schemas/v2beta2.json
  docs/content/en/schemas/v2beta3.json
  docs/content/en/schemas/v2beta4.json
  docs/content/en/schemas/v2beta5.json
  docs/content/en/schemas/v2beta6.json
  docs/content/en/schemas/v2beta7.json
  docs/content/en/schemas/v2beta8.json
  docs/content/en/schemas/v2beta9.json
  hack/schemas/main.go
  hack/schemas/testdata/inline-anyof/output.json
  hack/schemas/testdata/inline-hybrid/output.json
  hack/schemas/testdata/inline/output.json
  hack/schemas/testdata/integer/output.json
Labels: cla: yes, size/XXL

#5793 [V3] add renderer basic struct.
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/renderer_test.go
  testutil/util.go
Labels: cla: yes, size/L

#5905 Rework `debug` docs and add small section on troubleshooting
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/L

#5901 Improve documentation of docker buildArgs (#5871)
  docs/content/en/schemas/v2beta16.json
  pkg/skaffold/docker/build_args_test.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/M

#5911 Container Structure Test page should use `skaffold test`
  docs/content/en/docs/pipeline-stages/testers/structure.md
Labels: cla: yes, size/XS

#5912 Add missing flags to `skaffold test`
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/S

#5906 Pass kubeconfig to `kpt live`
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
Labels: cla: yes, size/M
