Repository GoogleContainerTools/skaffold, pull requests merged in 2021-01, with the labels that each got.

#5202 CNCF Buildpacks => Cloud Native Buildpacks
  ROADMAP.md
Labels: cla: yes, size/XS

#5196 yaml encoders should be flushed.
  pkg/skaffold/yaml/yaml.go
Labels: cla: yes, size/XS

#5190 Add the test command to the dev loop
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/dev.go
Labels: cla: yes, size/M

#5212 Update boilerplate.py year check.
  hack/boilerplate/boilerplate.py
Labels: cla: yes, size/XS

#5199 Allow multiple configs in single skaffold.yaml
  pkg/skaffold/schema/versions.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/L

#5215 Update Skaffold dependencies
  Makefile
  deploy/buildpacks/publish.sh
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/M

#5225 Fix port forward
  integration/examples/microservices-docker/docker-compose.yml
Labels: size/XS

#5226 [feature] Implement local docker deployment
  go.mod
  integration/examples/docker-deploy/skaffold.yaml
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/docker/log.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/log/logger.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/L

#5222 [doc] fix profile activation sample
  docs/content/en/samples/profiles/activations.yaml
Labels: cla: yes, size/XS

#5223 Update jib to 2.7.1
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#5211 some fixes on documents
  docs/content/en/docs/pipeline-stages/init.md
  docs/content/en/docs/workflows/dev.md
Labels: cla: yes, size/XS

#5203 Release automation changes
  .github/workflows/draft-release.yml
Labels: cla: yes, size/M

#5227 Feature/docker deploy
  integration/examples/docker-deploy/skaffold.yaml
  integration/examples/microservices-docker/docker-compose.yml
  integration/examples/microservices-docker/leeroy-app/kubernetes/deployment.yaml
  integration/examples/microservices-docker/leeroy-web/kubernetes/deployment.yaml
  integration/examples/microservices-docker/skaffold.yaml
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
Labels: cla: yes, size/L

#5219 Modify Travis directive restricting builds to master
  .travis.yml
Labels: cla: yes, size/S

#5229 Feature/docker deploy
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/runner/portforwarder.go
Labels: cla: yes, size/M

#5230 fix bad merge
  pkg/skaffold/deploy/docker/deploy.go
Labels: cla: yes, size/XS

#5232 Implement container sync for docker deployer.
  integration/examples/react-reload-docker/README.md
  integration/examples/react-reload-docker/app/.babelrc
  integration/examples/react-reload-docker/app/.dockerignore
  integration/examples/react-reload-docker/app/.gitignore
  integration/examples/react-reload-docker/app/Dockerfile
  integration/examples/react-reload-docker/app/package.json
  integration/examples/react-reload-docker/app/src/components/HelloWorld.js
  integration/examples/react-reload-docker/app/src/index.html
  integration/examples/react-reload-docker/app/src/main.js
  integration/examples/react-reload-docker/app/src/styles/HelloWorld.css
  integration/examples/react-reload-docker/app/webpack.config.js
  integration/examples/react-reload-docker/skaffold.yaml
  pkg/skaffold/sync/docker.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/L

#5234 Implement docker logging
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/docker/log.go
  pkg/skaffold/deploy/docker/tracker.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/kubernetes/log.go
  pkg/skaffold/log/logger.go
  pkg/skaffold/log/util.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/logger.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/L

#5236 Fix container cleanup
  pkg/skaffold/deploy/docker/deploy.go
Labels: cla: yes, size/XS

#5235 Implement debugging for docker deploy
  pkg/skaffold/debug/docker_adapter.go
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/docker/image.go
Labels: cla: yes, size/L

#5177 Ensure init generates /-delimted paths
  pkg/skaffold/build/buildpacks/init.go
  pkg/skaffold/build/buildpacks/init_test.go
  pkg/skaffold/build/jib/init.go
  pkg/skaffold/build/jib/init_test.go
  pkg/skaffold/docker/docker_init.go
  pkg/skaffold/docker/docker_init_test.go
  pkg/skaffold/initializer/analyze/analyze.go
  pkg/skaffold/initializer/analyze/builder.go
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/build/util.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/testdata/init/windows/apps/web/build/Dockerfile
  pkg/skaffold/initializer/testdata/init/windows/apps/web/deployment.yaml
  pkg/skaffold/initializer/testdata/init/windows/apps/web/web.go
  pkg/skaffold/initializer/testdata/init/windows/skaffold.yaml
Labels: cla: yes, size/L

#5205 Add go tag `filepath` that converts marked fields to absolute paths
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/tags/paths.go
  pkg/skaffold/tags/paths_test.go
  pkg/skaffold/tags/paths_windows_test.go
  pkg/skaffold/trigger/fsnotify/trigger.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/workdir.go
Labels: cla: yes, size/L

#5237 Enable MTU path discovery on Linux and setup registry-mirrors for kind
  .travis.yml
  Makefile
  hack/generate-kind-config.sh
Labels: cla: yes, size/M

#5079 Fix for humanize time in #5005
  integration/skaffold/helper.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/load_images.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: cla: yes, size/L

#5238 Fix github action script
  .github/workflows/draft-release.yml
Labels: cla: yes, size/XS

#5220 Avoid possible hang in util.RunCmdOut by using byte buffers instead of pipes
  pkg/skaffold/util/cmd.go
Labels: cla: yes, size/M

#5247 change default status check timeout to 10 minutes
  pkg/skaffold/deploy/status/status_check.go
Labels: cla: yes, size/XS

#5254 Include commands and directory in run output
  integration/skaffold/helper.go
Labels: cla: yes, size/S

#5251 Configure maven connection pool TTL to avoid connection resets from stale connections
  integration/examples/buildpacks-java/.mvn/jvm.config
  integration/examples/jib-multimodule/.mvn/jvm.config
  integration/examples/jib-multimodule/.mvn/wrapper/maven-wrapper.properties
  integration/examples/jib-sync/.mvn/jvm.config
  integration/examples/jib-sync/.mvn/wrapper/maven-wrapper.properties
  integration/examples/jib/.mvn/wrapper/maven-wrapper.properties
  integration/testdata/debug/java/.mvn/jvm.config
  integration/testdata/debug/java/.mvn/wrapper/maven-wrapper.properties
  integration/testdata/jib/.mvn/jvm.config
  integration/testdata/jib/.mvn/wrapper/maven-wrapper.properties
Labels: cla: yes, size/S

#5252 Fix test timeout failures in TestDebug/helm
  integration/util.go
Labels: cla: yes, size/S

#5256 Use gcr.io/google-appengine/openjdk:8 to avoid toomanyrequests
  integration/testdata/debug/java/pom.xml
Labels: cla: yes, size/XS

#5186 Add transparent init
  cmd/skaffold/app/cmd/build.go
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/debug_test.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/filter.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/generate_pipeline.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/run_test.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/runner_test.go
  cmd/skaffold/app/cmd/test.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/initializer/transparent.go
  pkg/skaffold/initializer/transparent_test.go
Labels: cla: yes, size/L

#5233 Create nsis installer script
  installers/windows/skaffold.nsi
Labels: cla: yes, size/L

#5250 Fix statik directory structure
  .gitignore
  cmd/skaffold/app/secret/statik/fs.go
  hack/generate-statik.sh
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/meter_test.go
Labels: cla: yes, size/M

#5262 Go 1.12 is not supported by Delve 1.5.x
  integration/examples/helm-deployment/Dockerfile
Labels: cla: yes, size/XS

#5217 Config dependencies
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/parse_config.go
  cmd/skaffold/app/cmd/parse_config_test.go
  cmd/skaffold/app/cmd/runner.go
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/schemas/v2beta11.json
  integration/examples/microservices/skaffold.yaml
  integration/examples/multi-config-microservices/README.md
  integration/examples/multi-config-microservices/base/Dockerfile
  integration/examples/multi-config-microservices/base/skaffold.yaml
  integration/examples/multi-config-microservices/leeroy-app/Dockerfile
  integration/examples/multi-config-microservices/leeroy-app/app.go
  integration/examples/multi-config-microservices/leeroy-app/kubernetes/deployment.yaml
  integration/examples/multi-config-microservices/leeroy-app/skaffold.yaml
  integration/examples/multi-config-microservices/leeroy-web/Dockerfile
  integration/examples/multi-config-microservices/leeroy-web/kubernetes/deployment.yaml
  integration/examples/multi-config-microservices/leeroy-web/skaffold.yaml
  integration/examples/multi-config-microservices/leeroy-web/web.go
  integration/examples/multi-config-microservices/skaffold.yaml
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/generate_pipeline.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/samples_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/schema/versions_test.go
Labels: cla: yes, size/XXL

#5258 fix termination event not being sent
  pkg/skaffold/errors/errors.go
  pkg/skaffold/event/event.go
Labels: cla: yes, size/S

#5267 Fix race condition when running tests for pkg/skaffold/instrumentation
  cmd/skaffold/skaffold.go
  pkg/skaffold/instrumentation/meter.go
Labels: cla: yes, size/XS

#5268 Configure Maven Wagon HTTP to retry on errors to successful connections
  integration/examples/buildpacks-java/.mvn/jvm.config
  integration/examples/jib-multimodule/.mvn/jvm.config
  integration/examples/jib-sync/.mvn/jvm.config
  integration/testdata/debug/java/.mvn/jvm.config
  integration/testdata/jib/.mvn/jvm.config
Labels: cla: yes, size/S

#5269 escape backticks in commit message
  .github/workflows/draft-release.yml
Labels: cla: yes, size/XS

#5274 group all configs in each example project prior to validation test.
  pkg/skaffold/schema/samples_test.go
  pkg/skaffold/walk/walk.go
Labels: cla: yes, size/M

#5277 remove `$`in regex match for github action
  .github/workflows/draft-release.yml
Labels: cla: yes, size/XS

#5272 write credits to directory specified by -d
  cmd/skaffold/app/cmd/credits/export.go
  integration/credits_test.go
Labels: cla: yes, size/S

#5270 substitute periods in sanitizeImageName()
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/build/resolve_test.go
Labels: cla: yes, size/M

#5276 Improve `completion` missing-arg help text
  cmd/skaffold/app/cmd/completion.go
Labels: cla: yes, size/XS

#5282 readability changes to init docs
  docs/content/en/docs/pipeline-stages/init.md
Labels: cla: yes, size/S

#5172 Skaffold proto updates for adding the test command to the dev loop.
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: area/testing, cla: yes

#5294 enable local search for skaffold remove ads
  docs/config.toml
Labels: cla: yes, size/XS

#5290 Fixes for generating new schema version
  cmd/skaffold/app/cmd/parse_config_test.go
  hack/versions/cmd/new/version.go
  pkg/skaffold/walk/walk.go
Labels: cla: yes, size/S

#5291 Add missing fields to global config doc
  docs/content/en/docs/design/global-config.md
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/S

#5281 Create documentation surrounding telemetry collection
  Makefile
  docs/content/en/docs/resources/telemetry/_index.md
  docs/content/en/docs/resources/telemetry/main.js
  docs/content/en/docs/resources/telemetry/metrics.json
  hack/struct-json/main.go
  pkg/skaffold/instrumentation/meter.go
Labels: cla: yes, size/L

#5298 specify FlagAddMethod on artifact and kubernetes-manifest flags
  cmd/skaffold/app/cmd/init.go
Labels: cla: yes, size/XS

#5295 add --generate-manifests section to init docs
  docs/content/en/docs/pipeline-stages/init.md
  docs/data/maturity.json
Labels: cla: yes, size/S

#5299 wip: disable google search to use offline search
  deploy/webhook/Dockerfile
  docs/config.toml
Labels: cla: yes, size/XS

#5306 Fix up `debug` test's kustomize profile to remove the `kubectl` deployer
  integration/testdata/debug/skaffold.yaml
Labels: cla: yes, size/XS

#5288 add collect metrics to the global config
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/skaffold.go
  pkg/skaffold/config/global_config.go
  pkg/skaffold/config/util.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/prompt.go
  pkg/skaffold/instrumentation/prompt_test.go
Labels: cla: yes, size/L

#5280 Change cloud build release script to pull metric credentials keys for release
  deploy/cloudbuild-release.yaml
  deploy/cloudbuild.yaml
  deploy/skaffold/Dockerfile
Labels: cla: yes, size/S

#5297 Add timestamps to tool output if --timestamp flag is set
  cmd/skaffold/app/cmd/cmd.go
Labels: cla: yes, size/XS

#5304 Minor doc updates to Telemetry
  docs/content/en/docs/resources/telemetry/_index.md
  docs/content/en/docs/resources/telemetry/metrics.json
  pkg/skaffold/instrumentation/meter.go
Labels: cla: yes, size/L

#5311 Mark _index.md pages with `no_list` to prevent subpage panel generation
  docs/content/en/docs/_index.md
  docs/content/en/docs/environment/_index.md
  docs/content/en/docs/pipeline-stages/_index.md
  docs/content/en/docs/pipeline-stages/builders/_index.md
  docs/content/en/docs/pipeline-stages/deployers/_index.md
  docs/content/en/docs/references/_index.md
  docs/content/en/docs/resources/_index.md
  docs/content/en/docs/workflows/getting-started-with-your-project.md
Labels: area/docs, cla: yes, size/XS

#5313 print otel errors with logrus instead of straight to stderr
  pkg/skaffold/instrumentation/meter.go
Labels: cla: yes, size/XS

#5305 run ./hack/generate-man.sh automatically in ./hack/new_version.sh
  hack/new_version.sh
Labels: cla: yes, size/XS

#5314 fix cloudbuild release to re-genreate secret and upload it to a GCS bucket
  deploy/cloudbuild-release.yaml
  deploy/setup-secret.sh
Labels: cla: yes, size/M

#5316 release: v1.19.0
  CHANGELOG.md
Labels: cla: yes, draft-release, size/M

#5312 Add prompt for users to pick manifests to generate during `skaffold init --generate-manifests`
  go.mod
  go.sum
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/prompt/prompt.go
  pkg/skaffold/initializer/prompt/prompt_test.go
Labels: cla: yes, size/M

#5321 add docs for `config dependencies` feature
  docs/content/en/docs/design/config.md
  docs/content/en/docs/references/yaml/_index.html
  docs/content/en/docs/tutorials/_index.md
  docs/content/en/docs/tutorials/config-dependencies.md
Labels: cla: yes, size/L
