Repository GoogleContainerTools/skaffold, pull requests merged in 2021-08, with the labels that each got.

#6315 [v2] v2 kpt deployer accepts and can override inventory info.
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  hack/generate-statik.sh
  pkg/skaffold/deploy/v2/kpt/errors.go
  pkg/skaffold/deploy/v2/kpt/kpt.go
  pkg/skaffold/parser/config_test.go
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
  pkg/skaffold/tags/paths_test.go
  pkg/skaffold/tags/paths_windows_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes, size/XL

#6337 hooks: prepend pod/container name to container hooks log lines
  integration/examples/lifecycle-hooks/README.md
  integration/examples/lifecycle-hooks/skaffold.yaml
  pkg/skaffold/deploy/component/kubernetes/component.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/hooks/container.go
  pkg/skaffold/hooks/container_test.go
  pkg/skaffold/hooks/host.go
  pkg/skaffold/hooks/sync.go
  pkg/skaffold/hooks/sync_test.go
  pkg/skaffold/kubernetes/logger/formatter.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/log/stream/stream.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/types.go
Labels: cla: yes, size/L

#6345 Ensure Cleanup is called if Deploy creates resources but fails
  pkg/skaffold/runner/v1/apply.go
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/XS

#6342 fix: remote manifest image substitution
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/kubernetes/manifest/images_test.go
Labels: cla: yes, size/L

#6354 Fix issue with displaying survey prompts when we shouldn't
  cmd/skaffold/app/cmd/cmd.go
Labels: cla: yes, size/XS

#6284 Mark GCP Buildpacks builder as trusted in the examples
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  integration/examples/buildpacks-java/skaffold.yaml
  integration/examples/buildpacks-node/skaffold.yaml
  integration/examples/buildpacks-python/skaffold.yaml
  integration/examples/buildpacks/skaffold.yaml
  integration/examples/dev-journey-buildpacks/skaffold.yaml
Labels: cla: yes, size/S

#6339 [v2] Fix un-registered render manifest dependencies.
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/generate_test.go
Labels: cla: yes, size/L

#6356 Add Log helper function to output package
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/M

#6362 Ignore leading 'v' when parsing helm versions
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/XS

#6332 ResourceForwarder should wait for its forwards
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
Labels: cla: yes, size/L

#6293 Add trace-level port-allocation logs
  pkg/skaffold/util/port.go
Labels: cla: yes, size/S

#6369 update validation message
  pkg/skaffold/schema/validation/validation.go
Labels: cla: yes, size/XS

#6358 Add `SkaffoldLogEvent`s for pod updates
  pkg/skaffold/event/v2/status_check.go
  pkg/skaffold/kubernetes/status/resource/deployment.go
  pkg/skaffold/kubernetes/status/resource/deployment_test.go
  pkg/skaffold/kubernetes/status/resource/logfile.go
  pkg/skaffold/kubernetes/status/resource/status.go
  pkg/skaffold/kubernetes/status/resource/status_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/kubernetes/status/status_check_test.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
Labels: cla: yes, size/M

#6365 Add eventV2.BuildCancelled
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/event/v2/build.go
Labels: cla: yes, size/S

#6366 fix build --push=false for missing kubeconfig
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/M

#6368 fix: make `client.Client` kubernetesContext aware
  integration/util.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/secret.go
  pkg/skaffold/build/cluster/secret_test.go
  pkg/skaffold/deploy/component/kubernetes/accessor_test.go
  pkg/skaffold/deploy/component/kubernetes/component.go
  pkg/skaffold/deploy/component/kubernetes/debugger_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/label/labels.go
  pkg/skaffold/deploy/label/labels_test.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/hooks/container.go
  pkg/skaffold/hooks/container_test.go
  pkg/skaffold/hooks/sync_test.go
  pkg/skaffold/kubernetes/client/client.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/context/context_test.go
  pkg/skaffold/kubernetes/debugging/container_manager.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/owner.go
  pkg/skaffold/kubernetes/owner_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/kubernetes/util.go
  pkg/skaffold/kubernetes/watcher.go
  pkg/skaffold/kubernetes/watcher_test.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/v1/dev_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
  pkg/webhook/kubernetes/deployment.go
  pkg/webhook/kubernetes/service.go
Labels: cla: yes, size/L

#6376 hooks: implement kubectl deploy hooks
  docs/content/en/schemas/v2beta21.json
  integration/examples/lifecycle-hooks/deployment.yaml
  integration/examples/lifecycle-hooks/k8s-pod.yaml
  integration/examples/lifecycle-hooks/skaffold.yaml
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/hooks/container.go
  pkg/skaffold/hooks/deploy.go
  pkg/skaffold/hooks/deploy_test.go
  pkg/skaffold/log/stream/stream.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L, kokoro:force-run

#6372 fix: schema gen for `ContainerHook`
  docs/content/en/schemas/v2beta20.json
  pkg/skaffold/schema/v2beta20/config.go
Labels: cla: yes, size/S

#6364 [v2] Enable set labels in kpt v2 deployer
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/renderer_test.go
  pkg/skaffold/runner/v2/new.go
  pkg/skaffold/runner/v2/render.go
Labels: cla: yes, size/M

#6387 [v2] enable `skaffold apply`
  pkg/skaffold/runner/v2/apply.go
Labels: cla: yes, size/M

#6385 Validate generated schemas in generator script
  docs/content/en/schemas/v2beta19.json
  hack/schemas/main.go
  hack/schemas/main_test.go
  hack/schemas/testdata/inline-skiptrim/input.go
  hack/schemas/testdata/inline-skiptrim/output.json
  hack/schemas/testdata/invalid-schema/input.go
  pkg/skaffold/schema/v2beta19/config.go
Labels: cla: yes, size/L

#6386 hooks: update deploy docs
  docs/content/en/docs/pipeline-stages/lifecycle-hooks.md
Labels: cla: yes, size/M

#6395 Cleanup pod `SkaffoldLogEvent` messages
  pkg/skaffold/event/v2/status_check.go
  pkg/skaffold/kubernetes/status/resource/deployment.go
Labels: cla: yes, size/S

#6388 [v2] enable `skaffold delete` in kpt v2 deployer & backport ContainerHook
  docs/content/en/schemas/v2beta19.json
  docs/content/en/schemas/v2beta20.json
  docs/content/en/schemas/v2beta21.json
  pkg/skaffold/deploy/v2/kpt/kpt.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/schema/v2beta19/config.go
  pkg/skaffold/schema/v2beta20/config.go
Labels: cla: yes, size/M

#6397 [v2] Improve user experience on specifying inventory in kpt v2 deployer.
  pkg/skaffold/deploy/v2/kpt/errors.go
  pkg/skaffold/deploy/v2/kpt/kpt.go
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes, size/M

#6370 fix status check showing unhealthy pods from prev iteration
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/kubernetes/status/status_check_test.go
Labels: !! do-not-merge !!, cla: yes, size/M

#6401 Set exit code 127 for CLI validation errors
  cmd/skaffold/app/exitcode.go
  cmd/skaffold/app/exitcode_test.go
  cmd/skaffold/app/skaffold.go
  cmd/skaffold/app/skaffold_test.go
  cmd/skaffold/skaffold.go
  testutil/util.go
Labels: cla: yes, size/L

#6384 GitLab (with capital 'L')
  docs/content/en/docs/tutorials/ci_cd.md
Labels: cla: yes, size/S

#6402 Add functionality to support patterns in `--user` flag
  pkg/skaffold/constants/constants.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/user/user.go
  pkg/skaffold/user/user_test.go
  pkg/skaffold/version/version.go
  pkg/skaffold/version/version_test.go
Labels: cla: yes, size/L

#6343 Support passing additional CLI flags to docker build
  docs/content/en/schemas/v2beta21.json
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/S

#6398 Change parsing templated image warning to debug info
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/kubernetes/manifest/images_test.go
  pkg/skaffold/tag/util/util.go
Labels: cla: yes, size/S

#6380 Add support for Kaniko flag --image-fs-extract-retry
  docs/content/en/schemas/v2beta21.json
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/kaniko/args.go
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/S

#6405 fix lint broken on master
  pkg/skaffold/tag/util/util.go
Labels: cla: yes, size/XS

#6236 [design proposal] Add config option 'deploy.config.transformableAllowList'
  docs/design_proposals/configurable-transformable-allowlist.md
Labels: cla: yes, size/M, triage/discuss

#6406 [v2] Add inventory flags for `skaffold apply`
  cmd/skaffold/app/cmd/apply.go
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/v2/kpt/kpt.go
  pkg/skaffold/deploy/v2/kpt/kpt_test.go
  pkg/skaffold/runner/deployer.go
Labels: cla: yes, size/M

#6394 remove single `kubeContext` validation
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes, size/M

#6407 mute application logs when a new iteration starts.
  pkg/skaffold/kubernetes/logger/formatter.go
  pkg/skaffold/kubernetes/logger/formatter_test.go
Labels: cla: yes, size/M

#6410 Move deployment controller check to pod validator
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/kubernetes/status/status_check_test.go
Labels: cla: yes, size/M

#6409 Release v1.30.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/README.md
  examples/lifecycle-hooks/k8s-pod.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L

#6286 Restore import path with uppercase characters in custom build ko example
  integration/examples/custom/build.sh
  integration/examples/custom/k8s/pod.yaml
  integration/examples/custom/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/kubernetes/loader/load.go
  pkg/skaffold/kubernetes/loader/load_test.go
Labels: cla: yes, size/M

#6054 Add core ko builder implementation
  docs/design_proposals/ko-builder.md
  go.mod
  go.sum
  pkg/skaffold/build/ko/build.go
  pkg/skaffold/build/ko/build_test.go
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/builder_test.go
  pkg/skaffold/build/ko/ko.go
  pkg/skaffold/build/ko/ko_test.go
  pkg/skaffold/build/ko/publisher.go
  pkg/skaffold/build/ko/publisher_test.go
  pkg/skaffold/build/ko/schema/temporary.go
Labels: cla: yes, size/XL

#6422 remove note on vendor/ usage from DEVELOPMENT.md
  DEVELOPMENT.md
Labels: cla: yes, size/S

#6427 add opt out operational metrics note
  docs/content/en/docs/install/_index.md
Labels: meta/docs-preview, cla: yes, size/XS

#6426 Various small UX improvements
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/config.go
  cmd/skaffold/app/cmd/credits.go
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/filter.go
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/schema.go
  cmd/skaffold/app/skaffold_test.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/L

#6437 Refine ko builder behavior for main packages
  docs/design_proposals/ko-builder.md
Labels: cla: yes, size/M

#6436 hooks: add metrics
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/types.go
Labels: cla: yes, size/M

#6446 add skaffold inspect tests list command
  cmd/skaffold/app/cmd/inspect.go
  cmd/skaffold/app/cmd/inspect_tests.go
  pkg/skaffold/inspect/tests/list.go
  pkg/skaffold/inspect/tests/list_test.go
Labels: cla: yes, size/L

#6444 performance comparison on demand github action
  .github/workflows/performance-comparison-label.yml
  .github/workflows/performance-comparison.yml
  Makefile
  go.mod
  go.sum
  hack/comparisonstats/comment-text/comment.txt
  hack/comparisonstats/devrunner/devrunner.go
  hack/comparisonstats/events/parse.go
  hack/comparisonstats/events/parse_test.go
  hack/comparisonstats/main.go
  hack/comparisonstats/types/types.go
  hack/comparisonstats/util/util.go
  hack/comparisonstats/util/util_test.go
  hack/comparisonstats/validate/validate.go
  hack/golangci-lint.sh
Labels: cla: yes, size/XXL

#6463 fix: TestDebug/buildpacks by pinning go version
  integration/testdata/debug/skaffold.yaml
Labels: cla: yes, size/XS

#6445 Change wording describing how profiles work
  docs/content/en/docs/environment/profiles.md
Labels: cla: yes, size/XS

#6460 Update Jib plugin versions to 3.1.4
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#6474 Fix integration/'s randomPort() to return an unallocated port
  integration/rpc_test.go
Labels: cla: yes, size/S

#6458 document `make quicktest`
  DEVELOPMENT.md
Labels: cla: yes, size/XS

#6428 Fix #6408 - Add `--load-images` flag to deploy
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/deploy_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/M

#6447 Implement Target support for ko builder
  pkg/skaffold/build/ko/build.go
  pkg/skaffold/build/ko/build_test.go
  pkg/skaffold/build/ko/schema/temporary.go
  pkg/skaffold/build/ko/testdata/package-main-in-root/go.mod
  pkg/skaffold/build/ko/testdata/package-main-in-root/main.go
  pkg/skaffold/build/ko/testdata/package-main-not-in-root/baz/main.go
  pkg/skaffold/build/ko/testdata/package-main-not-in-root/go.mod
Labels: cla: yes, size/M

#6464 Configure Dependabot to only allow security updates
  .github/dependabot.yml
Labels: cla: yes, size/XS

#6475 Only cache $GOPATH/pkg/mod on Travis
  .travis.yml
Labels: cla: yes, size/XS

#6455 Add skip_test env for custom build script
  docs/content/en/docs/pipeline-stages/builders/custom.md
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/custom/script.go
  pkg/skaffold/build/custom/script_test.go
  pkg/skaffold/build/custom/types.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/constants/constants.go
Labels: cla: yes, size/M

#6453 fix: do not sync remote configs for specific commands
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/S

#6454 hooks: implement for `helm` and `kustomize` deployers
  docs/content/en/docs/pipeline-stages/lifecycle-hooks.md
  docs/content/en/schemas/v2beta22.json
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/hooks/deploy.go
  pkg/skaffold/hooks/deploy_test.go
  pkg/skaffold/hooks/types.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L

#6141 Enable GitHub CodeQL code scanning
  .github/workflows/codeql-analysis.yml
Labels: cla: yes, size/M

#6469 Wrap tester in `SkaffoldRunner` to improve `SkaffoldLogEvent` labelling
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/runner.go
  pkg/skaffold/runner/v1/runner_test.go
  pkg/skaffold/runner/v1/test.go
  pkg/skaffold/test/test_factory.go
Labels: cla: yes, size/M

#6499 fix: bad merge
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/XS

#6493 Fix skaffold inspect tests flags and help message
  cmd/skaffold/app/cmd/inspect_tests.go
  pkg/skaffold/inspect/tests/list.go
  pkg/skaffold/inspect/types.go
Labels: cla: yes, size/S

#6506 Add newlines to `SkaffoldLogEvent`s that come from `logrus`
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/event/v2/logger.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/v1/dev.go
Labels: cla: yes, size/XS

#6507 Add new `enums.LogLevel` to indicate skaffold's standard output
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/event/v2/logger.go
  pkg/skaffold/event/v2/status_check.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes, size/L

#6505 Updated Cloud Code links to link to debug page
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/XS

#6503 docs: dev.md improvements
  docs/content/en/docs/workflows/dev.md
Labels: cla: yes, area/docs, size/S, docs-fixit

#6496 Add `Dir` config field to ko builder
  docs/design_proposals/ko-builder.md
  pkg/skaffold/build/ko/build_test.go
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/builder_test.go
  pkg/skaffold/build/ko/schema/temporary.go
Labels: cla: yes, size/L

#6537 docs: rename section "Working with Skaffold" to "Guides"
  docs/content/en/docs/workflows/_index.md
Labels: cla: yes, size/XS

#6538 docs: update `dev` documentation for `test` phase;
  docs/content/en/docs/workflows/dev.md
Labels: cla: yes, size/S

#6539 docs: update `test` phase references
  docs/content/en/docs/_index.md
Labels: cla: yes, size/XS

#6536 [docs fixit] update skaffold fix text to have full description of command
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/cli/index_header
Labels: cla: yes, size/XS

#6543 copy over identical windows unit test from travis to gh actions
  .github/workflows/integration-windows.yml
Labels: cla: yes, size/S

#6547 fix: helm resource labeller checking wrong kubectl context
  pkg/skaffold/deploy/label/labels.go
Labels: cla: yes, size/S

#6535 Plumb `context.Context` down into functions in pkg/skaffold/sync
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/S

#6534 Send success for pods for a deployment when its rolled out successfully
  pkg/skaffold/kubernetes/status/resource/deployment.go
  pkg/skaffold/kubernetes/status/resource/deployment_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/kubernetes/status/status_check_test.go
Labels: cla: yes, size/M

#6549 remove .travis.yml, completing gh action migration
  .travis.yml
  README.md
Labels: cla: yes, size/L

#6545 Add option to wait for connection to `/v2/events` on gRPC/HTTP server
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/skaffold.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/server/server.go
Labels: cla: yes, size/M

#6530 Fix buildpacks builder output to go through Event API
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/logger.go
Labels: cla: yes, size/S
