Repository GoogleContainerTools/skaffold, pull requests merged in 2021-04, with the labels that each got.

#5594 Adding testing phase to Skaffold run
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/run_test.go
  integration/run_test.go
  integration/testdata/custom-test/skaffold.yaml
Labels: area/testing, cla: yes, kind/feature-request, size/L

#5623 Add `BuilderContext` interface to encapsulate `RunContext` and provide additional builder constructor requirements.
  pkg/skaffold/build/cluster/cluster_test.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/build/cluster/secret_test.go
  pkg/skaffold/build/cluster/types.go
  pkg/skaffold/build/cluster/types_test.go
  pkg/skaffold/build/gcb/buildpacks_test.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/gcb/spec_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/runner/builder.go
  pkg/skaffold/runner/new.go
Labels: cla: yes, size/L

#5622 Add event API v2 server handler
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/event_test.go
  pkg/skaffold/server/server.go
  pkg/skaffold/server/v2/endpoints.go
  pkg/skaffold/server/v2/server.go
  pkg/skaffold/server/v2/server_test.go
Labels: cla: yes, size/L

#5626 Add `TaskSucceeded()` func to `event/v2` package
  pkg/skaffold/event/v2/event.go
Labels: cla: yes, size/S

#5625 rename errors.FileSync errors.Sync
  pkg/skaffold/errors/errors.go
  pkg/skaffold/errors/errors_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/event_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/server/v2/endpoints.go
Labels: cla: yes, size/M

#5614 Fix 5301: Build dependencies for sync inherited from `required` artifacts; cache build dependencies between devloops
  pkg/skaffold/build/dependencies.go
  pkg/skaffold/build/dependencies_test.go
  pkg/skaffold/build/docker/docker_test.go
  pkg/skaffold/build/docker/errors_test.go
  pkg/skaffold/build/docker/types.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/spec_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/diagnose/diagnose_test.go
  pkg/skaffold/runner/builder.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/runner/listen.go
  pkg/skaffold/runner/listen_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/XL

#5630 Add service config to leeroy-web deployment.yaml
  examples/microservices/leeroy-web/kubernetes/deployment.yaml
Labels: cla: yes, size/S

#5631 Bring survey prompt back to 10 days and every 90 days.
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
Labels: cla: yes, size/XS

#5636 Reset API intents on every dev cycle to avoid queueing
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/runner/intent.go
  pkg/skaffold/runner/runner_test.go
Labels: cla: yes, size/M

#5640 Added helm remote repo example
  integration/examples/helm-remote-repo/README.md
  integration/examples/helm-remote-repo/skaffold.yaml
Labels: cla: yes, size/S

#5633 Refactor `skaffold test` implementation
  pkg/skaffold/test/custom/custom.go
  pkg/skaffold/test/custom/custom_test.go
  pkg/skaffold/test/structure/error.go
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/test/structure/structure_test.go
  pkg/skaffold/test/test_factory.go
  pkg/skaffold/test/types.go
Labels: cla: yes, size/L

#5627 [kpt deployer] Fix non-kustomize manifests not rendered issue
  pkg/skaffold/deploy/kpt/kpt.go
Labels: cla: yes, size/S

#5651 Update Jib to 3.0 and set base images
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/M

#5657 Mark structureTests as filepaths
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/XS

#5641 [refactor] move phase constants from `pkg/skaffold/errors` to `pkg/skaffold/constants`
  pkg/skaffold/constants/constants.go
  pkg/skaffold/errors/errors.go
  pkg/skaffold/errors/errors_test.go
  pkg/skaffold/errors/init_problems_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/event_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/server/v2/endpoints.go
Labels: cla: yes, size/L

#5637 Emit TaskEvent messages for DevLoop, Build, and Deploy phases
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/server/server.go
Labels: cla: yes, size/M

#5646 fix concurrency issue in multi-config
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/build/builder_mux_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/versions_test.go
  pkg/skaffold/util/util.go
Labels: cla: yes, size/M

#5663 Try reducing ttl to 30 seconds
  examples/buildpacks-java/.mvn/jvm.config
  examples/jib-multimodule/.mvn/jvm.config
  examples/jib-sync/.mvn/jvm.config
  integration/examples/buildpacks-java/.mvn/jvm.config
  integration/examples/jib-multimodule/.mvn/jvm.config
  integration/examples/jib-sync/.mvn/jvm.config
  integration/testdata/debug/java/.mvn/jvm.config
  integration/testdata/jib/.mvn/jvm.config
Labels: cla: yes, size/S

#5554 Revise port-forward behaviour
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/pipeline-stages/port-forwarding.md
  docs/content/en/docs/references/cli/_index.md
  integration/examples/jib-sync/README.md
  integration/examples/remote-multi-config-microservices/README.md
  pkg/skaffold/config/options.go
  pkg/skaffold/config/portforward.go
  pkg/skaffold/config/portforward_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, kokoro:force-run, size/XL

#5654 Fix `default-repo` by supporting nil as default value for flags
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/flags_test.go
  pkg/skaffold/config/types.go
  pkg/skaffold/config/types_test.go
Labels: cla: yes, size/M

#5652 Support --cache-artifacts flag for render
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: cla: yes, size/XS

#5649 Add user flag to all minikube command invocations
  pkg/skaffold/cluster/minikube.go
  pkg/skaffold/cluster/minikube_test.go
  pkg/skaffold/test/structure/structure_test.go
Labels: cla: yes, platform/minikube, size/L

#5672 Add back 'tag' digest source
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/M

#5676 helm `render` needs to handle `repo` parameter
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/S

#5644 Deprecate --render-only and --render-output flags
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/references/deprecation.md
Labels: cla: yes, size/S

#5661 Add InputDigest support to CustomTemplateTagger
  pkg/skaffold/tag/tagger_mux.go
  pkg/skaffold/tag/tagger_mux_test.go
Labels: cla: yes, size/S

#5678 Make test dependencies retrieval per artifact.
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/dev_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/test/test_factory.go
  pkg/skaffold/test/test_factory_test.go
  pkg/skaffold/test/types.go
Labels: cla: yes, size/M

#5670 Forwarding resources should not allocate system ports
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/server/server.go
  pkg/skaffold/util/port.go
  pkg/skaffold/util/port_test.go
Labels: cla: yes, size/L

#5680 Document portforwarding behavior for system ports
  docs/content/en/docs/pipeline-stages/port-forwarding.md
Labels: cla: yes, size/XS

#5679 fix: test dependencies triggering retest for all artifacts
  pkg/skaffold/runner/changeset.go
  pkg/skaffold/runner/dev.go
Labels: cla: yes, size/M

#5682 Revert mk user flag
  pkg/skaffold/cluster/minikube.go
  pkg/skaffold/cluster/minikube_test.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/test/structure/structure_test.go
Labels: cla: yes, size/L

#5677 Adding workspace to tests.
  docs/content/en/schemas/v2beta14.json
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/test/custom/custom.go
  pkg/skaffold/test/custom/custom_test.go
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/test/structure/structure_test.go
  pkg/skaffold/test/test_factory.go
  pkg/skaffold/test/test_factory_test.go
Labels: cla: yes, size/L

#5537 Remove global single instance of `skaffoldOpts` in skaffold error package and use runContext Config
  cmd/skaffold/app/cmd/build_test.go
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/debug_test.go
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/cmd/run_test.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/runner_test.go
  pkg/skaffold/build/build_problems.go
  pkg/skaffold/build/build_problems_test.go
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/build/builder_mux_test.go
  pkg/skaffold/deploy/deploy_problems.go
  pkg/skaffold/deploy/deploy_problems_test.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/parse_test.go
  pkg/skaffold/docker/remote_test.go
  pkg/skaffold/errors/build_problems.go
  pkg/skaffold/errors/build_problems_test.go
  pkg/skaffold/errors/deploy_problems.go
  pkg/skaffold/errors/err_map.go
  pkg/skaffold/errors/errors.go
  pkg/skaffold/errors/errors_test.go
  pkg/skaffold/errors/init_problems.go
  pkg/skaffold/errors/problem.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/initializer/init_problems.go
  pkg/skaffold/initializer/init_problems_test.go
Labels: cla: yes, size/XXL

#5685 release: v1.22.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/README.md
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/build.gradle
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/pom.xml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/README.md
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/pom.xml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/leeroy-web/kubernetes/deployment.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/README.md
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#5688 Fix typo
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/XS

#5675 Add taskevents Test, StatusCheck, and fix duplicates for Deploy
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/deploy.go
Labels: cla: yes, size/S

#5693 fix file sync comment in examples/hot-reload/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  integration/examples/hot-reload/skaffold.yaml
Labels: cla: yes, size/XS

#5694 [V3] Add flag as v3 entrypoint.
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
Labels: area/v3, cla: yes, size/S

#5698 add host support for docker build
  docs/content/en/schemas/v2beta15.json
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/S

#5710 Add BuildSubtask emission for v2 API
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/runner/new.go
  testutil/event/config.go
Labels: cla: yes, size/M

#5468 Do not display `helm` warnings for multi-config projects
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/M

#5714 Improve multi-config documentation
  docs/content/en/docs/design/config.md
Labels: cla: yes, size/M

#5491 Add Cluster Internal Service Error code along with runcontext
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  go.mod
  pkg/skaffold/deploy/deploy_problems.go
  pkg/skaffold/deploy/deploy_problems_test.go
  pkg/skaffold/deploy/error/errors.go
  pkg/skaffold/deploy/error/errors_test.go
  pkg/skaffold/deploy/helm/errors.go
  pkg/skaffold/deploy/kubectl/errors.go
  pkg/skaffold/deploy/kustomize/errors.go
  pkg/skaffold/errors/errors.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes, size/L

#5712 Make status-check flag nillable
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/init_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/config/types.go
  pkg/skaffold/config/types_test.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/L

#5699 Add build-concurrency flag
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/build/builder_mux_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/M

#5689 Emit TaskEvents Protos for PortForwarding
  pkg/skaffold/constants/constants.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/event_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager_test.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/portforwarder.go
  pkg/skaffold/runner/runner.go
Labels: cla: yes, size/L

#5722 Do not swallow parsing errors
  pkg/skaffold/schema/errors/errors.go
Labels: cla: yes, size/S

#5708 add skaffold build --push flag
  cmd/skaffold/app/cmd/build.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/build_deploy_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/new_test.go
Labels: cla: yes, size/L

#5723 Fix Helm deployment check to only retrieve deployed YAML
  integration/testdata/helm/skaffold-helm/templates/NOTES.txt
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/M

#5724 Fix go module names to be unique
  codelab/03_buildpacks-runimage-override/app/go.mod
  integration/examples/custom-buildx/go.mod
Labels: cla: yes, size/XS

#5715 Added fix for RPC port detection
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/server/server.go
  pkg/skaffold/util/port.go
  pkg/skaffold/util/port_test.go
Labels: cla: yes, size/M

#5731 Add user flag with allowed user list to upload metrics
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/config/options.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/types.go
Labels: cla: yes, size/L

#5732 Add `--user` flag to all minikube command invocations
  pkg/skaffold/cluster/minikube.go
  pkg/skaffold/cluster/minikube_test.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/test/structure/structure_test.go
Labels: cla: yes, size/L

#5736 release: v1.23.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom-buildx/go.mod
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#5742 Revert "release: v1.23.0"
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom-buildx/go.mod
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#5744 release: v1.23.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom-buildx/go.mod
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes, size/L

#5734 use os.Lookup instead of os.Get
  pkg/skaffold/instrumentation/export.go
Labels: cla: yes, size/XS

#5747 Bump several build dependencies
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.deps
Labels: cla: yes, size/S

#5753 Protect errors.allErrors with mutex
  pkg/skaffold/errors/errors.go
  pkg/skaffold/errors/problem.go
Labels: cla: yes, size/XS

#5735 Use GCR registry mirror in Travis for Linux-based platforms
  .travis.yml
Labels: cla: yes, size/S

#5751 Support templated release names in helm render
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, release/fixes, size/M

#5729 [V3] (Part 2) Add new schema to latest/v2
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/latest/v2/upgrade.go
  pkg/skaffold/schema/v3alpha1/config.go
  pkg/skaffold/schema/v3alpha1/upgrade.go
Labels: area/v3, cla: yes, size/L

#5750 Fix tarring of build context for artifacts with source dependencies
  integration/examples/microservices/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/build/docker/types.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/spec_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/build/local/types.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/graph/dependencies.go
  pkg/skaffold/graph/dependencies_test.go
  pkg/skaffold/runner/builder.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/listen.go
  pkg/skaffold/runner/listen_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/tag/input_digest.go
Labels: cla: yes, size/L

#5761 [Refactor] Move kubernetes log code to pkg/skaffold/kubernetes/logger
  pkg/skaffold/kubernetes/image_list.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/runner/logger.go
Labels: cla: yes, size/L

#5762 skaffold diagnose to not initialize runconfig for yaml only flag
  cmd/skaffold/app/cmd/diagnose.go
  cmd/skaffold/app/cmd/diagnose_test.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/runner/runcontext/context.go
Labels: cla: yes, size/L

#5764 Update api.md
  docs/content/en/docs/design/api.md
Labels: cla: yes, size/XS

#5769 fix SecurityContext typo
  docs/content/en/schemas/v2beta10.json
  docs/content/en/schemas/v2beta11.json
  docs/content/en/schemas/v2beta12.json
  docs/content/en/schemas/v2beta13.json
  docs/content/en/schemas/v2beta14.json
  docs/content/en/schemas/v2beta15.json
  docs/content/en/schemas/v2beta16.json
  docs/content/en/schemas/v2beta3.json
  docs/content/en/schemas/v2beta4.json
  docs/content/en/schemas/v2beta5.json
  docs/content/en/schemas/v2beta6.json
  docs/content/en/schemas/v2beta7.json
  docs/content/en/schemas/v2beta8.json
  docs/content/en/schemas/v2beta9.json
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/schema/v2beta10/config.go
  pkg/skaffold/schema/v2beta11/config.go
  pkg/skaffold/schema/v2beta12/config.go
  pkg/skaffold/schema/v2beta13/config.go
  pkg/skaffold/schema/v2beta14/config.go
  pkg/skaffold/schema/v2beta15/config.go
  pkg/skaffold/schema/v2beta3/config.go
  pkg/skaffold/schema/v2beta4/config.go
  pkg/skaffold/schema/v2beta5/config.go
  pkg/skaffold/schema/v2beta6/config.go
  pkg/skaffold/schema/v2beta7/config.go
  pkg/skaffold/schema/v2beta8/config.go
  pkg/skaffold/schema/v2beta9/config.go
Labels: cla: yes, size/M

#5706 Add StatusCheck field to skaffold.yaml (#4904)
  docs/content/en/docs/workflows/ci-cd.md
  docs/content/en/schemas/v2beta16.json
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/deploy_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/runcontext/context_test.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L
