Repository GoogleContainerTools/skaffold, pull requests merged in 2021-02, with the labels that each got.

#5319 add integration test for `skaffold init --artifact`
  integration/init_test.go
  integration/testdata/init/hello-with-manifest/k8s-pod.yaml
  integration/testdata/init/hello-with-manifest/skaffold.yaml
Labels: cla: yes, size/M

#5328 fix pulling secrets in cloudbuild release for latest builds
  deploy/cloudbuild.yaml
Labels: cla: yes, size/XS

#5324 refactor instrumentation package
  Makefile
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/prompt_test.go
  pkg/skaffold/instrumentation/types.go
Labels: cla: yes, refactor

#5330 add `build-dependencies` metric
  docs/content/en/docs/resources/telemetry/metrics.json
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/types.go
Labels: cla: yes, needs-rebase, size/M

#5308 Make integration.WaitForPodsReady use pod `Ready` condition
  integration/debug_test.go
  integration/testdata/debug/skaffold.yaml
  integration/util.go
Labels: cla: yes, size/M

#5337 Fix example `multi-config-microservices` broken due to missed runtime image update
  examples/multi-config-microservices/base/Dockerfile
  integration/examples/multi-config-microservices/base/Dockerfile
  integration/run_test.go
Labels: cla: yes, size/XS

#5322 export metrics related to user enum flags
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
Labels: cla: yes, size/S

#5344 Configure k3d to use registry-mirrors
  Makefile
  hack/generate-k3d-registries.sh
Labels: cla: yes, size/M

#5325 TypeScript support for the existing Node.js example
  integration/examples/typescript/README.md
  integration/examples/typescript/backend/.dockerignore
  integration/examples/typescript/backend/.gitignore
  integration/examples/typescript/backend/Dockerfile
  integration/examples/typescript/backend/package.json
  integration/examples/typescript/backend/src/index.ts
  integration/examples/typescript/backend/src/utils/index.ts
  integration/examples/typescript/backend/tsconfig.json
  integration/examples/typescript/k8s/deployment.yaml
  integration/examples/typescript/skaffold.yaml
Labels: cla: yes, size/L

#5346 Update telemetry prompt links
  pkg/skaffold/instrumentation/prompt.go
Labels: cla: yes, size/XS

#5286 Update release to build darwin/arm64 binary
  Makefile
  deploy/cross/Dockerfile
  go.mod
  go.sum
Labels: cla: yes, size/M

#5351 Update dependencies to fix `getCPUInfo` error on darwin/arm64
  go.mod
  go.sum
Labels: cla: yes, size/XS

#5347 Unhide --auto-{build,deploy,sync} and update debug notes
  cmd/skaffold/app/cmd/debug.go
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/M

#5353 track the platform type at the launch level
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/types.go
Labels: cla: yes, size/XS

#5287 Update docs with darwin/arm64 binaries
  docs/content/en/docs/install/_index.md
  integration/examples/typescript/skaffold.yaml
Labels: cla: yes, size/M

#5350 use status code string in error label
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
Labels: cla: yes, size/S

#5375 Document steps to use sErrors.ErrDef class to provide actionable error messages
  DEVELOPMENT.md
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes, size/M

#5385 Add error codes for test failures
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/test/error.go
  pkg/skaffold/test/structure/error.go
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/test/test.go
  pkg/skaffold/test/test_test.go
  proto/skaffold.pb.go
  proto/skaffold.proto
Labels: cla: yes

#5390 Disable telemetry reporting for nightlies
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
Labels: cla: yes, size/XS

#5389 Fix absolute path substitution in configs imported as dependencies.
  cmd/skaffold/app/cmd/parse_config.go
  cmd/skaffold/app/cmd/parse_config_test.go
  pkg/skaffold/schema/latest/config.go
Labels: cla: yes

#5359 add debug/iterations metric
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
Labels: cla: yes, size/M

#5323 Programatically create a dashboard for flag metric descriptors
  Makefile
  go.mod
  hack/patch-dashboard/main.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/meter.go
Labels: cla: yes, size/L

#5391 Move current proto/ into proto/v1/
  docs/content/en/docs/design/api.md
  hack/generate-proto.sh
  hack/proto/Dockerfile
  integration/cache_test.go
  integration/debug_test.go
  integration/dev_test.go
  integration/rpc_test.go
  integration/sync_test.go
  pkg/diag/recommender/container_errors.go
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/diag/validator/recommender.go
  pkg/diag/validator/resource.go
  pkg/diag/validator/resource_test.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/docker/errors.go
  pkg/skaffold/build/jib/errors.go
  pkg/skaffold/deploy/error/errors.go
  pkg/skaffold/deploy/helm/errors.go
  pkg/skaffold/deploy/kubectl/errors.go
  pkg/skaffold/deploy/kustomize/errors.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/resource/deployment_test.go
  pkg/skaffold/deploy/resource/status.go
  pkg/skaffold/deploy/resource/status_test.go
  pkg/skaffold/deploy/status/status_check.go
  pkg/skaffold/deploy/status/status_check_test.go
  pkg/skaffold/docker/errors.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/errors/build_problems.go
  pkg/skaffold/errors/build_problems_test.go
  pkg/skaffold/errors/deploy_problems.go
  pkg/skaffold/errors/deploy_problems_test.go
  pkg/skaffold/errors/err_def.go
  pkg/skaffold/errors/err_map.go
  pkg/skaffold/errors/errors.go
  pkg/skaffold/errors/errors_test.go
  pkg/skaffold/errors/init_problems.go
  pkg/skaffold/errors/init_problems_test.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/event/util.go
  pkg/skaffold/event/util_test.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/types.go
  pkg/skaffold/kubernetes/manifest/errors.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/server/endpoints.go
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
  pkg/skaffold/test/error.go
  pkg/skaffold/test/structure/error.go
  proto/v1/markdown.tmpl
  proto/v1/skaffold.pb.go
  proto/v1/skaffold.pb.gw.go
  proto/v1/skaffold.proto
Labels: cla: yes, size/L

#5360 Update pack to 0.17.0 with Platform API 0.5
  go.mod
  go.sum
Labels: cla: yes, size/XS

#5402 run go mod tidy
  go.mod
  go.sum
Labels: cla: yes, size/XS

#5408 Make hack/new_version.sh propose a realistic next version
  hack/versions/cmd/new/version.go
Labels: cla: yes, size/M

#5405 Fixes #5404: Skaffold configs downloaded from a url can define remote config dependencies
  cmd/skaffold/app/cmd/parse_config.go
  cmd/skaffold/app/cmd/parse_config_test.go
Labels: cla: yes, size/M

#5378 Create a test factory to support multiple test types
  pkg/skaffold/runner/new.go
  pkg/skaffold/test/error.go
  pkg/skaffold/test/structure/error.go
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/test/structure/structure_test.go
  pkg/skaffold/test/structure/types.go
  pkg/skaffold/test/structure/types_test.go
  pkg/skaffold/test/test_factory.go
  pkg/skaffold/test/test_factory_test.go
  pkg/skaffold/test/types.go
Labels: cla: yes, size/XL

#5409 add tutorial for buildpacks run image override
  codelab/03_buildpacks-runimage-override/README.md
  codelab/03_buildpacks-runimage-override/app/go.mod
  codelab/03_buildpacks-runimage-override/app/main.go
  codelab/03_buildpacks-runimage-override/base/Dockerfile
  codelab/03_buildpacks-runimage-override/base/hello.txt
  codelab/03_buildpacks-runimage-override/k8s/web.yaml
  codelab/03_buildpacks-runimage-override/skaffold.yaml
  codelab/03_buildpacks-runimage-override/tutorial.md
Labels: cla: yes, size/L

#5433 Extracting structure tests run logic into a separate method.
  pkg/skaffold/test/structure/structure.go
Labels: area/testing, cla: yes, size/S

#5429 Update _index.md
  docs/content/en/docs/install/_index.md
Labels: cla: yes, size/XS

#5430 Update gcr.io/k8s-skaffold/pack to 0.17.0
  deploy/buildpacks/publish.sh
Labels: cla: yes, size/XS

#5435 Add golint support for M1 macs (darwin/arm64 arch)
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/flags.go
  hack/golangci-lint.sh
  hack/install_golint.sh
  hack/man/man_test.go
  hack/schemas/main.go
  hack/schemas/main_test.go
  hack/struct-json/main.go
  integration/build_cluster_test.go
  integration/dev_test.go
  integration/rpc_test.go
  integration/util.go
  pkg/skaffold/build/jib/init.go
  pkg/skaffold/build/jib/jib.go
  pkg/skaffold/build/jib/sync_test.go
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/build/tag/tag.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python_test.go
  pkg/skaffold/initializer/analyze/directory.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/runner/render.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v1beta9/upgrade.go
  pkg/skaffold/schema/v2beta10/config.go
  pkg/skaffold/schema/v2beta11/config.go
  pkg/skaffold/schema/v2beta12/config.go
  pkg/skaffold/schema/v2beta9/config.go
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/util/cmd_test.go
  pkg/skaffold/util/tar.go
  pkg/skaffold/util/util.go
  testutil/util.go
Labels: cla: yes, size/L

#5416 Handle nil PortForward item on setting defaults
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
Labels: cla: yes, size/S

#5437 Add metric for the count of skaffold configurations in current session; fix the build platform type metric to save list of all platforms
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/types.go
Labels: cla: yes, size/S

#5184 proposal for user generated tagger.
  docs/design_proposals/digest-tagger.md
Labels: cla: yes, size/S

#5448 Fix syntax of link to SOPS github repo
  docs/content/en/docs/tutorials/ci_cd.md
Labels: cla: yes, size/XS

#5441 skip validating Dockerfile using explicit syntax directive
  go.sum
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/parse_test.go
Labels: cla: yes, size/M

#5457 Update Jib to 2.8.0
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#5447 Add support for no-option-value; surface per-option-defaults
  cmd/skaffold/app/cmd/commands.go
  cmd/skaffold/app/cmd/debug_test.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/flags_test.go
  docs/content/en/docs/references/cli/_index.md
  examples/buildpacks/main.go
Labels: cla: yes, size/L

#5452 fix logic that set absolute paths in the parsed configuration
  pkg/skaffold/tags/paths.go
  pkg/skaffold/tags/paths_test.go
Labels: cla: yes, size/S

#5453 fix: use reflection in `GetYamlTags` instead of manipulating strings
  pkg/skaffold/initializer/util/util.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/yamltags/tags.go
  pkg/skaffold/yamltags/tags_test.go
Labels: cla: yes, size/L

#5462 add validation to ensure image names are unique
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes, size/M

#5461 Update grpc.md
  docs/content/en/docs/references/api/grpc.md
  proto/v1/markdown.tmpl
Labels: cla: yes, size/XS
