Repository GoogleContainerTools/skaffold, pull requests merged in 2021-06, with the labels that each got.

#5910 Always create a secret during release
  deploy/setup-secret.sh
Labels: cla: yes, size/S

#5915 Add step field for `BuildSubtaskEvent` to represent the different parts of a build for an artifact
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/event/v2/build.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/runner/build_deploy.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/L

#5921 Add/fix remoteChart tests
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/M

#5924 Add pointer for .NET debugging for Rider
  docs/content/en/docs/workflows/debug.md
Labels: cla: yes, size/S

#5918 Update metadata event emission to happen every devloop and update build metadata
  pkg/skaffold/event/v2/metadata.go
  pkg/skaffold/event/v2/metadata_test.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/new.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/L

#5922 Use Helm chart version in render
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/S

#5854 skaffold trace wrapping of critical functions & skaffold trace exporters via SKAFFOLD_TRACE env var
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/skaffold.go
  examples/jaeger-skaffold-trace/README.md
  go.mod
  go.sum
  integration/examples/jaeger-skaffold-trace/README.md
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/custom/build.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/jib/build.go
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/graph/dependencies.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/new.go
  pkg/skaffold/instrumentation/trace.go
  pkg/skaffold/instrumentation/trace_test.go
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/kubernetes/manifest/images_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/runner/v1/apply.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/new.go
Labels: cla: yes, size/XL

#5894 Refactor to use new SkaffoldWriter type
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/skaffold.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/result.go
  pkg/skaffold/output/color.go
  pkg/skaffold/output/color_test.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
Labels: cla: yes, size/L

#5931 Remove goreport card
  README.md
Labels: cla: yes, size/XS

#5919 Ensure tag stripping logic can optionally accept digests
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/util.go
  pkg/skaffold/kubernetes/colorpicker.go
  pkg/skaffold/kubernetes/colorpicker_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/tag/util.go
  pkg/skaffold/tag/util_test.go
Labels: cla: yes, size/M

#5929 Add additional detail text field for task protos
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/test/test_factory.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/L

#5932 Pause debug pod watchers before next iteration deploy
  pkg/skaffold/kubernetes/debugging/container_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/watcher.go
Labels: cla: yes, size/M

#5920 Fix up missed remote -> remotePath changes
  docs/content/en/schemas/v2beta17.json
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/S

#5934 Add support for Port forwarding with resourceName with Templated Fields
  docs/content/en/docs/environment/templating.md
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
Labels: cla: yes, size/M

#5940 [v3] Add the Kptfile struct to render.
  pkg/skaffold/render/kptfile/pipeline_type.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/renderer_test.go
Labels: cla: yes, size/L

#5939 Show more detailed error when unknown Project
  pkg/skaffold/build/build_problems.go
  pkg/skaffold/build/build_problems_test.go
Labels: cla: yes, size/S

#5948 Document `inputDigest` tagger, and move `sha256` tagger to end
  docs/content/en/docs/design/_index.md
  docs/content/en/docs/pipeline-stages/taggers.md
  docs/content/en/samples/taggers/inputDigest.yaml
Labels: cla: yes, size/M

#5944 add command `skaffold inspect build-env add local`
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/inspect_build_env.go
  pkg/skaffold/inspect/buildEnv/add_local.go
  pkg/skaffold/inspect/buildEnv/add_local_test.go
  pkg/skaffold/inspect/types.go
Labels: cla: yes, size/L

#5938 Add distinct error codes for docker no space error and better suggestion
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/docker/docker_test.go
  pkg/skaffold/build/docker/errors.go
  pkg/skaffold/build/docker/errors_test.go
  pkg/skaffold/build/docker/types.go
  pkg/skaffold/build/local/types.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes

#5927 Remove unsupported `docker.secret.dst` field
  docs/content/en/schemas/v2beta17.json
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/schema/v2beta16/upgrade.go
  pkg/skaffold/schema/v2beta16/upgrade_test.go
Labels: cla: yes, size/M

#5949 Redo deduplication of deploy taskevents
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/XS

#5937 Add event logger type and function to set event context for writer
  pkg/skaffold/event/v2/config.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/logger.go
  pkg/skaffold/event/v2/logger_test.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
Labels: cla: yes, size/L

#5951 setup /v2/skaffoldLogs endpoint
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/server/v2/endpoints.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.pb.gw.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/L

#5935 add command `skaffold inspect build-env modify googleCloudBuild`
  cmd/skaffold/app/cmd/inspect.go
  cmd/skaffold/app/cmd/inspect_build_env.go
  cmd/skaffold/app/cmd/inspect_modules.go
  cmd/skaffold/app/cmd/inspect_profiles.go
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/inspect/buildEnv/modify_gcb.go
  pkg/skaffold/inspect/buildEnv/modify_gcb_test.go
  pkg/skaffold/inspect/errors.go
  pkg/skaffold/inspect/types.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.pb.gw.go
Labels: cla: yes

#5941 Ignore first user cancelled and get actual error as final error
  pkg/skaffold/deploy/status/status_check.go
  pkg/skaffold/deploy/status/status_check_test.go
Labels: cla: yes, size/M

#5958 Avoid adding image digest twice to tag on render
  pkg/skaffold/build/util.go
  pkg/skaffold/build/util_test.go
Labels: cla: yes, size/S

#5886 Fix and cleanup Kpt fn integration
  Makefile
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
Labels: cla: yes, size/L

#5942 [v3] Add validator in render v2.
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/renderer_test.go
  pkg/skaffold/render/validate/validate.go
  pkg/skaffold/render/validate/validate_test.go
Labels: area/render, area/v3, cla: yes, size/L

#5963 have BuildSubtaskEvent use InProgress status
  pkg/skaffold/event/v2/build.go
Labels: cla: yes, size/XS

#5962 skaffold inspect build-env googleCloudBuild fix to add missing flag o…
  Makefile
  cmd/skaffold/app/cmd/inspect_build_env.go
  pkg/skaffold/inspect/buildEnv/add_gcb.go
  pkg/skaffold/inspect/types.go
Labels: cla: yes, size/M

#5969 add `--all` flag to `inspect modules list` command; other refactors
  cmd/skaffold/app/cmd/inspect.go
  cmd/skaffold/app/cmd/inspect_build_env.go
  cmd/skaffold/app/cmd/inspect_modules.go
  cmd/skaffold/app/cmd/inspect_profiles.go
  pkg/skaffold/git/gitutil.go
  pkg/skaffold/inspect/buildEnv/add_cluster.go
  pkg/skaffold/inspect/buildEnv/add_cluster_test.go
  pkg/skaffold/inspect/buildEnv/add_gcb.go
  pkg/skaffold/inspect/buildEnv/add_gcb_test.go
  pkg/skaffold/inspect/buildEnv/add_local.go
  pkg/skaffold/inspect/buildEnv/add_local_test.go
  pkg/skaffold/inspect/buildEnv/list.go
  pkg/skaffold/inspect/buildEnv/list_test.go
  pkg/skaffold/inspect/buildEnv/modify_gcb.go
  pkg/skaffold/inspect/buildEnv/modify_gcb_test.go
  pkg/skaffold/inspect/modules/list.go
  pkg/skaffold/inspect/modules/list_test.go
  pkg/skaffold/inspect/profiles/list.go
  pkg/skaffold/inspect/profiles/list_test.go
  pkg/skaffold/inspect/types.go
  pkg/skaffold/parser/config.go
  pkg/skaffold/parser/types.go
Labels: cla: yes, size/L

#5972 Buildpacks builder supports mounting read/write volumes (experimental)
  docs/content/en/schemas/v2beta17.json
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/lifecycle_test.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L

#5964 make sure SkaffoldLogEvent types go through correct endpoint
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/logger_test.go
Labels: cla: yes, size/S

#5961 Emit status check subtask events for V2 API
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/status/status_check.go
  pkg/skaffold/errors/errors.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/status_check.go
  pkg/skaffold/event/v2/status_check_test.go
Labels: cla: yes, size/L

#5981 Construct ColorPicker without images
  pkg/skaffold/kubernetes/colorpicker.go
  pkg/skaffold/kubernetes/colorpicker_test.go
  pkg/skaffold/kubernetes/logger/log.go
Labels: cla: yes, size/S

#5982 release: v1.26.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/backend/Gemfile.lock
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L

#5976 add skaffold+minikube integration tests built on gh actions
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
Labels: cla: yes, size/L

#5978 Use golang:1.15-alpine in proto gen
  hack/proto/Dockerfile
Labels: cla: yes, size/XS

#5987 fix issues in `inspect build-env add cluster` command
  cmd/skaffold/app/cmd/inspect_build_env.go
  integration/inspect_test.go
  integration/testdata/inspect/cluster/skaffold.add.default.yaml
  integration/testdata/inspect/cluster/skaffold.add.profile.yaml
  integration/testdata/inspect/cluster/skaffold.cluster.yaml
  integration/testdata/inspect/cluster/skaffold.local.yaml
  integration/testdata/inspect/cluster/skaffold.modified.default.yaml
  integration/testdata/inspect/cluster/skaffold.modified.profile.yaml
  integration/testdata/inspect/gcb/skaffold.add.default.yaml
  integration/testdata/inspect/gcb/skaffold.add.profile.yaml
  integration/testdata/inspect/gcb/skaffold.gcb.yaml
  integration/testdata/inspect/gcb/skaffold.local.yaml
  integration/testdata/inspect/gcb/skaffold.modified.default.yaml
  integration/testdata/inspect/gcb/skaffold.modified.profile.yaml
  pkg/skaffold/inspect/buildEnv/add_cluster.go
Labels: cla: yes

#5974 Move PodSelector into Deployer
  integration/render_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/kubernetes/image_list.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/new_test.go
  pkg/skaffold/runner/v1/runner.go
  testutil/checks.go
Labels: cla: yes, size/L

#5991 Update Jib to 3.1.0
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#5990 Move Logger from Runner into Deployer
  integration/dev_test.go
  integration/render_test.go
  integration/skaffold/helper.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/watcher.go
  pkg/skaffold/log/log.go
  pkg/skaffold/log/logger_mux.go
  pkg/skaffold/log/provider.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/logger.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/new_test.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: cla: yes, size/XL

#5993 Clear `ApplicationLogEvent` and `SkaffoldLogEvent` buffers on new dev iteration
  pkg/skaffold/event/v2/event.go
Labels: cla: yes, size/XS

#5996 Re-use key created for a release.
  deploy/setup-secret.sh
Labels: cla: yes, size/S

#6002 fix command example
  cmd/skaffold/app/cmd/inspect_build_env.go
Labels: cla: yes, size/XS

#6008 Cherry pick patch release commits
  cmd/skaffold/app/cmd/inspect_build_env.go
  deploy/setup-secret.sh
  integration/inspect_test.go
  integration/testdata/inspect/cluster/skaffold.add.default.yaml
  integration/testdata/inspect/cluster/skaffold.add.profile.yaml
  integration/testdata/inspect/cluster/skaffold.cluster.yaml
  integration/testdata/inspect/cluster/skaffold.local.yaml
  integration/testdata/inspect/cluster/skaffold.modified.default.yaml
  integration/testdata/inspect/cluster/skaffold.modified.profile.yaml
  integration/testdata/inspect/gcb/skaffold.add.default.yaml
  integration/testdata/inspect/gcb/skaffold.add.profile.yaml
  integration/testdata/inspect/gcb/skaffold.gcb.yaml
  integration/testdata/inspect/gcb/skaffold.local.yaml
  integration/testdata/inspect/gcb/skaffold.modified.default.yaml
  integration/testdata/inspect/gcb/skaffold.modified.profile.yaml
  pkg/skaffold/inspect/buildEnv/add_cluster.go
Labels: cla: yes

#6007 Update Jib versions to 3.1.1
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: cla: yes, size/S

#5953 [v3] Add proto for render error code and suggestions.
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/renderer_test.go
  pkg/skaffold/render/validate/validate.go
  pkg/skaffold/render/validate/validate_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes

#6006 Emit `PortFowardEvent`s for API V2
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
Labels: cla: yes, size/M

#6014 fix `setup-secret.sh` script
  .gitignore
  deploy/setup-secret.sh
Labels: cla: yes, size/M

#6010 fix status-check to return success only on exact success criteria match
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  pkg/skaffold/deploy/status/status_check.go
Labels: cla: yes, size/L

#6020 Fix panic on nil dereference in debugging.ContainerManager
  pkg/skaffold/kubernetes/debugging/container_manager.go
Labels: cla: yes, size/S

#6022 Update to github.com/gogo/protobuf v1.3.2 (GO-2021-0053)
  go.mod
  go.sum
Labels: cla: yes, size/XS

#5965 use event writer in skaffold execution
  pkg/skaffold/build/result.go
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/event/v2/build.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/output/output.go
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/S

#6021 Move Debugger from Runner into Deployer
  integration/debug_test.go
  pkg/skaffold/debug/annotations/annotations.go
  pkg/skaffold/debug/apply_transforms.go
  pkg/skaffold/debug/cnb.go
  pkg/skaffold/debug/cnb_test.go
  pkg/skaffold/debug/debug.go
  pkg/skaffold/debug/debug_test.go
  pkg/skaffold/debug/debugger_mux.go
  pkg/skaffold/debug/provider.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_netcore.go
  pkg/skaffold/debug/transform_netcore_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
  pkg/skaffold/debug/transform_test.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/kubernetes/debugging/container_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: cla: yes, size/XL

#6023 fix: gcb api throttling retry backoff not implemented correctly
  pkg/skaffold/build/gcb/cloud_build.go
Labels: cla: yes, size/XS

#6017 Document Helm image reference strategies
  docs/content/en/docs/pipeline-stages/deployers/helm.md
Labels: cla: yes, size/L

#6033 Refactor runID usage, populate runID field in metadata event
  pkg/skaffold/deploy/label/labeller.go
  pkg/skaffold/deploy/status/status_check_test.go
  pkg/skaffold/event/v2/config.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/event_test.go
  pkg/skaffold/event/v2/metadata.go
  pkg/skaffold/event/v2/metadata_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/new.go
  testutil/event/config.go
Labels: cla: yes, size/M

#6026 Convert PortForwarder to Accessor, move to Deployer
  pkg/skaffold/access/access.go
  pkg/skaffold/access/access_mux.go
  pkg/skaffold/access/provider.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/label/labeller.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/entry_manager_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager_test.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/port_forward_integration.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/dev.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: cla: yes, size/L

#6027 send fully formatted output of application log through event stream
  pkg/skaffold/event/v2/application_logs.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/logger/log_test.go
  pkg/skaffold/output/color.go
  pkg/skaffold/output/color_test.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/L

#6037 Add description for status check `TaskEvent`, fix casing for build event description
  pkg/skaffold/runner/build_deploy.go
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/XS

#6042 Add dependency on ko
  go.mod
  go.sum
  pkg/skaffold/build/ko/ko.go
  pkg/skaffold/build/ko/ko_test.go
Labels: cla: yes, size/M

#6038 add gh actions early success if change is docs only
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
Labels: cla: yes, size/M

#6035 Log when unable to retrieve access token
  pkg/skaffold/gcp/auth.go
Labels: cla: yes, size/XS

#6058 fix invalid config version links in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: cla: yes, size/XS

#6044 refactor: move status-checker under deployer
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/resource/deployment.go
  pkg/skaffold/deploy/util/logfile_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/kubernetes/status/status_check_test.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/v1/apply.go
  pkg/skaffold/runner/v1/deploy.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/runner_test.go
  pkg/skaffold/status/provider.go
  pkg/skaffold/status/provider_test.go
  pkg/skaffold/status/status.go
  pkg/skaffold/status/status_mux.go
  pkg/skaffold/status/status_mux_test.go
Labels: cla: yes, size/XL

#6059 add error code for exec format error
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/diag/validator/pod.go
  pkg/diag/validator/pod_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes, size/L

#6049 Rename build_deploy.go to build.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/v1/build_test.go
Labels: cla: yes

#6064 Ensure events are serialized
  pkg/skaffold/event/event.go
  pkg/skaffold/event/v2/event.go
Labels: cla: yes, size/M

#6063 Enable init flags `XXenableJibInit` and `XXenableBuildpacksInit` by default
  cmd/skaffold/app/cmd/init.go
  cmd/skaffold/app/cmd/init_test.go
Labels: cla: yes, size/S

#6061 Ensure output stream is set before port forwarding
  integration/dev_test.go
  pkg/skaffold/kubernetes/portforward/entry_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder_test.go
  pkg/skaffold/kubernetes/portforward/resource_forwarder_test.go
  pkg/skaffold/runner/v1/dev.go
Labels: cla: yes, size/M

#6051 [v2] Add transformer in renderer step.
  hack/versions/pkg/schema/check.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/transform/transform.go
  pkg/skaffold/render/transform/transform_test.go
  pkg/skaffold/render/validate/validate.go
  pkg/skaffold/schema/latest/v2/config.go
  pkg/skaffold/schema/v3alpha1/config.go
Labels: cla: yes, size/L

#6071 Use StdEncoding for git hash directory name
  pkg/skaffold/git/gitutil.go
Labels: cla: yes, size/XS

#6046 Updates to ko builder design proposal to add implementation approach
  docs/design_proposals/ko-builder.md
Labels: cla: yes, size/L

#6055 add custom parameters to structured tests
  docs/content/en/docs/pipeline-stages/testers/structure.md
  docs/content/en/samples/testers/structure/structureTestArgs.yaml
  docs/content/en/schemas/v2beta18.json
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/test/structure/structure_test.go
Labels: cla: yes, size/L

#6024 Fix setting `kubeContext` in skaffold
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/kubernetes/context/context.go
  pkg/skaffold/kubernetes/context/context_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/runcontext/context_test.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/new_test.go
  pkg/skaffold/status/provider.go
  pkg/skaffold/status/provider_test.go
Labels: cla: yes, size/XXL

#6075 Minor cleanup to structure tests
  pkg/skaffold/test/structure/structure_test.go
Labels: cla: yes, size/M

#6031 Add skaffold triage party config to skaffold repo
  deploy/triage-party/skaffold.yaml
Labels: cla: yes, size/XL

#6065 Fill id field for `StatusCheckSubtaskEvent`s
  pkg/skaffold/event/v2/status_check.go
  pkg/skaffold/kubernetes/status/status_check.go
Labels: cla: yes, size/XS

#6073 Use non alpine image and protoc 3.17.3 in proto generation
  hack/proto/Dockerfile
  proto/v1/skaffold.pb.go
  proto/v1/skaffold.pb.gw.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.pb.gw.go
Labels: cla: yes, size/L

#6076 Remove podSelector from Runner
  integration/render_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/v1/deploy_test.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/runner/v1/runner.go
  testutil/checks.go
Labels: cla: yes, size/L

#6084 fix v3alpha version
  pkg/skaffold/schema/versions.go
Labels: cla: yes, size/XS

#6080 Put `-f skaffold-overrides.yaml` at end of helm arg list
  pkg/skaffold/deploy/helm/args.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/M

#6093 GCB project guessing should support Artifact Registry images
  pkg/skaffold/gcp/projectid.go
  pkg/skaffold/gcp/projectid_test.go
Labels: cla: yes, size/XS

#6087 add source file and module to config parsing error description
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/runner.go
  pkg/skaffold/schema/validation/samples_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: cla: yes, size/L

#6090 fix: port-forward for multi-config projects
  pkg/skaffold/access/provider.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/runner/v1/new.go
Labels: cla: yes, size/L

#6094 Fix instructions to add actionable error codes.
  DEVELOPMENT.md
Labels: cla: yes, size/M

#6101 Escape parentheses in shJoin
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_test.go
Labels: cla: yes, size/XS

#6104 Fetch and set up secret for skaffold-metrics project
  deploy/setup-secret.sh
Labels: cla: yes, size/XS

#6105 Fix typo in executed file name
  DEVELOPMENT.md
Labels: cla: yes, size/XS

#6083 Add node selector option for building image on k8s cluster with Kaniko.
  docs/content/en/schemas/v2beta18.json
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/S

#6043 Fix 4979 render should validate manifests
  cmd/skaffold/app/cmd/fix.go
  cmd/skaffold/app/cmd/runner.go
  cmd/skaffold/app/cmd/runner_test.go
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/schema/validation/samples_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes, size/M

#6108 log metrics upload failure and write to file instead.
  pkg/skaffold/instrumentation/export.go
Labels: cla: yes, size/XS

#6106 Optimize k8s-skaffold/skaffold image
  deploy/skaffold/Dockerfile
Labels: cla: yes, size/S

#6109 release: v1.27.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/build.gradle
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/pom.xml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/pom.xml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/backend/Gemfile.lock
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L

#6111 Add information about workspace and dockerfile to artifact metadata
  pkg/skaffold/event/v2/metadata.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: cla: yes, size/L
