Repository GoogleContainerTools/skaffold, pull requests merged in 2021-09, with the labels that each got.

#6540 docs: fix duplicate subpage listing
  docs/config.toml
  docs/content/en/docs/design/_index.md
  docs/content/en/docs/tutorials/_index.md
  docs/content/en/docs/workflows/_index.md
Labels: cla: yes, size/M

#6550 Use `ResourceStatusCheckEvent[Updated/Completed]` where appropriate
  pkg/skaffold/kubernetes/status/resource/deployment.go
  pkg/skaffold/kubernetes/status/status_check.go
Labels: cla: yes, size/S

#6559 docs: use dropdown menu for selecting version
  docs/layouts/partials/page-meta-links.html
  docs/static/javascripts/schemas.js
Labels: cla: yes, size/M

#6560 Use dlog to parse docker container logs
  go.mod
  go.sum
  pkg/skaffold/docker/logger/log.go
Labels: cla: yes, size/XS

#6522 Make inputDigest hash calculation independent of workspace path
  pkg/skaffold/tag/input_digest.go
  pkg/skaffold/tag/input_digest_test.go
Labels: cla: yes, size/M

#6575 fix: linters for go1.17
  cmd/skaffold/app/signals_test.go
  hack/boilerplate/boilerplate.py
  hack/tools/tools.go
  pkg/skaffold/build/jib/jib_non_windows_test.go
  pkg/skaffold/build/jib/jib_windows_test.go
  pkg/skaffold/gcp/auth_test.go
  pkg/skaffold/kubectl/exec.go
  pkg/skaffold/tag/git_commit_test.go
  pkg/skaffold/tags/paths_test.go
  pkg/skaffold/util/wrapper_unix.go
  pkg/skaffold/util/wrapper_unix_test.go
  pkg/skaffold/util/wrapper_windows_test.go
Labels: cla: yes, size/S

#6574 fix: iterative-status-check only for deployers defining hooks
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
Labels: cla: yes, size/L

#6555 Fix issue 6513 - CI/CD page readability
  docs/content/en/docs/workflows/ci-cd.md
  docs/layouts/partials/hooks/head-end.html
  docs/static/javascripts/fade.js
  docs/static/stylesheets/line-spacing.css
Labels: cla: yes, size/S

#6548 Run CodeQL analysis nightly and cache the go modules cache
  .github/workflows/codeql-analysis.yml
Labels: cla: yes, size/S

#6563 Detect ko images for debugging, by envvar
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
Labels: cla: yes, size/XS

#6569 Detect ko images for debugging, by image author
  pkg/skaffold/debug/apply_transforms.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
Labels: cla: yes, size/S

#6452 New config option deploy.transformableAllowList
  docs/content/en/schemas/v2beta23.json
  pkg/skaffold/deploy/deploy_problems_test.go
  pkg/skaffold/deploy/types/types.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/runner_test.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/L

#6546 Ko builder: Add Env, Flags, and Ldflags config
  docs/design_proposals/ko-builder.md
  go.mod
  go.sum
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/builder_test.go
  pkg/skaffold/build/ko/schema/temporary.go
Labels: cla: yes, size/L

#6577 docs: mention hooks don't run on cached artifacts
  docs/content/en/docs/pipeline-stages/lifecycle-hooks.md
Labels: cla: yes, size/XS

#6357 Write a custom lint rule to disable use of logrus package
  cmd/skaffold/app/cmd/cmd.go
  hack/golangci-lint.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/linters/logrus.go
  hack/tools/logrus_analyzer.go
  pkg/skaffold/build/cluster/logs.go
  pkg/skaffold/build/cluster/logs_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/kubernetes/debugging/transform.go
  pkg/skaffold/kubernetes/portforward/kubectl_forwarder.go
  pkg/skaffold/output/log/log.go
  pkg/skaffold/output/log/log_test.go
  pkg/skaffold/tag/util/util.go
  pkg/skaffold/warnings/warnings.go
Labels: cla: yes, size/L

#6585 Updates skaffold.yaml example in helm section
  docs/content/en/docs/pipeline-stages/deployers/helm.md
Labels: cla: yes, size/XS

#6581 Persist EventV2 logs when `--event-log-file` exists
  pkg/skaffold/server/server.go
Labels: cla: yes, size/XS

#6561 add testType field to skaffold inspect tests output
  pkg/skaffold/inspect/tests/list.go
  pkg/skaffold/inspect/tests/list_test.go
Labels: cla: yes, size/S

#6582 Updating load images to use only local images
  pkg/skaffold/runner/v1/deploy.go
Labels: cla: yes, size/XS

#6592 Fix wrong link on the custom-tests example, fixes #6591
  examples/custom-tests/README.md
Labels: cla: yes, size/XS

#6587 fix: treat pod deletion as if its containers were terminated
  pkg/skaffold/kubernetes/debugging/container_manager.go
  pkg/skaffold/kubernetes/debugging/container_manager_test.go
  pkg/skaffold/kubernetes/watcher.go
Labels: cla: yes, size/L

#6590 Make TestHelmDeploy hermetic
  Makefile
  pkg/skaffold/deploy/helm/helm_test.go
Labels: cla: yes, size/XS

#6459 api: Strict port number handling and --enable-rpc deprecation
  cmd/skaffold/app/cmd/debug_test.go
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/init_test.go
  docs/content/en/docs/design/api.md
  docs/content/en/docs/references/cli/_index.md
  integration/debug_test.go
  integration/port_forward_test.go
  integration/rpc_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/config/types.go
  pkg/skaffold/config/types_test.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/hooks/env.go
  pkg/skaffold/hooks/env_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/server/server.go
  pkg/skaffold/server/server_test.go
Labels: !! do-not-merge !!, cla: yes, size/L

#6599 Extend `--artifact` API schema to allow for manifest generation
  integration/init_test.go
  pkg/skaffold/initializer/build/builders.go
  pkg/skaffold/initializer/build/cli.go
  pkg/skaffold/initializer/build/init.go
  pkg/skaffold/initializer/build/init_test.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/build/util.go
  pkg/skaffold/initializer/config_test.go
  pkg/skaffold/initializer/init.go
Labels: cla: yes, size/L

#6528 Implement Debugger for Docker Deployer
  cmd/skaffold/app/cmd/debug.go
  docs/content/en/schemas/v2beta23.json
  integration/debug_test.go
  integration/diagnose_test.go
  integration/testdata/debug/skaffold.yaml
  integration/util.go
  pkg/skaffold/build/docker/docker_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/debug/apply_transforms.go
  pkg/skaffold/deploy/deploy_problems_test.go
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/docker/port.go
  pkg/skaffold/deploy/docker/port_test.go
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/debugger/adapter.go
  pkg/skaffold/docker/debugger/debug.go
  pkg/skaffold/docker/debugger/debug_test.go
  pkg/skaffold/docker/debugger/transform.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/kubernetes/debugging/transform.go
  pkg/skaffold/kubernetes/debugging/transform_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/new.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/util/port.go
Labels: cla: yes, size/XXL

#6583 Allow multiple docker secrets - #6498
  docs/content/en/schemas/v2beta23.json
  integration/testdata/build/secret/Dockerfile
  integration/testdata/build/secret/mysecondsecret.txt
  integration/testdata/build/secret/skaffold.yaml
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/schema/v2beta22/upgrade.go
  pkg/skaffold/schema/v2beta22/upgrade_test.go
Labels: cla: yes, size/M

#6606 fix: add podforwaders correctly for multimodule projects
  pkg/skaffold/deploy/component/kubernetes/component.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager.go
  pkg/skaffold/kubernetes/portforward/forwarder_manager_test.go
Labels: cla: yes, size/M

#6578 Improves code coverage (a little bit)
  pkg/skaffold/diagnose/diagnose_test.go
Labels: cla: yes, size/XS

#6608 Drop codecov threshold to 30%
  codecov.yml
Labels: cla: yes, size/XS

#6611 Clean up deps
  go.mod
  go.sum
Labels: cla: yes, size/XS

#6595 Ko: disable compiler optimizations and inlining when debugging
  docs/design_proposals/ko-builder.md
  pkg/skaffold/build/ko/build_test.go
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/builder_test.go
  pkg/skaffold/build/ko/ko.go
  pkg/skaffold/build/ko/ko_test.go
Labels: cla: yes, size/M

#6593 Rename ko builder `target` field to `main`
  docs/design_proposals/ko-builder.md
  pkg/skaffold/build/ko/build.go
  pkg/skaffold/build/ko/build_test.go
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/schema/temporary.go
Labels: cla: yes, size/M

#6596 Ko builder support for insecure registries
  pkg/skaffold/build/ko/build_test.go
  pkg/skaffold/build/ko/ko.go
  pkg/skaffold/build/ko/ko_test.go
  pkg/skaffold/build/ko/publisher.go
  pkg/skaffold/build/ko/publisher_test.go
Labels: cla: yes, size/L

#6613 Add initial docs for Docker deployer
  docs/content/en/docs/pipeline-stages/deployers/_index.md
  docs/content/en/docs/pipeline-stages/deployers/docker.md
  docs/content/en/samples/deployers/docker.yaml
  docs/data/maturity.json
Labels: cla: yes, size/M

#6620 Check for nil when retrieving docker support mounts
  pkg/skaffold/docker/debugger/debug.go
  pkg/skaffold/docker/debugger/debug_test.go
Labels: cla: yes, size/XS

#6597 Add image label support to ko builder
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/builder_test.go
Labels: cla: yes, size/M

#6618 fix: remove "managed-by" fixing helm conflict (fixes #6421)
  integration/render_test.go
  pkg/skaffold/deploy/label/labeller.go
  pkg/skaffold/sync/sync_test.go
Labels: cla: yes, size/S

#6630 Update pack image to v0.21.1
  deploy/buildpacks/publish.sh
Labels: cla: yes, size/XS

#6621 Create port map on container config if empty
  pkg/skaffold/deploy/docker/port.go
  pkg/skaffold/deploy/docker/port_test.go
Labels: cla: yes, size/M

#6631 chore: update skaffold Q4 planning board
  deploy/triage-party/skaffold.yaml
Labels: cla: yes, size/S

#6625 refactor: Rename a couple of scripts for consistency
  DEVELOPMENT.md
  hack/boilerplate/boilerplate.py
  hack/golangci-lint.sh
  hack/install-golint.sh
  hack/new-version.sh
  hack/versions/pkg/schema/check.go
Labels: cla: yes, size/XS

#6632 feat:(build/docker): support env as secret source
  docs/content/en/schemas/v2beta24.json
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: cla: yes, size/S

#6643 fix: Wait for context cancel in k8s pod watcher
  pkg/skaffold/kubernetes/debugging/container_manager.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder.go
  pkg/skaffold/kubernetes/portforward/pod_forwarder_test.go
  pkg/skaffold/kubernetes/watcher.go
  pkg/skaffold/kubernetes/watcher_test.go
Labels: cla: yes, size/L

#6651 fix: properly generate enums for config schemas when running `make generate-schemas`
  docs/content/en/schemas/v2beta10.json
  docs/content/en/schemas/v2beta11.json
  docs/content/en/schemas/v2beta12.json
  docs/content/en/schemas/v2beta13.json
  docs/content/en/schemas/v2beta14.json
  docs/content/en/schemas/v2beta15.json
  docs/content/en/schemas/v2beta16.json
  docs/content/en/schemas/v2beta17.json
  docs/content/en/schemas/v2beta18.json
  docs/content/en/schemas/v2beta19.json
  docs/content/en/schemas/v2beta20.json
  docs/content/en/schemas/v2beta21.json
  docs/content/en/schemas/v2beta22.json
  docs/content/en/schemas/v2beta23.json
  docs/content/en/schemas/v2beta24.json
  docs/content/en/schemas/v2beta3.json
  docs/content/en/schemas/v2beta4.json
  docs/content/en/schemas/v2beta5.json
  docs/content/en/schemas/v2beta6.json
  docs/content/en/schemas/v2beta7.json
  docs/content/en/schemas/v2beta8.json
  docs/content/en/schemas/v2beta9.json
  hack/schemas/main.go
Labels: cla: yes, size/XL

#6645 feat: add preliminary support for Config Connector service KRM
  pkg/skaffold/kubernetes/manifest/visitor.go
  pkg/skaffold/kubernetes/manifest/visitor_test.go
Labels: cla: yes, size/L

#6656 fix: fix unit test for skaffold inspect tests list
  pkg/skaffold/inspect/tests/list_test.go
Labels: cla: yes, size/S
