Repository GoogleContainerTools/skaffold, pull requests merged in 2021-10, with the labels that each got.

#6658 fix: Use gcloud spec pool instead of deprecated WorkerPool
  pkg/skaffold/build/gcb/spec.go
Labels: cla: yes, size/XS

#6605 Support globstar in dependencies for file watching
  pkg/skaffold/build/list/list.go
  pkg/skaffold/build/list/list_test.go
Labels: cla: yes, size/L

#6665 fix: change init builder-prompt to a single-select
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/prompt/prompt.go
  pkg/skaffold/initializer/prompt/prompt_test.go
Labels: cla: yes, size/M

#6647 feat: Add ko artifact type to schema
  docs/content/en/schemas/v2beta24.json
  pkg/skaffold/build/ko/build.go
  pkg/skaffold/build/ko/build_test.go
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/builder_test.go
  pkg/skaffold/build/ko/schema/temporary.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/schema/latest/v2/config.go
Labels: cla: yes, size/L

#6663 chore: log errors when retrieving build logs
  pkg/skaffold/build/result.go
Labels: cla: yes, size/XS

#6669 revert: fix: change init builder-prompt to a single-select
  pkg/skaffold/initializer/build/builders_test.go
  pkg/skaffold/initializer/build/resolve.go
  pkg/skaffold/initializer/prompt/prompt.go
  pkg/skaffold/initializer/prompt/prompt_test.go
Labels: cla: yes, size/M

#6617 Ko builder: Implement file watch dependencies
  docs/design_proposals/ko-builder.md
  pkg/skaffold/build/ko/dependencies.go
  pkg/skaffold/build/ko/dependencies_test.go
  pkg/skaffold/build/ko/ko.go
Labels: cla: yes, size/L

#6133 Validate changed examples with "local" builder
  .github/workflows/verify-examples.yml
Labels: cla: yes, size/M, triage/discuss

#6649 doc: document Helm deployer's IMAGE_NAME<N>, IMAGE_TAG<N>, IMAGE_DIGEST<N>
  docs/content/en/docs/environment/templating.md
Labels: cla: yes, size/XS

#6664 feat: Add distinct error codes for GCB failures
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/build/gcb/cloud_build.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: cla: yes, size/XXL

#6673 fix: correct ko package imports and logging function call
  pkg/skaffold/build/ko/dependencies.go
  pkg/skaffold/build/ko/dependencies_test.go
  pkg/skaffold/build/result.go
Labels: cla: yes, size/S

#6674 fix: ensure run-id is added to resources in skaffold apply
  cmd/skaffold/app/cmd/flags.go
  integration/apply_test.go
  integration/render_test.go
  integration/testdata/apply/deployment.yaml
  integration/testdata/apply/skaffold.yaml
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/new.go
Labels: cla: yes, size/L

#6678 fix: Sanitize image names when default repo unset
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/build/scheduler_test.go
Labels: cla: yes, size/S

#6779 docs: skaffold apply supports status check
  docs/content/en/docs/workflows/ci-cd.md
Labels: cla: yes, size/XS

#6774 chore: add script to improve QOL when doing release
  hack/release.sh
  hack/release/changelog/main.go
  hack/release/changelog/main_test.go
  hack/release/changelog/template.md
  hack/release/changelog/testdata/changelog.md
  hack/release/changelog/testdata/expected.md
  hack/versions/pkg/schema/version.go
Labels: cla: yes, size/L

#6744 chore: make test env check output what was found
  pkg/skaffold/build/docker/docker_test.go
  testutil/cmd_helper.go
Labels: cla: yes, size/S
