Repository GoogleContainerTools/skaffold, pull requests merged in 2022-05, with the labels that each got.

#7363 chore: reenable TestDeployTailDefaultNamespace
  integration/deploy_test.go
Labels: size/XS

#7328 feat: add new skaffold verify command and verify phase
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/verify.go
  docs/content/en/docs/references/cli/_index.md
  go.mod
  go.sum
  hack/golangci.yml
  integration/skaffold/helper.go
  integration/testdata/verify-fail/skaffold.yaml
  integration/testdata/verify-succeed/skaffold.yaml
  integration/verify_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/docker/deploy_test.go
  pkg/skaffold/deploy/docker/port/port.go
  pkg/skaffold/deploy/docker/port/port_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/logger/log.go
  pkg/skaffold/event/v2/event.go
  pkg/skaffold/event/v2/state.go
  pkg/skaffold/event/v2/state_test.go
  pkg/skaffold/event/v2/verify.go
  pkg/skaffold/runner/runcontext/v2/context.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/v2/new.go
  pkg/skaffold/runner/v2/runner.go
  pkg/skaffold/runner/v2/verify.go
  pkg/skaffold/runner/verifier.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/verify/docker/verify.go
  pkg/skaffold/verify/verify.go
  pkg/skaffold/verify/verify_mux.go
  pkg/skaffold/verify/verify_mux_test.go
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: size/XXL

#7365 ci: fix vulnerability in performance comparison script
  .github/workflows/performance-comparison.yml
Labels: size/XS

#7370 ci: reenable `TestRunTail` integration test
  integration/run_test.go
Labels: size/XS

#7371 ci: fix and reenable `TestControlAPIManualTriggers`
  integration/control_api_test.go
  integration/testdata/dev/skaffold.yaml
Labels: size/XS

#7362 fix: no colored output with concurrency!=1
  pkg/skaffold/build/result.go
Labels: size/XS

#7373 ci: introduce scorecard gh action for security scanning
  .github/workflows/scorecards.yml
Labels: size/M

#7372 chore: include `fs/assets/check.txt` in `.gitignore`
  .gitignore
Labels: size/XS

#7334 feat: support the contextSubPath param in the Kaniko Artifact
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/gcb/kaniko.go
  pkg/skaffold/build/kaniko/args.go
  pkg/skaffold/build/kaniko/args_test.go
  pkg/skaffold/build/kaniko/utils.go
  pkg/skaffold/build/kaniko/utils_test.go
  pkg/skaffold/docker/build_args.go
  pkg/skaffold/graph/dependencies.go
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#7350 feat: helm init without artifact image overrides.
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/initializer/analyze/analyze.go
  pkg/skaffold/initializer/analyze/helm.go
  pkg/skaffold/initializer/deploy/helm.go
  pkg/skaffold/initializer/deploy/helm_test.go
  pkg/skaffold/initializer/deploy/init.go
  pkg/skaffold/initializer/deploy/testutil.go
  pkg/skaffold/initializer/errors/errors.go
  pkg/skaffold/initializer/helm_test.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/initializer/testdata/init/helm-deployment/skaffold.yaml
  pkg/skaffold/initializer/transparent_test.go
Labels: size/XL

#7361 fix: Update Golang-based examples to use go.mod
  integration/examples/compose/Dockerfile
  integration/examples/compose/go.mod
  integration/examples/cross-platform-builds/Dockerfile
  integration/examples/cross-platform-builds/go.mod
  integration/examples/custom-buildx/Dockerfile
  integration/examples/custom-buildx/go.mod
  integration/examples/custom-tests/Dockerfile
  integration/examples/custom-tests/go.mod
  integration/examples/docker-deploy/bert/Dockerfile
  integration/examples/docker-deploy/bert/go.mod
  integration/examples/docker-deploy/ernie/Dockerfile
  integration/examples/docker-deploy/ernie/go.mod
  integration/examples/gcb-kaniko/Dockerfile
  integration/examples/gcb-kaniko/go.mod
  integration/examples/generate-pipeline/Dockerfile
  integration/examples/generate-pipeline/go.mod
  integration/examples/getting-started-kustomize/app/Dockerfile
  integration/examples/getting-started-kustomize/app/go.mod
  integration/examples/getting-started/Dockerfile
  integration/examples/getting-started/go.mod
  integration/examples/google-cloud-build/Dockerfile
  integration/examples/google-cloud-build/go.mod
  integration/examples/helm-deployment/Dockerfile
  integration/examples/helm-deployment/go.mod
  integration/examples/kaniko/Dockerfile
  integration/examples/kaniko/go.mod
  integration/examples/lifecycle-hooks/Dockerfile
  integration/examples/lifecycle-hooks/go.mod
  integration/examples/microservices/leeroy-app/Dockerfile
  integration/examples/microservices/leeroy-app/go.mod
  integration/examples/microservices/leeroy-web/Dockerfile
  integration/examples/microservices/leeroy-web/go.mod
  integration/examples/multi-config-microservices/leeroy-app/Dockerfile
  integration/examples/multi-config-microservices/leeroy-app/go.mod
  integration/examples/multi-config-microservices/leeroy-web/Dockerfile
  integration/examples/multi-config-microservices/leeroy-web/go.mod
  integration/examples/profile-patches/base-service/Dockerfile
  integration/examples/profile-patches/base-service/go.mod
  integration/examples/profile-patches/hello-service/Dockerfile
  integration/examples/profile-patches/hello-service/go.mod
  integration/examples/profile-patches/world-service/Dockerfile
  integration/examples/profile-patches/world-service/go.mod
  integration/examples/profiles/hello-service/Dockerfile
  integration/examples/profiles/hello-service/go.mod
  integration/examples/profiles/world-service/Dockerfile
  integration/examples/profiles/world-service/go.mod
  integration/examples/simple-artifact-dependency/app/Dockerfile
  integration/examples/simple-artifact-dependency/app/go.mod
  integration/examples/structure-tests/Dockerfile
  integration/examples/structure-tests/go.mod
  integration/examples/tagging-with-environment-variables/Dockerfile
  integration/examples/tagging-with-environment-variables/go.mod
Labels: size/L

#7389 docs: fix ko multi-platform example
  docs/content/en/samples/builders/ko-platforms.yaml
Labels: size/XS

#7377 chore: update render and deploy documentation to properly reflect v2 funcitonality
  docs-v2/content/en/docs/pipeline-stages/deployers/_index.md
  docs-v2/content/en/docs/pipeline-stages/deployers/kpt.md
  docs-v2/content/en/docs/pipeline-stages/deployers/kustomize.md
  docs-v2/content/en/docs/pipeline-stages/renderers/_index.md
  docs-v2/content/en/docs/pipeline-stages/renderers/docker.md
  docs-v2/content/en/docs/pipeline-stages/renderers/helm.md
  docs-v2/content/en/docs/pipeline-stages/renderers/kpt.md
  docs-v2/content/en/docs/pipeline-stages/renderers/kubectl.md
  docs-v2/content/en/docs/pipeline-stages/renderers/kustomize.md
  docs-v2/content/en/docs/pipeline-stages/renderers/rawYaml.md
  docs-v2/content/en/samples/deployers/kpt.yaml
  docs-v2/content/en/samples/renderers/docker.yaml
  docs-v2/content/en/samples/renderers/helm.yaml
  docs-v2/content/en/samples/renderers/kpt.yaml
  docs-v2/content/en/samples/renderers/kustomize.yaml
  docs-v2/content/en/samples/renderers/rawYaml.yaml
Labels: size/L

#7393 fix: fetch images by platform tag when using` --platform`
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/cache/details.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/custom/build.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/jib/gradle.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/maven.go
  pkg/skaffold/build/jib/maven_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_util.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/docker/remote_test.go
  pkg/skaffold/runner/v2/render.go
  pkg/skaffold/util/platform.go
Labels: size/L

#7402 fix: change error to warning for build platform mismatch with cluster node platform
  pkg/skaffold/platform/resolver.go
  pkg/skaffold/platform/resolver_test.go
Labels: size/XS

#7399 fix: TestModules integration tests
  integration/modules_test.go
  integration/render_test.go
  integration/testdata/modules/app1/skaffold.yaml
  integration/testdata/modules/app2/skaffold.yaml
  integration/testdata/modules/app3/skaffold.yaml
  integration/testdata/modules/skaffold.yaml
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/render/config.go
  pkg/skaffold/render/renderer/kpt/kpt.go
  pkg/skaffold/render/renderer/kpt/kpt_test.go
  pkg/skaffold/render/renderer/kubectl/kubectl.go
  pkg/skaffold/render/renderer/kubectl/kubectl_test.go
  pkg/skaffold/render/renderer/noop/noop.go
  pkg/skaffold/render/renderer/render_mux.go
  pkg/skaffold/render/renderer/render_mux_test.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/runner/renderer.go
  pkg/skaffold/runner/runcontext/v2/context.go
  pkg/skaffold/runner/v2/new.go
Labels: size/L

#7396 fix: update pkg/webhook to support previewing v2 docs site from github label
  deploy/docs-v2/cloudbuild-release.yaml
  deploy/docs-v2/cloudbuild.yaml
  deploy/webhook-v2/Dockerfile
  deploy/webhook-v2/cloudbuild.yaml
  deploy/webhook-v2/deployment.yaml
  deploy/webhook-v2/skaffold.yaml
  pkg/webhook/constants/constants.go
  pkg/webhook/kubernetes/deployment.go
  webhook/webhook.go
Labels: size/M

#7404 cherrypick: fix: change error to warning for build platform (#7402)
  pkg/skaffold/platform/resolver.go
  pkg/skaffold/platform/resolver_test.go
Labels: size/XS

#7397 chore: fix TestDockerDebug integration test
  cmd/skaffold/app/cmd/render.go
  integration/debug_test.go
  integration/dev_test.go
  integration/skaffold/helper.go
  integration/testdata/debug/skaffold.yaml
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
Labels: size/M

#7403 fix: `apply` not using config set `kubeContext` or `statusCheck`
  pkg/skaffold/runner/deployer.go
Labels: size/S

#7407 docs: use `image` instead of `imageKey` to improve consistency in Helm documentation
  docs/content/en/docs/pipeline-stages/deployers/helm.md
Labels: size/S

#7391 feat: Initial implementation of Cloud Run deployer
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  integration/deploy_cloudrun_test.go
  integration/testdata/deploy-cloudrun/service.yaml
  integration/testdata/deploy-cloudrun/skaffold.yaml
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/cloudrun/deploy_test.go
  pkg/skaffold/deploy/cloudrun/status.go
  pkg/skaffold/deploy/cloudrun/status_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/schema/latest/config.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XXL

#7415 [V1] refactor: rename helm.Deployer to helm.Deployer3 to prepare for helm31Deployer
  pkg/skaffold/deploy/helm/args.go
  pkg/skaffold/deploy/helm/deploy3base.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: size/M

#7412 chore: disable TestDebugEventsRPC_StatusCheck
  integration/debug_test.go
  integration/examples/multi-config-microservices/leeroy-app/skaffold.yaml
  integration/examples/multi-config-microservices/leeroy-web/skaffold.yaml
  integration/testdata/debug/skaffold.yaml
  pkg/skaffold/build/cache/details.go
Labels: size/M

#7408 fix: integration/sync_file tests
  integration/sync_test.go
  integration/testdata/file-sync/skaffold-infer.yaml
  integration/testdata/file-sync/skaffold-manual.yaml
Labels: size/S

#7411 feat: Add region configuration for gcb
  integration/run_test.go
  integration/testdata/gcp-with-location/Dockerfile
  integration/testdata/gcp-with-location/README.md
  integration/testdata/gcp-with-location/go.mod
  integration/testdata/gcp-with-location/k8s-pod.yaml
  integration/testdata/gcp-with-location/main.go
  integration/testdata/gcp-with-location/skaffold.yaml
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/schema/latest/config.go
Labels: size/M

#7416 fix: correct render output; render func parameters
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/run_test.go
  integration/examples/getting-started/artifacts.json
  integration/examples/getting-started/images.json
  integration/examples/getting-started/skaffold.yaml
  integration/render_test.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/render/renderer/kpt/kpt.go
  pkg/skaffold/render/renderer/kpt/kpt_test.go
  pkg/skaffold/render/renderer/kubectl/kubectl.go
  pkg/skaffold/render/renderer/kubectl/kubectl_test.go
  pkg/skaffold/render/renderer/noop/noop.go
  pkg/skaffold/render/renderer/render_mux.go
  pkg/skaffold/render/renderer/render_mux_test.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
  pkg/skaffold/runner/v2/dev.go
  pkg/skaffold/runner/v2/render.go
  pkg/skaffold/runner/v2/runner_test.go
Labels: size/L

#7414 feat: allow specifying args to be passed to kustomize build
  integration/testdata/debug/skaffold.yaml
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/generate_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v2beta28/upgrade.go
  pkg/skaffold/schema/v2beta28/upgrade_test.go
Labels: size/L

#7423 feat: [V1] Add helm3.1deployer no op
  integration/debug_test.go
  pkg/skaffold/deploy/helm/deploy30.go
  pkg/skaffold/deploy/helm/deploy31.go
  pkg/skaffold/deploy/helm/deploy3base.go
  pkg/skaffold/deploy/helm/deployer.go
  pkg/skaffold/deploy/helm/helm30_test.go
  pkg/skaffold/deploy/helm/helm31_test.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: size/XXL

#7426 chore: remove hydrationDir from kubectl renderer
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
Labels: size/M

#7418 fix: render v2 for multi-config projects
  cmd/skaffold/app/cmd/runner.go
  integration/examples/multi-config-microservices/leeroy-app/skaffold.yaml
  integration/examples/multi-config-microservices/leeroy-web/skaffold.yaml
  integration/testdata/modules/app1/skaffold.yaml
  integration/testdata/modules/app2/skaffold.yaml
  integration/testdata/modules/app3/skaffold.yaml
  pkg/skaffold/schema/defaults/defaults.go
Labels: size/M

#7430 fix: running skaffold from a directory other than repository root
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/bazel/build_test.go
Labels: size/S

#7359 fix/chore: update helm label render logic and refactor test
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: size/XS

#7432 chore: fix integration/test_debug/helm test
  integration/debug_test.go
  integration/skaffold/helper.go
  pkg/skaffold/config/options.go
Labels: size/S

#7438 feat: upgrade pack CLI dependency
  go.mod
  go.sum
Labels: size/XS

#7439 chore: remove debug logging from verify command
  pkg/skaffold/docker/logger/log.go
  pkg/skaffold/verify/docker/verify.go
Labels: size/XS

#7440 feat: Add privateWorkerPool and location configuration for gcb
  docs/content/en/schemas/v2beta29.json
  integration/inspect_test.go
  integration/run_test.go
  integration/testdata/gcb-with-location/Dockerfile
  integration/testdata/gcb-with-location/go.mod
  integration/testdata/gcb-with-location/k8s-pod.yaml
  integration/testdata/gcb-with-location/main.go
  integration/testdata/gcb-with-location/skaffold.yaml
  integration/testdata/inspect/gcb/skaffold.add.default.yaml
  integration/testdata/inspect/gcb/skaffold.add.profile.yaml
  integration/testdata/inspect/gcb/skaffold.gcb.yaml
  integration/testdata/inspect/gcb/skaffold.local.yaml
  integration/testdata/inspect/gcb/skaffold.modified.default.yaml
  integration/testdata/inspect/gcb/skaffold.modified.profile.yaml
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v2beta28/upgrade.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: size/L

#7450 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: size/S

#7463 fix: Fix broken markdown
  docs/content/en/docs/workflows/debug.md
Labels: size/XS
