Repository GoogleContainerTools/skaffold, pull requests merged in 2022-01, with the labels that each got.

#6984 fix: correct $SKIP_TEST env for custom builder
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/v1/dev.go
Labels: size/S

#6976 fix: limit number of simultaneous taggers to GOMAXPROCS
  pkg/skaffold/runner/build.go
Labels: size/S

#6964 feat: monitor OS vulnerability in Skaffold LTS images.
  deploy/lts-vuln-monitor/cloudbuild.yaml
  deploy/lts-vuln-monitor/report.sh
  deploy/lts-vuln-monitor/scan.sh
Labels: size/L

#6993 doc: add some detail to local clusters and minikube docker
  docs/content/en/docs/environment/local-cluster.md
Labels: size/M

#6982 feat: allow specifying hook command directory
  docs/content/en/schemas/v2beta27.json
  integration/examples/lifecycle-hooks/skaffold.yaml
  pkg/skaffold/hooks/host.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: size/S

#6955 feat(lint): added lib for getting yaml line #s for a given schema struct, sub-element and sub-fields. supports patches & profiles
  pkg/skaffold/parser/config.go
  pkg/skaffold/parser/config_test.go
  pkg/skaffold/parser/configlocations/configlocations.go
  pkg/skaffold/parser/types.go
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: size/XL

#6977 feat(lsp): add virtual file system support to ReadConfiguration and use this in LSP for buffer files and lint
  go.mod
  pkg/skaffold/lint/dockerfiles.go
  pkg/skaffold/lint/k8smanifests.go
  pkg/skaffold/lint/lint.go
  pkg/skaffold/lint/skaffoldyamls.go
  pkg/skaffold/lsp/document_manager.go
  pkg/skaffold/lsp/handler.go
  pkg/skaffold/util/config.go
Labels: size/M

#7005 refactor(configlocations): make yamlinfos field private
  pkg/skaffold/parser/config_test.go
  pkg/skaffold/parser/configlocations/configlocations.go
Labels: size/M

#7004 fix: add godoc to Fs var in config.go
  pkg/skaffold/util/config.go
Labels: size/XS

#7000 fix(ci): fix lts image build
  Makefile
Labels: size/XS

#7010 fix(ko): Default repo for pushing `ko://` images
  docs/content/en/docs/pipeline-stages/builders/ko.md
  pkg/skaffold/build/ko/build.go
  pkg/skaffold/build/ko/build_test.go
Labels: size/S

#7011 fix(labelling): hotfix for issues related to deploy erroring due to nested yaml field overriding in StatefulSet w/ PVC
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/kubernetes/manifest/labels.go
  pkg/skaffold/kubernetes/manifest/namespaces.go
  pkg/skaffold/kubernetes/manifest/visitor.go
  pkg/skaffold/kubernetes/manifest/visitor_test.go
Labels: size/M

#7014 fix: unblock cloud build edge builds
  Makefile
Labels: size/XS

#7006 feat: add 'branches' git tag variant
  pkg/skaffold/tag/git_commit.go
  pkg/skaffold/tag/git_commit_test.go
Labels: size/M

#7009 fix(ko): Debug port forwarding for `ko://` images
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/deploy/util/util_test.go
Labels: size/M

#6985 feat: fetch default-repo from local cluster
  pkg/skaffold/config/types.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/runner/runcontext/context.go
Labels: size/L

#7027 fix: allow quotes on base image tags in Dockerfiles
  pkg/skaffold/docker/parse.go
  pkg/skaffold/docker/parse_test.go
Labels: size/XS

#7028 feat(deps): Update Skaffold images to Go 1.17.3
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#7003 feat(validations): add line number output skaffold to validation errors
  integration/build_dependencies_test.go
  pkg/skaffold/parser/configlocations/configlocations.go
  pkg/skaffold/parser/types.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: size/XL

#7025 fix: integration test skaffold config
  integration/testdata/apply/skaffold.yaml
Labels: size/XS

#6914 fix: Allow apply of manifests without file name restrictions (#6871)
  integration/init_test.go
  integration/testdata/init/hello/.deployment.yaml.expected
  pkg/skaffold/kubernetes/util.go
  pkg/skaffold/schema/versions.go
Labels: cla: yes, size/S

#7040 chore: update Jib versions to 3.2.0 in examples
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: size/S

#7044 ci: use consistent go build paths caching
  .github/workflows/codeql-analysis.yml
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
  .github/workflows/integration-windows.yml
  .github/workflows/unit-tests-darwin.yml
Labels: size/L

#7038 ci: ensure build_deps:latest and build_deps:latest-lts are pushed on change
  deploy/cloudbuild-lts.yaml
  deploy/cloudbuild.yaml
Labels: size/XS

#7037 fix: include registry for `docker login` and `gcloud auth configure-docker`
  pkg/skaffold/build/build_problems.go
  pkg/skaffold/build/build_problems_test.go
Labels: size/M

#7045 fix: Helm: uninstall: Release not loaded #5414
  pkg/skaffold/deploy/helm/deploy.go
Labels: size/XS

#7042 feat(tag): validate generated/provided tag
  go.mod
  go.sum
  pkg/skaffold/tag/tag.go
  pkg/skaffold/tag/tag_test.go
Labels: size/S

#6979 feat: update to buildpacks/pack v0.23.0
  go.mod
  go.sum
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/buildpacks/env.go
  pkg/skaffold/build/buildpacks/fetcher.go
  pkg/skaffold/build/buildpacks/fetcher_test.go
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/lifecycle_test.go
  pkg/skaffold/build/buildpacks/logger.go
  pkg/skaffold/debug/cnb.go
  pkg/skaffold/debug/cnb_test.go
Labels: size/L

#7060 chore: install gke-gcloud-auth-plugin in skaffold images
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS
