Repository GoogleContainerTools/skaffold, pull requests merged in 2022-10, with the labels that each got.

#7906 docs: Add examples to the info sidebar
  docs-v2/layouts/partials/info-panel.html
  docs/data/maturity.json
  docs/layouts/partials/info-panel.html
Labels: size/L

#7907 fix: resolve issue where helm render did not respect --namespace flag
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/XS

#7884 fix: ensure project descriptor in Pack Build
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/buildpacks/lifecycle.go
Labels: size/M

#7912 chore: change survey prompt frequency
  pkg/skaffold/survey/config.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: size/S

#7917 docs: Add version menu label
  docs-v2/config.toml
  docs-v2/layouts/partials/navbar.html
  docs-v2/static/stylesheets/colors.css
Labels: size/S

#7928 chore: update cross and multi-platform build maturity
  docs-v2/data/maturity.json
Labels: size/XS

#7920 docs: Add banner to v1 and v2 docs indicating that v1 is archived
  docs-v2/content/en/docs/_index.md
  docs-v2/static/stylesheets/font.css
  docs/config.toml
Labels: size/S

#7921 chore: update skaffold Dockerfiles to pull from approved GCS buckets vs open internet
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/S

#7867 fix: add inputDigest tagger alias to customTemplate tagger
  pkg/skaffold/tag/custom_template.go
  pkg/skaffold/tag/custom_template_test.go
  pkg/skaffold/tag/git_commit_test.go
  pkg/skaffold/tag/input_digest.go
  pkg/skaffold/tag/tag_test.go
  pkg/skaffold/tag/tagger_mux.go
  pkg/skaffold/tag/template_utils.go
  pkg/skaffold/tag/template_utils_test.go
Labels: size/L

#7888 docs(ko): Design proposal: Hot reloading in dev
  docs-v2/design_proposals/ko-builder-auto-sync.md
Labels: area/sync, ko, area/dev, size/L, build/ko, builder/ko

#7936 fix: allow `init` without `render` and `deploy`
  pkg/skaffold/initializer/render/init.go
Labels: size/S, 2.0.0

#7937 [skaffold v2] fix: Cloud Code log viewer shows render stage correctly
  pkg/skaffold/runner/render.go
Labels: size/XS

#7939 docs: Add new inputDigest tagger alias to customTemplate tagger
  docs/content/en/docs/pipeline-stages/taggers.md
Labels: size/XS

#7931 docs: Fix v1 and v2 docs links
  docs-v2/content/en/docs/_index.md
  docs/config.toml
Labels: size/XS

#7951 docs: Update _index.md
  docs-v2/content/en/docs/_index.md
Labels: size/XS

#7952 docs: update v1 and v2 docs to properly reflect recent tagger changes
  docs-v2/content/en/docs/pipeline-stages/taggers.md
  docs/content/en/docs/pipeline-stages/taggers.md
Labels: size/XS

#7953 docs: update skaffold v2 intro text to have correct expanded scope
  docs-v2/config.toml
  docs-v2/content/en/_index.html
  docs-v2/content/en/docs/_index.md
  installers/windows/skaffold.nsi
Labels: size/S

#7949 fix: no longer pass os env vars through to verify as this can cause unexpected issues with PATH, GOPATH, etc.
  integration/verify_test.go
  pkg/skaffold/verify/docker/verify.go
Labels: size/S

#7948 chore: update skaffold v2 docs to point reference v2.0.0 and not v2.0.0-beta*
  docs-v2/content/en/docs/install/_index.md
Labels: size/M

#7950 update skaffold verify to GA maturity
  docs-v2/data/maturity.json
Labels: size/XS

#7925 fix: reverse order of deployers during cleanup (#7284)
  .gitignore
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
Labels: size/M

#7961 chore: add generic `util.Ptr` function
  cmd/skaffold/app/cmd/config/list_test.go
  cmd/skaffold/app/cmd/config/set_test.go
  cmd/skaffold/app/cmd/diagnose.go
  pkg/skaffold/build/builder_mux_test.go
  pkg/skaffold/build/buildpacks/build_test.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/build/custom/dependencies_test.go
  pkg/skaffold/build/docker/docker_test.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/kaniko/args_test.go
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/config/types.go
  pkg/skaffold/config/types_test.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/deploy/component/kubernetes/monitor_test.go
  pkg/skaffold/docker/build_args.go
  pkg/skaffold/docker/build_args_test.go
  pkg/skaffold/docker/default_repo_test.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/image_test.go
  pkg/skaffold/docker/parse_test.go
  pkg/skaffold/docker/syncmap_test.go
  pkg/skaffold/git/gitutil_test.go
  pkg/skaffold/hooks/env_test.go
  pkg/skaffold/hooks/sync.go
  pkg/skaffold/inspect/buildEnv/add_cluster.go
  pkg/skaffold/inspect/buildEnv/add_gcb.go
  pkg/skaffold/inspect/buildEnv/add_local.go
  pkg/skaffold/inspect/buildEnv/add_local_test.go
  pkg/skaffold/inspect/buildEnv/modify_gcb.go
  pkg/skaffold/instrumentation/prompt/prompt_test.go
  pkg/skaffold/parser/config_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/survey/survey_test.go
  pkg/skaffold/sync/sync_test.go
  pkg/skaffold/util/util.go
  pkg/skaffold/util/util_test.go
Labels: size/XL

#7965 fix: resolve regression where skaffold v2 would not respect configured kubectl context namespaces
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/runner/runcontext/context.go
Labels: size/M

#7963 release: v2.0.0
  CHANGELOG.md
Labels: !! do-not-merge !!, size/M

#7968 docs: Add a copy of the buildpacks node tutorial without a skaffold.yaml
  examples/buildpacks-node-tutorial/.gitignore
  examples/buildpacks-node-tutorial/README.md
  examples/buildpacks-node-tutorial/k8s/web.yaml
  examples/buildpacks-node-tutorial/package.json
  examples/buildpacks-node-tutorial/project.toml
  examples/buildpacks-node-tutorial/public/index.html
  examples/buildpacks-node-tutorial/src/index.js
  integration/examples/buildpacks-node-tutorial/.gitignore
  integration/examples/buildpacks-node-tutorial/README.md
  integration/examples/buildpacks-node-tutorial/k8s/web.yaml
  integration/examples/buildpacks-node-tutorial/package.json
  integration/examples/buildpacks-node-tutorial/project.toml
  integration/examples/buildpacks-node-tutorial/public/index.html
  integration/examples/buildpacks-node-tutorial/src/index.js
Labels: size/L

#7969 chore: bump version deps
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
Labels: size/S

#7987 docs: Fix helm command
  docs-v2/content/en/docs/pipeline-stages/renderers/helm.md
Labels: size/XS

#7986 fix: stderr of "helm template" not printed
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/XS

#7982 chore: set v3 schema as the first schema shown on v2 doc site
  docs-v2/config.toml
  docs-v2/static/javascripts/schemas.js
Labels: size/S

#7998 fix: revert "fix: no longer pass os env vars through to verify as thiss can cause unexpected issues with PATH, GOPATH, etc (#7949)"
  integration/verify_test.go
  pkg/skaffold/verify/docker/verify.go
Labels: size/S

#7999 release: v2.0.1
  CHANGELOG.md
Labels: size/M

#8000 chore: make syncstore generic
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/docker/dependencies.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/graph/dependencies.go
  pkg/skaffold/util/store.go
  pkg/skaffold/util/store_test.go
Labels: size/L
