Repository GoogleContainerTools/skaffold, pull requests merged in 2022-02, with the labels that each got.

#7049 feat(kustomize): Template `paths`
  docs/content/en/docs/environment/templating.md
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
Labels: size/M

#7061 chore: update go.mod go directive and go mod tidy
  go.mod
  go.sum
Labels: size/XS

#7074 feat(logs): allow user config for parsing json application logs when using kubernetes deployers
  docs/content/en/docs/pipeline-stages/log-tailing.md
  docs/content/en/schemas/v2beta27.json
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/kubernetes/logger/formatter.go
  pkg/skaffold/kubernetes/logger/formatter_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/log/formatter.go
  pkg/skaffold/log/formatter_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/schema/latest/v1/config.go
Labels: size/L

#7067 fix: dont update last-prompted if check-update is false
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
Labels: size/M

#7091 fix: failing windows UT
  pkg/skaffold/build/docker/docker_test.go
Labels: size/XS

#7088 fix: use go 1.17.x in verify-examples github action
  .github/workflows/verify-examples.yml
  integration/render_test.go
Labels: size/XS

#7090 docs: document cross-platform build support
  docs/content/en/docs/pipeline-stages/builders/_index.md
  docs/content/en/docs/pipeline-stages/builders/custom.md
  docs/content/en/samples/builders/platforms/artifact-constraints.yaml
  docs/content/en/samples/builders/platforms/pipeline-constraints.yaml
Labels: size/M

#7100 docs: add section on deactivating profiles
  docs/content/en/docs/environment/profiles.md
Labels: size/S

#7094 [V2] refactor: remove yaml v2 dependency and use skaffold pkg/yaml instead
  pkg/skaffold/render/renderer/renderer.go
Labels: size/S

#7089 fix: correctly set the default value of `StatusCheck` to nil
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: size/S

#7109 [V2] refactor: remove pointers from render code.
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/transform/transform.go
  pkg/skaffold/render/validate/validate.go
Labels: size/M

#7116 chore(deps): bump flask version from 2.0.2 to 2.0.3 in buildpacks-python example
  examples/buildpacks-python/requirements.txt
  integration/examples/buildpacks-python/requirements.txt
Labels: size/XS

#7102 feat: add argo workflows kinds to transformable allow list
  pkg/skaffold/kubernetes/manifest/visitor.go
Labels: size/M

#7117 chore(deps): bump puma from 4.3.9 to 4.3.11 in ruby example
  examples/ruby/backend/Gemfile.lock
  integration/examples/ruby/backend/Gemfile.lock
Labels: size/XS

#7112 fix: parsing alternative config filename `skaffold.yml` by supporting absolute paths in `config.ReadConfiguration`
  pkg/skaffold/util/config.go
Labels: size/S

#7115 chore: Update ROADMAP.md
  ROADMAP.md
Labels: size/S

#7068 Make explicit that user needs to change PROJECT_ID
  examples/google-cloud-build/skaffold.yaml
  integration/examples/gcb-kaniko/skaffold.yaml
  integration/examples/google-cloud-build/skaffold.yaml
Labels: size/XS

#7120 fix: skaffold's assumption for image tag when building via buildkit and custom output
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
Labels: size/XS

#7107 fix: correctly handle excluded profiles
  pkg/skaffold/parser/config.go
Labels: size/S

#7138 fix: Typo in warning message
  pkg/skaffold/platform/resolver.go
Labels: size/XS

#7129 docs: refresh DEVELOPMENT.md
  DEVELOPMENT.md
Labels: size/M

#7136 fix: `make preview-docs` should run for Mac M1
  deploy/docs/local-preview.sh
Labels: size/XS

#7134 feat: implement cross-platform support for GCB build env
  integration/examples/cross-platform-builds/Dockerfile
  integration/examples/cross-platform-builds/skaffold.yaml
  pkg/skaffold/build/gcb/buildpacks_test.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/jib_test.go
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/gcb/spec.go
  pkg/skaffold/build/gcb/spec_test.go
  pkg/skaffold/build/gcb/types.go
  pkg/skaffold/platform/platform_test.go
Labels: size/L

#7135 fix: specifying platforms in ko builder
  docs/content/en/docs/pipeline-stages/builders/ko.md
  docs/content/en/samples/builders/ko-platforms.yaml
  docs/content/en/schemas/v2beta28.json
  pkg/skaffold/build/ko/build.go
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/builder_test.go
  pkg/skaffold/platform/platform.go
  pkg/skaffold/schema/latest/v1/config.go
  pkg/skaffold/schema/v2beta27/upgrade.go
  pkg/skaffold/schema/v2beta27/upgrade_test.go
Labels: size/M

#7140 docs: cross platform build support in GCB
  docs/content/en/docs/pipeline-stages/builders/_index.md
Labels: size/XS

#7118 [v2] feat: Add kubectl renderer
  go.sum
  pkg/skaffold/render/renderer/kpt/kpt.go
  pkg/skaffold/render/renderer/kpt/kpt_test.go
  pkg/skaffold/render/renderer/kubectl/kubectl.go
  pkg/skaffold/render/renderer/kubectl/kubectl_test.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/util/util.go
  pkg/skaffold/render/transform/transform.go
  pkg/skaffold/runner/v2/new.go
  pkg/skaffold/runner/v2/runner_test.go
Labels: size/XL

#7108 docs: Remove references to XXenableJibInit and XXenableBuildpacksInit from init docs
  docs/content/en/docs/pipeline-stages/init.md
Labels: size/S

#7142 feat: cross-platform support with kaniko builder
  docs/content/en/docs/pipeline-stages/builders/_index.md
  pkg/skaffold/build/cluster/cluster.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
Labels: size/M
