Repository GoogleContainerTools/skaffold, pull requests merged in 2022-08, with the labels that each got.

#7713 fix: update deployers documentation to match with current skaffold v2…
  docs-v2/content/en/docs/pipeline-stages/deployers/_index.md
Labels: size/XS

#7694 feat: add flags for Cloud Run configuration
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
Labels: size/L

#7707 chore: support `artifactOverrides` schema functionality from v2beta* in v3alpha* via `setValue*`
  examples/templated-fields/charts/values.yaml
  examples/templated-fields/skaffold.yaml
  pkg/skaffold/helm/args.go
  pkg/skaffold/schema/v2beta29/upgrade.go
Labels: size/M

#7706 fix: specifying target platform for image pulls
  pkg/skaffold/build/buildpacks/fetcher.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/test/structure/structure.go
  pkg/skaffold/verify/docker/verify.go
Labels: size/M

#7697 feat: Support multiple renderer render in skaffold dev and skaffold run
  integration/examples/multiple-renderers/backend/Chart.yaml
  integration/examples/multiple-renderers/backend/src/Dockerfile
  integration/examples/multiple-renderers/backend/src/database.go
  integration/examples/multiple-renderers/backend/src/go.mod
  integration/examples/multiple-renderers/backend/src/go.sum
  integration/examples/multiple-renderers/backend/src/main.go
  integration/examples/multiple-renderers/backend/src/mongodb.go
  integration/examples/multiple-renderers/backend/templates/deployment.yaml
  integration/examples/multiple-renderers/backend/templates/guestbook-mongodb.deployment.yaml
  integration/examples/multiple-renderers/backend/templates/guestbook-mongodb.service.yaml
  integration/examples/multiple-renderers/backend/templates/service.yaml
  integration/examples/multiple-renderers/backend/val.yaml
  integration/examples/multiple-renderers/backend/values.yaml
  integration/examples/multiple-renderers/frontend/k8s/deployment.yaml
  integration/examples/multiple-renderers/frontend/k8s/service.yaml
  integration/examples/multiple-renderers/frontend/src/Dockerfile
  integration/examples/multiple-renderers/frontend/src/go.mod
  integration/examples/multiple-renderers/frontend/src/go.sum
  integration/examples/multiple-renderers/frontend/src/main.go
  integration/examples/multiple-renderers/frontend/src/static/style.css
  integration/examples/multiple-renderers/frontend/src/templates/home.tpl
  integration/examples/multiple-renderers/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/render/renderer/renderer.go
Labels: size/XL

#7703 fix: retagging an image index
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_util.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/docker/remote_test.go
Labels: size/M

#7718 fix: update changelog generation code to support skaffold v2
  hack/release/changelog/main.go
Labels: size/XS

#7720 add v3alpha1.json schema to docs-v2/
  docs-v2/content/en/schemas/v3alpha1.json
Labels: size/XXL

#7717 docs: update skaffold render to reflect current skaffold v2 status
  docs-v2/config.toml
  docs-v2/content/en/docs/pipeline-stages/renderers/_index.md
  docs-v2/content/en/docs/pipeline-stages/renderers/kpt.md
  docs-v2/content/en/schemas/v2beta29.json
  docs/config.toml
Labels: size/XXL

#7719 feat: Remove duplicate kustomize config
  docs-v2/content/en/docs/environment/templating.md
  docs-v2/content/en/samples/deployers/kubectl.yaml
  docs-v2/content/en/samples/deployers/kustomize.yaml
  docs-v2/content/en/samples/deployers/status-check.yaml
  docs-v2/content/en/samples/pipeline-stages/init-example.yaml
  docs-v2/content/en/samples/profiles/activations.yaml
  docs-v2/content/en/samples/profiles/patches.yaml
  docs-v2/content/en/samples/profiles/profiles.yaml
  docs-v2/content/en/samples/renderers/docker.yaml
  docs-v2/content/en/samples/renderers/kustomize.yaml
  docs-v2/content/en/samples/resource-selector/resource-selector-allow-example.yaml
  docs-v2/content/en/samples/resource-selector/resource-selector-crd-example.yaml
  docs-v2/content/en/samples/resource-selector/resource-selector-deny-example.yaml
  docs/content/en/docs/pipeline-stages/renderers/kustomize.md
  docs/content/en/samples/renderers/kustomize.yaml
  pkg/skaffold/constants/constants.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/constants.go
  pkg/skaffold/deploy/kubectl/kustomize_test.go
  pkg/skaffold/deploy/kustomize/constants/constants.go
  pkg/skaffold/deploy/kustomize/errors.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/event/util.go
  pkg/skaffold/event/util_test.go
  pkg/skaffold/event/v2/metadata.go
  pkg/skaffold/event/v2/metadata_test.go
  pkg/skaffold/generate_pipeline/tasks.go
  pkg/skaffold/generate_pipeline/tasks_test.go
  pkg/skaffold/initializer/analyze/kustomize.go
  pkg/skaffold/kubectl/cli.go
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/generate_test.go
  pkg/skaffold/render/generate/util.go
  pkg/skaffold/render/renderer/kubectl/kubectl_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/v2/runner_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v2beta29/upgrade.go
  pkg/skaffold/schema/validation/samples_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
Labels: size/XXL

#7664 feat: respect CLI flag in skaffold render
  cmd/skaffold/app/cmd/flags.go
  docs-v2/content/en/api-v2/skaffold.swagger.json
  docs-v2/content/en/api/skaffold.swagger.json
  docs-v2/content/en/docs/references/api-v2/grpc.md
  docs-v2/content/en/docs/references/api/grpc.md
  docs/content/en/api-v2/skaffold.swagger.json
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api-v2/grpc.md
  docs/content/en/docs/references/api/grpc.md
  docs/content/en/docs/references/cli/_index.md
  examples/getting-started/k8s-pod.yaml
  integration/render_test.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kubectl/kustomize_test.go
  pkg/skaffold/kubernetes/manifest/errors.go
  pkg/skaffold/kubernetes/manifest/namespace_test.go
  pkg/skaffold/kubernetes/manifest/namespaces.go
  pkg/skaffold/render/config.go
  pkg/skaffold/render/generate/generate_test.go
  pkg/skaffold/render/renderer/kpt/kpt.go
  pkg/skaffold/render/renderer/kpt/kpt_test.go
  pkg/skaffold/render/renderer/kubectl/kubectl.go
  pkg/skaffold/render/renderer/kubectl/kubectl_test.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/util/util.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XXL

#7727 docs: update docs-v2 'installing skaffold' to match skaffold v2.0.0-beta1 installation instructions
  docs-v2/content/en/docs/install/_index.md
Labels: size/L

#7671 use absolute paths to the container_image.tar in bazel build.
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/bazel/build_test.go
Labels: size/M

#7723 feat: fix render and deploy when using kustomize and helm deployer.
  integration/examples/getting-started-kustomize/skaffold.yaml
  integration/run_test.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/renderer.go
  pkg/skaffold/runner/renderer_test.go
  pkg/skaffold/schema/defaults/defaults.go
Labels: size/L

#7729 fix: add cloud run deployer nil check
  pkg/skaffold/schema/defaults/defaults.go
Labels: size/XS

#7730 fix: fix v3alpha*.json generation, v3alpha1 schema and misc schemas fixes
  docs-v2/content/en/schemas/v3alpha1.json
  hack/schemas/main.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v2beta29/config.go
Labels: size/M

#7731 fix: Don't add kubectl deployer when cloud run deployer present.
  pkg/skaffold/schema/defaults/defaults.go
Labels: size/XS

#7732 chore: update skaffold-v2 docs site to be created per pr for beta->GA period
  deploy/docs-v2/cloudbuild-release.yaml
  deploy/docs-v2/cloudbuild.yaml
Labels: size/S

#7735 chore: update skaffold-v2 docs site cb job endpoint and separate docs pipelines
  deploy/docs-v2/cloudbuild-release.yaml
  deploy/docs-v2/cloudbuild.yaml
  docs-v2/.firebaserc
Labels: size/S

#7733 docs: add initial docs for Cloud Run Deployer
  docs-v2/content/en/docs/pipeline-stages/deployers/cloudrun.md
  docs-v2/content/en/samples/deployers/cloudrun.yaml
  docs-v2/content/en/schemas/v3alpha1.json
  docs-v2/data/maturity.json
  pkg/skaffold/schema/latest/config.go
Labels: size/M

#7734 docs: helm render docs and few fixes
  docs-v2/content/en/docs/pipeline-stages/deployers/docker.md
  docs-v2/content/en/docs/pipeline-stages/renderers/helm.md
  docs-v2/content/en/samples/deployers/kpt.yaml
  docs-v2/content/en/samples/renderers/helm.yaml
  docs-v2/content/en/schemas/v3alpha1.json
  docs-v2/data/maturity.json
  pkg/skaffold/schema/latest/config.go
Labels: area/docs, size/L

#7737 docs: add new docs-v2 'upgrading from skaffold v1' docs section
  docs-v2/content/en/docs/install/_index.md
  docs-v2/content/en/docs/pipeline-stages/deployers/_index.md
  docs-v2/content/en/docs/pipeline-stages/deployers/cloudrun.md
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
  docs-v2/content/en/docs/pipeline-stages/deployers/kpt.md
  docs-v2/content/en/docs/pipeline-stages/renderers/_index.md
  docs-v2/content/en/docs/pipeline-stages/renderers/kpt.md
  docs-v2/content/en/docs/pipeline-stages/verify.md
  docs-v2/content/en/docs/upgrading/_index.md
  docs-v2/content/en/samples/verify/verify.yaml
  docs/content/en/docs/pipeline-stages/_index.md
Labels: size/L

#7736 release: v2.0.0-beta1
  CHANGELOG.md
Labels: size/M

#7738 docs: fix skaffold verify docs with proper image reference
  docs-v2/content/en/docs/pipeline-stages/verify.md
  docs-v2/content/en/samples/verify/verify.yaml
Labels: size/S

#7744 docs: fix accidental windows and docker tab removal in v2 install docs
  docs-v2/content/en/docs/install/_index.md
Labels: size/S

#7746 docs: update the skaffold v2 verify docs to explain only CLI available atm
  docs-v2/content/en/docs/pipeline-stages/verify.md
Labels: size/XS

#7740 fix: render `offline` flag should disable image platform lookup
  pkg/skaffold/render/renderer/util/util.go
Labels: size/XS, kokoro:force-run

#7747 docs: update the skaffold v2 verify docs to have working sample
  docs-v2/content/en/docs/pipeline-stages/verify.md
  docs-v2/content/en/samples/verify/verify.yaml
Labels: size/XS

#7751 docs: add skaffold verify feature maturity
  docs-v2/data/maturity.json
Labels: size/XS

#7750 fix: remove typo in manifests error message
  pkg/skaffold/kubernetes/manifest/errors.go
Labels: size/XS

#7758 docs: multi-platform docs
  docs-v2/content/en/docs/_index.md
  docs-v2/content/en/docs/pipeline-stages/builders/_index.md
  docs-v2/content/en/docs/workflows/handling-platforms.md
  docs-v2/data/maturity.json
  examples/cross-platform-builds/Dockerfile
  examples/cross-platform-builds/skaffold.yaml
  integration/examples/cross-platform-builds/Dockerfile
  integration/examples/cross-platform-builds/skaffold.yaml
Labels: size/L

#7743 fix: enable node platform affinity definition for `dev`, `debug` and `run` modes in mixed node clusters
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/types.go
  pkg/skaffold/config/util.go
  pkg/skaffold/config/util_test.go
  pkg/skaffold/runner/runcontext/v2/context.go
Labels: size/L

#7739 feat: cross-platform build support in GoogleCloudBuild
  docs-v2/content/en/schemas/v3alpha1.json
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/platform/platform.go
  pkg/skaffold/schema/latest/config.go
Labels: size/M

#7745 feat: implement creating `ManifestList` from single platform images
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/build/platform.go
  pkg/skaffold/docker/manifest_list.go
Labels: size/L

#7767 fix: improve multi-arch docs
  docs-v2/content/en/docs/workflows/handling-platforms.md
  docs-v2/static/images/multi-arch-flow.png
Labels: size/S

#7728 feat(ko): Inferred file sync for ko static assets
  docs-v2/content/en/docs/pipeline-stages/builders/ko.md
  docs-v2/content/en/docs/pipeline-stages/filesync.md
  docs/content/en/docs/pipeline-stages/builders/ko.md
  docs/content/en/docs/pipeline-stages/filesync.md
  integration/examples/ko-sync-infer/README.md
  integration/examples/ko-sync-infer/go.mod
  integration/examples/ko-sync-infer/k8s/example.yaml
  integration/examples/ko-sync-infer/kodata/index.html
  integration/examples/ko-sync-infer/main.go
  integration/examples/ko-sync-infer/skaffold.yaml
  pkg/skaffold/build/ko/sync/sync.go
  pkg/skaffold/build/ko/sync/sync_test.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: size/XL

#7772 chore: unit test for CreateManifestList
  pkg/skaffold/docker/manifest_list.go
  pkg/skaffold/docker/manifest_list_test.go
Labels: size/M

#7769 fix: add flags for build platform selection heuristics
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/platform/resolver.go
  pkg/skaffold/platform/resolver_test.go
  pkg/skaffold/runner/runcontext/v2/context.go
  pkg/skaffold/runner/v2/new.go
Labels: size/L

#7765 fix: add error code for cross-platform build failures
  docs-v2/content/en/api-v2/skaffold.swagger.json
  docs-v2/content/en/api/skaffold.swagger.json
  docs-v2/content/en/docs/references/api-v2/grpc.md
  docs-v2/content/en/docs/references/api/grpc.md
  docs/content/en/api-v2/skaffold.swagger.json
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api-v2/grpc.md
  docs/content/en/docs/references/api/grpc.md
  integration/examples/cross-platform-builds/skaffold.yaml
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/docker/errors.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XXL

#7768 fix: render should be online for `dev`, `deploy` and `run`.
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/run.go
  integration/dev_test.go
  pkg/skaffold/render/renderer/util/util.go
  pkg/skaffold/runner/v2/dev.go
Labels: size/S, v2 regression

#7777 docs: add missing v1.39.0 and v1.39.1 changelog.md release info
  CHANGELOG.md
Labels: size/M

#7780 release: v1.39.2
  CHANGELOG.md
Labels: size/S

#7781 chore: add-render-event-in-runner
  pkg/skaffold/runner/render.go
Labels: size/XS

#7784 fix: remove required tag from cloud run region
  docs-v2/content/en/api-v2/skaffold.swagger.json
  docs-v2/content/en/api/skaffold.swagger.json
  docs-v2/content/en/docs/references/api-v2/grpc.md
  docs-v2/content/en/docs/references/api/grpc.md
  docs-v2/content/en/schemas/v3alpha1.json
  docs/content/en/api-v2/skaffold.swagger.json
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api-v2/grpc.md
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XL

#7770 chore: safe type assersions
  docs-v2/content/en/api-v2/skaffold.swagger.json
  docs-v2/content/en/api/skaffold.swagger.json
  docs-v2/content/en/docs/references/api-v2/grpc.md
  docs-v2/content/en/docs/references/api/grpc.md
  docs/content/en/api-v2/skaffold.swagger.json
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api-v2/grpc.md
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/parser/config.go
  pkg/skaffold/schema/errors/errors.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XL

#7789 feat: add toleration for GKE ARM nodes taint
  cmd/skaffold/app/cmd/flags.go
  docs-v2/content/en/schemas/v3alpha1.json
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/kubernetes/manifest/affinity.go
  pkg/skaffold/kubernetes/manifest/affinity_test.go
  pkg/skaffold/kubernetes/manifest/gke_toleration.go
  pkg/skaffold/kubernetes/manifest/gke_toleration_test.go
  pkg/skaffold/kubernetes/manifest/visitor.go
  pkg/skaffold/render/config.go
  pkg/skaffold/render/renderer/kpt/kpt.go
  pkg/skaffold/render/renderer/kubectl/kubectl.go
  pkg/skaffold/render/renderer/util/util.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#7786 chore: raise error when there is a multiplatform build without container registry
  docs-v2/content/en/api-v2/skaffold.swagger.json
  docs-v2/content/en/api/skaffold.swagger.json
  docs-v2/content/en/docs/references/api-v2/grpc.md
  docs-v2/content/en/docs/references/api/grpc.md
  docs/content/en/api-v2/skaffold.swagger.json
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api-v2/grpc.md
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/build/errors.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XL

#7798 fix: add node unschedulable to retriable errors
  pkg/skaffold/kubernetes/status/resource/deployment.go
  pkg/skaffold/kubernetes/status/resource/deployment_test.go
Labels: size/S

#7795 fix: make helm renderer to use manifest.ManifestList
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/S

#7799 added apply to --rpc-port and --rpc-http-port definedons
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: size/XS

#7785 feat: add hooks support to render schema and phase
  docs-v2/content/en/schemas/v3alpha1.json
  integration/examples/lifecycle-hooks/k8s-pod.yaml
  integration/examples/lifecycle-hooks/skaffold.yaml
  pkg/skaffold/hooks/deploy_test.go
  pkg/skaffold/hooks/env.go
  pkg/skaffold/hooks/render.go
  pkg/skaffold/hooks/render_test.go
  pkg/skaffold/hooks/types.go
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/renderer/kubectl/kubectl.go
  pkg/skaffold/render/renderer/render_mux.go
  pkg/skaffold/render/renderer/render_mux_test.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/runner/renderer.go
  pkg/skaffold/runner/renderer_test.go
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#7814 fix: add auth to image pull
  pkg/skaffold/docker/manifest_list.go
Labels: size/XS

#7807 feat: add profile support to skaffold verify
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: size/S

#7817 fix: check platform values for known OS and Arch, and fail fast
  pkg/skaffold/platform/platform.go
  pkg/skaffold/platform/platform_test.go
Labels: size/M

#7800 feat: upgrade profiles when running skaffold fix
  pkg/skaffold/schema/v2beta29/upgrade.go
  pkg/skaffold/schema/v2beta29/upgrade_test.go
Labels: size/L

#7821 fix: add host platform metric to platform type events
  pkg/skaffold/instrumentation/export.go
Labels: size/S

#7818 chore: Add integration test for build cross platform images
  integration/binpack/gcp.go
  integration/build_test.go
  integration/testdata/build/docker-with-platform-amd/Dockerfile
  integration/testdata/build/docker-with-platform-amd/k8s/deployment.yaml
  integration/testdata/build/docker-with-platform-amd/k8s/pod.yaml
  integration/testdata/build/docker-with-platform-amd/main.go
  integration/testdata/build/docker-with-platform-amd/skaffold.yaml
  integration/testdata/build/docker-with-platform-arm/Dockerfile
  integration/testdata/build/docker-with-platform-arm/k8s/deployment.yaml
  integration/testdata/build/docker-with-platform-arm/k8s/pod.yaml
  integration/testdata/build/docker-with-platform-arm/main.go
  integration/testdata/build/docker-with-platform-arm/skaffold.yaml
  integration/testdata/build/gcb-with-platform/Dockerfile
  integration/testdata/build/gcb-with-platform/go.mod
  integration/testdata/build/gcb-with-platform/k8s-pod.yaml
  integration/testdata/build/gcb-with-platform/main.go
  integration/testdata/build/gcb-with-platform/skaffold.yaml
Labels: size/L

#7788 fix: Fill IMAGE_TAG,etc on Docker builds
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/docker/docker_test.go
  pkg/skaffold/build/docker/errors_test.go
  pkg/skaffold/build/local/local_test.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
Labels: size/M

#7823 fix: Remove the flag from deploy command
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
Labels: size/XS

#7825 fix: helm template warnings breaking yaml parsing
  pkg/skaffold/helm/bin.go
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/S

#7826 release: v2.0.0-beta2
  CHANGELOG.md
  integration/examples/cross-platform-builds/skaffold.yaml.v2
Labels: size/M

#7828 docs: update v2 docs to have up to date v2.0.0-beta2 links
  docs-v2/content/en/docs/install/_index.md
  docs-v2/content/en/docs/pipeline-stages/verify.md
  docs-v2/content/en/docs/upgrading/_index.md
Labels: size/M

#7829 chore: add render lifecycle hook highlight to changelog
  CHANGELOG.md
Labels: size/XS

#7831 chore: upgrade jib versions to 3.3.0
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: size/S

#7832 docs: fix small typo in v2.0.0-beta2 release changelog
  CHANGELOG.md
Labels: size/XS
