Repository GoogleContainerTools/skaffold, pull requests merged in 2022-11, with the labels that each got.

#8003 chore: upgrade jib plugin versions to 3.3.1
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: size/S

#8004 feat: new cloudbuild slim
  Makefile
  deploy/cloudbuild-slim.yaml
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/Dockerfile.slim
Labels: size/L

#8013 docs: update skaffold examples and documentation to properly reflect v1 ->v2 artifactOverrides changes
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
  examples/helm-deployment/README.md
  examples/templated-fields/skaffold.yaml
  integration/examples/templated-fields/skaffold.yaml
Labels: size/S

#8005 fix: not print error message if it is empty
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/S

#7991 chore: add v1.39.3 release CHANGELOG.md entry
  CHANGELOG.md
Labels: size/S

#7996 feat: new dockerfiles and cloudbuild config for slim image
  Makefile
  deploy/cloudbuild-slim.yaml
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/Dockerfile.slim
Labels: size/L

#8017 fix: add description to StatusCheck TaskEvent
  pkg/skaffold/kubernetes/status/status_check.go
Labels: size/XS

#7966 docs: migrate v2 docs -> skaffold.dev and v1 docs -> skaffold-v1.web.app
  deploy/docs-v2/cloudbuild-release.yaml
  deploy/docs/cloudbuild-release.yaml
  docs-v2/.firebaserc
  docs-v2/config.toml
  docs/.firebaserc
  docs/config.toml
Labels: size/S

#7887 feat: context copy retry. If we add a for loop and execute the kubectlcli.Run method for copying context to kaniko pod , this makes more reliable and less prune to network failures
  pkg/skaffold/build/cluster/kaniko.go
Labels: size/S

#8011 feat: add skipTests to ignore helm test directory on manifest generation
  docs-v2/content/en/schemas/v4beta1.json
  pkg/skaffold/render/renderer/helm/helm.go
  pkg/skaffold/schema/latest/config.go
Labels: size/S

#8036 fix: properly add RemoteManifests support to skaffold v2
  docs-v2/content/en/schemas/v4beta1.json
  pkg/skaffold/render/errors/errors.go
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/util.go
  pkg/skaffold/render/renderer/util/util.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/v3/upgrade.go
  pkg/skaffold/schema/v3/upgrade_test.go
Labels: size/L

#8035 docs: update skaffold.gliffy diagram with updated information for skaffold v2
  docs-v2/diagrams/skaffold.gliffy
  docs-v2/static/images/architecture.png
Labels: size/XS

#8028 fix: preserve configs order when creating renderers and deployers
  integration/deploy_test.go
  integration/testdata/multi-config-dependencies-order/module1/Dockerfile
  integration/testdata/multi-config-dependencies-order/module1/k8s/k8s-pod.yaml
  integration/testdata/multi-config-dependencies-order/module1/main.go
  integration/testdata/multi-config-dependencies-order/module1/skaffold.yaml
  integration/testdata/multi-config-dependencies-order/module2/Dockerfile
  integration/testdata/multi-config-dependencies-order/module2/k8s/k8s-pod.yaml
  integration/testdata/multi-config-dependencies-order/module2/main.go
  integration/testdata/multi-config-dependencies-order/module2/skaffold.yaml
  integration/testdata/multi-config-dependencies-order/module3/Dockerfile
  integration/testdata/multi-config-dependencies-order/module3/k8s/k8s-pod.yaml
  integration/testdata/multi-config-dependencies-order/module3/main.go
  integration/testdata/multi-config-dependencies-order/module3/skaffold.yaml
  integration/testdata/multi-config-dependencies-order/module4/Dockerfile
  integration/testdata/multi-config-dependencies-order/module4/k8s/k8s-pod.yaml
  integration/testdata/multi-config-dependencies-order/module4/main.go
  integration/testdata/multi-config-dependencies-order/module4/skaffold.yaml
  integration/testdata/multi-config-dependencies-order/skaffold.yaml
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/renderer.go
  pkg/skaffold/runner/renderer_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/runner/runner_test.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: size/L

#8044 chore(doc): note that filesync works for debug
  docs-v2/data/maturity.json
  docs/data/maturity.json
Labels: size/XS

#8038 Avoid nil context error
  pkg/skaffold/deploy/kubectl/kubectl.go
Labels: size/XS

#8001 chore: update workflow files
  .github/workflows/codeql-analysis.yml
  .github/workflows/draft-release.yml
  .github/workflows/integration-darwin.yml
  .github/workflows/integration-linux.yml
  .github/workflows/integration-windows.yml
  .github/workflows/performance-comparison-label.yml
  .github/workflows/performance-comparison.yml
  .github/workflows/unit-tests-darwin.yml
Labels: size/S

#8007 fix: container image push to local cluster
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kubectl/kustomize_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
Labels: size/M

#8043 chore: update examples/getting-started to go 1.19
  examples/getting-started/Dockerfile
  examples/getting-started/go.mod
Labels: size/XS

#8046 fix: use std lib signal handling
  cmd/skaffold/app/signals.go
  cmd/skaffold/app/signals_test.go
  cmd/skaffold/app/skaffold.go
Labels: size/M

#7915 feat: add support for deploying Cloud Run Jobs.
  pkg/skaffold/deploy/cloudrun/cloudrun.go
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/cloudrun/deploy_test.go
  pkg/skaffold/deploy/cloudrun/status.go
  pkg/skaffold/deploy/cloudrun/status_test.go
  pkg/skaffold/kubernetes/manifest/visitor.go
Labels: size/XL

#8051 chore(deps): bump some .github/workflows deps
  .github/workflows/performance-comparison.yml
  .github/workflows/scorecards.yml
Labels: size/XS

#8054 docs: Linked to the Google Cloud Solutions Template
  docs-v2/content/en/docs/quickstart/_index.md
Labels: size/XS

#8019 docs: update skaffold examples and documentation to properly reflect v1 ->v2 artifactOverrides changes - 2nd attempt
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
  examples/helm-deployment/skaffold.yaml
Labels: !! do-not-merge !!, size/S

#8050 fix(sec): upgrade runc version v1.0.2 -> v1.1.2
  go.mod
  go.sum
Labels: size/XS

#8065 chore: update examples/* repos to use v4beta1 schema
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/Dockerfile
  examples/getting-started/go.mod
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/README.md
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
Labels: size/L

#8067 chore: update skaffold deps image dependencies
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  integration/examples/remote-multi-config-microservices/skaffold.yaml
Labels: size/L

#8077 fix: resolve issue where skaffold apply didn't respect config - statu…
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
Labels: kokoro:run, size/S

#8079 chore: update examples/* repos to use v3 schema (revert 3f82f13b02117f823694125d7149bca06a8d64f3)
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/Dockerfile
  examples/getting-started/go.mod
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/README.md
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
Labels: size/L

#8078 chore: update changelog.md to include v1.39.4
  CHANGELOG.md
Labels: size/S

#8083 fix: override protocols argument pass to helm post-renderer
  cmd/skaffold/app/cmd/filter.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/helm/bin.go
  pkg/skaffold/helm/bin_test.go
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/M

#8085 fix: resolve issue where skaffold filter command did not properly configure the filter allow & deny lists
  cmd/skaffold/app/cmd/filter.go
Labels: size/XS

#8087 fix: add unique tag to test image to avoid collisions with other tests
  integration/run_test.go
Labels: size/XS

#8097 feat: completion for the Fish shell
  cmd/skaffold/app/cmd/completion.go
  docs/content/en/docs/references/cli/_index.md
Labels: size/S

#8080 chore: reduce gcp integration test time
  integration/apply_test.go
  integration/build_test.go
  integration/deploy_cloudrun_test.go
  integration/deploy_test.go
  integration/multiplatform_test.go
  integration/run_test.go
  integration/testdata/multi-config-pods/skaffold.yaml
  integration/util.go
Labels: size/L

#8066 fix: correct issues with current upgrade logic for artifactOverrides with helm imageStrategy
  integration/helm_test.go
  integration/run_test.go
  integration/testdata/helm-multi-config/Makefile
  integration/testdata/helm-multi-config/app1/Dockerfile
  integration/testdata/helm-multi-config/app2/Dockerfile
  integration/testdata/helm-multi-config/charts/app/.helmignore
  integration/testdata/helm-multi-config/charts/app/Chart.yaml
  integration/testdata/helm-multi-config/charts/app/templates/NOTES.txt
  integration/testdata/helm-multi-config/charts/app/templates/_helpers.tpl
  integration/testdata/helm-multi-config/charts/app/templates/deployment.yaml
  integration/testdata/helm-multi-config/charts/app/values.yaml
  integration/testdata/helm-multi-config/skaffold/app1/skaffold.yml
  integration/testdata/helm-multi-config/skaffold/app2/skaffold.yml
  integration/testdata/helm-multi-config/skaffold/skaffold.yml
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/schema/v2beta29/upgrade.go
Labels: size/L

#8102 release: v2.0.2
  CHANGELOG.md
Labels: size/M

#8103 chore: bump skaffold container images jdk version to JDK 17
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8012 feat: Add support for Cloud Run services to stream logs
  pkg/skaffold/deploy/cloudrun/accessor_test.go
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/cloudrun/formatter.go
  pkg/skaffold/deploy/cloudrun/formatter_test.go
  pkg/skaffold/deploy/cloudrun/log.go
  pkg/skaffold/deploy/cloudrun/log_test.go
  proto/enums/enums.pb.go
  proto/v1/skaffold.pb.go
Labels: size/XL

#8108 fix: examples schema check failing
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
Labels: size/L

#8104 docs: add link to Cloud Run YAML reference in deployer doc
  docs-v2/content/en/docs/pipeline-stages/deployers/cloudrun.md
Labels: size/XS

#8096 feat: implement cleanup for Cloud Run Jobs
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/cloudrun/deploy_test.go
Labels: size/L

#8112 fix: gcp jib-gradle test
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-gradle/gradle.properties
  integration/examples/jib-gradle/gradle/wrapper/gradle-wrapper.jar
  integration/examples/jib-gradle/gradle/wrapper/gradle-wrapper.properties
  integration/examples/jib-gradle/gradlew
  integration/examples/jib-gradle/gradlew.bat
  integration/examples/jib-gradle/skaffold.yaml
  integration/examples/jib-gradle/src/main/groovy/example/micronaut/Application.groovy
  integration/examples/jib-sync/build.gradle
Labels: size/L

#8113 chore: bump skaffold image deps
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
Labels: size/S

#8119 docs: Add code samples to v2 info sidebar
  docs-v2/data/maturity.json
Labels: size/L

#8125 chore: remove resolved or obsolete TODO, etc. code comments
  pkg/skaffold/render/renderer/noop/noop.go
Labels: size/XS

#8101 docs: update docs with fixes for helm, quickstart and install pages
  docs-v2/content/en/docs/install/_index.md
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
  docs-v2/content/en/docs/pipeline-stages/renderers/helm.md
  docs-v2/content/en/docs/quickstart/_index.md
  docs/content/en/docs/install/_index.md
Labels: size/L

#8124 fix: always add namespaces in generated manifests regardless of offline=[true|false]
  integration/render_test.go
  pkg/skaffold/deploy/kubectl/constants.go
  pkg/skaffold/render/renderer/util/util.go
Labels: size/S

#8106 chore: repartition integration test
  Makefile
  integration/binpack/binpack.go
  integration/binpack/binpack_test.go
  integration/binpack/gcp.go
  integration/build_dependencies_test.go
  integration/build_test.go
  integration/credits_test.go
  integration/debug_test.go
  integration/delete_test.go
  integration/deploy_test.go
  integration/dev_dependencies_test.go
  integration/dev_test.go
  integration/diagnose_test.go
  integration/helm_test.go
  integration/init_test.go
  integration/inspect_test.go
  integration/modules_test.go
  integration/port_forward_test.go
  integration/render_test.go
  integration/rpc_test.go
  integration/run_test.go
  integration/schema_test.go
  integration/sync_test.go
  integration/test_events_test.go
Labels: size/L

#8136 fix: pin github actions to ubuntu 20.04 to avoid python + gcloud issues
  .github/workflows/codeql-analysis.yml
  .github/workflows/draft-release.yml
  .github/workflows/integration-linux.yml
  .github/workflows/linters-checks-and-unit-tests-linux.yml
  .github/workflows/performance-comparison-label.yml
  .github/workflows/performance-comparison.yml
  .github/workflows/scorecards.yml
  .github/workflows/verify-examples.yml
Labels: size/S

#8132 fix: bump skaffold slim image deps
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8138 chore: fix profile patch validation against original config
  pkg/skaffold/schema/profiles.go
  pkg/skaffold/schema/profiles_test.go
Labels: size/S

#8141 fix: correct recently released schemas to have correct schema field key
  docs-v2/content/en/schemas/v2beta29.json
  docs-v2/content/en/schemas/v3.json
  docs-v2/content/en/schemas/v3alpha1.json
  docs-v2/content/en/schemas/v4beta1.json
  docs/content/en/schemas/v2beta29.json
Labels: size/S

#8145 chore: fix github workflow linux unit diagnostics tests run command
  .github/workflows/linters-checks-and-unit-tests-linux.yml
Labels: size/XS

#8148 chore: Fix gcloud install in v1 workflow
  .github/workflows/integration-linux.yml
  .github/workflows/performance-comparison.yml
  .github/workflows/scorecards.yml
  examples/bazel/.bazelrc
  examples/bazel/WORKSPACE
  integration/examples/bazel/.bazelrc
  integration/examples/bazel/WORKSPACE
  integration/rpc_test.go
Labels: size/L

#8153 chore: fix gcloud install with latest ubuntu
  .github/workflows/codeql-analysis.yml
  .github/workflows/draft-release.yml
  .github/workflows/integration-linux.yml
  .github/workflows/linters-checks-and-unit-tests-linux.yml
  .github/workflows/performance-comparison-label.yml
  .github/workflows/performance-comparison.yml
  .github/workflows/scorecards.yml
  .github/workflows/verify-examples.yml
  examples/bazel/.bazelrc
  examples/bazel/WORKSPACE
  integration/examples/bazel/.bazelrc
  integration/examples/bazel/WORKSPACE
Labels: size/M

#8117 fix: new condition to create hydrate-dir only if a kpt renderer or deployer
  .github/workflows/integration-linux.yml
  integration/render_test.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/deploy/util/util_test.go
  pkg/skaffold/runner/new.go
Labels: size/L

#8165 docs: remove TODOs from resource selector docs
  docs-v2/content/en/docs/tutorials/skaffold-resource-selector.md
Labels: size/XS

#8152 fix: change to make buildFlatMap support arrays as YAML values
  pkg/skaffold/schema/util/util.go
  pkg/skaffold/schema/util/util_test.go
Labels: size/L

#8129 fix: properly wire deploy.kubectl.defaultNamespace field to be set in SKAFFOLD_NAMESPACES
  pkg/skaffold/runner/runcontext/context.go
Labels: size/S

#8156 chore: add log-streaming and cloud-run-proxy gcloud components
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/S

#8147 fix: support alternative env var naming using support env variable + artifact-name (vs env variable + index)
  integration/testdata/helm-multi-config/skaffold/app1/skaffold.yml
  integration/testdata/helm-multi-config/skaffold/app2/skaffold.yml
  pkg/skaffold/helm/args.go
  pkg/skaffold/schema/v2beta29/upgrade.go
Labels: size/M

#8164 docs: update helm docs to reflect new prioritization and changes to setValueTemplates
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
  docs-v2/content/en/docs/pipeline-stages/renderers/helm.md
Labels: size/L

#8171 chore: Optimize GitHub action
  .github/workflows/integration-darwin.yml
  .github/workflows/linters-checks.yml
  .github/workflows/unit-tests-darwin.yml
  .github/workflows/unit-tests-linux.yml
  .github/workflows/unit-tests-windows.yml
  Makefile
Labels: size/L

#8118 fix: integration-test cleanup
  integration/deploy_test.go
  integration/dev_test.go
  integration/housekeeping_messages_test.go
  integration/multiplatform_test.go
  integration/sync_test.go
Labels: size/M

#8174 chore: fix doc edit url
  docs-v2/layouts/partials/page-meta-links.html
Labels: size/XS

#8175 fix: support alternative env var naming using support env variable + artifact-name (vs env variable + index)
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
  docs-v2/content/en/docs/pipeline-stages/renderers/helm.md
  integration/testdata/helm-multi-config/skaffold/app1/skaffold.yml
  integration/testdata/helm-multi-config/skaffold/app2/skaffold.yml
  pkg/skaffold/helm/args.go
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/schema/v2beta29/upgrade.go
  pkg/skaffold/util/util.go
Labels: size/L
