Repository GoogleContainerTools/skaffold, pull requests merged in 2022-09, with the labels that each got.

#7835 fix: add remote image support to verify
  pkg/skaffold/verify/docker/verify.go
Labels: size/S, area/verify

#7794 chore: transform installation of go-licenses from go-get to go install
  hack/generate-embedded-files.sh
Labels: size/XS

#7847 fix: remove Cloud Run location validation for non-remote commands
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: size/M

#7845 chore: remove unnecessary rerender from devloop,
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/dev_test.go
Labels: size/S

#7841 fix: adjust set namespace logic
  pkg/skaffold/kubernetes/manifest/errors.go
  pkg/skaffold/kubernetes/manifest/namespace_test.go
  pkg/skaffold/kubernetes/manifest/namespaces.go
Labels: size/M

#7843 add: added service account to cloud build config
  docs-v2/content/en/schemas/v3alpha1.json
  pkg/skaffold/build/gcb/spec.go
  pkg/skaffold/schema/latest/config.go
Labels: size/S

#7857 docs: Fix incorrect default set for project for jib
  docs-v2/content/en/docs/pipeline-stages/builders/jib.md
Labels: size/XS

#7861 chore: update Ingress manifests
  examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/ingress.yaml
  examples/helm-deployment-dependencies/skaffold-helm/templates/ingress.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/charts/subchart/templates/ingress.yaml
  integration/examples/helm-deployment-dependencies/skaffold-helm/templates/ingress.yaml
  integration/render_test.go
  integration/testdata/helm-render/skaffold-helm/templates/ingress.yaml
  integration/testdata/helm/skaffold-helm/templates/ingress.yaml
  pkg/skaffold/deploy/helm/parse_test.go
  pkg/skaffold/deploy/testdata/foo/templates/ingress.yaml
Labels: size/M

#7869 chore: skip buildpacks integration test if being run on arm cluster
  Makefile
  integration/run_test.go
Labels: size/XS

#7870 docs: add kpt manifest.transform|validate functionality examples
  docs-v2/content/en/docs/pipeline-stages/renderers/kpt.md
  docs-v2/content/en/samples/renderers/kpt-manifest-fields.yaml
  docs/content/en/docs/pipeline-stages/_index.md
Labels: size/M

#7866 fix: backport Bazel build context fixes to v1
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/bazel/build_test.go
Labels: size/M

#7877 fix: remove RenderConfig and fix manifests issues with multi-config
  pkg/skaffold/render/renderer/render_mux.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/runner/renderer.go
  pkg/skaffold/runner/runcontext/context.go
Labels: size/M

#7878 release: v2.0.0-beta3
  CHANGELOG.md
Labels: size/M

#7875 fix: copy dependencies to a new slice to prevent mutation affecting the cache value
  pkg/skaffold/graph/dependencies.go
Labels: size/XS

#7879 Beta3 docs
  docs-v2/content/en/docs/install/_index.md
  docs-v2/content/en/docs/pipeline-stages/verify.md
  docs-v2/content/en/docs/upgrading/_index.md
Labels: size/M

#7852 test: Add multi platform integration tests
  integration/multiplatform_test.go
  integration/testdata/multi-config-pods/module1/Dockerfile
  integration/testdata/multi-config-pods/module1/k8s/k8s-pod.yaml
  integration/testdata/multi-config-pods/module1/main.go
  integration/testdata/multi-config-pods/module1/skaffold.yaml
  integration/testdata/multi-config-pods/module2/Dockerfile
  integration/testdata/multi-config-pods/module2/k8s/k8s-pod.yaml
  integration/testdata/multi-config-pods/module2/main.go
  integration/testdata/multi-config-pods/module2/skaffold.yaml
  integration/testdata/multi-config-pods/skaffold.yaml
Labels: size/L

#7874 Add an example for helm chart with multiple images
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
  docs/content/en/docs/pipeline-stages/deployers/helm.md
Labels: size/L

#7882 fix: deploy integration test image builds need to be multi-platform since we're testing against 3 types of k8s cluster
  integration/deploy_test.go
Labels: size/XS

#7885 chore: enable platform flag in render command
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/apply_test.go
Labels: size/XS

#7880 docs: add cloud deploy info to skaffold ci-cd docs
  docs-v2/content/en/docs/workflows/ci-cd.md
  docs/content/en/docs/workflows/ci-cd.md
Labels: size/S

#7890 use relref shortcode to fix links
  docs-v2/content/en/docs/pipeline-stages/renderers/helm.md
  docs-v2/content/en/docs/workflows/debug.md
Labels: size/S

#7895 chore(examples): update examples to Spring Boot 2.7.4 and SnakeYAML 1.32
  .gitignore
  examples/buildpacks-java/pom.xml
  examples/dev-journey-buildpacks/pom.xml
  examples/jib-multimodule/pom.xml
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/buildpacks-java/pom.xml
  integration/examples/dev-journey-buildpacks/pom.xml
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
Labels: size/L

#7896 chore: use cmp.Diff to check for differences
  integration/build_test.go
Labels: size/S

#7893 chore: move deploy error codes to render error codes
  docs-v2/content/en/api-v2/skaffold.swagger.json
  docs-v2/content/en/api/skaffold.swagger.json
  docs-v2/content/en/docs/references/api-v2/grpc.md
  docs-v2/content/en/docs/references/api/grpc.md
  docs/content/en/api-v2/skaffold.swagger.json
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api-v2/grpc.md
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/kubernetes/manifest/errors.go
  pkg/skaffold/kubernetes/manifest/errors_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XL

#7903 chore: update Google API client libraries
  go.mod
  go.sum
Labels: size/XS
