Repository GoogleContainerTools/skaffold, pull requests merged in 2022-04, with the labels that each got.

#7256 chore: update Jib plugin versions to 3.2.1 in examples
  examples/jib-gradle/build.gradle
  examples/jib-multimodule/pom.xml
  examples/jib-sync/build.gradle
  examples/jib-sync/pom.xml
  examples/jib/pom.xml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-multimodule/pom.xml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/pom.xml
  integration/examples/jib/pom.xml
  integration/testdata/debug/java/pom.xml
  integration/testdata/jib/pom.xml
Labels: size/S

#7263 chore: update go version in actions that weren't specifying go 1.17
  .github/workflows/linters-checks-and-unit-tests-linux.yml
  .github/workflows/performance-comparison.yml
Labels: size/XS

#7251 fix: fix bazel-out path for `rules_docker-0.23.0`
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/bazel/build_test.go
Labels: size/M

#7268 chore: PR to update pull request template
  .github/pull_request_template.md
Labels: size/S

#7271 release: v1.38.0
  CHANGELOG.md
Labels: size/M

#7278 fix: add default value for status-check flag when no value is specified
  cmd/skaffold/app/cmd/flags.go
  integration/run_test.go
Labels: size/M

#7293 fix: fix kubectl result formatting for debug logs
  pkg/skaffold/deploy/kubectl/cli.go
Labels: size/XS

#7303 revert: "chore: PR to update pull request template"
  .github/pull_request_template.md
Labels: size/S

#7306 fix: make TestDevPortForwardDefaultNamespace pass
  integration/dev_test.go
  integration/examples/microservices/skaffold.yaml
  pkg/skaffold/runner/v2/render.go
Labels: size/M

#7312 chore: Add cluster type to exported metrics.
  pkg/skaffold/instrumentation/export.go
Labels: size/XS

#7314 fix: set build concurrency correctly for multi-config projects
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/build/builder_mux_test.go
Labels: size/S

#7317 chore: Add test for filter command
  cmd/skaffold/app/cmd/filter.go
  cmd/skaffold/app/cmd/filter_test.go
  pkg/skaffold/render/renderer/util/util.go
Labels: size/L

#7316 chore: [v1] cherry pick the fix to collect cluster type on v1 branch
  hack/versions/pkg/schema/check.go
  pkg/skaffold/instrumentation/export.go
Labels: size/XS

#7324 fix: change type of BuildpackArtifact.Volumes
  pkg/skaffold/build/buildpacks/lifecycle.go
  pkg/skaffold/build/buildpacks/lifecycle_test.go
  pkg/skaffold/schema/latest/config.go
Labels: size/M

#7319 chore: v1: add `--transform` to v1 filter command.
  cmd/skaffold/app/cmd/filter.go
  cmd/skaffold/app/cmd/filter_test.go
  cmd/skaffold/app/cmd/flags.go
  pkg/skaffold/deploy/util/util.go
Labels: size/L

#7308 fix: find and prioritize WORKSPACE.bazel
  pkg/skaffold/build/bazel/dependencies.go
  pkg/skaffold/build/bazel/dependencies_test.go
Labels: size/M

#7321 feat: allow using env vars within deploy.helm.releases[].repo field
  docs/content/en/docs/environment/templating.md
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: size/M

#7333 fix: default digest-source to tag for local clusters
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  pkg/skaffold/constants/constants.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/runcontext/v2/context.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/v2/render.go
Labels: size/M

#7332 fix: Update skaffold-kustomize-args.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  integration/examples/kustomize/skaffold-kustomize-args.yaml
Labels: size/XS

#7282 fix: do not replace every string matching image names
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/kubernetes/manifest/images_test.go
Labels: size/L

#7339 refactor: replace statik with embed
  .gitignore
  Makefile
  cmd/skaffold/app/cmd/credits/export.go
  cmd/skaffold/app/cmd/credits/statik/statik.go
  cmd/skaffold/app/cmd/schema/print.go
  cmd/skaffold/app/cmd/schema/print_test.go
  deploy/skaffold/Dockerfile
  deploy/skaffold/Dockerfile.lts
  fs/assets/help.txt
  fs/fs.go
  go.mod
  hack/boilerplate/boilerplate.py
  hack/generate-embedded-files.sh
  hack/tools/go.mod
  hack/tools/tools.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  testutil/fake_fs.go
Labels: size/L

#7329 chore: Fix render and deploy
  cmd/skaffold/app/cmd/deploy.go
  cmd/skaffold/app/cmd/render.go
  cmd/skaffold/app/cmd/run.go
  cmd/skaffold/app/cmd/run_test.go
  integration/deploy_test.go
  integration/examples/getting-started/artifacts.json
  integration/examples/getting-started/images.json
  integration/examples/getting-started/skaffold.yaml
  integration/init_test.go
  integration/render_test.go
  integration/testdata/getting-started/skaffold.yaml
  integration/testdata/jib/.mvn/wrapper/maven-wrapper.jar
  pkg/skaffold/config/types.go
  pkg/skaffold/deploy/deploy.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/errors.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
  pkg/skaffold/deploy/util/logfile_test.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/deploy/util/util_test.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/generate_test.go
  pkg/skaffold/render/renderer/kpt/kpt.go
  pkg/skaffold/render/renderer/kpt/kpt_test.go
  pkg/skaffold/render/renderer/kubectl/kubectl.go
  pkg/skaffold/render/renderer/kubectl/kubectl_test.go
  pkg/skaffold/render/renderer/noop/noop.go
  pkg/skaffold/render/renderer/renderer.go
  pkg/skaffold/render/renderer/util/util.go
  pkg/skaffold/runner/notification.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/timings_test.go
  pkg/skaffold/runner/v2/apply.go
  pkg/skaffold/runner/v2/cleanup.go
  pkg/skaffold/runner/v2/deploy.go
  pkg/skaffold/runner/v2/deploy_test.go
  pkg/skaffold/runner/v2/dev.go
  pkg/skaffold/runner/v2/render.go
  pkg/skaffold/runner/v2/runner_test.go
  testutil/cmd_helper.go
Labels: size/XXL

#7349 fix: properly update 'label' field for helm + render w/ -l flag
  pkg/skaffold/deploy/helm/helm.go
Labels: size/M

#7347 fix: cloud build for using private workerpool
  integration/inspect_test.go
  integration/testdata/inspect/gcb/skaffold.add.default.yaml
  integration/testdata/inspect/gcb/skaffold.add.profile.yaml
  integration/testdata/inspect/gcb/skaffold.gcb.yaml
  integration/testdata/inspect/gcb/skaffold.local.yaml
  integration/testdata/inspect/gcb/skaffold.modified.default.yaml
  integration/testdata/inspect/gcb/skaffold.modified.profile.yaml
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: size/L

#7360 release: v1.37.2
  CHANGELOG.md
Labels: size/S
