Repository GoogleContainerTools/skaffold, pull requests merged in 2022-06, with the labels that each got.

#7470 chore: fix-TestRunRenderOnly test
  cmd/skaffold/app/cmd/run.go
  integration/run_test.go
Labels: size/XS

#7467 chore: fix integration run test
  integration/examples/custom-tests/skaffold.yaml
  integration/examples/profiles/skaffold.yaml
  integration/examples/structure-tests/skaffold.yaml
  integration/examples/tagging-with-environment-variables/skaffold.yaml
  integration/run_test.go
  integration/testdata/custom-test/skaffold.yaml
  integration/testdata/deploy-multiple/skaffold.yaml
Labels: size/M

#7500 chore: re-enable cache_test
  integration/cache_test.go
Labels: size/S

#7501 fix: partition GCP integration tests
  integration/binpack/binpack.go
  integration/binpack/binpack_test.go
  integration/binpack/gcp.go
  integration/util.go
Labels: size/M

#7502 feat: handle minikube exit code 89
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
Labels: size/S

#7516 chore: skip failing tests until fixed for v2
  integration/deploy_cloudrun_test.go
  integration/dev_test.go
  integration/run_test.go
Labels: size/M

#7448 feat: add warning message when no pods are matched for an image doing sync
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/syncer_mux.go
Labels: size/S

#7521 fix: delete and Cleanup now have manifests plumbed through
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/dev_test.go
  cmd/skaffold/app/cmd/util.go
  pkg/skaffold/deploy/deploy_mux.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/runner/runner.go
  pkg/skaffold/runner/timings.go
  pkg/skaffold/runner/v2/cleanup.go
Labels: size/M

#7530 chore: re-enable-integration/housekeeping_messages_test.go
  integration/housekeeping_messages_test.go
Labels: size/XS

#7524 chore: re-enable-integration/test_test.go
  integration/test_test.go
Labels: size/XS

#7507 chore: re-enable integration/diagonose test
  integration/diagnose_test.go
Labels: size/S

#7512 chore: re-enable integration/filter_test
  integration/filter_test.go
Labels: size/XS

#7528 chore: re-enable integration/test_events_test.go
  integration/test_events_test.go
  integration/testdata/test-events/skaffold.yaml
Labels: size/S

#7508 chore: re-enable-integration/rpc_test
  integration/rpc_test.go
Labels: size/M

#7509 chore: re-enable integration/custom_test
  integration/custom_test.go
Labels: size/XS

#7523 chore: re-enable tests in port_forward_test.go
  integration/port_forward_test.go
Labels: size/S

#7511 chore: re-enable tests in integration/sync_test.go
  integration/sync_test.go
Labels: size/S

#7534 fix: resolve windows TestDockerCLICheckCacheFromArgs error
  pkg/skaffold/docker/dependencies.go
Labels: size/XS

#7535 fix: unskip tests in versions_test.go and get them passing
  pkg/skaffold/schema/versions_test.go
Labels: size/M

#7532 fix: get TestDev_WithDependencies passing and unskip the test
  integration/dev_dependencies_test.go
  integration/testdata/build-dependencies/skaffold.yaml
Labels: size/S

#7529 chore: re-enable-integration/build_cluster_test
  integration/build_cluster_test.go
  integration/testdata/kaniko-insecure-registry/skaffold.yaml
  integration/testdata/skaffold-in-cluster/skaffold.yaml
Labels: size/S

#7536 fix: unskip tests in render_test.go and get them passing
  integration/render_test.go
Labels: size/XS

#7541 chore: revert "chore: re-enable-integration/build_cluster_test"
  integration/build_cluster_test.go
  integration/testdata/kaniko-insecure-registry/skaffold.yaml
  integration/testdata/skaffold-in-cluster/skaffold.yaml
Labels: size/S

#7527 fix: plumb manifests through Apply to get functionality working
  cmd/skaffold/app/cmd/delete.go
  cmd/skaffold/app/cmd/dev.go
  cmd/skaffold/app/cmd/util.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/runner/v2/apply.go
Labels: size/L

#7510 chore: re-enable/integration/dev_test
  integration/dev_test.go
Labels: size/M

#7547 fix: unskip tests in apply_test.go and get them passing
  integration/apply_test.go
  integration/examples/helm-deployment/skaffold.yaml
Labels: size/XS

#7548 fix: unskip tests in samples_test.go and get them passing
  docs-v2/content/en/samples/builders/ko-platforms.yaml
  docs/content/en/samples/builders/ko-platforms.yaml
  pkg/skaffold/schema/validation/samples_test.go
Labels: size/S

#7553 chore: fix flaky test -TestDevAutoSyncAPITrigger
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
Labels: size/S

#7550 feat: add `hostPlatform` and `targetPlatforms` to event APIs
  docs-v2/content/en/api-v2/skaffold.swagger.json
  docs-v2/content/en/api/skaffold.swagger.json
  docs-v2/content/en/docs/references/api-v2/grpc.md
  docs-v2/content/en/docs/references/api/grpc.md
  docs/content/en/api-v2/skaffold.swagger.json
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api-v2/grpc.md
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/scheduler.go
  pkg/skaffold/event/event.go
  pkg/skaffold/event/event_test.go
  pkg/skaffold/event/v2/build.go
  proto/v1/skaffold.pb.go
  proto/v1/skaffold.proto
  proto/v2/skaffold.pb.go
  proto/v2/skaffold.proto
Labels: size/XL

#7556 Feat: Implement Services Port Forwarding for Cloud Run
  docs/content/en/api/skaffold.swagger.json
  docs/content/en/docs/references/api/grpc.md
  pkg/skaffold/deploy/cloudrun/accessor.go
  pkg/skaffold/deploy/cloudrun/accessor_test.go
  pkg/skaffold/deploy/cloudrun/cloudrun.go
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/cloudrun/deploy_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XL

#7569 doc: remove image build from the render command decription
  cmd/skaffold/app/cmd/render.go
  docs/content/en/docs/references/cli/_index.md
Labels: size/XS

#7580 release: v1.39.0
  CHANGELOG.md
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
Labels: size/L

#7579 fix: switch cloud run deployer to prefer project in Skaffold manifest over Cloud Run manifest
  integration/testdata/deploy-cloudrun/skaffold.yaml
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/cloudrun/deploy_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/schema/latest/config.go
Labels: size/M

#7585 Revert helm 3.0 and 3.1 deployer changes.
  integration/debug_test.go
  pkg/skaffold/deploy/helm/args.go
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/deploy30.go
  pkg/skaffold/deploy/helm/deploy31.go
  pkg/skaffold/deploy/helm/deployer.go
  pkg/skaffold/deploy/helm/helm30_test.go
  pkg/skaffold/deploy/helm/helm31_test.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/initializer/init_test.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/v1/runner_test.go
Labels: size/XXL

#7586 release: v1.39.1
  .github/workflows/draft-release.yml
  CHANGELOG.md
  hack/release.sh
  hack/release/changelog/main.go
Labels: size/S

#7593 fix: index out of range error
  pkg/skaffold/build/cache/details.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/jib/gradle_test.go
  pkg/skaffold/build/jib/maven_test.go
  pkg/skaffold/docker/remote.go
  pkg/skaffold/util/platform.go
Labels: size/M

#7596 release: v1.39.1
  CHANGELOG.md
Labels: size/XS

#7591 fix: [v1] do not replace every string matching image names
  pkg/skaffold/kubernetes/manifest/images.go
  pkg/skaffold/kubernetes/manifest/images_test.go
Labels: size/L

#7578 feat: adding support for supplying manifests with url
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/kubernetes/manifest/gcs.go
  pkg/skaffold/kubernetes/manifest/url.go
  pkg/skaffold/render/generate/generate.go
  pkg/skaffold/render/generate/generate_test.go
Labels: size/L

#7603 chore: Remove render from deployer inteface
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/deploy_mux_test.go
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kustomize/kustomize.go
  pkg/skaffold/deploy/kustomize/kustomize_test.go
Labels: size/XL

#7612 docs: add missing templatable field
  docs/content/en/docs/environment/templating.md
Labels: size/XS
