Repository GoogleContainerTools/skaffold, pull requests merged in 2022-12, with the labels that each got.

#8184 chore: update CHANGELOG.md to include v2.0.3
  CHANGELOG.md
Labels: size/S

#8179 feat: remove jdk from slim image deps
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8176 docs: update templated fields docs to reflect recent changes
  docs-v2/content/en/docs/environment/templating.md
Labels: size/XS, bugbash/q4-2022

#8196 chore: re-enable TestBuildKanikoInsecureRegistry gcp test
  integration/build_cluster_test.go
Labels: size/XS

#8201 chore: update error message for build failure due to failed image push
  pkg/skaffold/build/build_problems.go
  pkg/skaffold/build/build_problems_test.go
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/build/builder_mux_test.go
Labels: size/M

#8198 chore: re-enable gcp tests
  integration/examples/kaniko/skaffold.yaml
  integration/run_test.go
Labels: size/M

#8195 chore: fix latest label misplaced issue
  docs-v2/config.toml
Labels: size/XS

#8210 chore: Revert re-enable TestBuildKanikoInsecureRegistry gcp test
  integration/build_cluster_test.go
Labels: size/XS

#8208 feat: changing messages when no artifacts are detected
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/deploy.go
  pkg/skaffold/runner/dev.go
Labels: size/S

#8199 feat: enable --tag flag in render command
  cmd/skaffold/app/cmd/flags.go
  docs/content/en/docs/references/cli/_index.md
  integration/render_test.go
Labels: size/M

#8213 fix: `generate-man.sh` should update docs-v2
  docs-v2/content/en/docs/references/cli/_index.md
  hack/generate-man.sh
Labels: size/XS

#8173 feat: add life cycle hooks to Cloud Run deployer
  docs-v2/content/en/schemas/v4beta2.json
  examples/lifecycle-hooks/k8s-pod.yaml
  examples/lifecycle-hooks/skaffold.yaml
  integration/deploy_cloudrun_test.go
  integration/testdata/deploy-cloudrun-with-hooks/module1/service.yaml
  integration/testdata/deploy-cloudrun-with-hooks/module1/skaffold.yaml
  integration/testdata/deploy-cloudrun-with-hooks/module2/service.yaml
  integration/testdata/deploy-cloudrun-with-hooks/module2/skaffold.yaml
  integration/testdata/deploy-cloudrun-with-hooks/skaffold.yaml
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/hooks/deploy.go
  pkg/skaffold/hooks/deploy_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#8205 docs: Update _index.md
  docs-v2/content/en/docs/quickstart/_index.md
Labels: size/XS

#8214 chore: updated github workflows to more gracefully handle cancel-in-progress
  .github/workflows/codeql-analysis.yml
  .github/workflows/draft-release.yml
  .github/workflows/integration-linux.yml
  .github/workflows/linters-checks.yml
  .github/workflows/performance-comparison-label.yml
  .github/workflows/performance-comparison.yml
  .github/workflows/unit-tests-darwin.yml
  .github/workflows/unit-tests-linux.yml
  .github/workflows/unit-tests-windows.yml
  .github/workflows/verify-examples.yml
Labels: size/S

#8222 fix: expand namespace with env variables
  integration/run_test.go
  integration/testdata/kubectl-with-default-namespace/Dockerfile
  integration/testdata/kubectl-with-default-namespace/go.mod
  integration/testdata/kubectl-with-default-namespace/k8s-pod.yaml
  integration/testdata/kubectl-with-default-namespace/main.go
  integration/testdata/kubectl-with-default-namespace/skaffold.yaml
  pkg/skaffold/runner/runcontext/context.go
Labels: size/M

#8217 docs: kpt validators link to render properly
  docs-v2/content/en/docs/pipeline-stages/renderers/kpt.md
Labels: size/XS

#8229 docs: how-to default values for template variables
  docs-v2/content/en/docs/environment/templating.md
Labels: size/XS

#8230 fix: validate whether kubeContext is blank or not
  pkg/skaffold/kubectl/cli.go
Labels: size/XS

#8209 chore: don't stop on failed cleanup
  integration/delete_test.go
  pkg/skaffold/deploy/deploy_mux.go
Labels: size/S

#8232 docs: missing `}` in docs/environment/templating.md
  docs-v2/content/en/docs/environment/templating.md
Labels: size/XS

#8197 chore: change integration test default repo to a dedicated testing repo
  Makefile
  integration/build_dependencies_test.go
  integration/build_test.go
  integration/examples/generate-pipeline/expectedPipeline.yaml
  integration/examples/ko/cloudbuild.yaml
  integration/examples/ko/skaffold.yaml
  integration/helm_test.go
  integration/multiplatform_test.go
  integration/render_test.go
  integration/skaffold/helper.go
  integration/testdata/build/gcb-with-platform/k8s-pod.yaml
  integration/testdata/build/gcb-with-platform/skaffold.yaml
  integration/testdata/deploy-multiple/kubectl/k8s-pod.yaml
  integration/testdata/deploy-multiple/skaffold.yaml
  integration/testdata/fix/k8s-pod.yaml
  integration/testdata/fix/skaffold.yaml
  integration/testdata/gcb-explicit-repo/skaffold.yaml
  integration/testdata/gcb-with-location/k8s-pod.yaml
  integration/testdata/gcb-with-location/skaffold.yaml
  integration/testdata/generate_pipeline/existing_oncluster/expectedPipeline.yaml
  integration/testdata/generate_pipeline/existing_other/expectedPipeline.yaml
  integration/testdata/generate_pipeline/multiple_configs/expectedPipeline.yaml
  integration/testdata/generate_pipeline/multiple_configs/expectedSkaffold.yaml
  integration/testdata/generate_pipeline/multiple_configs/skaffold.yaml
  integration/testdata/generate_pipeline/no_profiles/expectedPipeline.yaml
  integration/testdata/helm-render/builds.out.json
  integration/testdata/helm-render/skaffold-helm/values.yaml
  integration/testdata/helm-render/skaffold.yaml
  integration/testdata/helm/skaffold.yaml
  integration/testdata/init/compose/docker-compose.yaml
  integration/testdata/init/compose/skaffold.yaml
  integration/testdata/kaniko-explicit-repo/skaffold.yaml
  integration/testdata/skaffold-in-cluster/README.md
  integration/testdata/skaffold-in-cluster/skaffold.yaml
Labels: size/L

#8211 docs: update `build-artifacts` flag description
  cmd/skaffold/app/cmd/flags.go
  docs-v1/content/en/docs/references/cli/_index.md
  docs-v2/content/en/docs/references/cli/_index.md
Labels: size/L

#8202 feat: new `--auto` flag
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/runner.go
  docs-v1/content/en/docs/references/cli/_index.md
  docs-v2/content/en/docs/references/cli/_index.md
  pkg/skaffold/config/options.go
  pkg/skaffold/initializer/init.go
  pkg/skaffold/initializer/transparent.go
Labels: size/M

#8236 feat: always override `skaffold.dev/run-id` label and allow setting it via `--label` flag
  cmd/skaffold/app/cmd/flags.go
  docs-v2/content/en/docs/references/cli/_index.md
  pkg/skaffold/kubernetes/manifest/labels.go
  pkg/skaffold/kubernetes/manifest/labels_test.go
Labels: size/M

#8249 fix: scanning ignored files in dev session
  pkg/skaffold/docker/dependencies.go
  pkg/skaffold/docker/syncmap.go
  pkg/skaffold/walk/walk.go
Labels: size/S

#8258 test: use `T.Setenv` to set env vars in tests
  cmd/skaffold/app/skaffold_test.go
  integration/run_test.go
  integration/verify_test.go
  pkg/skaffold/build/ko/builder_test.go
  pkg/skaffold/docker/auth_test.go
  pkg/skaffold/gcp/auth_test.go
  pkg/skaffold/instrumentation/trace_test.go
  pkg/skaffold/kubernetes/context/context_test.go
  testutil/env.go
  testutil/kubecontext.go
Labels: size/M

#8256 fix: remove kubecontext check warning from kubectl deploy
  pkg/skaffold/deploy/kubectl/kubectl.go
Labels: size/XS

#8261 fix: correct issue where skaffold setTemplateValues env vars were in some cases empty
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
  docs-v2/content/en/docs/pipeline-stages/renderers/helm.md
  integration/helm_test.go
  integration/render_test.go
  integration/testdata/helm-multi-config/Makefile
  integration/testdata/helm-multi-config/skaffold/app1/skaffold.yml
  integration/testdata/helm-multi-config/skaffold/app2/skaffold.yml
  integration/testdata/helm-statefulset-v1-schema/Dockerfile
  integration/testdata/helm-statefulset-v1-schema/README.md
  integration/testdata/helm-statefulset-v1-schema/charts/Chart.yaml
  integration/testdata/helm-statefulset-v1-schema/charts/templates/deployment.yaml
  integration/testdata/helm-statefulset-v1-schema/charts/values.yaml
  integration/testdata/helm-statefulset-v1-schema/main.go
  integration/testdata/helm-statefulset-v1-schema/skaffold.yaml
  pkg/skaffold/schema/v2beta29/upgrade.go
  pkg/skaffold/util/util.go
Labels: size/L

#8269 fix: resolve issue where skaffold would not add digest when using helm in v1 -> v2 migration case
  integration/helm_test.go
  integration/testdata/helm-multi-config/skaffold/app1/skaffold.yml
  integration/testdata/helm-multi-config/skaffold/app2/skaffold.yml
  pkg/skaffold/helm/args.go
  pkg/skaffold/schema/v2beta29/upgrade.go
Labels: !! do-not-merge !!, size/S

#8220 feat: more meaningful error message for kustomize issues: #8218
  pkg/skaffold/render/generate/util.go
Labels: size/XS

#8271 docs: Remove extraneous 'F' in 'Depending'
  docs-v2/content/en/docs/pipeline-stages/deployers/helm.md
Labels: size/XS

#8273 chore: add v2.0.4 information to CHANGELOG.md
  CHANGELOG.md
Labels: size/S

#8264 feat: get image digest from container logs for kaniko builder
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/constants/constants.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/versions_test.go
Labels: size/M

#8274 docs: Update Quickstart and Tutorials pages with new Skaffold onboarding walkthrough
  docs-v2/content/en/docs/quickstart/_index.md
  docs-v2/content/en/docs/tutorials/build-and-deploy-to-kubernetes.md
Labels: size/L
