Repository GoogleContainerTools/skaffold, pull requests merged in 2023-10, with the labels that each got.

#9100 feat: Support post-renderer for helm deployer.
  cmd/skaffold/app/cmd/filter.go
  cmd/skaffold/app/cmd/filter_test.go
  integration/helm_test.go
  integration/testdata/helm/change_replicas.py
  integration/testdata/helm/skaffold.yaml
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/helm/bin.go
  pkg/skaffold/helm/bin_test.go
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/L

#9109 docs: update changelog for v2.8.0
  CHANGELOG.md
  docs-v2/content/en/schemas/version-mappings/v4beta7-version.json
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/go-integration-coverage/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  examples/using-env-file/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#9125 docs: fix releaseNoteLink for v2.8.0
  docs-v2/content/en/schemas/version-mappings/v4beta7-version.json
Labels: size/XS

#9074 fix: kpt force named "false" in schema
  docs-v2/content/en/schemas/v4beta8.json
  pkg/skaffold/schema/latest/config.go
Labels: size/S

#9150 chore: add new config to control the pull behaviour for verify
  pkg/skaffold/runner/verifier.go
  pkg/skaffold/verify/docker/verify.go
  pkg/skaffold/verify/docker/verify_test.go
Labels: size/L
