Repository GoogleContainerTools/skaffold, pull requests merged in 2023-05, with the labels that each got.

#8710 fix: new `remove` method in docker client to use in custom actions and don't get the error related with prune
  pkg/skaffold/actions/docker/task.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/verify/docker/verify.go
Labels: size/S

#8726 release: v2.4.0
  CHANGELOG.md
Labels: size/M

#8729 test: comment last line of expected log due to issue #8728
  integration/exec_test.go
Labels: size/XS

#8737 fix: missing Sessionable ID in exported metrics
  pkg/skaffold/instrumentation/firelog/exporter.go
  pkg/skaffold/instrumentation/firelog/exporter_test.go
  pkg/skaffold/instrumentation/firelog/types.go
Labels: size/M

#8739 release: v2.4.0
  CHANGELOG.md
Labels: size/XS

#8727 fix: scanning filter not working properly due to version sorting
  deploy/vuln-monitor/scan.sh
Labels: size/XS

#8750 fix: resolve issues with hack/new-version.sh so it works w/ no manual changes necessary
  hack/versions/cmd/new/templates/upgrade_test.template
  hack/versions/cmd/new/version.go
  pkg/skaffold/schema/latest/config.go
Labels: size/M

#8752 fix: resolve issue where hack/release.sh wouldn't mark schema as released
  hack/versions/cmd/mark_latest_released/main.go
Labels: size/XS

#8756 fix: discard standout from helm dep command to not have corrupted data in output yaml file
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/XS

#8761 chore: fix for Helm render with dependencies v2.4.1
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/XS

#8769 release: v2.4.1
  CHANGELOG.md
Labels: size/S

#8774 chore: update Dockerfile bin deps
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
  deploy/skaffold/digests/kustomize.amd64.sha256
Labels: size/M

#8783 chore: Release/v2.0.11
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
  deploy/skaffold/digests/kustomize.amd64.sha256
  go.mod
  go.sum
  hack/update-lts-dependencies.sh
Labels: size/XXL

#8782 chore: Release/v1.39.10
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
  deploy/skaffold/digests/kustomize.amd64.sha256
  go.mod
  go.sum
  hack/update-lts-dependencies.sh
Labels: size/XXL

#8784 chore: Release/v2.3.2
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
  deploy/skaffold/digests/kustomize.amd64.sha256
  go.mod
  go.sum
  hack/update-lts-dependencies.sh
  pkg/skaffold/inspect/executionModes/list_test.go
Labels: size/XXL

#8790 chore: update gcloud URL in Dockerfile.deps.*
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#8755 feat: new k8s task and exec env for custom actions
  integration/exec_k8s_actions_test.go
  integration/testdata/custom-actions-k8s/app/Dockerfile
  integration/testdata/custom-actions-k8s/app/main.go
  integration/testdata/custom-actions-k8s/exec.env
  integration/testdata/custom-actions-k8s/skaffold.yaml
  pkg/diag/validator/validator.go
  pkg/skaffold/actions/docker/exec_env.go
  pkg/skaffold/actions/docker/exec_env_test.go
  pkg/skaffold/actions/k8sjob/exec_env.go
  pkg/skaffold/actions/k8sjob/task.go
  pkg/skaffold/actions/runner.go
  pkg/skaffold/actions/runner_test.go
  pkg/skaffold/actions/types.go
  pkg/skaffold/k8sjob/util.go
  pkg/skaffold/runner/actions.go
  pkg/skaffold/runner/actions_runner.go
  pkg/skaffold/verify/k8sjob/verify.go
Labels: size/XXL

#8789 chore: update go deps
  go.mod
  go.sum
  vendor/github.com/docker/distribution/Dockerfile
  vendor/github.com/docker/distribution/registry/client/errors.go
  vendor/github.com/docker/distribution/registry/client/transport/http_reader.go
  vendor/k8s.io/kubectl/pkg/util/deployment/deployment.go
  vendor/modules.txt
Labels: size/XS

#8773 chore: add script to update lts dependencies
  hack/update-lts-dependencies.sh
Labels: size/L

#8792 chore: update Dockerfile.deps.* to use python3
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#8793 chore: update Dockerfile.deps.* to use python3
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8794 chore: update Dockerfile.deps.* to use python3
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8762 docs: add `overrides` and `jobManifestPath` to verify docs
  docs-v2/content/en/docs/verify.md
  docs-v2/content/en/samples/verify/verify.yaml
Labels: size/M

#8812 test: disable failing buildpacks tests
  integration/debug_test.go
  integration/run_test.go
Labels: size/M

#8808 docs: update skaffold.yaml page to show latest schema version
  docs-v2/config.toml
Labels: size/XS

#8810 chore: update various container deps.
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
Labels: size/M

#8815 chore: update various container deps.
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
Labels: size/M

#8817 test: disable failing buildpacks tests (#8812)
  integration/debug_test.go
  integration/run_test.go
Labels: size/M

#8818 test: disable failing buildpacks tests (#8812)
  integration/debug_test.go
  integration/run_test.go
Labels: size/M

#8821 chore: update various container deps. (#8810)
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
Labels: size/S

#8823 release: v2.5.0
  CHANGELOG.md
Labels: size/M

#8827 chore: update various container deps. (#8810)
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
Labels: size/M

#8828 fix: broken merge
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#8833 test: increase progressDeadlineSeconds timeout for TestRunUnstableChecked
  integration/testdata/unstable-deployment/incorrect-deployment.yaml
Labels: size/XS

#8757 fix: Replace Kustomize field `patches` in examples
  examples/go-integration-coverage/k8s/overlays/coverage/Kustomization
  examples/kustomize/kustomization.yaml
  integration/examples/go-integration-coverage/k8s/overlays/coverage/Kustomization
  integration/examples/kustomize/kustomization.yaml
Labels: deploy/kustomize, size/XS

#8835 test: v1.39.13 increase progressDeadlineSeconds timeout for TestRunUnstableChecked
  integration/testdata/unstable-deployment/incorrect-deployment.yaml
Labels: size/XS
