Repository GoogleContainerTools/skaffold, pull requests merged in 2023-08, with the labels that each got.

#8981 fix: status check connecting to the wrong k8s context
  pkg/skaffold/kubernetes/status/resource/deployment.go
Labels: size/XS

#8986 chore: remove latest tagging from release process
  Makefile
  deploy/cloudbuild-release.yaml
Labels: size/XS

#8987 chore: remove latest tagging from release process v2.3
  .github/workflows/integration-linux.yml
  Makefile
  deploy/cloudbuild-release.yaml
Labels: size/XS

#8984 chore: remove latest tagging from release process v1.39
  .github/workflows/integration-linux.yml
  Makefile
Labels: size/XS

#8985 chore: remove latest tagging in release process 2.0
  .github/workflows/integration-linux.yml
  Makefile
Labels: size/XS

#8983 docs: add example to use cloudrun deployer + local build
  docs-v2/content/en/docs/deployers/cloudrun.md
  docs-v2/content/en/samples/deployers/cloud-run/local-build-image.yaml
Labels: size/M

#8992 chore: upgrade go 1.19.10 -> 1.20.7
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#9012 chore: upgrade go 1.19.10 -> 1.21.0
  deploy/skaffold/Dockerfile.deps
Labels: size/XS

#9011 chore: upgrade go 1.19.10 -> 1.21.0
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#9010 chore: upgrade go 1.19.10 -> 1.21.0
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#9009 chore: upgrade go 1.19.10 -> 1.21.0
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8991 fix: documentation for Helm Template Value
  docs-v2/content/en/docs/renderers/helm.md
Labels: size/XS

#9017 docs: Update documentation
  docs-v2/content/en/docs/environment/templating.md
Labels: size/S

#9008 fix: #9006 - Filter port forwarding resources for docker deploy
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/docker/deploy_test.go
Labels: size/L

#9018 Ignore unset variables from minikube docker-env
  pkg/skaffold/docker/client.go
Labels: size/XS

#8966 feat: support overrides in helm renderer
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/L

#9015 fix: status check lists all events
  pkg/diag/validator/deployment.go
  pkg/diag/validator/validator.go
  pkg/skaffold/kubernetes/status/resource/deployment.go
Labels: size/M

#9023 feat: support url as kustomize file path
  integration/render_test.go
  integration/testdata/kustomize/remote/skaffold.yaml
  pkg/skaffold/render/renderer/kustomize/kustomize.go
Labels: size/S

#9029 Use moby/patternmatcher for dockerignore
  go.mod
  go.sum
  pkg/skaffold/docker/dockerignore.go
  vendor/github.com/moby/patternmatcher/LICENSE
  vendor/github.com/moby/patternmatcher/NOTICE
  vendor/github.com/moby/patternmatcher/patternmatcher.go
  vendor/modules.txt
Labels: size/M

#9020 feat: enable skaffold render to track telemetry
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/render.go
  integration/housekeeping_messages_test.go
  pkg/skaffold/instrumentation/prompt/prompt.go
  pkg/skaffold/instrumentation/prompt/prompt_test.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: size/L

#9016 feat: crd status check
  cmd/skaffold/app/cmd/flags.go
  docs-v1/content/en/api-v2/skaffold.swagger.json
  docs-v1/content/en/api/skaffold.swagger.json
  docs-v1/content/en/docs/references/api-v2/grpc.md
  docs-v1/content/en/docs/references/api/grpc.md
  docs-v2/content/en/api-v2/skaffold.swagger.json
  docs-v2/content/en/api/skaffold.swagger.json
  docs-v2/content/en/docs/references/api-v2/grpc.md
  docs-v2/content/en/docs/references/api/grpc.md
  docs-v2/content/en/docs/references/cli/_index.md
  pkg/diag/validator/config_connector.go
  pkg/diag/validator/custom_resource.go
  pkg/diag/validator/validator.go
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/component/kubernetes/component.go
  pkg/skaffold/deploy/component/kubernetes/monitor_test.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kpt/kpt.go
  pkg/skaffold/deploy/kpt/kpt_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/deploy/kubectl/kubectl_test.go
  pkg/skaffold/deploy/kubectl/kustomize_test.go
  pkg/skaffold/kubernetes/manifest/selector.go
  pkg/skaffold/kubernetes/manifest/selector_test.go
  pkg/skaffold/kubernetes/manifest/visitor_test.go
  pkg/skaffold/kubernetes/status/resource/deployment.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/runcontext/context.go
  proto/enums/enums.pb.go
  proto/enums/enums.proto
  proto/v1/skaffold.pb.go
  proto/v2/skaffold.pb.go
Labels: size/XL

#9052 fix: save runtime type in artifact json
  cmd/skaffold/app/cmd/build_test.go
  pkg/skaffold/graph/artifact_graph.go
Labels: size/M

#9050 fix: verify flaky tests
  integration/exec_k8s_actions_test.go
  integration/testdata/verify-succeed-k8s/skaffold.yaml
  integration/verify_test.go
Labels: size/M

#9061 chore: remove refs to deprecated io/ioutil
  pkg/skaffold/inspect/jobManifestPaths/modify.go
  pkg/skaffold/inspect/namespaces/list.go
  pkg/skaffold/k8sjob/util.go
  pkg/skaffold/render/renderer/kustomize/kustomize.go
Labels: size/S

#9048 feat: bazel oci rule support
  integration/run_test.go
  integration/testdata/bazel-rules-oci/BUILD
  integration/testdata/bazel-rules-oci/WORKSPACE
  integration/testdata/bazel-rules-oci/deploy.yaml
  integration/testdata/bazel-rules-oci/skaffold.yaml
  integration/testdata/bazel-rules-oci/sub-dir/BUILD
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/bazel/build_test.go
  testutil/fake_image_api.go
Labels: size/L

#9059 docs: Update changelog for 2.7.0
  CHANGELOG.md
Labels: size/M

#9060 chore: update the release script
  hack/release.sh
  hack/release/main.go
Labels: size/S
