Repository GoogleContainerTools/skaffold, pull requests merged in 2023-09, with the labels that each got.

#9057 feat: allow specifying a remote config dependency from Google Cloud Storage
  cmd/skaffold/app/cmd/flags.go
  cmd/skaffold/app/cmd/inspect.go
  cmd/skaffold/app/cmd/inspect_build_env.go
  cmd/skaffold/app/cmd/inspect_execution_modes.go
  cmd/skaffold/app/cmd/inspect_job_manifest_paths.go
  cmd/skaffold/app/cmd/inspect_modules.go
  cmd/skaffold/app/cmd/inspect_namespaces.go
  cmd/skaffold/app/cmd/inspect_profiles.go
  cmd/skaffold/app/cmd/inspect_tests.go
  cmd/skaffold/app/cmd/lint.go
  docs-v2/content/en/docs/design/config.md
  docs-v2/content/en/docs/references/cli/_index.md
  docs-v2/content/en/schemas/v4beta7.json
  examples/remote-multi-config-microservices/README.md
  integration/examples/remote-multi-config-microservices/README.md
  pkg/skaffold/config/options.go
  pkg/skaffold/config/remote_cache.go
  pkg/skaffold/config/remote_cache_test.go
  pkg/skaffold/gcs/gsutil.go
  pkg/skaffold/gcs/gsutil_test.go
  pkg/skaffold/git/gitutil.go
  pkg/skaffold/git/gitutil_test.go
  pkg/skaffold/inspect/buildEnv/add_cluster.go
  pkg/skaffold/inspect/buildEnv/add_gcb.go
  pkg/skaffold/inspect/buildEnv/list.go
  pkg/skaffold/inspect/executionModes/list.go
  pkg/skaffold/inspect/jobManifestPaths/list.go
  pkg/skaffold/inspect/modules/list.go
  pkg/skaffold/inspect/namespaces/list.go
  pkg/skaffold/inspect/profiles/list.go
  pkg/skaffold/inspect/tests/list.go
  pkg/skaffold/inspect/types.go
  pkg/skaffold/kubernetes/manifest/gcs.go
  pkg/skaffold/kubernetes/manifest/util.go
  pkg/skaffold/lint/dockerfiles.go
  pkg/skaffold/lint/k8smanifests.go
  pkg/skaffold/lint/skaffoldyamls.go
  pkg/skaffold/lint/types.go
  pkg/skaffold/lsp/handler.go
  pkg/skaffold/parser/config.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/util/gsutil.go
  pkg/skaffold/util/gsutil_test.go
Labels: size/XL

#9047 feat: Add global build pre- and post-hooks
  docs-v2/content/en/schemas/v4beta7.json
  integration/examples/lifecycle-hooks/skaffold.yaml
  pkg/skaffold/runner/builder.go
  pkg/skaffold/runner/builder_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#9078 feat: emit metrics for exec, verify and render
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/exec.go
  cmd/skaffold/app/cmd/render.go
  hack/versions/pkg/schema/check.go
  integration/housekeeping_messages_test.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/prompt/prompt.go
  pkg/skaffold/instrumentation/prompt/prompt_test.go
  pkg/skaffold/output/output.go
  pkg/skaffold/output/output_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
Labels: size/L

#9072 feat: Add skaffold inspect command for adding config dependencies
  cmd/skaffold/app/cmd/inspect.go
  cmd/skaffold/app/cmd/inspect_config_dependencies.go
  pkg/skaffold/inspect/configDependencies/add.go
  pkg/skaffold/inspect/configDependencies/add_test.go
Labels: size/L

#9087 chore: verify should preserve job manifest envs
  integration/testdata/verify-succeed-k8s/job.yaml
  integration/testdata/verify-succeed-k8s/skaffold.yaml
  integration/verify_test.go
  pkg/skaffold/verify/k8sjob/verify.go
  pkg/skaffold/verify/k8sjob/verify_test.go
Labels: size/L

#9088 docs: add templatable field
  docs-v2/content/en/docs/environment/templating.md
Labels: size/XS

#9094 chore: add set docker host by current context
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
  pkg/skaffold/test/structure/structure_test.go
Labels: size/M

#9090 feat: inject namespace from rendered manifests in post deploy hooks
  integration/deploy_hooks_test.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/hooks/deploy.go
  pkg/skaffold/hooks/deploy_test.go
  pkg/skaffold/hooks/env.go
  pkg/skaffold/hooks/env_test.go
Labels: size/L

#9083 docs: Fix document tutorials/skaffold-resource-selector.md
  docs-v2/content/en/docs/tutorials/skaffold-resource-selector.md
Labels: size/M
