Repository GoogleContainerTools/skaffold, pull requests merged in 2023-01, with the labels that each got.

#8294 fix: write maximum of 200 metrics per session
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/recorder.go
Labels: size/L

#8295 feat: allow specifying debug runtime in `skaffold.yaml` for artifact
  cmd/skaffold/app/cmd/util.go
  docs-v2/content/en/schemas/v4beta2.json
  pkg/skaffold/build/builder_mux.go
  pkg/skaffold/build/cache/retrieve.go
  pkg/skaffold/build/result.go
  pkg/skaffold/debug/apply_transforms.go
  pkg/skaffold/debug/transform.go
  pkg/skaffold/debug/transform_go.go
  pkg/skaffold/debug/transform_go_test.go
  pkg/skaffold/debug/transform_jvm.go
  pkg/skaffold/debug/transform_jvm_test.go
  pkg/skaffold/debug/transform_netcore.go
  pkg/skaffold/debug/transform_netcore_test.go
  pkg/skaffold/debug/transform_nodejs.go
  pkg/skaffold/debug/transform_nodejs_test.go
  pkg/skaffold/debug/transform_python.go
  pkg/skaffold/debug/transform_python_test.go
  pkg/skaffold/debug/types/types.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/graph/artifact_graph.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#8280 docs: remove duplicate maturity entry for Cloud Run Deployer
  docs-v2/data/maturity.json
Labels: size/S

#8298 docs: update docs for new `runtimeType` field
  docs-v2/content/en/docs/workflows/debug.md
  docs-v2/content/en/samples/debug/runtime-type.yaml
Labels: size/S

#8296 feat: support-external-cmd-call-in-template
  pkg/skaffold/util/env_template.go
  pkg/skaffold/util/env_template_test.go
Labels: size/M

#8259 fix: use release namespace in render when specified
  integration/render_test.go
  integration/testdata/helm-namespace/charts/Chart.yaml
  integration/testdata/helm-namespace/charts/templates/deployment.yaml
  integration/testdata/helm-namespace/charts/values.yaml
  integration/testdata/helm-namespace/skaffold.yaml
  pkg/skaffold/render/config.go
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/M

#8312 fix: resolve issue where skaffold always added namespace to rendered manifests
  integration/render_test.go
  pkg/skaffold/deploy/kubectl/constants.go
  pkg/skaffold/render/renderer/util/util.go
Labels: size/S

#8314 feat: change components installed in docker images to include alpha and beta
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8309 feat: add new inspect namespaces list command to skaffold
  cmd/skaffold/app/cmd/inspect.go
  cmd/skaffold/app/cmd/inspect_namespaces.go
  pkg/skaffold/inspect/namespaces/list.go
  pkg/skaffold/inspect/namespaces/list_test.go
Labels: size/L

#8323 fix: use new URL format for Google Cloud Build log
  pkg/skaffold/build/gcb/cloud_build.go
Labels: size/XS

#8326 doc: Updating installation link for Cloud Code in VSCode
  docs-v2/content/en/docs/install/_index.md
Labels: size/XS

#8334 chore: unskip TestFix* integration tests
  integration/fix_test.go
Labels: size/XS

#8135 fix: resolve issue where skaffold would panic when StatusCheck was not set
  pkg/skaffold/runner/deployer.go
Labels: size/XS

#8333 fix: backport, divide stdout and stderr from helm to not create corrupted outputs
  pkg/skaffold/deploy/helm/deploy.go
  pkg/skaffold/deploy/helm/util.go
Labels: size/M, kokoro:force-run

#8335 fix: add proper artifactOverrides->setValueTemplates conversion when upgrading from v2beta29
  integration/fix_test.go
  integration/testdata/fix-v2beta29/skaffold.yaml
  pkg/skaffold/schema/v2beta29/upgrade.go
Labels: size/L

#8292 Handle StatefulSets with an OnDelete update strategy
  pkg/skaffold/kubernetes/status/resource/deployment.go
Labels: size/S

#8338 docs: update cloudrun docs to include log streaming and Job support
  docs-v2/content/en/docs/pipeline-stages/deployers/cloudrun.md
Labels: size/XS

#8270 feat: add keep-running-on-failure-implementation
  cmd/skaffold/app/cmd/flags.go
  docs-v2/content/en/docs/references/cli/_index.md
  integration/control_api_test.go
  integration/custom_test.go
  integration/dev_dependencies_test.go
  integration/dev_test.go
  integration/modules_test.go
  integration/rpc_test.go
  integration/sync_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/runner/dev.go
  pkg/skaffold/util/term/term.go
Labels: size/L

#8340 feat: add ingore-path kaniko flag support
  docs-v2/content/en/schemas/v4beta2.json
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/build/kaniko/args.go
  pkg/skaffold/build/kaniko/args_test.go
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/schema/latest/config.go
Labels: size/M

#8345 chore: add v2.0.5 changelog info
  CHANGELOG.md
Labels: size/S

#8346 chore: add v1.39.5 changelog info
  CHANGELOG.md
Labels: size/S

#8344 docs: remove `log tailing` from note of unsupported features for Cloud Run
  docs-v2/content/en/docs/pipeline-stages/deployers/cloudrun.md
Labels: size/XS

#8337 docs: add status check documentation for new tolerateFailuresUntilDeadline config field
  docs-v2/content/en/docs/pipeline-stages/status-check.md
  docs-v2/content/en/samples/deployers/status-check-tolerateFailuresUntilDeadline.yaml
Labels: size/S

#8347 chore: update skaffold image deps based on lts policy
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
Labels: size/S

#8343 release: v2.1.0
  CHANGELOG.md
Labels: size/M

#8353 fix: resolve issue where skaffold version would print nothing
  Makefile
Labels: size/XS

#8352 test: integration test for helm render with OCI repo
  integration/helm_test.go
  integration/skaffold/helper.go
Labels: size/M

#8349 feat: add support for remote docker over ssh
  pkg/skaffold/docker/client.go
  pkg/skaffold/docker/client_test.go
Labels: size/S

#8329 feat: add timeout for copying build context on kaniko
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/docker/context.go
  pkg/skaffold/sources/upload.go
  pkg/skaffold/sync/docker.go
  pkg/skaffold/sync/kubectl.go
  pkg/skaffold/util/tar.go
  pkg/skaffold/util/tar_test.go
Labels: size/L

#8351 fix: resolve issue where kubectl Flags.Apply namespace flag usage would fail
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/inspect/namespaces/list.go
  pkg/skaffold/util/util.go
Labels: size/M

#8369 fix: resolve issue where verify incorrectly failed when run with multiple modules where any module didn't have verify test cases
  pkg/skaffold/schema/validation/validation.go
Labels: size/XS
