Repository GoogleContainerTools/skaffold, pull requests merged in 2023-03, with the labels that each got.

#8479 chore: release/v1.39.6
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/S

#8459 feat: support deploying to multiple clusters
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/kubernetes/logger/formatter.go
  pkg/skaffold/kubernetes/logger/formatter_test.go
  pkg/skaffold/kubernetes/logger/log.go
  pkg/skaffold/runner/runcontext/context.go
Labels: size/M

#8484 Docs: Update _index.md to use more appropriate grammar
  docs-v2/content/en/docs/testers/_index.md
Labels: size/XS

#8480 chore: Security hotfixes for v2.0.6 branch
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/S

#8482 fix: skaffold render namespace regression in v2
  pkg/skaffold/runner/renderer.go
  pkg/skaffold/schema/v2beta29/upgrade.go
  pkg/skaffold/schema/v2beta29/upgrade_test.go
Labels: size/M

#8487 chore: update CHANGELOG.md with 3 patch releases
  CHANGELOG.md
Labels: size/M

#8493 fix: retag multiarch images
  pkg/skaffold/build/cache/details.go
  pkg/skaffold/build/cache/lookup.go
Labels: size/S

#8490 docs: add `minikube tunnel` command in the tutorial
  docs-v2/content/en/docs/quickstart/_index.md
Labels: size/XS

#8496 release: v2.2.0
  CHANGELOG.md
  examples/README.md
  examples/kustomize/kustomization.yaml
  examples/kustomize/skaffold.yaml
  examples/using-env-file/Dockerfile
  examples/using-env-file/README.md
  examples/using-env-file/go.mod
  examples/using-env-file/k8s-pod.yaml
  examples/using-env-file/main.go
  examples/using-env-file/skaffold.env
  examples/using-env-file/skaffold.yaml
Labels: size/L

#8457 fix: add upgrade logic to inject a kubectl deployer when an old kustomize deployer is detected
  cmd/skaffold/app/cmd/fix_test.go
  pkg/skaffold/schema/v2beta29/upgrade.go
  pkg/skaffold/schema/v2beta29/upgrade_test.go
Labels: size/L

#8488 dep: replace dockerignore.ReadAll withgithub.com/moby/buildkit/frontend/dockerfile/dockerignore.ReadAll
  pkg/skaffold/docker/dependencies.go
Labels: size/XS

#8477 docs: add tooltip with yaml path in Skaffold yaml reference page
  docs-v2/content/en/docs/references/yaml/main.css
  docs-v2/content/en/docs/references/yaml/main.js
Labels: size/M

#8491 feat: Whitelist strimzi.io CRDs
  pkg/skaffold/kubernetes/manifest/visitor.go
Labels: size/S

#8508 chore: bump examples to latest released version v4beta3
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/cloud-spanner-bootstrap/go.mod
  examples/grpc-e2e-tests/cloud-spanner-bootstrap/go.sum
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  examples/using-env-file/skaffold.yaml
Labels: size/L

#8502 chore: bump github.com/rjeczalik/notify to get rid of deprecation on darwin
  go.mod
  go.sum
Labels: size/XS

#8516 fix: can't use ctrl-c to terminate building with kaniko at uploading build context stage
  pkg/skaffold/build/cluster/kaniko.go
Labels: size/XS

#8514 fix: move verify schema changes to v4beta4 and remove it from already released v4beta3
  docs-v2/content/en/schemas/v4beta3.json
  pkg/skaffold/schema/v4beta3/config.go
Labels: size/L

#8546 chore: Add output flag for diagnose
  cmd/skaffold/app/cmd/diagnose.go
  docs-v2/content/en/docs/references/cli/_index.md
  integration/diagnose_test.go
Labels: size/M

#8543 fix: `kubectl create` with `dry-run` shouldn't pass the namespace flag
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/kubectl/cli.go
Labels: size/M, kokoro:force-run

#8540 chore: upgrade go version in skaffold image
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8549 fix: make it so tolerateFailuresUntilDeadline also handles kubectl failures (vs. just parsing kubectl resource status values).
  pkg/skaffold/kubernetes/status/resource/deployment.go
  pkg/skaffold/kubernetes/status/resource/deployment_test.go
  pkg/skaffold/kubernetes/status/status_check.go
  pkg/skaffold/kubernetes/status/status_check_test.go
Labels: size/L

#8551 Revert "fix: `kubectl create` with `dry-run` shouldn't pass the namespace flag"
  pkg/skaffold/deploy/kubectl/cli.go
  pkg/skaffold/kubectl/cli.go
Labels: size/M

#8524 chore: update cloudbuild config to publish distroless-skaffold image to artifact registry for vulns scanning
  deploy/cloudbuild-release-lts.yaml
  deploy/cloudbuild.yaml
  deploy/skaffold/Dockerfile.skaffold
Labels: size/M

#8557 fix: improve verify command s.t. os envs not passed through to container envs and instead add a flag for this purpose
  cmd/skaffold/app/cmd/flags.go
  docs-v2/content/en/docs/references/cli/_index.md
  hack/boilerplate/boilerplate.py
  integration/testdata/verify-fail-k8s/verify.env
  integration/testdata/verify-fail/verify.env
  integration/testdata/verify-succeed-k8s/verify.env
  integration/testdata/verify-succeed/verify.env
  integration/verify_test.go
  pkg/skaffold/config/options.go
  pkg/skaffold/runner/verifier.go
  pkg/skaffold/verify/docker/verify.go
  pkg/skaffold/verify/k8sjob/verify.go
  pkg/skaffold/verify/util/util.go
  pkg/skaffold/verify/util/util_test.go
Labels: size/L

#8555 chore: firelog exporter
  pkg/skaffold/instrumentation/ci.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/firelog/exporter.go
  pkg/skaffold/instrumentation/firelog/exporter_test.go
  pkg/skaffold/instrumentation/firelog/types.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/meter_test.go
  pkg/skaffold/instrumentation/types.go
  testutil/env.go
Labels: size/XL

#8570 chore: enhance vuln monitor
  deploy/lts-vuln-monitor/report.sh
  deploy/lts-vuln-monitor/scan.sh
  deploy/vuln-monitor/cloudbuild.yaml
  deploy/vuln-monitor/report.sh
  deploy/vuln-monitor/scan.sh
Labels: size/L

#8585 fix: correctly rewrite /deploy/kubectl/manifests in patch upgrades
  pkg/skaffold/schema/v2beta29/upgrade.go
  pkg/skaffold/schema/v2beta29/upgrade_test.go
Labels: size/XS

#8582 chore: fix transformer share config-map issues
  pkg/skaffold/render/transform/transform.go
  pkg/skaffold/render/transform/transform_test.go
Labels: size/M

#8583 chore: upgrade docker version in skaffold image
  deploy/skaffold/Dockerfile.deps
Labels: size/XS

#8577 chore: change verify schema from v1.Container to subset of direct primitive types
  docs-v2/content/en/schemas/v4beta4.json
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/verify/k8sjob/verify.go
Labels: size/L

#8590 chore: "revert upgrade docker version in skaffold image (#8583)"
  deploy/skaffold/Dockerfile.deps
Labels: size/XS

#8575 feat: add 'skaffold inspect jobManifestPath' and 'skaffold transform-schema jobManifestPath' commands
  cmd/skaffold/app/cmd/inspect.go
  cmd/skaffold/app/cmd/inspect_job_manifest_paths.go
  cmd/skaffold/app/cmd/inspect_namespaces.go
  pkg/skaffold/inspect/jobManifestPaths/list.go
  pkg/skaffold/inspect/jobManifestPaths/list_test.go
  pkg/skaffold/inspect/jobManifestPaths/modify.go
  pkg/skaffold/inspect/jobManifestPaths/modify_test.go
  pkg/skaffold/verify/docker/verify.go
Labels: size/L

#8598 chore "revert: firelog exporter (#8555)"
  pkg/skaffold/instrumentation/ci.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/firelog/exporter.go
  pkg/skaffold/instrumentation/firelog/exporter_test.go
  pkg/skaffold/instrumentation/firelog/types.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/meter_test.go
  pkg/skaffold/instrumentation/types.go
  testutil/env.go
Labels: size/XL

#8593 release: v2.3.0
  CHANGELOG.md
Labels: size/M

#8486 feat: helm dependency build on render
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/M, kokoro:force-run

#8607 chore: bump examples/ schema versions
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  examples/using-env-file/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#8599 chore: restore firelog exporter (#8555)
  pkg/skaffold/instrumentation/ci.go
  pkg/skaffold/instrumentation/export.go
  pkg/skaffold/instrumentation/export_test.go
  pkg/skaffold/instrumentation/firelog/exporter.go
  pkg/skaffold/instrumentation/firelog/exporter_test.go
  pkg/skaffold/instrumentation/firelog/types.go
  pkg/skaffold/instrumentation/meter.go
  pkg/skaffold/instrumentation/meter_test.go
  pkg/skaffold/instrumentation/types.go
  testutil/env.go
Labels: size/XL

#8596 chore: upgrade docker and make integration-in-docker to use docker dependencies from pr
  Makefile
  deploy/skaffold/Dockerfile.deps
Labels: size/S

#8571 docs: minor edits to Cloud Build docs
  docs-v2/content/en/docs/builders/build-environments/cloud-build.md
Labels: size/M

#8584 fix: use active gcp account
  pkg/skaffold/gcp/auth.go
  pkg/skaffold/gcp/auth_test.go
  pkg/skaffold/gcp/client.go
Labels: size/L

#8612 chore: bump image deps
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
Labels: size/S

#8601 docs: update verify docs to reflect k8s job support
  docs-v2/content/en/docs/verify.md
  docs-v2/content/en/samples/verify/verify.yaml
Labels: size/S

#8618 fix: fix issue where verify would panic if a jobManifestPath with no spec.template.spec.metadata.labels existed
  pkg/skaffold/verify/k8sjob/verify.go
Labels: size/XS
