Repository GoogleContainerTools/skaffold, pull requests merged in 2023-12, with the labels that each got.

#9210 fix: add riscv64 to the install-golint.sh script
  hack/install-golint.sh
Labels: size/XS

#9212 fix: remove global helm flags from flags sent to `skaffold filter`
  integration/helm_test.go
  integration/render_test.go
  integration/testdata/helm-render/skaffold.yaml
  integration/testdata/helm/skaffold.yaml
  pkg/skaffold/helm/bin.go
  pkg/skaffold/helm/bin_test.go
Labels: size/L

#9218 chore: change bazel example
  examples/bazel/.bazelrc
  examples/bazel/.bazelversion
  examples/bazel/.gitignore
  examples/bazel/BUILD
  examples/bazel/BUILD.bazel
  examples/bazel/MODULE.bazel
  examples/bazel/README.md
  examples/bazel/WORKSPACE
  examples/bazel/WORKSPACE.bazel
  examples/bazel/deploy.yaml
  examples/bazel/main.go
  examples/bazel/skaffold.yaml
  integration/examples/bazel/.bazelrc
  integration/examples/bazel/.bazelversion
  integration/examples/bazel/.gitignore
  integration/examples/bazel/BUILD
  integration/examples/bazel/BUILD.bazel
  integration/examples/bazel/MODULE.bazel
  integration/examples/bazel/README.md
  integration/examples/bazel/WORKSPACE
  integration/examples/bazel/WORKSPACE.bazel
  integration/examples/bazel/deploy.yaml
  integration/examples/bazel/main.go
  integration/examples/bazel/skaffold.yaml
Labels: size/L

#9207 chore: inject imageInfo when expanding templates for ko builder
  integration/run_test.go
  pkg/skaffold/build/ko/build.go
  pkg/skaffold/build/ko/builder.go
  pkg/skaffold/build/ko/builder_test.go
  pkg/skaffold/constants/constants.go
Labels: size/M

#9216 chore: clean up example project deps
  examples/grpc-e2e-tests/tests/go.mod
  integration/examples/grpc-e2e-tests/tests/go.mod
Labels: size/XS
