Repository GoogleContainerTools/skaffold, pull requests merged in 2023-06, with the labels that each got.

#8834 chore: update release build script to support internal scanning
  Makefile
  deploy/cloudbuild-release-lts.yaml
  deploy/cloudbuild.yaml
Labels: size/XS

#8840 chore: add scanning marker for vulns scanning v1.39
  Makefile
  deploy/cloudbuild-release-lts.yaml
  deploy/cloudbuild.yaml
Labels: size/XS

#8841 chore: add scanning marker for vulns scanning v2.0
  Makefile
  deploy/cloudbuild-release-lts.yaml
  deploy/cloudbuild.yaml
Labels: size/XS

#8842 chore: cherry-pick scanning marker change to release/v2.3
  Makefile
  deploy/cloudbuild-release-lts.yaml
  deploy/cloudbuild.yaml
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  examples/using-env-file/skaffold.yaml
  hack/versions/pkg/schema/check.go
  integration/examples/remote-multi-config-microservices/skaffold.yaml
  pkg/skaffold/update/update.go
Labels: size/L

#8851 feat: logic to only emit the tags related with verify on `skaffold verify`
  cmd/skaffold/app/cmd/exec.go
  cmd/skaffold/app/cmd/verify.go
  integration/testdata/verify-succeed/app/Dockerfile
  integration/testdata/verify-succeed/app/main.go
  integration/testdata/verify-succeed/skaffold.yaml
  integration/verify_test.go
  pkg/skaffold/runner/verify.go
Labels: size/L

#8850 chore: add lock to jib cache lookup
  pkg/skaffold/build/jib/jib.go
Labels: size/XS

#8847 fix: logic to interrupt a k8sjob logs as soon as it fails
  integration/exec_k8s_actions_test.go
  integration/testdata/custom-actions-k8s/skaffold.yaml
  pkg/skaffold/actions/k8sjob/task.go
  pkg/skaffold/k8sjob/logger/log.go
Labels: size/M

#8862 fix: condition to not update helm deployer hook patches, is not needed
  cmd/skaffold/app/cmd/fix_test.go
  pkg/skaffold/schema/v2beta29/upgrade.go
Labels: size/M

#8878 fix: increase progressDeadlineSeconds for TestRunUnstable test and change in baseRef
  hack/versions/pkg/schema/check.go
  integration/testdata/unstable-deployment/incorrect-deployment.yaml
Labels: size/XS

#8871 fix: logic to interrupt a k8sjob logs as soon as it fails (#8847)
  integration/exec_k8s_actions_test.go
  integration/testdata/custom-actions-k8s/skaffold.yaml
  pkg/skaffold/actions/k8sjob/task.go
  pkg/skaffold/k8sjob/logger/log.go
Labels: size/M

#8877 fix: #8870 manifest kustomize paths using env var with absolute path
  pkg/skaffold/render/renderer/kustomize/kustomize.go
Labels: size/S

#8801 feat: new verify timeout config feature
  docs-v2/content/en/schemas/v4beta6.json
  integration/testdata/verify-fail-k8s/skaffold.yaml
  integration/testdata/verify-fail/skaffold.yaml
  integration/testdata/verify-succeed-k8s/skaffold.yaml
  integration/testdata/verify-succeed/skaffold.yaml
  integration/verify_test.go
  pkg/skaffold/actions/k8sjob/task.go
  pkg/skaffold/k8sjob/logger/log.go
  pkg/skaffold/k8sjob/util.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/verify/docker/verify.go
  pkg/skaffold/verify/k8sjob/verify.go
Labels: size/XL

#8896 chore: upgrade go version
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#8895 chore: upgrade go version
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8894 chore: upgrade go version
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.lts
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#8905 fix: add docker to the LTS container images
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#8907 fix: add docker to the LTS container images (#8905)
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#8909 fix: add docker to the LTS container images (#8905)
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#8908 fix: add docker to the LTS container images (#8905)
  deploy/skaffold/Dockerfile.deps.lts
Labels: size/XS

#8897 fix: Clean up dev images except the last
  integration/dev_test.go
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/types.go
Labels: size/M

#8902 chore: port apply-setter krm function over to skaffold
  integration/render_test.go
  pkg/skaffold/render/applysetters/LICENSE
  pkg/skaffold/render/applysetters/apply_setters.go
  pkg/skaffold/render/applysetters/apply_setters_test.go
  pkg/skaffold/render/applysetters/walk.go
  pkg/skaffold/render/renderer/kubectl/kubectl.go
  pkg/skaffold/render/renderer/kustomize/kustomize.go
Labels: size/XXL

#8918 chore: push scanning marker tag to remote-v1.39
  deploy/cloudbuild-release-lts.yaml
Labels: size/XS

#8885 feat: implement skaffold delete for docker deployer using docker labels
  integration/delete_test.go
  integration/testdata/docker-deploy/skaffold.yaml
  pkg/skaffold/actions/docker/exec_env.go
  pkg/skaffold/actions/docker/exec_env_test.go
  pkg/skaffold/deploy/docker/deploy.go
  pkg/skaffold/deploy/label/labeller.go
  pkg/skaffold/docker/debugger/debug.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/verify/docker/verify.go
Labels: size/L

#8916 chore: push scanning marker tag to remote v2.0
  deploy/cloudbuild-release-lts.yaml
Labels: size/XS

#8917 chore: push scanning marker tag to remote
  deploy/cloudbuild-release-lts.yaml
Labels: size/XS

#8919 chore: push scanning marker tag to remote gcr-v2.3
  deploy/cloudbuild-release-lts.yaml
Labels: size/XS
