Repository GoogleContainerTools/skaffold, pull requests merged in 2024-07, with the labels that each got.

#9456 feat: make ADC the default option for GCP authentication when using go-containerregistry
  pkg/skaffold/docker/authenticators.go
  pkg/skaffold/docker/authenticators_test.go
Labels: size/L

#9471 docs: update changelog for v2.13.0
  CHANGELOG.md
Labels: size/M

#9469 feat: default to ADC when `gcloud` cred helper is configured in docker/config.json when using docker go library
  pkg/skaffold/docker/auth.go
  pkg/skaffold/docker/auth_test.go
Labels: size/L

#9261 feat: added retry on files sync error
  pkg/skaffold/runner/dev.go
Labels: size/S

#9479 feat: 2.13.1 cherry picks
  integration/deploy_cloudrun_test.go
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/cloudrun/deploy_test.go
  pkg/skaffold/docker/auth.go
  pkg/skaffold/docker/auth_test.go
Labels: size/L

#9445 Use bazel info workspace to get workspace, check for MODULE.bazel
  pkg/skaffold/build/bazel/dependencies.go
  pkg/skaffold/build/bazel/dependencies_test.go
  pkg/skaffold/tag/custom_template_test.go
Labels: size/M
