Repository GoogleContainerTools/skaffold, pull requests merged in 2024-12, with the labels that each got.

#9596 fix(homepage): fix gem icon
  docs-v2/content/en/_index.html
Labels: size/XS

#9597 chore: update the CODEOWNERS file
  .github/CODEOWNERS
Labels: size/S

#9601 chore: remove MAINTAINERS
  MAINTAINERS
Labels: size/XS

#9604 test: Fix the Bazel integration test.
  integration/testdata/bazel-rules-oci/BUILD
  integration/testdata/bazel-rules-oci/MODULE.bazel
  integration/testdata/bazel-rules-oci/WORKSPACE
  integration/testdata/bazel-rules-oci/sub-dir/BUILD
Labels: size/M

#9614 ci: remove deprecated workflow for creating release. This would prevent accidental trigger of this workflow
  .github/workflows/draft-release.yml
Labels: size/M

#9615 ci: cleaning up references to skaffold slim as it is no longer used
  Makefile
  deploy/cloudbuild-slim.yaml
  deploy/skaffold/Dockerfile.deps.slim
  deploy/skaffold/Dockerfile.slim
Labels: size/L

#9616 chore: cleaning up final references to slim from skaffold
  hack/update-lts-dependencies.sh
Labels: size/XS

#9574 chore: upgrade versions of integration test tooling
  .github/workflows/integration-linux.yml
Labels: size/S

#9582 Support TemplateField for build.artifacts.docker.cliFlags
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/docker/docker_test.go
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/docker/image_test.go
Labels: size/M

#9237 docs: Document some undocumented config options
  docs-v2/content/en/docs/design/global-config.md
Labels: size/XS

#9495 feat: transform imagePullPolicy when using local cluster
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/kubernetes/manifest/image_pull_policy.go
  pkg/skaffold/kubernetes/manifest/image_pull_policy_test.go
Labels: size/L

#9619 chore: allow dependabot to upgrade more dependencies
  .github/dependabot.yml
Labels: size/M
