Repository GoogleContainerTools/skaffold, pull requests merged in 2024-04, with the labels that each got.

#9300 feat: Support Bazel platform mappings
  docs-v2/content/en/schemas/v4beta10.json
  examples/bazel/BUILD.bazel
  examples/bazel/MODULE.bazel
  examples/bazel/README.md
  integration/examples/bazel/BUILD.bazel
  integration/examples/bazel/MODULE.bazel
  integration/examples/bazel/README.md
  integration/examples/bazel/skaffold.yaml
  pkg/skaffold/build/bazel/build.go
  pkg/skaffold/build/bazel/build_test.go
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#9376 release: v2.11.0
  CHANGELOG.md
  docs-v2/content/en/schemas/version-mappings/v4beta10-version.json
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/go-integration-coverage/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/service/go.mod
  examples/grpc-e2e-tests/service/go.sum
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  examples/using-env-file/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#9363 docs: add bazel cross-platform documentation
  docs-v2/content/en/docs/builders/builder-types/bazel.md
  docs-v2/content/en/docs/builders/cross-platform.md
  docs-v2/content/en/samples/builders/bazel-xplat.yaml
Labels: size/M

#9390 feat(docker-network): docker.network now supports any value
  docs-v2/content/en/schemas/v4beta10.json
  fs/assets/credits_generated/github.com/hashicorp/hcl/go.mod
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/schema/validation/validation_test.go
Labels: size/S

#9387 fix: add --load flag for local buildkit
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/docker/docker_test.go
Labels: size/M

#9309 fix(tar): data race fix
  pkg/skaffold/util/tar.go
Labels: size/M

#9270 fix(kaniko): delete kaniko pod on graceful shutdown
  pkg/skaffold/build/cluster/kaniko.go
Labels: size/XS
