Repository GoogleContainerTools/skaffold, pull requests merged in 2024-01, with the labels that each got.

#9211 fix: Scope Issue with the 'entry' variable when looking up remote images and tests additions
  integration/build_dependencies_test.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve_test.go
Labels: size/L

#9203 feat: Skaffold post renderer
  docs-v2/content/en/schemas/v4beta9.json
  integration/examples/lifecycle-hooks/k8s-pod.yaml
  integration/render_test.go
  integration/testdata/post-render-hooks/module1/Dockerfile
  integration/testdata/post-render-hooks/module1/k8s/k8s-pod.yaml
  integration/testdata/post-render-hooks/module1/main.go
  integration/testdata/post-render-hooks/module1/skaffold.yaml
  integration/testdata/post-render-hooks/module2/Dockerfile
  integration/testdata/post-render-hooks/module2/k8s/k8s-pod.yaml
  integration/testdata/post-render-hooks/module2/main.go
  integration/testdata/post-render-hooks/module2/skaffold.yaml
  integration/testdata/post-render-hooks/skaffold.yaml
  pkg/skaffold/hooks/build.go
  pkg/skaffold/hooks/build_test.go
  pkg/skaffold/hooks/deploy.go
  pkg/skaffold/hooks/host.go
  pkg/skaffold/hooks/host_test.go
  pkg/skaffold/hooks/render.go
  pkg/skaffold/hooks/render_test.go
  pkg/skaffold/hooks/sync.go
  pkg/skaffold/render/renderer/render_mux.go
  pkg/skaffold/runner/renderer.go
  pkg/skaffold/schema/latest/config.go
  testutil/util.go
Labels: size/XL

#9240 fix: apply-setter and transformer should ignore non-k8s-resource for kustomize paramterization
  .github/workflows/integration-linux.yml
  .github/workflows/performance-comparison.yml
  integration/render_test.go
  pkg/skaffold/render/renderer/kustomize/kustomize.go
Labels: size/M

#9243 fix: helm-deploy-chart-path-template
  integration/run_test.go
  integration/testdata/helm/skaffold.yaml
  pkg/skaffold/deploy/helm/helm.go
Labels: size/S

#9247 docs: update changelog for v2.10.0
  CHANGELOG.md
  docs-v2/content/en/schemas/version-mappings/v4beta9-version.json
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/go-integration-coverage/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/k8s-pod.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/backend/Gemfile.lock
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  examples/using-env-file/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#9258 fix: print output from post render hook in console when `withChange: false`
  integration/render_test.go
  integration/skaffold/helper.go
  integration/testdata/post-render-hooks/module1/skaffold.yaml
  pkg/skaffold/hooks/render.go
  pkg/skaffold/output/log/log.go
Labels: size/M

#9271 feat(tar): added logs to CreateTar func
  pkg/skaffold/util/tar.go
Labels: size/S

#9267 feat: extracted kaniko copyTimeout and copyMaxRetries into config
  docs-v2/content/en/schemas/v4beta10.json
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/versions_test.go
Labels: size/M

#9278 fix(lookupRemote): fixed lookup.go lookupRemote to compare remote and cached digests
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/runner/new.go
Labels: size/M

#9269 fix(kaniko): resolve blocking on Ctrl+C during Docker context creation
  pkg/skaffold/build/cluster/kaniko.go
Labels: size/S
