Repository GoogleContainerTools/skaffold, pull requests merged in 2024-02, with the labels that each got.

#9295 fix(helm): use secrets helm plugin to render when useHelmSecrets is true
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/S

#9301 fix(lookupRemote): cherry-pick cache remote fix
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.slim
  hack/versions/pkg/schema/check.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/runner/new.go
Labels: size/L

#9303 chore: upgrade go to v1.21.6 due to vuls
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.slim
Labels: size/XS

#9293 chore: new googleCloudBuildRepoV2 field to configure a remote dependency
  docs-v2/content/en/schemas/v4beta10.json
  integration/deploy_test.go
  integration/remote_config_dependency_test.go
  pkg/skaffold/git/errors.go
  pkg/skaffold/git/gitutil.go
  pkg/skaffold/git/gitutil_test.go
  pkg/skaffold/parser/config.go
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#9313 fix: revert cache lookup changes
  integration/build_dependencies_test.go
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/runner/new.go
Labels: size/L
