Repository GoogleContainerTools/skaffold, pull requests merged in 2024-08, with the labels that each got.

#9503 fix: keep the original template if template expansion fails
  integration/diagnose_test.go
  integration/testdata/diagnose/not-all-envs-set/skaffold.yaml
  pkg/skaffold/tags/templates.go
  pkg/skaffold/tags/templates_test.go
Labels: size/L

#9504 fix: keep the original template if template expansion fails (#9503)
  integration/diagnose_test.go
  integration/testdata/diagnose/not-all-envs-set/skaffold.yaml
  pkg/skaffold/tags/templates.go
  pkg/skaffold/tags/templates_test.go
Labels: size/L

#9430 feat(git): added commit hash support to git.ref
  pkg/skaffold/git/gitutil.go
Labels: size/S

#9467 fix(docs): fix docs build for v1 and v2
  deploy/docs-v2/local-preview.sh
  deploy/webhook-v2/Dockerfile
  deploy/webhook/Dockerfile
Labels: size/XS

#9511 fix(wait): Add panic prevent WaitForPodInitialized
  pkg/skaffold/kubernetes/wait.go
Labels: size/XS

#9476 feat(kaniko): Optimize kaniko build by 50% using compression and add progress
  docs-v2/content/en/schemas/v4beta12.json
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/kaniko/types.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/defaults/defaults_test.go
  pkg/skaffold/schema/latest/config.go
  pkg/skaffold/schema/versions_test.go
Labels: size/M
