Repository GoogleContainerTools/skaffold, pull requests merged in 2024-11, with the labels that each got.

#9556 chore: bump golang-jwt/jwt/v4 from 4.5.0 to 4.5.1
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: size/XS

#9501 chore(logs): add log message for total time taken to complete skaffold dev loop
  pkg/skaffold/runner/dev.go
Labels: size/XS

#9517 docs: Fix `IMAGE_NAME` var name for the Nth artifact
  docs-v2/content/en/docs/environment/templating.md
Labels: size/S

#9521 fix: Set the client DialContext to the connhelper dialer DOCKER_HOST is present
  pkg/skaffold/docker/client.go
Labels: size/XS

#9513 chore: remove unused taggers field
  pkg/skaffold/tag/tagger_mux.go
Labels: size/XS

#9558 fix(config): Replace json tag with yaml for VerifyEnvVar
  docs-v2/content/en/schemas/v4beta12.json
  pkg/skaffold/inspect/jobManifestPaths/modify_test.go
  pkg/skaffold/schema/latest/config.go
Labels: size/M

#9493 feat(sync): Add pod filter using FieldSelector
  pkg/skaffold/sync/sync.go
  pkg/skaffold/sync/sync_test.go
Labels: size/M

#9571 chore: bump go version from 1.22 to 1.23
  .github/workflows/integration-linux.yml
  .github/workflows/linters-checks.yml
  .github/workflows/performance-comparison.yml
  .github/workflows/unit-tests-darwin.yml
  .github/workflows/unit-tests-linux.yml
  .github/workflows/unit-tests-windows.yml
  .github/workflows/verify-examples.yml
  cmd/skaffold/app/cmd/inspect_config_dependencies.go
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/Dockerfile.deps.slim
  fs/assets/credits_generated/github.com/hashicorp/hcl/go.mod
  go.mod
  hack/golangci-lint.sh
  hack/tools/go.mod
  hack/versions/pkg/diff/godiff_test.go
  integration/build_test.go
  integration/skaffold/helper.go
  pkg/diag/validator/validator.go
  pkg/skaffold/deploy/cloudrun/deploy_test.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/filemon/changes.go
  pkg/skaffold/gcs/gsutil.go
  pkg/skaffold/git/errors.go
  pkg/skaffold/inspect/errors.go
  pkg/skaffold/kubernetes/status/resource/status.go
  pkg/skaffold/lsp/handler.go
  pkg/skaffold/parser/config_test.go
  pkg/skaffold/render/renderer/helm/helm.go
  pkg/skaffold/render/transform/transform.go
  pkg/skaffold/render/validate/validate.go
  pkg/skaffold/schema/errors/errors.go
  pkg/skaffold/schema/validation/validation.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/sync/syncer_mux.go
  pkg/skaffold/tags/paths.go
  pkg/skaffold/test/custom/custom_test.go
  pkg/skaffold/update/update.go
Labels: size/L

#9553 feat(cluster): Add labels to cluster config
  docs-v2/content/en/schemas/v4beta12.json
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/schema/latest/config.go
Labels: size/S

#9578 fix: Wrap errors when unmarshal Cloud Run deploy manifests fail.
  pkg/skaffold/deploy/cloudrun/deploy.go
Labels: size/S

#9580 fix: Handle `StandalonePods` `Succeeded` case when checking status
  pkg/skaffold/kubernetes/status/resource/deployment.go
  pkg/skaffold/kubernetes/status/resource/deployment_test.go
Labels: size/M

#9520 feat(bin): Add graceful shutdown for helm command
  pkg/skaffold/helm/bin.go
Labels: size/XS

#9584 fix: Update the k8s Job container logic for custom actions to match v…
  pkg/skaffold/actions/k8sjob/task.go
  pkg/skaffold/actions/k8sjob/task_test.go
Labels: size/L
