Repository GoogleContainerTools/skaffold, pull requests merged in 2025-01, with the labels that each got.

#9623 fix: upgrade gradle to 8.11.1 and set java version used to 21.
  .github/workflows/integration-linux.yml
  examples/jib-gradle/build.gradle
  examples/jib-gradle/gradle.properties
  examples/jib-gradle/gradle/wrapper/gradle-wrapper.jar
  examples/jib-gradle/gradle/wrapper/gradle-wrapper.properties
  examples/jib-gradle/gradlew
  examples/jib-gradle/gradlew.bat
  examples/jib-gradle/settings.gradle
  examples/jib-gradle/skaffold.yaml
  examples/jib-sync/build.gradle
  examples/jib-sync/gradle/wrapper/gradle-wrapper.jar
  examples/jib-sync/gradle/wrapper/gradle-wrapper.properties
  examples/jib-sync/gradlew
  examples/jib-sync/gradlew.bat
  examples/jib-sync/skaffold-gradle.yaml
  integration/examples/jib-gradle/build.gradle
  integration/examples/jib-gradle/gradle.properties
  integration/examples/jib-gradle/gradle/wrapper/gradle-wrapper.jar
  integration/examples/jib-gradle/gradle/wrapper/gradle-wrapper.properties
  integration/examples/jib-gradle/gradlew
  integration/examples/jib-gradle/gradlew.bat
  integration/examples/jib-gradle/settings.gradle
  integration/examples/jib-gradle/skaffold.yaml
  integration/examples/jib-sync/build.gradle
  integration/examples/jib-sync/gradle/wrapper/gradle-wrapper.jar
  integration/examples/jib-sync/gradle/wrapper/gradle-wrapper.properties
  integration/examples/jib-sync/gradlew
  integration/examples/jib-sync/gradlew.bat
  integration/examples/jib-sync/skaffold-gradle.yaml
Labels: size/XL

#9642 chore: update go version used in the published container
  deploy/skaffold/Dockerfile.deps
Labels: size/XS

#9646 chore: upgrade all bundled tools in the Skaffold container
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/digests/bazel.amd64.sha256
  deploy/skaffold/digests/container-structure-test.amd64.sha512
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/k3d.amd64.sha256
  deploy/skaffold/digests/kind.amd64.sha512
  deploy/skaffold/digests/kompose.amd64.sha256
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha512
  deploy/skaffold/digests/kustomize.amd64.sha256
Labels: size/M

#9589 feat(verify.go): Add pod fail reason and message to output
  pkg/skaffold/verify/k8sjob/verify.go
Labels: size/S

#9600 fix: Helm deploy was not working with variable templatinging chart path
  pkg/skaffold/deploy/helm/helm.go
Labels: size/XS

#9425 docs: Propose build batching for Bazel.
  docs-v2/design_proposals/concurrent-bazel-builds.md
Labels: size/L

#9624 feat(helm): Add helm dependencies support
  docs-v2/content/en/schemas/v4beta12.json
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/deploy/helm/util_test.go
  pkg/skaffold/schema/defaults/defaults.go
  pkg/skaffold/schema/latest/config.go
Labels: size/XL

#9661 chore: move deprecated library location to new location
  go.mod
  go.sum
  pkg/skaffold/docker/default_repo.go
  pkg/skaffold/docker/reference.go
  pkg/skaffold/kubernetes/loader/load.go
  vendor/github.com/docker/distribution/.golangci.yml
  vendor/github.com/docker/distribution/.mailmap
  vendor/github.com/docker/distribution/BUILDING.md
  vendor/github.com/docker/distribution/Dockerfile
  vendor/github.com/docker/distribution/Makefile
  vendor/github.com/docker/distribution/blobs.go
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/docker/distribution/registry.go
  vendor/github.com/docker/distribution/registry/api/v2/descriptors.go
  vendor/github.com/docker/distribution/registry/api/v2/urls.go
  vendor/github.com/docker/distribution/registry/client/blob_writer.go
  vendor/github.com/docker/distribution/registry/client/errors.go
  vendor/github.com/docker/distribution/registry/client/repository.go
  vendor/github.com/docker/distribution/registry/storage/cache/memory/memory.go
  vendor/github.com/docker/distribution/vendor.conf
  vendor/modules.txt
Labels: size/S

#9373 fix: retry on errors when watching pods
  pkg/skaffold/kubernetes/wait.go
  pkg/skaffold/kubernetes/wait_test.go
  vendor/k8s.io/apimachinery/pkg/util/cache/expiring.go
  vendor/k8s.io/apimachinery/pkg/util/cache/lruexpirecache.go
  vendor/k8s.io/apimachinery/pkg/util/diff/diff.go
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/doc.go
  vendor/k8s.io/client-go/tools/cache/expiration_cache.go
  vendor/k8s.io/client-go/tools/cache/expiration_cache_fakes.go
  vendor/k8s.io/client-go/tools/cache/fake_custom_store.go
  vendor/k8s.io/client-go/tools/cache/fifo.go
  vendor/k8s.io/client-go/tools/cache/heap.go
  vendor/k8s.io/client-go/tools/cache/index.go
  vendor/k8s.io/client-go/tools/cache/listers.go
  vendor/k8s.io/client-go/tools/cache/listwatch.go
  vendor/k8s.io/client-go/tools/cache/mutation_cache.go
  vendor/k8s.io/client-go/tools/cache/mutation_detector.go
  vendor/k8s.io/client-go/tools/cache/object-names.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/cache/reflector_data_consistency_detector.go
  vendor/k8s.io/client-go/tools/cache/reflector_metrics.go
  vendor/k8s.io/client-go/tools/cache/retry_with_deadline.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/tools/cache/store.go
  vendor/k8s.io/client-go/tools/cache/synctrack/lazy.go
  vendor/k8s.io/client-go/tools/cache/synctrack/synctrack.go
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/client-go/tools/cache/undelta_store.go
  vendor/k8s.io/client-go/tools/pager/pager.go
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/k8s.io/utils/trace/README.md
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: size/M

#9663 chore: final cleanups of the go.mod file
  go.mod
  go.sum
  pkg/skaffold/config/util.go
  vendor/github.com/aws/aws-sdk-go-v2/config/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/config/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/credentials/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/credentials/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/api_op_DescribeImageScanFindings.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/api_op_GetLifecyclePolicyPreview.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/internal/endpoints/endpoints.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/CHANGELOG.md
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/go_module_metadata.go
  vendor/github.com/aws/aws-sdk-go-v2/service/sts/internal/endpoints/endpoints.go
  vendor/modules.txt
Labels: size/M

#9665 feat: implement kaniko.imagePullSecret for pulling images from private registry w/ auth
  docs-v2/content/en/schemas/v4beta12.json
  pkg/skaffold/build/cluster/pod.go
  pkg/skaffold/build/cluster/pod_test.go
  pkg/skaffold/schema/latest/config.go
Labels: size/S

#9669 fix: Make defaultNamespace warning more useful
  pkg/skaffold/runner/runcontext/context.go
Labels: size/XS

#9666 fix: Add Dockerfile for digest calculation
  pkg/skaffold/tag/input_digest.go
  pkg/skaffold/tag/input_digest_test.go
Labels: size/M

#9664 fix: make `IMAGE_TAG` available in buildArgs when used in docker `FROM`
  cmd/skaffold/app/cmd/diagnose.go
  hack/boilerplate/boilerplate.py
  integration/build_test.go
  integration/testdata/docker-run-with-build-args/artifact-with-dependency/base/Dockerfile
  integration/testdata/docker-run-with-build-args/artifact-with-dependency/base/go.mod
  integration/testdata/docker-run-with-build-args/artifact-with-dependency/base/main.go
  integration/testdata/docker-run-with-build-args/artifact-with-dependency/child/Dockerfile
  integration/testdata/docker-run-with-build-args/artifact-with-dependency/skaffold.yaml
  integration/testdata/docker-run-with-build-args/single-artifact/Dockerfile
  integration/testdata/docker-run-with-build-args/single-artifact/script-latest.sh
  integration/testdata/docker-run-with-build-args/single-artifact/skaffold.yaml
  pkg/skaffold/build/cache/cache.go
  pkg/skaffold/build/cache/hash.go
  pkg/skaffold/build/cache/hash_test.go
  pkg/skaffold/build/cache/lookup.go
  pkg/skaffold/build/cache/lookup_test.go
  pkg/skaffold/build/cache/retrieve_test.go
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/build/docker/docker.go
  pkg/skaffold/build/gcb/cloud_build.go
  pkg/skaffold/build/gcb/docker.go
  pkg/skaffold/build/gcb/docker_test.go
  pkg/skaffold/build/gcb/kaniko.go
  pkg/skaffold/build/gcb/kaniko_test.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/util/util.go
  pkg/skaffold/diagnose/diagnose.go
  pkg/skaffold/diagnose/diagnose_test.go
  pkg/skaffold/docker/build_args.go
  pkg/skaffold/docker/build_args_test.go
  pkg/skaffold/docker/dependencies_test.go
  pkg/skaffold/docker/dockertest.go
  pkg/skaffold/docker/image.go
  pkg/skaffold/graph/dependencies.go
  pkg/skaffold/graph/dependencies_test.go
  pkg/skaffold/runner/build.go
  pkg/skaffold/runner/listen_test.go
  pkg/skaffold/runner/new.go
  pkg/skaffold/tag/custom_template_test.go
  pkg/skaffold/tag/input_digest.go
Labels: size/XL

#9668 release: v2.14.0
  CHANGELOG.md
  docs-v2/content/en/schemas/version-mappings/v4beta12-version.json
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/go-integration-coverage/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/backend/Gemfile.lock
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/README.md
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  examples/using-env-file/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: size/XXL

#9688 chore: Fix BuildContextCompressionLevel description, output the level
  docs-v2/content/en/schemas/v4beta12.json
  pkg/skaffold/build/cluster/kaniko.go
  pkg/skaffold/schema/latest/config.go
Labels: size/S

#9689 fix(helm): Add expand env template for dependsOn, fix concurrent installation
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/deploy/helm/util_test.go
Labels: size/M
