Repository GoogleContainerTools/skaffold, pull requests merged in 2025-05, with the labels that each got.

#9804 docs: remove reference to the deprecated office hours
  README.md
Labels: size/S

#9803 chore: remove the `skaffold survey` code
  cmd/skaffold/app/cmd/cmd.go
  cmd/skaffold/app/cmd/survey.go
  docs-v2/content/en/docs/references/cli/_index.md
  go.mod
  go.sum
  integration/housekeeping_messages_test.go
  pkg/skaffold/survey/config.go
  pkg/skaffold/survey/config_test.go
  pkg/skaffold/survey/survey.go
  pkg/skaffold/survey/survey_test.go
  vendor/github.com/pkg/browser/LICENSE
  vendor/github.com/pkg/browser/README.md
  vendor/github.com/pkg/browser/browser.go
  vendor/github.com/pkg/browser/browser_darwin.go
  vendor/github.com/pkg/browser/browser_freebsd.go
  vendor/github.com/pkg/browser/browser_linux.go
  vendor/github.com/pkg/browser/browser_netbsd.go
  vendor/github.com/pkg/browser/browser_openbsd.go
  vendor/github.com/pkg/browser/browser_unsupported.go
  vendor/github.com/pkg/browser/browser_windows.go
  vendor/modules.txt
Labels: size/XXL

#9805 chore: upgrade to Go 1.24.2
  .github/workflows/integration-linux.yml
  .github/workflows/linters-checks.yml
  .github/workflows/performance-comparison.yml
  .github/workflows/unit-tests-darwin.yml
  .github/workflows/unit-tests-linux.yml
  .github/workflows/unit-tests-windows.yml
  .github/workflows/verify-examples.yml
  deploy/skaffold/Dockerfile.deps
Labels: size/S

#9806 chore: update dependencies in Dockerfile and integration tests
  .github/workflows/integration-linux.yml
  deploy/skaffold/Dockerfile.deps
  deploy/skaffold/digests/bazel.amd64.sha256
  deploy/skaffold/digests/gcloud.amd64.sha256
  deploy/skaffold/digests/helm.amd64.sha256
  deploy/skaffold/digests/k3d.amd64.sha256
  deploy/skaffold/digests/kind.amd64.sha512
  deploy/skaffold/digests/kpt.amd64.sha256
  deploy/skaffold/digests/kubectl.amd64.sha256
Labels: size/M

#9807 chore: 2.16 release
  CHANGELOG.md
  examples/grpc-e2e-tests/service/go.mod
  examples/grpc-e2e-tests/service/go.sum
Labels: size/M

#9813 docs: add a KEYS file for verifying our releases
  KEYS
Labels: size/S

#9810 cicd: migrate internal build config to internal config repository.
  deploy/cloudbuild-louhi-release.yaml
Labels: size/M

#9816 doc: state default parameter for manifests::rawYaml
  docs-v2/content/en/docs/renderers/rawYaml.md
Labels: size/S

#9819 chore: reduce dependabot PRs
  .github/dependabot.yml
Labels: size/M

#9822 chore: updates to the GitHub Actions workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/performance-comparison-label.yml
  .github/workflows/performance-comparison.yml
  .github/workflows/scorecards.yml
Labels: size/L

#9814 fix(helm): Fix unformatted error message
  pkg/skaffold/render/renderer/helm/helm.go
Labels: size/XS

#9808 [bug]: Support helm depBuild flags for helm deploys
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
Labels: size/S
