Repository GoogleContainerTools/skaffold, pull requests merged in 2025-04, with the labels that each got.

#9774 fix: fix lifecycle version in go.mod
  go.mod
  vendor/modules.txt
Labels: size/XS

#9776 chore: update dockerfile and integration skaffold dependencies
  .github/workflows/integration-linux.yml
Labels: size/XS

#9777 chore: add changelog entry for 2.15
  CHANGELOG.md
  docs-v2/content/en/schemas/version-mappings/v4beta13-version.json
  examples/bazel/skaffold.yaml
  examples/buildpacks-java/skaffold.yaml
  examples/buildpacks-node/skaffold.yaml
  examples/buildpacks-python/skaffold.yaml
  examples/buildpacks/skaffold.yaml
  examples/cross-platform-builds/skaffold.yaml
  examples/custom-buildx/skaffold.yaml
  examples/custom-tests/skaffold.yaml
  examples/custom/skaffold.yaml
  examples/dev-journey-buildpacks/skaffold.yaml
  examples/docker-deploy/skaffold.yaml
  examples/gcb-kaniko/skaffold.yaml
  examples/generate-pipeline/skaffold.yaml
  examples/getting-started-kustomize/skaffold.yaml
  examples/getting-started/skaffold.yaml
  examples/go-integration-coverage/skaffold.yaml
  examples/google-cloud-build/skaffold.yaml
  examples/grpc-e2e-tests/skaffold.yaml
  examples/helm-deployment-dependencies/skaffold.yaml
  examples/helm-deployment/skaffold.yaml
  examples/helm-remote-repo/skaffold.yaml
  examples/helm-render/skaffold.yaml
  examples/hot-reload/skaffold.yaml
  examples/jib-gradle/skaffold.yaml
  examples/jib-multimodule/skaffold.yaml
  examples/jib-sync/skaffold-gradle.yaml
  examples/jib-sync/skaffold-maven.yaml
  examples/jib/skaffold.yaml
  examples/kaniko/skaffold.yaml
  examples/ko-sync-infer/skaffold.yaml
  examples/ko/skaffold.yaml
  examples/kustomize/skaffold-kustomize-args.yaml
  examples/kustomize/skaffold.yaml
  examples/lifecycle-hooks/skaffold.yaml
  examples/microservices/skaffold.yaml
  examples/multi-config-microservices/base/skaffold.yaml
  examples/multi-config-microservices/leeroy-app/skaffold.yaml
  examples/multi-config-microservices/leeroy-web/skaffold.yaml
  examples/multi-config-microservices/skaffold.yaml
  examples/multiple-renderers/skaffold.yaml
  examples/nodejs/skaffold.yaml
  examples/profile-patches/skaffold.yaml
  examples/profiles/skaffold.yaml
  examples/react-reload-docker/skaffold.yaml
  examples/react-reload/skaffold.yaml
  examples/remote-multi-config-microservices/skaffold.yaml
  examples/ruby/skaffold.yaml
  examples/simple-artifact-dependency/skaffold.yaml
  examples/structure-tests/skaffold.yaml
  examples/tagging-with-environment-variables/skaffold.yaml
  examples/templated-fields/skaffold.yaml
  examples/typescript/skaffold.yaml
  examples/using-env-file/skaffold.yaml
  pkg/skaffold/schema/latest/config.go
Labels: size/L

#9780 feat(config): Enhance config list/set output
  cmd/skaffold/app/cmd/config/list.go
  cmd/skaffold/app/cmd/config/list_test.go
  cmd/skaffold/app/cmd/config/set.go
Labels: size/S

#9790 cicd: adding louhi release file for internal release process for the image
  deploy/cloudbuild-louhi-release.yaml
Labels: size/M

#9786 docs: Make --no-prune documentation clearer
  cmd/skaffold/app/cmd/flags.go
  docs-v2/content/en/docs/references/cli/_index.md
Labels: size/XS

#9799 feat: Add support in Cloud Run for configuring tolerateFailuresUntilDeadline and disabling status checks
  pkg/skaffold/deploy/cloudrun/deploy.go
  pkg/skaffold/deploy/cloudrun/deploy_test.go
  pkg/skaffold/deploy/cloudrun/status.go
  pkg/skaffold/deploy/cloudrun/status_test.go
  pkg/skaffold/runner/deployer.go
  pkg/skaffold/runner/deployer_test.go
  pkg/skaffold/runner/runcontext/context.go
  pkg/skaffold/status/status.go
Labels: size/L

#9787 Bugfix: Only prune images if changed
  pkg/skaffold/build/local/local.go
  pkg/skaffold/build/local/local_test.go
Labels: size/L
