Repository GoogleContainerTools/skaffold, pull requests merged in 2025-02, with the labels that each got.

#9703 feat: revert "feat: transform imagePullPolicy when using local cluster (#9495)"
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/kubernetes/manifest/image_pull_policy.go
  pkg/skaffold/kubernetes/manifest/image_pull_policy_test.go
Labels: size/L

#9693 fix(helm): Fix helm package installation order
  pkg/skaffold/deploy/helm/dependencygraph.go
  pkg/skaffold/deploy/helm/dependencygraph_test.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/deploy/helm/util_test.go
  pkg/skaffold/schema/defaults/defaults.go
Labels: size/XXL

#9709 fix(helm): Fix helm package installation order (#9693)
  pkg/skaffold/deploy/helm/dependencygraph.go
  pkg/skaffold/deploy/helm/dependencygraph_test.go
  pkg/skaffold/deploy/helm/helm.go
  pkg/skaffold/deploy/helm/helm_test.go
  pkg/skaffold/deploy/helm/util.go
  pkg/skaffold/deploy/helm/util_test.go
  pkg/skaffold/schema/defaults/defaults.go
Labels: size/XXL

#9708 feat: revert "feat: transform imagePullPolicy when using local cluster (#9495)" (#9703)
  pkg/skaffold/deploy/kubectl/kubectl.go
  pkg/skaffold/kubernetes/manifest/image_pull_policy.go
  pkg/skaffold/kubernetes/manifest/image_pull_policy_test.go
Labels: size/L

#9727 Revert back to only allowing security updates from dependabot.
  .github/dependabot.yml
Labels: size/M

#9728 fix: port-forward error logs `failed to port forward`
  pkg/skaffold/kubectl/exec_windows.go
  pkg/skaffold/kubectl/exec_windows_test.go
Labels: size/M
